(function(){
'use strict';
var DATA_KEY='APP_AVISOS_WEB_DATOS_V112_AVISOS';
var TRASH_KEY='APP_AVISOS_WEB_PAPELERA_V113';
var FLAG='APP_AVISOS_V113_VOLVER_AVISOS';
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m];});}
function readJson(key,def){try{var r=localStorage.getItem(key);return r?JSON.parse(r):def;}catch(e){return def;}}
function writeJson(key,v){try{localStorage.setItem(key,JSON.stringify(v));return true;}catch(e){alert('No se pudo guardar.');return false;}}
function fechaES(v){if(!v)return '';var p=String(v).split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:String(v);}
function fechaHoraES(v){try{return v?new Date(v).toLocaleString('es-ES'):'';}catch(e){return String(v||'');}}
function estadoTexto(v){return v==='en_curso'?'EN CURSO':v==='finalizado'?'FINALIZADO':'PENDIENTE';}
function dataActual(){var d=readJson(DATA_KEY,null);if(!d||typeof d!=='object')d={empresa:{},tecnico:{},solicitante:{},avisos:[]};if(!Array.isArray(d.avisos))d.avisos=[];return d;}
function papelera(){var p=readJson(TRASH_KEY,[]);return Array.isArray(p)?p:[];}
function guardarPapelera(p){return writeJson(TRASH_KEY,p);}
function irAvisosTrasRecarga(){try{sessionStorage.setItem(FLAG,'1');location.reload();}catch(e){location.reload();}}
function cambiarVersion(){var small=document.querySelector('header .headerText small');if(small)small.textContent='V1.13 PRUEBA · Papelera de avisos';}
function idDeCard(card){var b=card.querySelector('button[onclick*="App.editarAviso("]');if(!b)return 0;var m=(b.getAttribute('onclick')||'').match(/App\.editarAviso\((\d+)\)/);return m?Number(m[1]):0;}
function moverAPapelera(id){var d=dataActual(),pos=d.avisos.findIndex(function(a){return Number(a.id)===Number(id);});if(pos<0)return;var a=d.avisos[pos];d.avisos.splice(pos,1);var p=papelera();p.push(Object.assign({},a,{eliminadoEn:new Date().toISOString()}));if(writeJson(DATA_KEY,d)&&guardarPapelera(p))irAvisosTrasRecarga();}
function restaurar(id){var p=papelera(),pos=p.findIndex(function(a){return Number(a.id)===Number(id);});if(pos<0)return;var a=p[pos];p.splice(pos,1);delete a.eliminadoEn;var d=dataActual();if(!d.avisos.some(function(x){return Number(x.id)===Number(a.id);}))d.avisos.push(a);if(writeJson(DATA_KEY,d)&&guardarPapelera(p))irAvisosTrasRecarga();}
function borrarDefinitivo(id){if(!confirm('¿Borrar definitivamente este aviso? Esta acción no se puede deshacer.'))return;var p=papelera().filter(function(a){return Number(a.id)!==Number(id);});if(guardarPapelera(p))renderPapelera();}
function mejorarTarjetas(){var cards=document.querySelectorAll('#listaAvisos .avisoCard');cards.forEach(function(card){if(card.querySelector('.v113Eliminar'))return;var id=idDeCard(card);if(!id)return;var actions=card.querySelector('.actions');if(!actions)return;actions.style.gridTemplateColumns='repeat(3,1fr)';var b=document.createElement('button');b.type='button';b.className='v113Eliminar';b.textContent='Eliminar';b.style.borderColor='#b42318';b.style.color='#b42318';b.addEventListener('click',function(){moverAPapelera(id);});actions.appendChild(b);});}
function crearUI(){var sec=document.getElementById('avisos');if(!sec||document.getElementById('papeleraV113Wrap'))return;var wrap=document.createElement('div');wrap.id='papeleraV113Wrap';wrap.innerHTML='<div class="card"><button id="papeleraV113Btn" type="button" class="full">🗑 Papelera (0)</button></div><div id="papeleraV113Box" class="card" style="display:none"><h3>Papelera</h3><p class="muted">Los avisos eliminados permanecen aquí hasta restaurarlos o borrarlos definitivamente.</p><div id="papeleraV113Lista"></div></div>';sec.appendChild(wrap);document.getElementById('papeleraV113Btn').addEventListener('click',function(){var box=document.getElementById('papeleraV113Box');box.style.display=box.style.display==='none'?'block':'none';renderPapelera();if(box.style.display==='block')window.scrollTo(0,Math.max(0,box.offsetTop-70));});}
function renderPapelera(){crearUI();var p=papelera().slice().sort(function(a,b){return String(b.eliminadoEn||'').localeCompare(String(a.eliminadoEn||''));});var btn=document.getElementById('papeleraV113Btn'),box=document.getElementById('papeleraV113Lista');if(btn)btn.textContent='🗑 Papelera ('+p.length+')';if(!box)return;if(!p.length){box.innerHTML='<div class="empty">La papelera está vacía.</div>';return;}box.innerHTML=p.map(function(a){return '<div class="avisoCard" style="border-color:#f1c7c2;background:#fffafa"><div class="avisoTop"><strong>'+esc(a.cliente||'SIN CLIENTE')+'</strong><span class="badge '+esc(a.estado||'pendiente')+'">'+estadoTexto(a.estado)+'</span></div><div class="avisoMeta">'+esc(fechaES(a.fecha))+(a.direccion?' · '+esc(a.direccion):'')+'</div>'+(a.concepto?'<div class="avisoConcepto"><b>'+esc(a.concepto)+'</b></div>':'')+'<div style="font-size:11px;color:#b42318;margin-top:5px">Eliminado: '+esc(fechaHoraES(a.eliminadoEn))+'</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px"><button type="button" data-restaurar="'+a.id+'">Restaurar</button><button type="button" data-borrar="'+a.id+'" style="border-color:#b42318;color:#b42318">Borrar definitivamente</button></div></div>';}).join('');box.querySelectorAll('[data-restaurar]').forEach(function(b){b.addEventListener('click',function(){restaurar(Number(b.getAttribute('data-restaurar')));});});box.querySelectorAll('[data-borrar]').forEach(function(b){b.addEventListener('click',function(){borrarDefinitivo(Number(b.getAttribute('data-borrar')));});});}
function aplicar(){cambiarVersion();crearUI();mejorarTarjetas();renderPapelera();}
var lista=document.getElementById('listaAvisos');if(lista){new MutationObserver(function(){mejorarTarjetas();}).observe(lista,{childList:true,subtree:true});}
setTimeout(aplicar,0);setTimeout(aplicar,250);
try{if(sessionStorage.getItem(FLAG)==='1'){sessionStorage.removeItem(FLAG);setTimeout(function(){if(window.App&&App.show)App.show('avisos');setTimeout(aplicar,50);},50);}}catch(e){}
})();
