(function(){'use strict';
var KEY='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',FLAGS='APP_AVISOS_FLAGS_V120',DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado',PLANS='planos',PHOTO_PREFIX='APP_AVISOS_FOTOS_V123_';
var urls=[];
function el(id){return document.getElementById(id)}function txt(v){return String(v==null?'':v)}function esc(v){return txt(v).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]})}
function data(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}}function fecha(v){if(!v)return'';var p=txt(v).split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:txt(v)}
function openDb(){return new Promise(function(ok,no){var r=indexedDB.open(DB,DBV);r.onupgradeneeded=function(){var q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains(PLANS))q.createObjectStore(PLANS)};r.onsuccess=function(){ok(r.result)};r.onerror=function(){no(r.error)}})}
function storeGet(store,key){return openDb().then(function(q){return new Promise(function(ok,no){var r=q.transaction(store,'readonly').objectStore(store).get(String(key));r.onsuccess=function(){var v=r.result;q.close();ok(v==null?null:v)};r.onerror=function(){var e=r.error;q.close();no(e)}})})}
function storePut(store,key,val){return openDb().then(function(q){return new Promise(function(ok,no){var t=q.transaction(store,'readwrite');t.objectStore(store).put(val,String(key));t.oncomplete=function(){q.close();ok()};t.onerror=function(){var e=t.error;q.close();no(e)}})})}
function storeKeys(store){return openDb().then(function(q){return new Promise(function(ok,no){var r=q.transaction(store,'readonly').objectStore(store).getAllKeys();r.onsuccess=function(){var v=r.result||[];q.close();ok(v)};r.onerror=function(){var e=r.error;q.close();no(e)}})})}
function optionList(){var s=el('photoSel'),a=(data().avisos||[]).slice().sort(function(x,y){return Number(y.id)-Number(x.id)}),old=s.value;s.innerHTML=a.length?a.map(function(x){return '<option value="'+Number(x.id)+'">'+esc(fecha(x.fecha)+' · '+(x.cliente||'SIN CLIENTE')+' · '+(x.direccion||''))+'</option>'}).join(''):'<option value="">No hay avisos</option>';if(old&&a.some(function(x){return String(x.id)===old}))s.value=old}
function photoKey(id){return PHOTO_PREFIX+String(id)}function getPhotos(id){return storeGet(STATE,photoKey(id)).then(function(v){return Array.isArray(v)?v:[]})}function putPhotos(id,a){return storePut(STATE,photoKey(id),a||[])}
function revoke(){urls.forEach(function(u){try{URL.revokeObjectURL(u)}catch(e){}});urls=[]}
function renderPhotos(){optionList();var id=Number(el('photoSel').value)||0,g=el('photoGrid'),empty=el('photoEmpty');revoke();if(!id){g.innerHTML='';empty.style.display='block';return}getPhotos(id).then(function(a){g.innerHTML='';empty.style.display=a.length?'none':'block';a.forEach(function(p,i){var u=URL.createObjectURL(p.blob);urls.push(u);var d=document.createElement('div');d.className='photo'+(p.cgp?' cgp':'');d.innerHTML='<img src="'+u+'" alt="Fotografía"><div class="meta">'+esc(p.nombre||('Foto '+(i+1)))+'</div>'+(p.cgp?'<span class="badge">CGP</span>':'')+'<div class="actions"><button type="button" data-act="cgp" data-i="'+i+'">'+(p.cgp?'CGP seleccionada':'Marcar como CGP')+'</button><button type="button" class="danger" data-act="del" data-i="'+i+'">Eliminar</button></div>';g.appendChild(d)});g.querySelectorAll('button').forEach(function(b){b.onclick=function(){var i=Number(b.dataset.i),act=b.dataset.act;if(act==='cgp')markCgp(id,i);else deletePhoto(id,i)}})})}
function resize(file){return new Promise(function(ok,no){var im=new Image(),u=URL.createObjectURL(file);im.onload=function(){try{var max=1600,w=im.width,h=im.height,s=Math.min(1,max/Math.max(w,h));w=Math.max(1,Math.round(w*s));h=Math.max(1,Math.round(h*s));var c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);c.toBlob(function(b){URL.revokeObjectURL(u);if(!b){no(new Error('No se pudo procesar la foto'));return}ok({blob:b,nombre:file.name||('foto_'+Date.now()+'.jpg'),creadaEn:new Date().toISOString(),cgp:false})},'image/jpeg',0.82)}catch(e){URL.revokeObjectURL(u);no(e)}};im.onerror=function(){URL.revokeObjectURL(u);no(new Error('No se pudo abrir la imagen'))};im.src=u})}
function addFiles(files){var id=Number(el('photoSel').value)||0;if(!id||!files.length)return;el('photoStatus').textContent='Procesando '+files.length+' fotografía(s)…';Promise.all(Array.from(files).map(resize)).then(function(nuevas){return getPhotos(id).then(function(a){return putPhotos(id,a.concat(nuevas))})}).then(function(){el('photoStatus').textContent='Fotografías guardadas en el aviso.';el('photoInput').value='';renderPhotos()}).catch(function(e){el('photoStatus').textContent='Error: '+e.message})}
function markCgp(id,i){getPhotos(id).then(function(a){a.forEach(function(p,j){p.cgp=j===i});return putPhotos(id,a)}).then(renderPhotos)}function deletePhoto(id,i){if(!confirm('¿Eliminar esta fotografía del aviso?'))return;getPhotos(id).then(function(a){a.splice(i,1);return putPhotos(id,a)}).then(renderPhotos)}
function blobToData(blob){return new Promise(function(ok,no){var r=new FileReader();r.onload=function(){ok(String(r.result))};r.onerror=function(){no(r.error)};r.readAsDataURL(blob)})}
function dataToBlob(s){var p=String(s).split(','),mime=(p[0].match(/data:([^;]+)/)||[])[1]||'application/octet-stream',bin=atob(p[1]||''),u=new Uint8Array(bin.length);for(var i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return new Blob([u],{type:mime})}
async function exportBackup(){var st=el('backupStatus');st.textContent='Preparando copia completa…';try{var main=data(),flags={};try{flags=JSON.parse(localStorage.getItem(FLAGS)||'{}')}catch(e){}var planKeys=await storeKeys(PLANS),plans={};for(var i=0;i<planKeys.length;i++){var k=String(planKeys[i]);if(k.indexOf('__')===0)continue;var v=await storeGet(PLANS,k);if(v&&v.blob){plans[k]={nombre:v.nombre||'',generadoEn:v.generadoEn||'',latitud:v.latitud||'',longitud:v.longitud||'',direccion:v.direccion||'',refCatastral:v.refCatastral||'',data:await blobToData(v.blob)}}}var stateKeys=await storeKeys(STATE),photos={};for(var j=0;j<stateKeys.length;j++){var sk=String(stateKeys[j]);if(sk.indexOf(PHOTO_PREFIX)!==0)continue;var arr=await storeGet(STATE,sk)||[],out=[];for(var z=0;z<arr.length;z++)out.push({nombre:arr[z].nombre||'',creadaEn:arr[z].creadaEn||'',cgp:!!arr[z].cgp,data:await blobToData(arr[z].blob)});photos[sk.slice(PHOTO_PREFIX.length)]=out}var pack={schema:'APP_AVISOS_BACKUP_V123',creadoEn:new Date().toISOString(),main:main,flags:flags,plans:plans,photos:photos},blob=new Blob([JSON.stringify(pack)],{type:'application/json'}),a=document.createElement('a'),d=new Date(),name='APP_Avisos_copia_'+d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')+'.json';a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.remove()},1500);st.textContent='Copia completa exportada: '+name}catch(e){st.textContent='No se pudo exportar la copia: '+e.message}}
async function importBackup(file){var st=el('backupStatus');try{var pack=JSON.parse(await file.text());if(!pack||pack.schema!=='APP_AVISOS_BACKUP_V123')throw new Error('El archivo no es una copia V1.23 válida.');if(!confirm('¿Importar esta copia? Reemplazará los datos locales de este dispositivo.'))return;st.textContent='Importando copia…';localStorage.setItem(KEY,JSON.stringify(pack.main||{}));localStorage.setItem(FLAGS,JSON.stringify(pack.flags||{}));var plans=pack.plans||{};for(var k in plans){var p=plans[k];await storePut(PLANS,k,{blob:dataToBlob(p.data),nombre:p.nombre||'',generadoEn:p.generadoEn||'',latitud:p.latitud||'',longitud:p.longitud||'',direccion:p.direccion||'',refCatastral:p.refCatastral||''})}var photos=pack.photos||{};for(var id in photos){var arr=(photos[id]||[]).map(function(p){return{blob:dataToBlob(p.data),nombre:p.nombre||'',creadaEn:p.creadaEn||'',cgp:!!p.cgp}});await putPhotos(id,arr)}st.textContent='Copia importada correctamente. Cierra y vuelve a abrir APP Avisos para recargar todos los datos.'}catch(e){st.textContent='No se pudo importar: '+e.message}}
window.show=function(v){el('workV').classList.toggle('hide',v!=='work');el('photosV').classList.toggle('hide',v!=='photos');el('backupV').classList.toggle('hide',v!=='backup');el('nWork').className=v==='work'?'on':'';el('nPhotos').className=v==='photos'?'on':'';el('nBackup').className=v==='backup'?'on':'';if(v==='photos')renderPhotos()};window.exportBackup=exportBackup;
el('photoSel').addEventListener('change',renderPhotos);el('photoInput').addEventListener('change',function(){addFiles(this.files)});el('backupInput').addEventListener('change',function(){if(this.files&&this.files[0])importBackup(this.files[0]);this.value=''});optionList();
})();
