(function(){'use strict';
var KEY='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',FLAGS='APP_AVISOS_FLAGS_V120',DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado';
var docs=new WeakSet(),frames=new WeakSet();
function isEmailKey(k){return /email|correo|mail/i.test(String(k||''));}
function skipKey(k){return /^(id|schema|estado|fecha|creadoEn|actualizadoEn|eliminadoEn|generadoEn|logoData|logo)$/i.test(String(k||''));}
function normalizeString(k,v){if(isEmailKey(k))return String(v).trim().toLowerCase();if(skipKey(k))return v;if(/^data:|^blob:|^https?:\/\//i.test(String(v)))return v;return String(v).toUpperCase();}
function normObj(o){if(!o||typeof o!=='object')return false;var changed=false;Object.keys(o).forEach(function(k){var v=o[k];if(typeof v==='string'){var n=normalizeString(k,v);if(n!==v){o[k]=n;changed=true;}}});return changed;}
function putState(raw){try{var r=indexedDB.open(DB,DBV);r.onupgradeneeded=function(){var d=r.result;if(!d.objectStoreNames.contains(STATE))d.createObjectStore(STATE);if(!d.objectStoreNames.contains('planos'))d.createObjectStore('planos');};r.onsuccess=function(){try{var d=r.result,t=d.transaction(STATE,'readwrite');t.objectStore(STATE).put(raw,KEY);t.oncomplete=function(){d.close();};t.onerror=function(){d.close();};}catch(e){try{r.result.close();}catch(x){}}};}catch(e){} }
function normalizeStored(){try{var raw=localStorage.getItem(KEY);if(!raw)return;var p=JSON.parse(raw),changed=false;['empresa','tecnico','solicitante'].forEach(function(k){if(normObj(p[k]))changed=true;});['avisos','papelera'].forEach(function(k){var a=p[k];if(Array.isArray(a))a.forEach(function(x){if(normObj(x))changed=true;});});if(changed){var out=JSON.stringify(p);localStorage.setItem(KEY,out);putState(out);}var fr=JSON.parse(localStorage.getItem(FLAGS)||'{}'),fc=false;Object.keys(fr||{}).forEach(function(k){if(fr[k]&&typeof fr[k].iban==='string'){var n=fr[k].iban.replace(/\s+/g,'').toUpperCase();if(n!==fr[k].iban){fr[k].iban=n;fc=true;}}});if(fc)localStorage.setItem(FLAGS,JSON.stringify(fr));}catch(e){console.warn('Normalización V1.25',e);} }
function isText(el){if(!el||!el.tagName)return false;if(el.tagName==='TEXTAREA')return true;if(el.tagName!=='INPUT')return false;var t=(el.type||'text').toLowerCase();return ['text','email','search','tel','url','password'].indexOf(t)>=0;}
function isEmailField(el){if(!el)return false;return (el.type||'').toLowerCase()==='email'||/email|correo|mail/i.test([el.id,el.name,el.placeholder,el.getAttribute('aria-label')].filter(Boolean).join(' '));}
function transform(el){if(!isText(el)||el.readOnly||el.disabled)return;var v=String(el.value||''),n=isEmailField(el)?v.toLowerCase():v.toUpperCase();el.style.textTransform=isEmailField(el)?'lowercase':'uppercase';if(n===v)return;var s=null,e=null;try{s=el.selectionStart;e=el.selectionEnd;}catch(x){}el.value=n;try{if(s!==null)el.setSelectionRange(s,e);}catch(x){}}
function scanDoc(doc){try{doc.querySelectorAll('input,textarea').forEach(transform);doc.querySelectorAll('iframe').forEach(bindFrame);}catch(e){} }
function bindDoc(doc){if(!doc||docs.has(doc))return;docs.add(doc);doc.addEventListener('input',function(ev){transform(ev.target);},true);doc.addEventListener('change',function(ev){transform(ev.target);},true);doc.addEventListener('blur',function(ev){transform(ev.target);},true);scanDoc(doc);try{new MutationObserver(function(){scanDoc(doc);}).observe(doc.documentElement||doc,{childList:true,subtree:true});}catch(e){} }
function bindFrame(fr){if(!fr)return;if(!frames.has(fr)){frames.add(fr);fr.addEventListener('load',function(){try{bindDoc(fr.contentDocument);}catch(e){};setTimeout(function(){try{scanDoc(fr.contentDocument);}catch(e){}},150);});}try{if(fr.contentDocument)bindDoc(fr.contentDocument);}catch(e){} }
function start(){bindDoc(document);var root=document.getElementById('app125');if(root)bindFrame(root);setInterval(function(){try{scanDoc(document);}catch(e){}},1200);}
normalizeStored();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
