(function(){'use strict';
const KEY='SOLTEC_AGENDA_V1',BACKUP='SOLTEC_AGENDA_V1_AUTOBACKUP';let materials=[],checklist=[],lastId='',saveTimer=0;
const $=id=>document.getElementById(id);
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function rows(){try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch(_){return[]}}
function write(x){try{const raw=JSON.stringify(x);localStorage.setItem(KEY,raw);localStorage.setItem(BACKUP,raw);try{window.dispatchEvent(new CustomEvent('agenda:changed'))}catch(_){}return true}catch(_){return false}}
function currentId(){return String(($('id')||{}).value||'')}
function load(){const id=currentId(),r=rows().find(x=>String(x.id)===id)||{};materials=Array.isArray(r.materials)?r.materials.map(x=>({text:String(x.text||''),qty:String(x.qty||'')})):[];checklist=Array.isArray(r.checklist)?r.checklist.map(x=>({id:x.id||('CK-'+Date.now()),text:String(x.text||''),done:!!x.done})):[];render()}
function payload(){return{materials:materials.filter(x=>x.text.trim()).map(x=>({text:x.text.trim(),qty:x.qty.trim()})),checklist:checklist.filter(x=>x.text.trim()).map(x=>({id:x.id,text:x.text.trim(),done:!!x.done}))}}function persist(id){id=String(id||currentId());if(!id)return;const all=rows(),r=all.find(x=>String(x.id)===id);if(!r)return;const p=payload();r.materials=p.materials;r.checklist=p.checklist;write(all)}function schedulePersist(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{if(currentId())persist()},180)}
function style(){if($('agendaTasksStyle'))return;const s=document.createElement('style');s.id='agendaTasksStyle';s.textContent='.agTaskBlock{grid-column:1/-1;border:1px solid #dbe3ee;border-radius:12px;padding:12px;background:#fbfcfe}.agTaskBlock h3{margin:0 0 8px;font-size:13px;color:#172b4d}.agTaskList{display:grid;gap:7px}.agMatRow{display:grid;grid-template-columns:1fr 110px auto;gap:7px}.agCheckRow{display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:center}.agTaskBlock input{margin:0}.agCheckRow input[type=checkbox]{width:auto}.agTaskAdd{margin-top:8px}.agProgress{font-size:11px;color:#475467;font-weight:800;margin-top:5px}.agSummary{font-size:11px;color:#475467;font-weight:800;margin-top:6px;display:flex;gap:8px;flex-wrap:wrap}@media(max-width:600px){.agMatRow{grid-template-columns:1fr 85px auto}}';document.head.appendChild(s)}
function inject(){style();const grid=document.querySelector('#form .formgrid');if(!grid||$('agendaMaterialsBlock'))return;const photo=$('photoInput');const photoWrap=photo&&photo.closest('.wide');const box=document.createElement('div');box.id='agendaMaterialsBlock';box.className='agTaskBlock';box.innerHTML='<h3>Material previsto / necesario</h3><div id="agendaMaterialsList" class="agTaskList"></div><button type="button" class="ghost agTaskAdd" id="agendaAddMaterial">＋ Añadir material</button>';const ck=document.createElement('div');ck.id='agendaChecklistBlock';ck.className='agTaskBlock';ck.innerHTML='<h3>Checklist del trabajo</h3><div id="agendaChecklistList" class="agTaskList"></div><button type="button" class="ghost agTaskAdd" id="agendaAddCheck">＋ Añadir tarea</button>';grid.insertBefore(box,photoWrap||null);grid.insertBefore(ck,photoWrap||null);$('agendaAddMaterial').onclick=()=>{materials.push({text:'',qty:''});renderMaterials();schedulePersist()};$('agendaAddCheck').onclick=()=>{checklist.push({id:'CK-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),text:'',done:false});renderChecklist();schedulePersist()};render()}
function renderMaterials(){const b=$('agendaMaterialsList');if(!b)return;b.innerHTML=materials.length?materials.map((x,i)=>'<div class="agMatRow"><input data-mtext="'+i+'" placeholder="Material / referencia" value="'+esc(x.text)+'"><input data-mqty="'+i+'" placeholder="Cantidad" value="'+esc(x.qty)+'"><button type="button" class="danger" data-mdel="'+i+'">×</button></div>').join(''):'<div class="hint">Sin material previsto.</div>';b.querySelectorAll('[data-mtext]').forEach(n=>n.oninput=()=>{materials[+n.dataset.mtext].text=n.value;schedulePersist()});b.querySelectorAll('[data-mqty]').forEach(n=>n.oninput=()=>{materials[+n.dataset.mqty].qty=n.value;schedulePersist()});b.querySelectorAll('[data-mdel]').forEach(n=>n.onclick=()=>{materials.splice(+n.dataset.mdel,1);renderMaterials();schedulePersist()})}
function renderChecklist(){const b=$('agendaChecklistList');if(!b)return;b.innerHTML=checklist.length?checklist.map((x,i)=>'<div class="agCheckRow"><input type="checkbox" data-cdone="'+i+'" '+(x.done?'checked':'')+'><input data-ctext="'+i+'" placeholder="Tarea a comprobar" value="'+esc(x.text)+'"><button type="button" class="danger" data-cdel="'+i+'">×</button></div>').join(''):'<div class="hint">Sin tareas de comprobación.</div>';b.querySelectorAll('[data-cdone]').forEach(n=>n.onchange=()=>{checklist[+n.dataset.cdone].done=n.checked;schedulePersist()});b.querySelectorAll('[data-ctext]').forEach(n=>n.oninput=()=>{checklist[+n.dataset.ctext].text=n.value;schedulePersist()});b.querySelectorAll('[data-cdel]').forEach(n=>n.onclick=()=>{checklist.splice(+n.dataset.cdel,1);renderChecklist();schedulePersist()})}
function render(){renderMaterials();renderChecklist()}
function summaryText(r){if(!r)return'';const m=Array.isArray(r.materials)?r.materials.length:0,cl=Array.isArray(r.checklist)?r.checklist:[],ph=Array.isArray(r.photos)?r.photos.length:0,done=cl.filter(x=>x.done).length;return [m?'🧰 '+m:'',cl.length?'☑ '+done+'/'+cl.length:'',ph?'📷 '+ph:''].filter(Boolean).join(' · ')}
function decorateCard(card,id){const r=rows().find(x=>String(x.id)===String(id));if(!r||!card)return;let p=card.querySelector('.agSummary'),t=summaryText(r);if(t){if(!p){p=document.createElement('div');p.className='agSummary';card.appendChild(p)}p.textContent=t}else if(p)p.remove()}
function decorate(){document.querySelectorAll('[data-job-id]').forEach(card=>decorateCard(card,card.dataset.jobId));document.querySelectorAll('[data-open-today]').forEach(b=>decorateCard(b.closest('.todayCard'),b.dataset.openToday));document.querySelectorAll('[data-open-p]').forEach(b=>decorateCard(b.closest('.pendingCard'),b.dataset.openP))}
function boot(){inject();const modal=$('modal'),form=$('form');if(form&&!form.__agendaTasks){form.__agendaTasks=true;form.addEventListener('submit',()=>{const id=currentId();if(id)setTimeout(()=>{persist(id);decorate()},80)});window.addEventListener('agenda:new',()=>{clearTimeout(saveTimer);materials=[];checklist=[];lastId='';render()});window.addEventListener('agenda:saved',ev=>{const id=String(ev&&ev.detail&&ev.detail.id||'');if(id)setTimeout(()=>{persist(id);decorate()},30)})}const id=currentId();if(modal&&modal.classList.contains('open')&&id!==lastId){lastId=id;load()}if(modal&&!modal.classList.contains('open'))lastId='';decorate();setTimeout(boot,500)}
boot();
})();