(function(){'use strict';
const BUILD='V135-AGENDA-VOICE1';
let checking=false,lastCheck=0;
function loadSafe(){try{if(!document.getElementById('s135SafeExit')){let s=document.createElement('script');s.id='s135SafeExit';s.src='./safeexit135.js?build='+encodeURIComponent(BUILD)+'&t='+Date.now();document.head.appendChild(s)}else if(window.Soltec135SafeExit&&window.Soltec135SafeExit.init){window.Soltec135SafeExit.init()}}catch(e){}}
function loadSafeAutoHide(){try{if(!document.getElementById('s135SafeExitAutoHide')){let s=document.createElement('script');s.id='s135SafeExitAutoHide';s.src='./safeexit135autohide.js?build='+encodeURIComponent(BUILD)+'&t='+Date.now();document.head.appendChild(s)}else if(window.Soltec135SafeExitAutoHide&&window.Soltec135SafeExitAutoHide.init){window.Soltec135SafeExitAutoHide.init()}}catch(e){}}
function loadRecovery(){try{if(!document.getElementById('s134Recovery')){let s=document.createElement('script');s.id='s134Recovery';s.src='./sync134recovery.js?build='+encodeURIComponent(BUILD)+'&t='+Date.now();s.onload=loadRevFix;document.head.appendChild(s)}else{if(window.Soltec134Recovery&&window.Soltec134Recovery.init)window.Soltec134Recovery.init();loadRevFix()}}catch(e){}}
function loadRevFix(){try{if(!document.getElementById('s134RevFix')){let s=document.createElement('script');s.id='s134RevFix';s.src='./sync134revfix.js?build='+encodeURIComponent(BUILD)+'&t='+Date.now();document.head.appendChild(s)}}catch(e){}}
function loadMobileClose(){try{if(!document.getElementById('s135SyncMobileClose')){let s=document.createElement('script');s.id='s135SyncMobileClose';s.src='./sync135mobileclose.js?build='+encodeURIComponent(BUILD)+'&t='+Date.now();document.head.appendChild(s)}}catch(e){}}
function loadHomeLogo(){try{if(!document.getElementById('s135HomeCompanyLogoScript')){let s=document.createElement('script');s.id='s135HomeCompanyLogoScript';s.src='./homecompanylogo135.js?build='+encodeURIComponent(BUILD)+'&t='+Date.now();document.head.appendChild(s)}else if(window.Soltec135HomeCompanyLogo&&window.Soltec135HomeCompanyLogo.init){window.Soltec135HomeCompanyLogo.init()}}catch(e){}}
function loadPartsDirect(){try{if(!document.getElementById('s135PartsDirectFix')){let s=document.createElement('script');s.id='s135PartsDirectFix';s.src='./parts135directfix.js?build='+encodeURIComponent(BUILD)+'&t='+Date.now();document.head.appendChild(s)}else if(window.Soltec135PartesDirectFix&&window.Soltec135PartesDirectFix.init){let f=document.getElementById('app134');if(f&&f.contentWindow)window.Soltec135PartesDirectFix.init(f.contentWindow)}}catch(e){}}
function loadPartsObra(){try{if(!document.getElementById('s135PartsObra')){let s=document.createElement('script');s.id='s135PartsObra';s.src='./parts135obra.js?build='+encodeURIComponent(BUILD)+'&t='+Date.now();document.head.appendChild(s)}else if(window.Soltec135PartesObra&&window.Soltec135PartesObra.init){let f=document.getElementById('app134');if(f&&f.contentWindow)window.Soltec135PartesObra.init(f.contentWindow)}}catch(e){}}
function loadPartsPhotos(){try{if(!document.getElementById('s135PartsPhotos')){let s=document.createElement('script');s.id='s135PartsPhotos';s.src='./parts135photos.js?build='+encodeURIComponent(BUILD)+'&t='+Date.now();document.head.appendChild(s)}else if(window.Soltec135PartesFotos&&window.Soltec135PartesFotos.init){let f=document.getElementById('app134');if(f&&f.contentWindow)window.Soltec135PartesFotos.init(f.contentWindow)}}catch(e){}}
function loadPartsDelete(){try{if(!document.getElementById('s135PartsDelete')){let s=document.createElement('script');s.id='s135PartsDelete';s.src='./parts135delete.js?build='+encodeURIComponent(BUILD)+'&t='+Date.now();document.head.appendChild(s)}else if(window.Soltec135PartesDelete&&window.Soltec135PartesDelete.init){let f=document.getElementById('app134');if(f&&f.contentWindow)window.Soltec135PartesDelete.init(f.contentWindow)}}catch(e){}}
function loadAvisosModos(){try{let f=document.getElementById('app134'),w=f&&f.contentWindow;if(!document.getElementById('s135AvisosModos')){let s=document.createElement('script');s.id='s135AvisosModos';s.src='./avisos135modos.js?build='+encodeURIComponent(BUILD)+'&t='+Date.now();s.onload=()=>{try{if(window.Soltec135AvisosModos&&window.Soltec135AvisosModos.init)window.Soltec135AvisosModos.init(w)}catch(e){}};document.head.appendChild(s)}else if(window.Soltec135AvisosModos&&window.Soltec135AvisosModos.init){window.Soltec135AvisosModos.init(w)}}catch(e){}}
function loadCnmcPosition(){try{let f=document.getElementById('app134'),w=f&&f.contentWindow;if(!document.getElementById('s135CnmcPosition')){let s=document.createElement('script');s.id='s135CnmcPosition';s.src='./cnmc135position.js?build='+encodeURIComponent(BUILD)+'&t='+Date.now();s.onload=()=>{try{if(window.Soltec135CnmcPosition&&window.Soltec135CnmcPosition.init)window.Soltec135CnmcPosition.init(w)}catch(e){}};document.head.appendChild(s)}else if(window.Soltec135CnmcPosition&&window.Soltec135CnmcPosition.init){window.Soltec135CnmcPosition.init(w)}}catch(e){}}
function loadAvisosObraPres(){try{let f=document.getElementById('app134'),w=f&&f.contentWindow;if(!document.getElementById('s135AvisosObraPres')){let s=document.createElement('script');s.id='s135AvisosObraPres';s.src='./avisos135obrapresupuesto.js?build='+encodeURIComponent(BUILD)+'&t='+Date.now();s.onload=()=>{try{if(window.Soltec135AvisosObraPresupuesto&&window.Soltec135AvisosObraPresupuesto.init)window.Soltec135AvisosObraPresupuesto.init(w)}catch(e){}};document.head.appendChild(s)}else if(window.Soltec135AvisosObraPresupuesto&&window.Soltec135AvisosObraPresupuesto.init){window.Soltec135AvisosObraPresupuesto.init(w)}}catch(e){}}
function loadPartsNew(){/* Partes V1.35 se carga como módulo estable desde index.html. */}
function loadAgenda(){try{let f=document.getElementById('app134'),w=f&&f.contentWindow;if(!document.getElementById('s135Agenda')){let s=document.createElement('script');s.id='s135Agenda';s.src='./agenda135.js?build='+encodeURIComponent(BUILD)+'&t='+Date.now();s.onload=()=>{try{if(window.Soltec135Agenda&&window.Soltec135Agenda.init)window.Soltec135Agenda.init(w)}catch(e){}};document.head.appendChild(s)}else if(window.Soltec135Agenda&&window.Soltec135Agenda.init){window.Soltec135Agenda.init(w)}}catch(e){}}
function loadAvisosCliente(){try{if(!document.getElementById('s135AvisosCliente')){let s=document.createElement('script');s.id='s135AvisosCliente';s.src='./avisos135cliente.js?build='+encodeURIComponent(BUILD)+'&t='+Date.now();document.head.appendChild(s)}else if(window.Soltec135AvisosCliente&&window.Soltec135AvisosCliente.init){window.Soltec135AvisosCliente.init()}loadSafe();loadSafeAutoHide();loadRecovery();loadPartsNew();loadAgenda();loadMobileClose();loadHomeLogo();loadPartsDirect();loadPartsObra();loadPartsPhotos();loadPartsDelete();loadAvisosModos();loadCnmcPosition();loadAvisosObraPres()}catch(e){}}
async function check(){loadAvisosCliente();if(checking)return false;const now=Date.now();if(now-lastCheck<3000)return false;lastCheck=now;checking=true;try{const r=await fetch('./build134.json?t='+now,{cache:'no-store'});if(!r.ok)return false;const x=await r.json();const remote=String(x&&x.build||'');if(!remote||remote===BUILD)return false;try{if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.getRegistration('./');if(reg)await reg.update()}}catch(e){}setTimeout(()=>location.reload(),100);return true}catch(e){return false}finally{checking=false}}
window.Soltec134AppUpdate={BUILD,check,loadAvisosCliente,loadSafe,loadSafeAutoHide,loadRecovery,loadRevFix,loadPartsNew,loadAgenda,loadMobileClose,loadHomeLogo,loadPartsDirect,loadPartsObra,loadPartsPhotos,loadPartsDelete,loadAvisosModos,loadCnmcPosition,loadAvisosObraPres};
loadAvisosCliente();
window.addEventListener('pageshow',()=>setTimeout(check,250));
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')setTimeout(check,500)});
})();
