(function(){'use strict';
const BUILD='V135-NUEVO-DIRECCION1',MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',FLAGS='APP_AVISOS_FLAGS_V120';
let appWindow=null,patched=false,timer=0;
function findWindow(){try{const f=document.getElementById('app134');return f&&f.contentWindow&&f.contentWindow.document?f.contentWindow:null}catch(e){return null}}
function d(){return appWindow&&appWindow.document}
function el(id){const x=d();return x&&x.getElementById(id)}
function lab(id){const n=el(id);return n&&n.closest?n.closest('label'):null}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function store(k,def){try{const x=JSON.parse(appWindow.localStorage.getItem(k)||'null');return x&&typeof x==='object'?x:def}catch(_){return def}}
function condNotices(){const p=store(MAIN,{avisos:[]}),f=store(FLAGS,{});return (Array.isArray(p.avisos)?p.avisos:[]).filter(a=>a&&f[String(a.id)]&&f[String(a.id)].condicionesSuministro).sort((a,b)=>Number(b.id||0)-Number(a.id||0))}
function mark(node,on){if(!node)return;node.dataset.s135ModeHidden=on?'1':'0';if(!on)node.style.removeProperty('display')}
function installCss(){const x=d();if(!x||x.getElementById('s135AvisosModosStyle'))return;const s=x.createElement('style');s.id='s135AvisosModosStyle';s.textContent='#formAviso[data-s135-aviso-mode="simple"] [data-s135-mode-hidden="1"]{display:none!important}#s135DupWrap{margin-top:8px;padding:10px;border:1px solid #dbe3ee;border-radius:10px;background:#f8fafc}#s135DupWrap label{display:block;font-weight:800;color:#24466e}#s135DupSel{display:block;width:100%;margin-top:6px;padding:10px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}#s135DupMsg{font-size:12px;color:#667085;margin-top:6px}';x.head.appendChild(s)}
function allTechnical(){const x=d(),f=el('formAviso');if(!x||!f)return[];const out=[];
 ['s132Loc','av135CartoDetails','s133PlanBox','s132CupsReq','s132Extra','s132CliExtra','av135Solicitudes','s132MemBox','mem132','s132CondFile','s132ActBox'].forEach(id=>{const n=el(id);if(n)out.push(n)});
 ['avRefCatastral','avLatitud','avLongitud','avCupsE','avCupsG','avTension','avIga','avPotenciaCalculada','avPotenciaSolicitada'].forEach(id=>{const n=lab(id);if(n)out.push(n)});
 f.querySelectorAll('.cartoBox').forEach(n=>out.push(n));
 const grid=f.querySelector('.grid2');if(grid){let hide=false;Array.from(grid.children).forEach(n=>{if(n.classList&&n.classList.contains('sectionTitle')){const t=String(n.textContent||'').toUpperCase();if(/DATOS DEL AVISO/.test(t)){hide=false;return}hide=/DATOS EL[ÉE]CTRICOS|DATOS ADICIONALES|CNMC|SUMINISTRO/.test(t)}if(hide)out.push(n)})}
 f.querySelectorAll('details,.s132box,.s132acc,.cartoBox').forEach(n=>{const t=String(n.textContent||'').toUpperCase();if(/CNMC|CARTOCIUDAD|PLANO DE SITUACI|CUPS|DATOS EL[ÉE]CTRICOS|CONDICIONES DE SUMINISTRO ACTUALES|ACTUACIONES DE CONDICIONES|DATOS ADICIONALES DEL SUMINISTRO/.test(t))out.push(n)});
 const pot=el('potenciaAviso');if(pot)out.push(pot);return Array.from(new Set(out))}
function setCondFlag(on){const n=el('s132CondFlag');if(n)n.checked=!!on}
function applyMode(mode){const f=el('formAviso');if(!f)return;installCss();const simple=mode==='simple';f.dataset.s135AvisoMode=simple?'simple':'full';allTechnical().forEach(n=>mark(n,simple));if(!simple)f.querySelectorAll('[data-s135-mode-hidden]').forEach(n=>mark(n,false));const title=el('formAvisoTitulo');if(title&&simple)title.textContent='Nuevo aviso'}
function ensureSelector(){const s=el('crearAvisoModo');if(!s)return false;const wanted=[['','Seleccionar…'],['nuevo','Nuevo'],['condiciones','Con condiciones de suministro'],['duplicar','Duplicar aviso existente con condiciones de suministro']];const cur=Array.from(s.options).map(o=>o.value+'|'+o.textContent).join('||'),next=wanted.map(o=>o[0]+'|'+o[1]).join('||');if(cur!==next){const v=s.value;s.innerHTML=wanted.map(o=>'<option value="'+o[0]+'">'+o[1]+'</option>').join('');if(wanted.some(o=>o[0]===v))s.value=v}return true}
function hideDup(){const w=el('s135DupWrap');if(w)w.style.display='none'}
function showDup(origDup){installCss();let wrap=el('s135DupWrap'),main=el('crearAvisoModo');if(!main)return;if(!wrap){wrap=d().createElement('div');wrap.id='s135DupWrap';const host=main.closest('label')||main;host.insertAdjacentElement('afterend',wrap)}const arr=condNotices();wrap.style.display='block';if(!arr.length){wrap.innerHTML='<div id="s135DupMsg">No hay avisos guardados con condiciones de suministro.</div>';return}wrap.innerHTML='<label>Selecciona el aviso con condiciones de suministro<select id="s135DupSel"><option value="">Seleccionar aviso…</option>'+arr.map(a=>{const txt=['#'+a.id,a.cliente||'Sin cliente',a.direccion||'',a.localidad||''].filter(Boolean).join(' · ');return '<option value="'+esc(a.id)+'">'+esc(txt)+'</option>'}).join('')+'</select></label><div id="s135DupMsg">Elige el aviso exacto que quieres duplicar.</div>';const sel=el('s135DupSel');if(sel)sel.onchange=function(){const id=Number(sel.value||0);if(!id)return;if(origDup)origDup(id);const f=el('formAviso');if(f)f.dataset.s135TipoNuevo='condiciones';setCondFlag(true);applyMode('full');wrap.style.display='none';if(main)main.value=''}}
function patch(){if(!appWindow)appWindow=findWindow();const w=appWindow;if(!w||!w.App)return false;ensureSelector();if(patched)return true;patched=true;const A=w.App,origMode=A.crearAvisoModo&&A.crearAvisoModo.bind(A),origNew=A.nuevoAviso&&A.nuevoAviso.bind(A),origEdit=A.editarAviso&&A.editarAviso.bind(A),origDup=A.duplicarAviso&&A.duplicarAviso.bind(A),origCancel=A.cancelarAviso&&A.cancelarAviso.bind(A),origSave=A.guardarAviso&&A.guardarAviso.bind(A);
 A.crearAvisoModo=function(){const s=el('crearAvisoModo'),v=s?String(s.value||''):'';hideDup();if(v==='condiciones'){if(origNew)origNew();const f=el('formAviso');if(f)f.dataset.s135TipoNuevo='condiciones';setCondFlag(true);applyMode('full');if(s)s.value='';return}if(v==='nuevo'){if(origNew)origNew();const f=el('formAviso');if(f)f.dataset.s135TipoNuevo='simple';setCondFlag(false);applyMode('simple');if(s)s.value='';return}if(v==='duplicar'){showDup(origDup);return}if(origMode)origMode()};
 if(origNew)A.nuevoAviso=function(){hideDup();const r=origNew();const f=el('formAviso');if(f&&!f.dataset.s135TipoNuevo)f.dataset.s135TipoNuevo='simple';setCondFlag(false);applyMode('simple');return r};
 if(origSave)A.guardarAviso=function(){const f=el('formAviso'),tipo=f&&f.dataset.s135TipoNuevo||'';if(tipo==='condiciones')setCondFlag(true);else if(tipo==='simple')setCondFlag(false);return origSave()};
 if(origEdit)A.editarAviso=function(id){hideDup();const r=origEdit(id);const f=el('formAviso');if(f)delete f.dataset.s135TipoNuevo;applyMode('full');return r};
 if(origDup)A.duplicarAviso=function(id){hideDup();const r=origDup(id);const f=el('formAviso');if(f)f.dataset.s135TipoNuevo='condiciones';setCondFlag(true);applyMode('full');return r};
 if(origCancel)A.cancelarAviso=function(){hideDup();const r=origCancel();const f=el('formAviso');if(f)delete f.dataset.s135TipoNuevo;applyMode('full');return r};return true}
function tick(){if(!appWindow)appWindow=findWindow();if(!appWindow)return;ensureSelector();patch();const f=el('formAviso');if(f&&f.dataset.s135AvisoMode==='simple')applyMode('simple')}
function init(w){if(w)appWindow=w;tick();if(timer)return;timer=setInterval(tick,300);setTimeout(tick,100);setTimeout(tick,600);setTimeout(tick,1500)}
window.Soltec135AvisosModos={init,version:BUILD};init();
})();