(function(){'use strict';
const B='V135-AVISOS7-DATOSCLIENTE';let done=false;
function loadSalida(){try{if(!document.getElementById('s135SafeExit')){let s=document.createElement('script');s.id='s135SafeExit';s.src='./safeexit135.js?build='+encodeURIComponent(B)+'&t='+Date.now();document.head.appendChild(s)}else if(window.Soltec135SafeExit&&window.Soltec135SafeExit.init)window.Soltec135SafeExit.init()}catch(e){}}
function frame(){try{let f=document.getElementById('app134');return f&&f.contentWindow&&f.contentWindow.document?f.contentWindow:null}catch(e){return null}}
function S(v){return String(v==null?'':v)}
function lab(d,id){let n=d.getElementById(id);return n&&n.closest?n.closest('label'):null}
function gv(d,id){let n=d.getElementById(id);return n?S(n.value).trim():''}
function avisoText(d,tipo){let ids=['avFecha','avEstado','avCliente','avContacto','avNif','avTelefono','avEmail','avDireccion','avCp','avLocalidad','avProvincia','avCupsE','avCupsG','avRefCatastral','avTension','avIga','avPotenciaCalculada','avPotenciaSolicitada','avConcepto','avObservaciones'];let labs=['Fecha','Estado','Cliente / Razón social','Nombre persona de contacto','DNI / NIF / CIF','Teléfono','Correo electrónico','Dirección del suministro','CP','Población / Localidad','Provincia','CUPS Electricidad','CUPS Gas','Referencia catastral','Tensión','IGA (A)','Potencia instalación calculada (kW)','Potencia para condiciones de suministro (kW)','Concepto aclarador','Observaciones'];let out=['Buenos días.','','Solicitamos '+tipo+' para el suministro indicado.','','DATOS DE LA FICHA',''];ids.forEach(function(id,i){out.push(labs[i].toLocaleUpperCase('es-ES')+':');out.push(gv(d,id)||'—');out.push('')});out.push('Un saludo.');return out.join('\n')}
function datosClienteText(d){let ids=['avCliente','avContacto','avNif','avTelefono','avEmail','avDireccion','avCp','avLocalidad','avProvincia','avCupsE','avCupsG','avRefCatastral','avConcepto','avObservaciones'];let labs=['Cliente / Razón social','Nombre persona de contacto','DNI / NIF / CIF','Teléfono','Correo electrónico','Dirección del suministro','CP','Población / Localidad','Provincia','CUPS Electricidad','CUPS Gas','Referencia catastral','Concepto aclarador','Observaciones'];let out=['Buenos días.','','Por favor, revise y complete los siguientes datos para mantener actualizada la ficha del suministro.','','DATOS DEL CLIENTE',''];ids.forEach(function(id,i){out.push(labs[i].toLocaleUpperCase('es-ES')+':');out.push(gv(d,id)||'____________________________');out.push('')});out.push('Gracias.','Un saludo.');return out.join('\n')}
function abrir(tipo){let w=frame();if(!w)return;let d=w.document,dir=gv(d,'avDireccion'),to='',sub='',body='';if(tipo==='cliente'){to=gv(d,'avEmail');sub='Datos cliente - '+(dir||gv(d,'avCliente')||'suministro');body=datosClienteText(d)}else{sub=tipo==='contrato'?(dir||'Solicitud contrato de electricidad'):('Condiciones de suministro - '+(dir||gv(d,'avCliente')||'suministro'));body=avisoText(d,tipo==='contrato'?'contrato de electricidad':'condiciones de suministro')}let url='mailto:'+encodeURIComponent(to)+'?subject='+encodeURIComponent(sub)+'&body='+encodeURIComponent(body);try{w.location.href=url}catch(e){try{w.open(url,'_blank')}catch(x){}}}
function inject(d,afterNode){let box=d.getElementById('av135Solicitudes');if(!box){box=d.createElement('div');box.id='av135Solicitudes';box.className='wide';box.innerHTML='<div class="sectionTitle">Solicitudes y datos por correo</div><div class="row" style="align-items:stretch"><button type="button" id="avBtnCondSum">Condiciones de suministro</button><button type="button" class="primary" id="avBtnContratoElec">Contrato de electricidad</button></div><button type="button" id="avBtnDatosCliente" class="full" style="margin-top:10px">✉ Datos al cliente</button><p class="muted" style="margin:8px 0 0">Datos al cliente abre un correo dirigido al correo de la ficha, con asunto Datos cliente + dirección y la ficha preparada para revisar o completar.</p>';afterNode.parentNode.insertBefore(box,afterNode.nextSibling)}let a=d.getElementById('avBtnCondSum'),b=d.getElementById('avBtnContratoElec'),c=d.getElementById('avBtnDatosCliente');if(a)a.onclick=function(){abrir('condiciones')};if(b)b.onclick=function(){abrir('contrato')};if(c)c.onclick=function(){abrir('cliente')}}
function moveCups(){loadSalida();let w=frame();if(!w)return;let d=w.document,phone=lab(d,'avTelefono'),e=lab(d,'avCupsE'),g=lab(d,'avCupsG');if(!phone||!e||!g)return;let note=e.nextElementSibling===g?g.nextElementSibling:null;if(!(note&&note.classList&&note.classList.contains('muted')))note=g.nextElementSibling;try{e.classList.add('wide');g.classList.add('wide');if(note&&note.parentNode){note.classList.add('wide');note.style.margin='0 0 8px'}}catch(x){}phone.parentNode.insertBefore(e,phone.nextSibling);phone.parentNode.insertBefore(g,e.nextSibling);if(note&&note.parentNode)phone.parentNode.insertBefore(note,g.nextSibling);inject(d,note&&note.parentNode?note:g);let i=d.getElementById('avCupsE'),j=d.getElementById('avCupsG');if(i){i.placeholder='CUPS electricidad';i.autocomplete='off'}if(j){j.placeholder='CUPS gas';j.autocomplete='off'}done=true}
function init(){loadSalida();moveCups();setTimeout(moveCups,300);setTimeout(moveCups,1000);setInterval(function(){if(!done)moveCups();loadSalida()},2000)}
window.Soltec135AvisosCliente={init:init,version:B,contrato:function(){abrir('contrato')},condiciones:function(){abrir('condiciones')},datosCliente:function(){abrir('cliente')}};init();
})();