(function(){'use strict';
const MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',FLAGS='APP_AVISOS_FLAGS_V120',OBRA='APP_AVISOS_OBRA_PRESUPUESTO_V135';let W,observer;
const EDIST=(function(){try{return new URL('./assets/logo_e-distribucion.jpg',window.location.href).href}catch(_){return './assets/logo_e-distribucion.jpg'}})();
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
function data(){try{return JSON.parse(W.localStorage.getItem(MAIN)||'{}')||{}}catch(_){return{}}}
function flags(){try{return JSON.parse(W.localStorage.getItem(FLAGS)||'{}')||{}}catch(_){return{}}}function obras(){try{return JSON.parse(W.localStorage.getItem(OBRA)||'{}')||{}}catch(_){return{}}}
function status(v){return v==='finalizado'?'Finalizado':v==='en_curso'?'En curso':'Pendiente'}
function compact(){if(!W)return;const d=W.document,box=d.getElementById('listaAvisos');if(!box)return;const notices=(data().avisos||[]),fm=flags(),om=obras();Array.from(box.querySelectorAll('.al135-card[data-id]')).forEach(card=>{const id=Number(card.dataset.id||0),cond=!!(fm[String(id)]&&fm[String(id)].condicionesSuministro);card.classList.toggle('al135-cond-hidden',cond)});Array.from(box.querySelectorAll('.avisoCard:not(.al135-card)')).forEach(card=>{const edit=card.querySelector('button[onclick*="editarAviso"]'),hit=edit&&String(edit.getAttribute('onclick')||'').match(/editarAviso\((\d+)\)/),id=hit?Number(hit[1]):0,a=notices.find(x=>Number(x.id)===id)||{},op=om[String(id)]||{},cond=!!(fm[String(id)]&&fm[String(id)].condicionesSuministro),det=d.createElement('details');det.className='avisoCard al135-card'+(cond?' al135-cond-hidden':'');det.dataset.id=String(id);const summary=d.createElement('summary'),place=[a.direccion,a.piso&&('Piso '+a.piso),a.puerta&&('Puerta '+a.puerta),a.cp,a.localidad].filter(Boolean).join(' · ');summary.innerHTML='<span class="al135-main"><strong>'+esc(a.cliente||'SIN CLIENTE')+'</strong><small>'+esc(place||'SIN DIRECCIÓN')+'</small>'+(op.obra||op.presupuesto==='SI'?'<small class="al135-obra">'+esc(op.obra||'SIN OBRA')+(op.presupuesto==='SI'?' · PRESUPUESTO'+(op.numero?' '+esc(op.numero):''):'')+'</small>':'')+'</span><span class="al135-state">'+(cond?'<img class="al135-edist" src="'+EDIST+'" alt="e-distribución" title="Condiciones de suministro">':'')+'<span class="badge '+esc(a.estado||'pendiente')+'">'+esc(status(a.estado))+'</span></span>';const body=d.createElement('div');body.className='al135-body';while(card.firstChild)body.appendChild(card.firstChild);det.appendChild(summary);det.appendChild(body);card.replaceWith(det)})}
function style(d){if(d.getElementById('avisosList135Style'))return;const s=d.createElement('style');s.id='avisosList135Style';s.textContent='.al135-card{padding:0!important;overflow:hidden}.al135-cond-hidden{display:none!important}.al135-card>summary{display:flex;align-items:center;justify-content:space-between;gap:10px;cursor:pointer;list-style:none;padding:12px 13px;background:#fff}.al135-card>summary::-webkit-details-marker{display:none}.al135-card>summary:after{content:"▾";color:#e7281c;font-size:18px}.al135-card[open]>summary:after{content:"▴"}.al135-main{display:flex;flex:1;min-width:0;flex-direction:column;gap:3px}.al135-main strong{font-size:14px;color:#172b4d;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.al135-main small{font-size:12px;color:#667085;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.al135-obra{color:#344054!important;font-weight:700}.al135-state{display:flex;align-items:center;gap:8px;margin-left:auto;white-space:nowrap}.al135-edist{width:68px;height:38px;object-fit:contain;display:block;border-radius:3px;background:#fff;flex:0 0 auto}.al135-card>summary .badge{white-space:nowrap}.al135-body{padding:0 12px 12px;border-top:1px solid #e5eaf0}.al135-body>.avisoTop{display:none}.al135-body .actions{margin-top:10px}@media(max-width:520px){.al135-card>summary{align-items:flex-start;flex-wrap:wrap}.al135-state{margin-left:0}.al135-main{flex-basis:58%}.al135-edist{width:60px;height:34px}}';d.head.appendChild(s)}
function hook(d){const A=W.App;if(!A||A.__list135)return;A.__list135=true;['show','filtrarAvisos','guardarAviso','eliminarAviso','restaurarAviso'].forEach(name=>{if(!A[name])return;const old=A[name].bind(A);A[name]=function(){const r=old.apply(null,arguments);setTimeout(compact,0);return r}});const box=d.getElementById('listaAvisos');if(box&&!observer){observer=new MutationObserver(()=>compact());observer.observe(box,{childList:true})}}
window.SoltecAvisosList135={init(w){W=w;const d=w.document;style(d);hook(d);compact();setTimeout(compact,150);setTimeout(compact,700)}}})();