(function(){'use strict';
const B='V135-ONECLICK3-TECLADO';let done=false,planObs=null,started=false;
function loadSalida(){try{if(!document.getElementById('s135SafeExit')){let s=document.createElement('script');s.id='s135SafeExit';s.src='./safeexit135.js?build='+encodeURIComponent(B)+'&t='+Date.now();document.head.appendChild(s)}else if(window.Soltec135SafeExit&&window.Soltec135SafeExit.init)window.Soltec135SafeExit.init()}catch(e){}}
function frame(){try{let f=document.getElementById('app134');return f&&f.contentWindow&&f.contentWindow.document?f.contentWindow:null}catch(e){return null}}
function S(v){return String(v==null?'':v)}
function lab(d,id){let n=d.getElementById(id);return n&&n.closest?n.closest('label'):null}
function gv(d,id){let n=d.getElementById(id);return n?S(n.value).trim():''}
function iban(d){return gv(d,'s132Iban')}
function addUnits(fields,d){let i=fields.findIndex(function(f){return f[0]==='Dirección del suministro'});if(i>=0)fields.splice(i+1,0,['Piso',()=>gv(d,'avPiso')],['Puerta',()=>gv(d,'avPuerta')])}
function avisoText(d,tipo){let fields=[['Fecha',()=>gv(d,'avFecha')],['Estado',()=>gv(d,'avEstado')],['Dirección del suministro',()=>gv(d,'avDireccion')],['Cliente / Razón social',()=>gv(d,'avCliente')],['Nombre persona de contacto',()=>gv(d,'avContacto')],['DNI / NIF / CIF',()=>gv(d,'avNif')],['Teléfono',()=>gv(d,'avTelefono')],['Correo electrónico',()=>gv(d,'avEmail')],['IBAN',()=>iban(d)],['CP',()=>gv(d,'avCp')],['Población / Localidad',()=>gv(d,'avLocalidad')],['Provincia',()=>gv(d,'avProvincia')],['CUPS Electricidad',()=>gv(d,'avCupsE')],['CUPS Gas',()=>gv(d,'avCupsG')],['Referencia catastral',()=>gv(d,'avRefCatastral')],['Tensión',()=>gv(d,'avTension')],['IGA (A)',()=>gv(d,'avIga')],['Potencia instalación calculada (kW)',()=>gv(d,'avPotenciaCalculada')],['Potencia para condiciones de suministro (kW)',()=>gv(d,'avPotenciaSolicitada')],['Concepto aclarador',()=>gv(d,'avConcepto')],['Observaciones',()=>gv(d,'avObservaciones')]],out=['Buenos días.','','Solicitamos '+tipo+' para el suministro indicado.','','DATOS DE LA FICHA',''];addUnits(fields,d);if(tipo==='contrato de electricidad'){let p=fields.findIndex(function(f){return f[0]==='Correo electrónico'});fields.splice(p+1,0,['Dirección fiscal / facturación',()=>gv(d,'avDireccionFiscal')],['Correo fiscal / facturación',()=>gv(d,'avEmailFiscal')])}fields.forEach(function(f){out.push(f[0].toLocaleUpperCase('es-ES')+':');out.push(f[1]()||'—');out.push('')});out.push('Un saludo.');return out.join('\n')}
function datosClienteText(d){let fields=[['Dirección del suministro',()=>gv(d,'avDireccion')],['Cliente / Razón social',()=>gv(d,'avCliente')],['Nombre persona de contacto',()=>gv(d,'avContacto')],['DNI / NIF / CIF',()=>gv(d,'avNif')],['Teléfono',()=>gv(d,'avTelefono')],['Correo electrónico',()=>gv(d,'avEmail')],['IBAN',()=>iban(d)],['CP',()=>gv(d,'avCp')],['Población / Localidad',()=>gv(d,'avLocalidad')],['Provincia',()=>gv(d,'avProvincia')],['CUPS Electricidad',()=>gv(d,'avCupsE')],['CUPS Gas',()=>gv(d,'avCupsG')],['Referencia catastral',()=>gv(d,'avRefCatastral')],['Concepto aclarador',()=>gv(d,'avConcepto')],['Observaciones',()=>gv(d,'avObservaciones')]],out=['Buenos días.','','Por favor, revise y complete los siguientes datos para mantener actualizada la ficha del suministro.','','DATOS DEL CLIENTE',''];addUnits(fields,d);fields.forEach(function(f){out.push(f[0].toLocaleUpperCase('es-ES')+':');out.push(f[1]()||'____________________________');out.push('')});out.push('Gracias.','Un saludo.');return out.join('\n')}
function abrir(tipo){let w=frame();if(!w)return;let d=w.document,dir=gv(d,'avDireccion'),to='',sub='',body='';if(tipo==='cliente'){to=gv(d,'avEmail');sub='Datos cliente - '+(dir||gv(d,'avCliente')||'suministro');body=datosClienteText(d)}else{sub=tipo==='contrato'?(dir||'Solicitud contrato de electricidad'):('Condiciones de suministro - '+(dir||gv(d,'avCliente')||'suministro'));body=avisoText(d,tipo==='contrato'?'contrato de electricidad':'condiciones de suministro')}let url='mailto:'+encodeURIComponent(to)+'?subject='+encodeURIComponent(sub)+'&body='+encodeURIComponent(body);try{w.location.href=url}catch(e){try{w.open(url,'_blank')}catch(x){}}}
function inject(d){let box=d.getElementById('av135Solicitudes');if(!box){box=d.createElement('div');box.id='av135Solicitudes';box.className='wide';box.innerHTML='<div class="sectionTitle">Solicitudes y datos por correo</div><div class="grid2" style="margin-bottom:10px"><label class="wide">Dirección fiscal / de facturación (solo contrato)<input id="avDireccionFiscal" autocomplete="street-address"></label><label class="wide">Correo fiscal / de facturación (solo contrato)<input id="avEmailFiscal" type="email" autocomplete="email"></label></div><div class="row" style="align-items:stretch"><button type="button" id="avBtnCondSum">Condiciones de suministro</button><button type="button" class="primary" id="avBtnContratoElec">Contrato de electricidad</button></div><button type="button" id="avBtnDatosCliente" class="full" style="margin-top:10px">✉ Datos al cliente</button><p class="muted" style="margin:8px 0 0">Los datos fiscales solo se incluyen en el contrato; no aparecen en la memoria CNMC.</p>'}let a=d.getElementById('avBtnCondSum'),b=d.getElementById('avBtnContratoElec'),c=d.getElementById('avBtnDatosCliente');if(a)a.onclick=function(){abrir('condiciones')};if(b)b.onclick=function(){abrir('contrato')};if(c)c.onclick=function(){abrir('cliente')};return box}
function editing(d){let a=d&&d.activeElement;if(!a||!a.closest||!a.closest('#formAviso'))return false;let t=String(a.tagName||'').toUpperCase();return t==='INPUT'||t==='TEXTAREA'||t==='SELECT'||!!a.isContentEditable}
function after(parent,node,ref){if(parent&&node&&ref&&ref.parentNode===parent&&ref.nextSibling!==node)parent.insertBefore(node,ref.nextSibling)}
function hideOldFlags(d){['s132CondFlag','s132Contrato'].forEach(function(id){let n=d.getElementById(id),sw=n&&n.closest?n.closest('.s132switch'):null;if(sw)sw.style.display='none'})}
function stableLayout(){layout();let w=frame(),d=w&&w.document;if(!d||editing(d))return;let address=lab(d,'avDireccion'),floor=lab(d,'avPiso'),door=lab(d,'avPuerta');if(!address||!floor||!door)return;if(address.nextElementSibling!==floor)address.insertAdjacentElement('afterend',floor);if(floor.nextElementSibling!==door)floor.insertAdjacentElement('afterend',door)}
function cartoDetails(d){let det=d.getElementById('av135CartoDetails'),old=det||d.querySelector('#formAviso .cartoBox');if(!old)return null;if(!det){if(old.tagName&&old.tagName.toLowerCase()==='details'){old.id='av135CartoDetails';det=old}else{det=d.createElement('details');det.id='av135CartoDetails';det.className=old.className;det.open=true;let sum=d.createElement('summary');sum.id='av135CartoSummary';sum.style.cssText='cursor:pointer;font-size:14px;font-weight:900;color:#24466e;padding:4px 0 8px';sum.textContent='📍 CartoCiudad · dirección y coordenadas';det.appendChild(sum);while(old.firstChild)det.appendChild(old.firstChild);old.replaceWith(det);let first=det.querySelector(':scope > strong');if(first)first.style.display='none'}}let res=d.getElementById('cartoResultados');if(res&&!res.dataset.av135Collapse){res.dataset.av135Collapse='1';res.addEventListener('click',function(ev){let b=ev.target&&ev.target.closest?ev.target.closest('.cartoResult'):null;if(!b)return;setTimeout(function(){let x=d.getElementById('av135CartoDetails');if(x&&gv(d,'avDireccion')){x.open=false;x.dataset.av135Key=[gv(d,'avId'),gv(d,'avDireccion'),gv(d,'avLatitud'),gv(d,'avLongitud')].join('|');let s=d.getElementById('av135CartoSummary');if(s)s.textContent='📍 CartoCiudad · '+gv(d,'avDireccion')}let p=d.getElementById('s133PlanBox');if(p&&p.tagName.toLowerCase()==='details'&&!planSaved(d))p.open=true},450)},true)}let key=[gv(d,'avId'),gv(d,'avDireccion'),gv(d,'avLatitud'),gv(d,'avLongitud')].join('|');if(det.dataset.av135Key!==key){det.dataset.av135Key=key;let ready=!!(gv(d,'avDireccion')&&gv(d,'avLatitud')&&gv(d,'avLongitud'));det.open=!ready;let s=d.getElementById('av135CartoSummary');if(s)s.textContent=ready?'📍 CartoCiudad · '+gv(d,'avDireccion'):'📍 CartoCiudad · dirección y coordenadas'}return det}
function planSaved(d){let im=d.getElementById('s133PlanImg'),st=d.getElementById('s133PlanStatus');return !!((im&&im.style.display==='block'&&im.getAttribute('src'))||(st&&/PLANO GUARDADO/i.test(st.textContent||'')))}
function syncPlan(d,collapse){let det=d.getElementById('s133PlanBox');if(!det||det.tagName.toLowerCase()!=='details')return;let sum=d.getElementById('av135PlanSummary'),saved=planSaved(d),prev=det.dataset.av135Saved;if(sum)sum.textContent=saved?'✅ Plano de situación guardado':'🗺 Plano de situación';if(saved&&(collapse||prev!=='1'))det.open=false;if(!saved&&prev==='1')det.open=true;det.dataset.av135Saved=saved?'1':'0'}
function planDetails(d){let box=d.getElementById('s133PlanBox');if(!box)return null;if(box.tagName.toLowerCase()!=='details'){let det=d.createElement('details');det.id='s133PlanBox';det.className=box.className;det.open=!planSaved(d);let sum=d.createElement('summary');sum.id='av135PlanSummary';sum.style.cssText='cursor:pointer;font-size:14px;font-weight:900;color:#24466e;padding:4px 0 8px';sum.textContent='🗺 Plano de situación';det.appendChild(sum);while(box.firstChild)det.appendChild(box.firstChild);box.replaceWith(det);let title=det.querySelector(':scope > .sectionTitle');if(title)title.style.display='none';box=det}syncPlan(d,false);let st=d.getElementById('s133PlanStatus');if(st&&!st.dataset.av135Observe){st.dataset.av135Observe='1';try{planObs=new MutationObserver(function(){syncPlan(d,true)});planObs.observe(st,{childList:true,subtree:true,characterData:true})}catch(e){}}return box}
function layout(){loadSalida();let w=frame();if(!w)return;let d=w.document,grid=d.querySelector('#formAviso .grid2');if(!grid||editing(d))return;hideOldFlags(d);let title=Array.from(grid.querySelectorAll('.sectionTitle')).find(function(x){return /FICHA DE CLIENTE|CLIENTE Y SUMINISTRO/i.test(x.textContent||'')});let address=lab(d,'avDireccion'),client=lab(d,'avCliente'),contact=lab(d,'avContacto'),nif=lab(d,'avNif'),phone=lab(d,'avTelefono'),email=lab(d,'avEmail'),ibanLab=lab(d,'s132Iban'),cp=lab(d,'avCp'),local=lab(d,'avLocalidad'),prov=lab(d,'avProvincia'),ref=lab(d,'avRefCatastral'),cupsE=lab(d,'avCupsE'),cupsG=lab(d,'avCupsG');if(!title||!address||!phone||!email||!ibanLab||!cp||!local||!prov)return;[address,client,contact,nif,phone,email,ibanLab,cp,local,prov,ref].forEach(function(n){if(n)n.classList.add('wide')});let chain=title;[address,client,contact,nif,phone,email,ibanLab,cp,local,prov,ref].forEach(function(n){if(n){after(grid,n,chain);chain=n}});let cli=d.getElementById('s132CliExtra');if(cli)cli.style.display='none';let cart=cartoDetails(d);if(cart){after(grid,cart,chain);chain=cart}let plan=planDetails(d);if(plan){after(grid,plan,chain);chain=plan}if(cupsE){cupsE.classList.add('wide');after(grid,cupsE,chain);chain=cupsE}if(cupsG){cupsG.classList.add('wide');after(grid,cupsG,chain);chain=cupsG}let note=cupsG?cupsG.nextElementSibling:null;if(!(note&&note.classList&&note.classList.contains('muted')))note=null;if(note){note.classList.add('wide');after(grid,note,chain);chain=note}let cupsReq=d.getElementById('s132CupsReq');if(cupsReq){after(grid,cupsReq,chain);chain=cupsReq}let mail=inject(d);if(mail){after(grid,mail,chain);chain=mail}let i=d.getElementById('avCupsE'),j=d.getElementById('avCupsG');if(i){i.placeholder='CUPS electricidad';i.autocomplete='off'}if(j){j.placeholder='CUPS gas';j.autocomplete='off'}done=true}
function init(){stableLayout();if(started)return;started=true;setTimeout(stableLayout,300);setTimeout(stableLayout,1000);setTimeout(stableLayout,2200)}
window.Soltec135AvisosCliente={init:init,version:B,contrato:function(){abrir('contrato')},condiciones:function(){abrir('condiciones')},datosCliente:function(){abrir('cliente')}};init();
})();
