(function(){'use strict';
const B='V135-AVISOS2-SOLICITUDES';let done=false;
function frame(){try{let f=document.getElementById('app134');return f&&f.contentWindow&&f.contentWindow.document?f.contentWindow:null}catch(e){return null}}
function S(v){return String(v==null?'':v)}
function lab(d,id){let n=d.getElementById(id);return n&&n.closest?n.closest('label'):null}
function gv(d,id){let n=d.getElementById(id);return n?S(n.value).trim():''}
function avisoText(d,tipo){let ids=['avFecha','avEstado','avCliente','avContacto','avNif','avTelefono','avEmail','avDireccion','avCp','avLocalidad','avProvincia','avCupsE','avCupsG','avRefCatastral','avTension','avIga','avPotenciaCalculada','avPotenciaSolicitada','avConcepto','avObservaciones'];let labs=['Fecha','Estado','Cliente','Contacto','Identificación','Teléfono','Correo','Dirección','CP','Localidad','Provincia','CUPS electricidad','CUPS gas','Referencia catastral','Tensión','IGA','Potencia calculada','Potencia solicitada','Concepto','Observaciones'];let out=['Buenos días.','','Solicitamos '+tipo+' para el suministro indicado.','','Datos del aviso:'];ids.forEach(function(id,i){out.push(labs[i]+': '+gv(d,id))});out.push('','Un saludo.');return out.join('\n')}
function abrir(tipo){let w=frame();if(!w)return;let d=w.document,dir=gv(d,'avDireccion'),sub=tipo==='contrato'?(dir||'Solicitud contrato de electricidad'):('Condiciones de suministro - '+(dir||gv(d,'avCliente')||'suministro')),body=avisoText(d,tipo==='contrato'?'contrato de electricidad':'condiciones de suministro'),url='mailto:?subject='+encodeURIComponent(sub)+'&body='+encodeURIComponent(body);try{w.location.href=url}catch(e){try{w.open(url,'_blank')}catch(x){}}}
function inject(d,afterNode){let box=d.getElementById('av135Solicitudes');if(!box){box=d.createElement('div');box.id='av135Solicitudes';box.className='wide';box.innerHTML='<div class="sectionTitle">Solicitudes a comercializadora</div><div class="row" style="align-items:stretch"><button type="button" id="avBtnCondSum">Condiciones de suministro</button><button type="button" class="primary" id="avBtnContratoElec">Contrato de electricidad</button></div><p class="muted" style="margin:8px 0 0">Contrato de electricidad abre correo con la dirección en el asunto y los datos del aviso en el cuerpo.</p>';afterNode.parentNode.insertBefore(box,afterNode.nextSibling)}let a=d.getElementById('avBtnCondSum'),b=d.getElementById('avBtnContratoElec');if(a)a.onclick=function(){abrir('condiciones')};if(b)b.onclick=function(){abrir('contrato')}}
function moveCups(){let w=frame();if(!w)return;let d=w.document,phone=lab(d,'avTelefono'),e=lab(d,'avCupsE'),g=lab(d,'avCupsG');if(!phone||!e||!g)return;let note=e.nextElementSibling===g?g.nextElementSibling:null;if(!(note&&note.classList&&note.classList.contains('muted')))note=g.nextElementSibling;try{e.classList.add('wide');g.classList.add('wide');if(note&&note.parentNode){note.classList.add('wide');note.style.margin='0 0 8px'}}catch(x){}phone.parentNode.insertBefore(e,phone.nextSibling);phone.parentNode.insertBefore(g,e.nextSibling);if(note&&note.parentNode)phone.parentNode.insertBefore(note,g.nextSibling);inject(d,note&&note.parentNode?note:g);let i=d.getElementById('avCupsE'),j=d.getElementById('avCupsG');if(i){i.placeholder='CUPS electricidad';i.autocomplete='off'}if(j){j.placeholder='CUPS gas';j.autocomplete='off'}done=true}
function init(){moveCups();setTimeout(moveCups,300);setTimeout(moveCups,1000);setInterval(function(){if(!done)moveCups()},2000)}
window.Soltec135AvisosCliente={init:init,version:B,contrato:function(){abrir('contrato')},condiciones:function(){abrir('condiciones')}};init();
})();