(function(){'use strict';
const BUILD='V135-AVISOS-MODOS2';
let appWindow=null,timer=0,patchedApp=null;
function resolveWindow(){try{if(appWindow&&appWindow.document&&appWindow.document.getElementById('crearAvisoModo'))return appWindow;const f=document.getElementById('app134');if(f&&f.contentWindow&&f.contentWindow.document)return f.contentWindow}catch(e){}return appWindow}
function d(){const w=resolveWindow();return w&&w.document}
function el(id){const x=d();return x&&x.getElementById(id)}
function lab(id){const n=el(id);return n&&n.closest?n.closest('label'):null}
function section(re){const x=d();if(!x)return null;return Array.from(x.querySelectorAll('#formAviso .sectionTitle')).find(n=>re.test(String(n.textContent||'')))||null}
function ensureCss(){const x=d();if(!x||x.getElementById('s135AvisosModosStyle'))return;const s=x.createElement('style');s.id='s135AvisosModosStyle';s.textContent=`#formAviso[data-s135-aviso-mode="simple"] #s132Loc,#formAviso[data-s135-aviso-mode="simple"] #av135CartoDetails,#formAviso[data-s135-aviso-mode="simple"] #s133PlanBox,#formAviso[data-s135-aviso-mode="simple"] #s132CupsReq,#formAviso[data-s135-aviso-mode="simple"] #s132Extra,#formAviso[data-s135-aviso-mode="simple"] #s132CliExtra,#formAviso[data-s135-aviso-mode="simple"] #av135Solicitudes,#formAviso[data-s135-aviso-mode="simple"] .cartoBox,#formAviso[data-s135-aviso-mode="simple"] [data-s135-tech="1"]{display:none!important}`;x.head.appendChild(s)}
function markTechnical(){const x=d();if(!x)return;['avRefCatastral','avDireccion','avPiso','avPuerta','avCp','avLocalidad','avProvincia','avLatitud','avLongitud','avCupsE','avCupsG','avTension','avIga','avPotenciaCalculada','avPotenciaSolicitada'].forEach(id=>{const n=lab(id);if(n)n.dataset.s135Tech='1'});const loc=section(/UBICACI[ÓO]N DEL SUMINISTRO/i),elec=section(/DATOS EL[EÉ]CTRICOS/i);if(loc)loc.dataset.s135Tech='1';if(elec)elec.dataset.s135Tech='1';const pot=el('potenciaAviso');if(pot)pot.dataset.s135Tech='1';const ref=lab('avRefCatastral');if(ref)ref.dataset.s135Tech='1';const cupE=lab('avCupsE'),cupG=lab('avCupsG');[cupE,cupG].forEach(n=>{if(n&&n.nextElementSibling&&n.nextElementSibling.classList&&n.nextElementSibling.classList.contains('muted'))n.nextElementSibling.dataset.s135Tech='1'})}
function applyMode(mode){const f=el('formAviso');if(!f)return;ensureCss();markTechnical();f.dataset.s135AvisoMode=mode==='simple'?'simple':'full';const t=el('formAvisoTitulo');if(t&&mode==='simple')t.textContent='Nuevo aviso'}
function ensureSelector(){const s=el('crearAvisoModo');if(!s)return false;const wanted=[['','Seleccionar…'],['nuevo','Nuevo'],['condiciones','Con condiciones de suministro'],['duplicar','Duplicar aviso existente']];const signature=Array.from(s.options).map(o=>o.value+'|'+o.textContent).join('||'),expected=wanted.map(o=>o[0]+'|'+o[1]).join('||');if(signature!==expected){const v=s.value;s.innerHTML=wanted.map(o=>'<option value="'+o[0]+'">'+o[1]+'</option>').join('');if(wanted.some(o=>o[0]===v))s.value=v}return true}
function patch(){const w=resolveWindow();if(!w||!w.App)return false;appWindow=w;ensureSelector();ensureCss();markTechnical();if(patchedApp===w.App)return true;patchedApp=w.App;const A=w.App,origMode=typeof A.crearAvisoModo==='function'?A.crearAvisoModo.bind(A):null,origNew=typeof A.nuevoAviso==='function'?A.nuevoAviso.bind(A):null,origEdit=typeof A.editarAviso==='function'?A.editarAviso.bind(A):null,origDup=typeof A.duplicarAviso==='function'?A.duplicarAviso.bind(A):null,origCancel=typeof A.cancelarAviso==='function'?A.cancelarAviso.bind(A):null;
A.crearAvisoModo=function(){const s=el('crearAvisoModo'),v=s?String(s.value||''):'';if(v==='condiciones'){if(s)s.value='nuevo';if(origMode)origMode();else if(origNew)origNew();applyMode('full');if(s)s.value='';return}if(v==='nuevo'){if(origMode)origMode();else if(origNew)origNew();applyMode('simple');setTimeout(()=>applyMode('simple'),100);setTimeout(()=>applyMode('simple'),500);return}if(origMode)origMode();if(v==='duplicar')applyMode('full')};
if(origNew)A.nuevoAviso=function(){const r=origNew();applyMode('simple');setTimeout(()=>applyMode('simple'),150);return r};
if(origEdit)A.editarAviso=function(id){const r=origEdit(id);applyMode('full');return r};
if(origDup)A.duplicarAviso=function(id){const r=origDup(id);applyMode('full');return r};
if(origCancel)A.cancelarAviso=function(){const r=origCancel();applyMode('full');return r};
return true}
function tick(){try{patch();ensureSelector();markTechnical();const f=el('formAviso');if(f&&f.dataset.s135AvisoMode==='simple')applyMode('simple')}catch(e){}}
function init(w){if(w)appWindow=w;tick();clearInterval(timer);timer=setInterval(tick,500)}
window.Soltec135AvisosModos={init,version:BUILD,applyMode};
init();
})();