(function(){'use strict';
const BUILD='V135-CNMC-DESGLOSE1';let W=null,timer=0,bound=false;
function d(){return W&&W.document}function e(id){const x=d();return x&&x.getElementById(id)}
function num(id){const n=parseFloat(String((e(id)||{}).value||'').replace(',','.'));return Number.isFinite(n)?n:0}
function fmt(n){return String(Math.round(n*100)/100).replace('.',',')}
function totals(){let a=0,b=0,c=0,g=0;for(let i=1;i<=3;i++)a+=num('t135VivPotencia'+i);for(let i=1;i<=2;i++)b+=num('t135LocPotencia'+i);for(let i=0;i<3;i++)c+=num('t135SerPotencia'+i);for(let i=0;i<2;i++)g+=num('t135GarPotencia'+i);return{a,b,c,d:g,total:a+b+c+g}}
function ensureSummary(){const box=e('s135Technical');if(!box)return null;let s=e('s135CnmcTotals');if(!s){s=d().createElement('div');s.id='s135CnmcTotals';s.className='s135-cnmc-totals';s.innerHTML='<div><span>A · Viviendas</span><strong id="s135CnmcA">0 kW</strong></div><div><span>B · Locales</span><strong id="s135CnmcB">0 kW</strong></div><div><span>C · Servicios comunes</span><strong id="s135CnmcC">0 kW</strong></div><div><span>D · Garajes</span><strong id="s135CnmcD">0 kW</strong></div><div class="total"><span>Potencia solicitada A+B+C+D</span><strong id="s135CnmcTotal">0 kW</strong></div>';const body=box.querySelector('.s132body');if(body)body.insertBefore(s,body.firstChild);else box.appendChild(s)}return s}
function ensureStyle(){const x=d();if(!x||x.getElementById('s135CnmcTotalsStyle'))return;const s=x.createElement('style');s.id='s135CnmcTotalsStyle';s.textContent='.s135-cnmc-totals{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin:8px 0 12px}.s135-cnmc-totals>div{border:1px solid #dbe3ee;border-radius:9px;padding:8px;background:#f8fafc}.s135-cnmc-totals span{display:block;font-size:11px;color:#667085;font-weight:800}.s135-cnmc-totals strong{display:block;margin-top:3px;font-size:15px;color:#173b68}.s135-cnmc-totals .total{grid-column:1/-1;border:2px solid #e7281c;background:#fff7f6}.s135-cnmc-totals .total strong{font-size:18px;color:#8f1d16}@media(max-width:620px){.s135-cnmc-totals{grid-template-columns:repeat(2,minmax(0,1fr))}}';x.head.appendChild(s)}
function calc(){ensureStyle();ensureSummary();const t=totals(),out=e('t135PotenciaTotal');[['s135CnmcA',t.a],['s135CnmcB',t.b],['s135CnmcC',t.c],['s135CnmcD',t.d],['s135CnmcTotal',t.total]].forEach(x=>{const n=e(x[0]);if(n)n.textContent=fmt(x[1])+' kW'});if(out){out.value=fmt(t.total);out.readOnly=true;out.dataset.cnmcAuto='1';const lab=out.closest&&out.closest('label');if(lab&&lab.firstChild)lab.firstChild.nodeValue='Potencia solicitada CNMC · A+B+C+D (kW)'}}
function place(){const x=d(),box=e('s135Technical');if(!x||!box)return false;const sum=box.querySelector(':scope > summary');if(sum)sum.textContent='📄 CNMC · Datos técnicos';const buttons=Array.from(x.querySelectorAll('#formAviso button,input[type="submit"]'));const save=buttons.find(n=>/GUARDAR\s+AVISO/i.test(String(n.textContent||n.value||'')));if(save){const anchor=save.closest('.row')||save.closest('.actions')||save;if(anchor&&anchor.parentNode&&box.nextSibling!==anchor)anchor.parentNode.insertBefore(box,anchor)}calc();return true}
function bind(){const x=d();if(!x||bound)return;bound=true;x.addEventListener('input',ev=>{const id=String(ev.target&&ev.target.id||'');if(/^t135(Viv|Loc|Ser|Gar)Potencia/.test(id))calc()},true);x.addEventListener('change',ev=>{const id=String(ev.target&&ev.target.id||'');if(/^t135(Viv|Loc|Ser|Gar)Potencia/.test(id))calc()},true)}
function tick(){if(!W){try{const f=document.getElementById('app134');if(f&&f.contentWindow&&f.contentWindow.document)W=f.contentWindow}catch(_){}}if(!W)return;bind();place()}
function init(w){if(w)W=w;tick();if(timer)return;timer=setInterval(tick,500);setTimeout(tick,120);setTimeout(tick,700);setTimeout(tick,1600)}
window.Soltec135CnmcPosition={init,version:BUILD};init();
})();