(function(){'use strict';
const CFG='APP_AVISOS_CONFIG_V127';let W,emails=[],primary='';
const el=(d,id)=>d.getElementById(id),parse=(v,x)=>{try{return JSON.parse(v||'')||x}catch(_){return x}},clean=v=>String(v||'').trim().toLowerCase();
function valid(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
function load(){const c=parse(W.localStorage.getItem(CFG),{}),m=c.emails||{},list=Array.isArray(m.comercializadora1Lista)?m.comercializadora1Lista:[];emails=list.map(clean).filter(valid);const old=clean(m.comercializadora1);if(old&&valid(old)&&!emails.includes(old))emails.unshift(old);primary=emails.includes(old)?old:(emails[0]||'')}
function save(){const c=parse(W.localStorage.getItem(CFG),{});c.emails=c.emails||{};c.emails.comercializadora1=primary||emails[0]||'';c.emails.comercializadora1Lista=emails.slice();W.localStorage.setItem(CFG,JSON.stringify(c));wireNotice(W.document)}
function options(selected){return emails.length?emails.map(x=>'<option value="'+x+'"'+(x===selected?' selected':'')+'>'+x+'</option>').join(''):'<option value="">SIN CORREOS CONFIGURADOS</option>'}
function renderConfig(d){const select=el(d,'s135Com1Config');if(select){select.innerHTML=options(primary);select.value=primary}}
function wireConfig(d){const input=el(d,'s132Com1');if(!input||el(d,'s135Com1Manager'))return;const label=input.closest('label'),box=d.createElement('div');box.id='s135Com1Manager';box.className='s135-email-manager';box.innerHTML='<b>COMERCIALIZADORA 1 · CORREOS</b><label>Correos guardados<select id="s135Com1Config"></select></label><div class="s135-email-row"><input id="s132Com1" type="email" placeholder="nuevo@correo.es" autocomplete="email"><button type="button" id="s135Com1Add">AÑADIR</button><button type="button" id="s135Com1Remove" class="danger">ELIMINAR</button></div><small>Elige un correo del desplegable o añade uno nuevo.</small>';label.replaceWith(box);renderConfig(d);
const select=el(d,'s135Com1Config'),newInput=el(d,'s132Com1');select.onchange=()=>{primary=select.value;save()};el(d,'s135Com1Add').onclick=()=>{const mail=clean(newInput.value);if(!valid(mail)){W.alert('ESCRIBE UN CORREO VÁLIDO.');return}if(!emails.includes(mail))emails.push(mail);primary=mail;newInput.value='';save();renderConfig(d)};el(d,'s135Com1Remove').onclick=()=>{const mail=select.value;if(!mail)return;if(!W.confirm('¿ELIMINAR '+mail+'?'))return;emails=emails.filter(x=>x!==mail);primary=emails[0]||'';save();renderConfig(d)};
const button=el(d,'s132SaveCfg');if(button&&!button.dataset.s135Emails){button.dataset.s135Emails='1';const old=button.onclick;button.onclick=function(){const pending=clean(newInput.value);if(pending&&valid(pending)&&!emails.includes(pending)){emails.push(pending);primary=pending}newInput.value=primary;const r=old&&old.call(this);save();newInput.value='';renderConfig(d);return r}}}
function wireNotice(d){const box=el(d,'av135Solicitudes');if(!box)return;let select=el(d,'s135Com1Notice');if(!select){const label=d.createElement('label');label.className='wide s135-notice-email';label.innerHTML='Correo de Comercializadora 1<select id="s135Com1Notice"></select>';const row=box.querySelector('.row');box.insertBefore(label,row||box.firstChild);select=el(d,'s135Com1Notice')}const selected=select.value||primary;select.innerHTML=options(selected);if(emails.includes(selected))select.value=selected}
function style(d){if(el(d,'emails135Style'))return;const s=d.createElement('style');s.id='emails135Style';s.textContent='.s135-email-manager{grid-column:1/-1;border:1px solid #dbe3ee;border-radius:10px;padding:10px;background:#f8fafc}.s135-email-manager>b{display:block;color:#24466e;margin-bottom:8px}.s135-email-row{display:grid;grid-template-columns:1fr auto auto;gap:7px;margin-top:7px}.s135-email-manager small{display:block;color:#667085;margin-top:6px}.s135-notice-email{display:block;margin:0 0 10px}@media(max-width:560px){.s135-email-row{grid-template-columns:1fr 1fr}.s135-email-row input{grid-column:1/-1}}';d.head.appendChild(s)}
window.SoltecEmails135={init(w){W=w;const d=w.document;load();style(d);wireConfig(d);wireNotice(d);setTimeout(()=>{wireConfig(d);wireNotice(d)},250);setTimeout(()=>{wireConfig(d);wireNotice(d)},1000)}}})();