(function(){'use strict';
const CFG='APP_AVISOS_CONFIG_V127';let W,state={com:{list:[],primary:''},cups:{list:[],primary:''}};
const el=(d,id)=>d.getElementById(id),parse=(v,x)=>{try{return JSON.parse(v||'')||x}catch(_){return x}},clean=v=>String(v||'').trim().toLowerCase(),valid=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
const spec={com:{input:'s132Com1',manager:'s135Com1Manager',select:'s135Com1Config',add:'s135Com1Add',remove:'s135Com1Remove',title:'COMERCIALIZADORA 1 · CORREOS',listKey:'comercializadora1Lista',primaryKey:'comercializadora1'},cups:{input:'s132CupsMail',manager:'s135CupsManager',select:'s135CupsConfig',add:'s135CupsAdd',remove:'s135CupsRemove',title:'SOLICITAR CUPS · CORREOS',listKey:'solicitarCupsLista',primaryKey:'solicitarCups'}};
function unique(a){return Array.from(new Set((a||[]).map(clean).filter(valid)))}
function load(){const c=parse(W.localStorage.getItem(CFG),{}),m=c.emails||{};state.com.list=unique(Array.isArray(m.comercializadora1Lista)?m.comercializadora1Lista:[]);const old=clean(m.comercializadora1);if(valid(old)&&!state.com.list.includes(old))state.com.list.unshift(old);state.com.primary=state.com.list.includes(old)?old:(state.com.list[0]||'');state.cups.list=unique(Array.isArray(m.solicitarCupsLista)?m.solicitarCupsLista:[]);const cupsOld=clean(m.solicitarCups);if(valid(cupsOld)&&!state.cups.list.includes(cupsOld))state.cups.list.unshift(cupsOld);if(!state.cups.list.length)state.cups.list=state.com.list.slice();state.cups.primary=state.cups.list.includes(cupsOld)?cupsOld:(state.cups.list[0]||'');persist()}
function persist(){const c=parse(W.localStorage.getItem(CFG),{});c.emails=c.emails||{};Object.keys(spec).forEach(k=>{const s=spec[k],x=state[k];c.emails[s.primaryKey]=x.primary||x.list[0]||'';c.emails[s.listKey]=x.list.slice()});W.localStorage.setItem(CFG,JSON.stringify(c));wireNotice(W.document)}
function options(k,selected){const a=state[k].list;return a.length?a.map(x=>'<option value="'+x+'"'+(x===selected?' selected':'')+'>'+x+'</option>').join(''):'<option value="">SIN CORREOS CONFIGURADOS</option>'}
function render(d,k){const x=state[k],select=el(d,spec[k].select);if(select){select.innerHTML=options(k,x.primary);select.value=x.primary}}
function manager(d,k){const s=spec[k],input=el(d,s.input);if(!input||el(d,s.manager))return;const label=input.closest('label'),box=d.createElement('div');box.id=s.manager;box.className='s135-email-manager';box.innerHTML='<b>'+s.title+'</b><label>Correos guardados<select id="'+s.select+'"></select></label><div class="s135-email-row"><input id="'+s.input+'" type="email" placeholder="nuevo@correo.es" autocomplete="email"><button type="button" id="'+s.add+'">AÑADIR</button><button type="button" id="'+s.remove+'" class="danger">ELIMINAR</button></div><small>Elige el correo principal o añade uno nuevo.</small>';label.replaceWith(box);render(d,k);const select=el(d,s.select),newInput=el(d,s.input);select.onchange=()=>{state[k].primary=select.value;persist()};el(d,s.add).onclick=()=>{const mail=clean(newInput.value);if(!valid(mail)){W.alert('ESCRIBE UN CORREO VÁLIDO.');return}if(!state[k].list.includes(mail))state[k].list.push(mail);state[k].primary=mail;newInput.value='';persist();render(d,k)};el(d,s.remove).onclick=()=>{const mail=select.value;if(!mail)return;if(!W.confirm('¿ELIMINAR '+mail+'?'))return;state[k].list=state[k].list.filter(x=>x!==mail);state[k].primary=state[k].list[0]||'';persist();render(d,k)}}
function hookSave(d){const button=el(d,'s132SaveCfg');if(!button||button.dataset.s135Emails)return;button.dataset.s135Emails='1';const old=button.onclick;button.onclick=function(){Object.keys(spec).forEach(k=>{const input=el(d,spec[k].input),pending=clean(input&&input.value);if(valid(pending)&&!state[k].list.includes(pending))state[k].list.push(pending);if(valid(pending))state[k].primary=pending;if(input)input.value=state[k].primary});const r=old&&old.call(this);persist();Object.keys(spec).forEach(k=>{const input=el(d,spec[k].input);if(input)input.value='';render(d,k)});return r}}
function addNoticeSelect(d,box,id,k,labelText,before){let select=el(d,id);if(!select){const label=d.createElement('label');label.className='wide s135-notice-email';label.innerHTML=labelText+'<select id="'+id+'"></select>';const host=before&&box.contains(before)?before.parentNode:(box.querySelector('.c135-tab-body')||box);const anchor=before&&before.parentNode===host?before:null;host.insertBefore(label,anchor||host.firstChild);select=el(d,id)}const selected=select.value||state[k].primary;select.innerHTML=options(k,selected);if(state[k].list.includes(selected))select.value=selected}
function wireNotice(d){const mail=el(d,'av135Solicitudes');if(mail)addNoticeSelect(d,mail,'s135Com1Notice','com','Correo de Comercializadora 1',mail.querySelector('.row'));const cups=el(d,'s132CupsReq');if(cups)addNoticeSelect(d,cups,'s135CupsNotice','cups','Correo para solicitar CUPS',el(d,'s132CupsSend'))}
function style(d){if(el(d,'emails135Style'))return;const s=d.createElement('style');s.id='emails135Style';s.textContent='.s135-email-manager{grid-column:1/-1;border:1px solid #dbe3ee;border-radius:10px;padding:10px;background:#f8fafc;margin-bottom:8px}.s135-email-manager>b{display:block;color:#24466e;margin-bottom:8px}.s135-email-row{display:grid;grid-template-columns:1fr auto auto;gap:7px;margin-top:7px}.s135-email-manager small{display:block;color:#667085;margin-top:6px}.s135-notice-email{display:block;margin:8px 0 10px}@media(max-width:560px){.s135-email-row{grid-template-columns:1fr 1fr}.s135-email-row input{grid-column:1/-1}}';d.head.appendChild(s)}
function wire(d){manager(d,'com');manager(d,'cups');hookSave(d);wireNotice(d)}
window.SoltecEmails135={init(w){W=w;const d=w.document;load();style(d);wire(d);setTimeout(()=>wire(d),250);setTimeout(()=>wire(d),1000)}}})();