(function(){'use strict';
const CFG='SOLTEC_SYNC_CONFIG_V134';
function syncCfg(w){for(const s of [window.localStorage,w.localStorage]){try{const c=JSON.parse(s.getItem(CFG)||'null');if(c&&String(c.serverUrl||'').trim()&&String(c.key||'').trim())return c}catch(x){}}return null}
function syncFinished(d){const x=d.getElementById('s134SyncStatus'),t=String(x&&x.textContent||'').toUpperCase();return t.includes('TODO ESTÁ ACTUALIZADO')||t.includes('SINCRONIZACIÓN COMPLETADA')||t.includes('DATOS DEL PC RECIBIDOS')||t.includes('CONFLICTO')||t.includes('PRIMERA SINCRONIZACIÓN')}
function syncActive(d){const x=d.getElementById('s134SyncStatus'),t=String(x&&x.textContent||'').toUpperCase();return t.includes('PREPARANDO')||t.includes('CONSULTANDO')||t.includes('ENVIANDO')||t.includes('RECIBIENDO')||t.includes('COMPROBANDO')}
async function startupSync(w){try{const d=w.document,b=d.getElementById('s134SyncNow'),cf=d.getElementById('s134Conflict');if(!b||b.disabled||syncFinished(d)||syncActive(d)||(cf&&cf.style.display!=='none'))return;const c=syncCfg(w);if(!c)return;const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),12000);let ok=false;try{const r=await w.fetch(String(c.serverUrl).trim().replace(/\/+$/,'')+'/api/status',{cache:'no-store',headers:{'X-Soltec-Key':String(c.key||'')},signal:ctl.signal});ok=!!r.ok}catch(x){}finally{clearTimeout(tm)}if(ok&&b&&!b.disabled&&!syncFinished(d)&&!syncActive(d))b.click()}catch(x){}}
function scheduleStartup(w){[2500,12000,30000].forEach(ms=>setTimeout(()=>startupSync(w),ms))}
function ensure(w){try{const d=w.document;if(!d||!d.body)return;let nav=d.querySelector('nav.bottom');if(!nav){nav=d.createElement('nav');nav.className='bottom';nav.setAttribute('aria-label','Navegación principal');d.body.appendChild(nav)}
nav.style.position='fixed';nav.style.left='0';nav.style.right='0';nav.style.bottom='0';nav.style.zIndex='9999';nav.style.display='grid';nav.style.gridTemplateColumns='repeat(4,1fr)';nav.style.visibility='visible';nav.style.opacity='1';nav.style.background='#fff';nav.style.borderTop='1px solid #dbe3ee';nav.style.padding='6px 5px calc(6px + env(safe-area-inset-bottom))';
const defs=[['navInicio','⌂<br>Inicio','inicio'],['navAvisos','☰<br>Avisos','avisos'],['navConfig','⚙<br>Empresa','config']];for(const [id,label,screen] of defs){let b=d.getElementById(id);if(!b){b=d.createElement('button');b.type='button';b.id=id;nav.appendChild(b)}b.innerHTML=label;b.style.display='block';b.style.visibility='visible';b.style.opacity='1';b.onclick=function(){if(w.App&&typeof w.App.show==='function')w.App.show(screen)}}
let f=d.getElementById('navFinalizar');if(!f){f=d.createElement('button');f.type='button';f.id='navFinalizar';nav.appendChild(f)}f.innerHTML='✅<br>Finalizar';f.style.display='block';f.style.visibility='visible';f.style.opacity='1';f.onclick=function(){if(window.Soltec134Auto&&typeof window.Soltec134Auto.finalizar==='function')window.Soltec134Auto.finalizar(w)};
}catch(x){console.error('V1.34 NAV FIX',x)}}
window.Soltec134NavFix={init:function(w){ensure(w);setTimeout(()=>ensure(w),300);setTimeout(()=>ensure(w),1200);setTimeout(()=>ensure(w),3000);scheduleStartup(w);try{w.addEventListener('online',()=>setTimeout(()=>startupSync(w),2500));w.document.addEventListener('visibilitychange',()=>{if(w.document.visibilityState==='visible')setTimeout(()=>startupSync(w),2500)})}catch(x){}}};
})();