(function(){'use strict';
const B='V135-FINAL2-HOME';let timer=0;
function frame(){try{let f=document.getElementById('app134');return f&&f.contentWindow&&f.contentWindow.document?f.contentWindow:null}catch(e){return null}}
function E(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function main(w){try{return JSON.parse(w.localStorage.getItem('APP_AVISOS_WEB_DATOS_V116_PERSISTENTE')||'{}')}catch(e){return{}}}
function parts(){try{return window.P2&&window.P2.parts?window.P2.parts():[]}catch(e){return[]}}
function showAvisos(w){try{if(w.App&&w.App.show)w.App.show('avisos');setTimeout(()=>{try{let d=w.document,s=d.getElementById('crearAvisoModo');if(s){s.value='nuevo';if(w.App&&w.App.crearAvisoModo)w.App.crearAvisoModo()}else{let f=d.getElementById('formAviso');if(f)f.style.display='block'}}catch(e){}},80)}catch(e){}}
function showPartes(w,tab){try{if(window.Soltec134PartsPdf&&window.Soltec134PartsPdf.init)window.Soltec134PartsPdf.init(w);if(window.Soltec134Parts&&window.Soltec134Parts.init)window.Soltec134Parts.init(w);if(window.Soltec134Parts&&window.Soltec134Parts.show)window.Soltec134Parts.show(w);else{let d=w.document,p=d.getElementById('partes');if(p){d.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));p.classList.add('active')}}setTimeout(()=>{let d=w.document,b=tab==='hist'?(d.getElementById('ptTabHist')||d.getElementById('pConsultar')):(d.getElementById('ptTabNuevo')||d.getElementById('pCrear'));if(b)b.click()},180)}catch(e){}}
function updateStats(w){let d=w.document,m=main(w),avis=(m.avisos||[]).length,pap=(m.papelera||[]).length,pa=parts(),firm=pa.filter(x=>x&&x.status!=='draft').length,el=d.getElementById('home135Stats');if(el)el.innerHTML='<b>'+avis+'</b> avisos activos · <b>'+pap+'</b> en papelera · <b>'+pa.length+'</b> partes · <b>'+firm+'</b> firmados/enviados'}
function inject(){let w=frame();if(!w)return;let d=w.document,sec=d.getElementById('inicio');if(!sec)return;let card=sec.querySelector('.card')||sec;if(!d.getElementById('home135Style')){let st=d.createElement('style');st.id='home135Style';st.textContent='#home135Quick{margin-top:12px}.home135grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.home135grid button{min-height:78px;text-align:left;border-radius:16px;background:#fff}.home135grid button.primary{background:#0b5ed7;color:#fff}.home135grid strong{display:block;font-size:17px}.home135grid span{display:block;font-size:12px;margin-top:5px;opacity:.75}#home135Stats{margin-top:10px;background:#f8fafc;border:1px solid #dbe3ee;border-radius:12px;padding:10px;font-size:12px;color:#667085}@media(max-width:520px){.home135grid{grid-template-columns:1fr}}';d.head.appendChild(st)}let box=d.getElementById('home135Quick');if(!box){box=d.createElement('div');box.id='home135Quick';box.innerHTML='<div class="sectionTitle">Trabajo rápido</div><div class="home135grid"><button type="button" id="h135Aviso" class="primary"><strong>☰ Crear aviso</strong><span>Alta directa de aviso nuevo</span></button><button type="button" id="h135Parte" class="primary"><strong>🧾 Crear parte</strong><span>Parte de trabajo desde avisos/clientes</span></button><button type="button" id="h135Partes"><strong>🔎 Consultar partes</strong><span>Histórico, PDF, correo y WhatsApp</span></button><button type="button" id="h135Empresa"><strong>⚙ Empresa</strong><span>Datos, textos y sincronización</span></button></div><div id="home135Stats"></div>';card.appendChild(box);d.getElementById('h135Aviso').onclick=()=>showAvisos(w);d.getElementById('h135Parte').onclick=()=>showPartes(w,'new');d.getElementById('h135Partes').onclick=()=>showPartes(w,'hist');d.getElementById('h135Empresa').onclick=()=>{try{if(w.App&&w.App.show)w.App.show('config')}catch(e){}}}updateStats(w)}
function init(){inject();if(!timer)timer=setInterval(inject,2000)}
window.Soltec135Home={init:init,version:B};init();
})();
