(function(){'use strict';
const B='V1.35-BETA3-FIX1-20260913',CFG='APP_AVISOS_PARTES_CONFIG_V134';
function A(){return window.P2||null}function W(){let a=A();return a&&a.w?a.w:null}function S(v){return v==null?'':String(v)}function J(v,d){try{return JSON.parse(v||'')||d}catch(e){return d}}
function base(){return{mailText:'Buenos días,\n\nAdjuntamos el parte de trabajo Nº {numero}, correspondiente al aviso {aviso}.\n\nCliente: {cliente}\nResultado: {resultado}\n\nUn saludo.',waText:'Buenos días. Enviamos el parte de trabajo Nº {numero} del aviso {aviso}. Cliente: {cliente}. Resultado: {resultado}.'}}
function cfg(){let w=W();if(!w)return base();return Object.assign(base(),J(w.localStorage.getItem(CFG),{}))}
function saveCfg(c){let w=W();if(!w)return;w.localStorage.setItem(CFG,JSON.stringify(c));try{w.localStorage.setItem('SOLTEC_SYNC_PENDING_V134','1')}catch(e){}}
function fill(t,p){p=(A()&&A().norm)?A().norm(p):p||{};return S(t).replaceAll('{numero}',S(p.partNo)).replaceAll('{cliente}',S(p.cliente)).replaceAll('{aviso}',S(p.avisoNo||p.avisoId)).replaceAll('{resultado}',S(p.resultado)).replaceAll('{tecnico}',S(p.tecnico))}
function mark(p,via){let a=A();if(!a||!p)return;p=a.norm(p);p.status='sent';p.locked=true;p.sentAt=new Date().toISOString();p.sentVia=via;a.put(p);if(a.get&&a.get()&&a.get().id===p.id)a.set(p)}
function send(via,p){let w=W(),c=cfg();if(!w||!p)return;let subject='Parte de trabajo Nº '+S(p.partNo),body=fill(via==='wa'?c.waText:c.mailText,p);try{if(via==='mail'){w.location.href='mailto:'+encodeURIComponent(S(p.email))+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);mark(p,'Correo');return}if(via==='wa'){let ph=S(p.telefono).replace(/\D/g,'');w.open('https://wa.me/'+ph+'?text='+encodeURIComponent(body),'_blank');mark(p,'WhatsApp');return}if(via==='share'&&w.navigator.share){w.navigator.share({title:subject,text:body});mark(p,'Compartido');return}}catch(e){w.alert('No se pudo preparar el envío: '+S(e&&e.message||e))}}
function injectCfg(){let w=W(),d=w&&w.document;if(!d)return;let card=d.querySelector('#partes .card');if(!card||d.getElementById('ptEnvioCfg'))return;let c=cfg(),box=d.createElement('div');box.id='ptEnvioCfg';box.className='ptBox';box.innerHTML='<details><summary><b>⚙ Configuración de envío de partes</b></summary><label>Texto del correo<textarea id="ptMailText" rows="6"></textarea></label><label>Texto de WhatsApp<textarea id="ptWaText" rows="4"></textarea></label><div class="ptSmall">Campos disponibles: {numero}, {cliente}, {aviso}, {resultado}, {tecnico}</div><button type="button" id="ptSaveEnvioCfg">Guardar textos</button></details>';let ref=d.getElementById('pNew')||d.getElementById('ptPaneNuevo');card.insertBefore(box,ref);d.getElementById('ptMailText').value=c.mailText;d.getElementById('ptWaText').value=c.waText;d.getElementById('ptSaveEnvioCfg').onclick=function(){saveCfg({mailText:d.getElementById('ptMailText').value,waText:d.getElementById('ptWaText').value});w.alert('Textos de envío guardados.')}}
function patchButtons(){let a=A(),w=W(),d=w&&w.document;if(!a||!d)return;injectCfg();let p=a.get&&a.get();let b=d.getElementById('pdf2');if(b&&!b.dataset.b3f){b.dataset.b3f='1';b.textContent='Ver PDF y abrir correo';b.onclick=function(){if(window.Soltec134PartsPdf&&window.Soltec134PartsPdf.open)window.Soltec134PartsPdf.open(a.get());setTimeout(()=>send('mail',a.get()),500)}}let m=d.getElementById('mail2');if(m){m.textContent='Correo';m.onclick=()=>send('mail',a.get())}let wa=d.getElementById('wa2');if(wa){wa.textContent='WhatsApp';wa.onclick=()=>send('wa',a.get())}let sh=d.getElementById('share2');if(sh){sh.textContent='Compartir';sh.onclick=()=>send('share',a.get())}d.querySelectorAll('[data-mail]').forEach(x=>x.onclick=()=>send('mail',a.parts().find(p=>p.id===x.dataset.mail)));d.querySelectorAll('[data-wa]').forEach(x=>x.onclick=()=>send('wa',a.parts().find(p=>p.id===x.dataset.wa)));d.querySelectorAll('[data-share]').forEach(x=>x.onclick=()=>send('share',a.parts().find(p=>p.id===x.dataset.share)))}
function patch(){try{if(window.P2UI&&!window.P2UI.__envioFix1){['form','hist','show'].forEach(k=>{let old=window.P2UI[k];if(typeof old==='function')window.P2UI[k]=function(){let r=old.apply(this,arguments);setTimeout(patchButtons,100);return r}});window.P2UI.__envioFix1=1}patchButtons()}catch(e){console.error('ENVIO PARTES FIX1',e)}}
setInterval(patch,700);window.Soltec135EnvioPartes={version:B,send:send,config:cfg};
})();
