(function(){'use strict';
const B='V1.35-BETA2-20260913',K='APP_AVISOS_PARTES_V134',M='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',P='SOLTEC_SYNC_PENDING_V134',L='APP_AVISOS_VERSIONLOG_V135';let cur=null;
const S=v=>v==null?'':String(v),J=(v,d)=>{try{return JSON.parse(v||'')||d}catch(e){return d}},E=v=>S(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),N=()=>new Date().toISOString(),DY=()=>N().slice(0,10);
function D(id){return window.P2.w&&window.P2.w.document.getElementById(id)}
function main(){let w=window.P2.w;return J(w.localStorage.getItem(M),{empresa:{},tecnico:{},avisos:[]})}
function av(){return (main().avisos||[]).slice().sort((a,b)=>S(b.fecha||b.actualizado).localeCompare(S(a.fecha||a.actualizado)))}
function nf(f){f=f||{};['antes','durante','despues'].forEach(k=>f[k]=Array.isArray(f[k])?f[k]:[]);return f}
function norm(p){p=p||{};let st=p.status==='signed'||p.status==='sent'?p.status:'draft';return{id:S(p.id)||('PT'+Date.now()+Math.random().toString(36).slice(2,5)),partNo:S(p.partNo)||next(),avisoId:S(p.avisoId||p.avisoNo),avisoNo:S(p.avisoNo||p.avisoId),cliente:S(p.cliente),direccion:S(p.direccion),contacto:S(p.contacto),telefono:S(p.telefono),email:S(p.email),fecha:S(p.fecha)||DY(),tecnico:S(p.tecnico),trabajos:S(p.trabajos),material:S(p.material||p.materialesTexto),resultado:S(p.resultado),notasInternas:S(p.notasInternas),fotos:nf(p.fotos),conformidad:!!p.conformidad,firmante:S(p.firmante||p.signerName),nif:S(p.nif||p.signerNif),firma:S(p.firma||p.signatureData),firmaTec:S(p.firmaTec||p.techSignatureData),status:st,locked:st!=='draft'||!!p.locked,createdAt:S(p.createdAt)||N(),updatedAt:S(p.updatedAt)||N(),build:S(p.build)||B,schema:'PARTES_V2'}}
function parts(){let w=window.P2.w,a=J(w.localStorage.getItem(K),[]);return (Array.isArray(a)?a:[]).map(norm)}
function next(){let y=new Date().getFullYear(),m=0;parts().forEach(p=>{let r=S(p.partNo).match(/^PT-(\d{4})-(\d+)/);if(r&&+r[1]===y)m=Math.max(m,+r[2]||0)});return 'PT-'+y+'-'+String(m+1).padStart(5,'0')}
function mark(){let w=window.P2.w;try{w.localStorage.setItem(P,'1');let a=J(w.localStorage.getItem(L),[]);if(!Array.isArray(a))a=[];if(!a.some(x=>x&&x.build===B))a.unshift({build:B,module:'Partes de Trabajo',dataSchema:'PARTES_V2',at:N(),note:'Beta 2: fotos, firmas y PDF'});w.localStorage.setItem(L,JSON.stringify(a.slice(0,50)))}catch(e){}}
function put(p){let w=window.P2.w,a=parts(),i=a.findIndex(x=>x.id===p.id);p=norm(p);p.updatedAt=N();p.build=B;i<0?a.unshift(p):a[i]=p;w.localStorage.setItem(K,JSON.stringify(a.map(norm)));mark();return p}
function make(id){let a=av().find(x=>S(x.id)===S(id));if(!a)return;let ex=parts().find(p=>p.avisoId===S(id)&&p.status==='draft'),te=S(main().tecnico&&main().tecnico.nombre);cur=ex||put({avisoId:S(a.id),avisoNo:S(a.id),cliente:S(a.cliente),direccion:S(a.direccion),contacto:S(a.contacto),telefono:S(a.telefono),email:S(a.email),fecha:DY(),tecnico:te,status:'draft'});window.P2UI&&window.P2UI.show&&window.P2UI.show()}
window.P2={B,w:null,S,J,E,D,N,DY,main,av,parts,norm,put,make,get:()=>cur,set:p=>{cur=p}};
})();
(function(){'use strict';
function A(){return window.P2}function D(id){return A().D(id)}function S(v){return A().S(v)}function E(v){return A().E(v)}let T,O;
function install(){let w=A().w;if(!D('p2css')){let st=w.document.createElement('style');st.id='p2css';st.textContent='#partes .ptTabs{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:12px}#partes .ptTabs button.active{background:#0b5ed7;color:#fff}.ptBox,.ptHist{border:1px solid #dbe3ee;border-radius:14px;background:#fff;padding:10px;margin:8px 0}.ptSmall{font-size:12px;color:#667085}.ptBadge{border-radius:999px;padding:5px 8px;background:#fff7db;font-size:11px;font-weight:900}.ptBadge.ok{background:#e8f3ff;color:#174ea6}.ptActions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.ptCreateFromAviso{grid-column:1/-1;border-color:#0b5ed7!important;color:#0b5ed7!important;background:#eef5ff!important}';w.document.head.appendChild(st)}let old=D('partes');if(old)old.remove();let m=w.document.querySelector('main');if(!m)return;let q=w.document.createElement('section');q.id='partes';q.className='screen';q.innerHTML='<div class=card><h2>Partes de trabajo <span class=ptBadge>V1.35 BETA 2</span></h2><div class=ptTabs><button id=pCrear class=active>➕ Crear parte</button><button id=pConsultar>🔎 Consultar partes</button></div><div id=pNew></div><div id=pHist style=display:none></div></div>';m.appendChild(q);D('pCrear').onclick=()=>tab(0);D('pConsultar').onclick=()=>tab(1)}
function nav(){let w=A().w,n=w.document.querySelector('nav.bottom');if(!n)return;let b=D('navPartes');if(!b){b=w.document.createElement('button');b.id='navPartes';b.innerHTML='🧾<br>Partes';n.insertBefore(b,D('navFinalizar')||null)}b.onclick=show}
function show(){install();nav();let w=A().w;w.document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));D('partes').classList.add('active');w.document.querySelectorAll('nav.bottom button').forEach(x=>x.classList.remove('active'));D('navPartes')?.classList.add('active');tab(0)}
function tab(h){D('pNew').style.display=h?'none':'block';D('pHist').style.display=h?'block':'none';D('pCrear').classList.toggle('active',!h);D('pConsultar').classList.toggle('active',!!h);h?hist():newp()}
function newp(){let x=D('pNew'),c=A().get();if(c)return form();let a=A().av();x.innerHTML='<div class=sectionTitle>➕ Crear parte desde aviso</div><label>Aviso / cliente<select id=selav><option value="">Seleccionar…</option>'+a.map(v=>'<option value="'+E(v.id)+'">'+E(v.id)+' · '+E(v.cliente||'Sin cliente')+'</option>').join('')+'</select></label><button id=mk class="primary full">Crear / continuar parte</button><div class=ptSmall>Copia datos del aviso. Ref. catastral fuera.</div>';D('mk').onclick=()=>{let id=D('selav').value;if(id)A().make(id)}}
function read(){let c=A().get();if(!c)return c;c.trabajos=D('trab')?.value||'';c.material=D('mat')?.value||'';c.resultado=D('res')?.value||'';c.notasInternas=D('notas')?.value||'';if(window.P2Extra?.read)P2Extra.read(c);return A().norm(c)}
function auto(){let c=A().get();if(!c||c.status!=='draft')return;clearTimeout(T);T=setTimeout(()=>{A().set(A().put(read()));let x=D('autos');if(x)x.textContent='Guardado '+new Date().toLocaleTimeString('es-ES')},400)}
function form(){let p=A().norm(A().get()),l=p.status!=='draft',x=D('pNew');A().set(p);x.innerHTML='<div class=ptBox><b>'+E(p.partNo)+'</b> <span class="ptBadge '+(l?'ok':'')+'">'+(l?'FIRMADO':'BORRADOR')+'</span><label>Nº aviso<input readonly value="'+E(p.avisoNo)+'"></label><label>Cliente<input readonly value="'+E(p.cliente)+'"></label><label>Dirección<input readonly value="'+E(p.direccion)+'"></label><label>Teléfono<input readonly value="'+E(p.telefono)+'"></label><div class=ptSmall>Referencia catastral fuera.</div></div><label>Trabajos realizados<textarea id=trab '+(l?'disabled':'')+'>'+E(p.trabajos)+'</textarea></label><label>Material empleado<textarea id=mat '+(l?'disabled':'')+'>'+E(p.material)+'</textarea></label><label>Resultado<select id=res '+(l?'disabled':'')+'><option></option>'+['Resuelto','Pendiente','Nueva visita','Requiere presupuesto'].map(r=>'<option '+(p.resultado===r?'selected':'')+'>'+r+'</option>').join('')+'</select></label>'+(window.P2Extra?.html?P2Extra.html(p,l):'')+'<label>Notas internas<textarea id=notas '+(l?'disabled':'')+'>'+E(p.notasInternas)+'</textarea></label><div id=autos class=ptSmall>Guardado automático activo</div><div class=ptActions><button id=goHist>Consultar partes</button>'+(l?'<button id=newOne>Crear otro</button>':'<button id=sign>Firmar y generar PDF</button><button id=close>Cerrar borrador</button>')+'</div>';bind(l);if(window.P2Extra?.bind)P2Extra.bind(p,l)}
function bind(l){let x=D('pNew');if(!l){x.querySelectorAll('textarea,input,select').forEach(i=>{if(i.type!=='file')i.oninput=auto});D('sign').onclick=sign;D('close').onclick=()=>{A().set(A().put(read()));A().set(null);newp()}}else D('newOne').onclick=()=>{A().set(null);newp()};D('goHist').onclick=()=>{let c=A().get();if(c&&c.status==='draft')A().set(A().put(read()));A().set(null);tab(1)}}
function sign(){let c=read();if(!S(c.trabajos).trim())return A().w.alert('Falta describir el trabajo.');if(!S(c.resultado))return A().w.alert('Falta resultado.');let er=window.P2Extra?.validate?P2Extra.validate(c):'';if(er)return A().w.alert(er);c.status='signed';c.locked=true;c.signedAt=A().N();c.pdfGeneratedAt=A().N();A().set(A().put(c));form();hist();if(window.P2Extra?.pdf)setTimeout(()=>P2Extra.pdf(A().get()),150)}
function hist(){let h=D('pHist'),q=S(D('busca')?.value).toLowerCase(),a=A().parts().filter(p=>!q||[p.partNo,p.avisoNo,p.cliente,p.tecnico,p.status,p.resultado].join(' ').toLowerCase().includes(q));h.innerHTML='<div class=sectionTitle>🔎 Consultar partes</div><input id=busca placeholder="Buscar parte" value="'+E(q)+'"><div class=counter>'+a.length+' parte(s)</div>'+a.map(p=>'<div class=ptHist><b>'+E(p.partNo)+'</b> <span class="ptBadge '+(p.status!=='draft'?'ok':'')+'">'+(p.status!=='draft'?'FIRMADO':'BORRADOR')+'</span><div class=ptSmall>Aviso '+E(p.avisoNo)+' · '+E(p.cliente)+'</div><div class=ptActions><button data-open="'+E(p.id)+'">Abrir</button><button data-new="'+E(p.avisoId)+'">Nuevo parte</button>'+(p.status!=='draft'?'<button data-pdf="'+E(p.id)+'">Ver PDF</button>':'')+'</div></div>').join('');D('busca').oninput=hist;h.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{A().set(A().parts().find(p=>p.id===b.dataset.open));tab(0)});h.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>A().make(b.dataset.new));h.querySelectorAll('[data-pdf]').forEach(b=>b.onclick=()=>P2Extra.pdf(A().parts().find(p=>p.id===b.dataset.pdf)))}
function avisobtn(){let w=A().w;w.document.querySelectorAll('#listaAvisos .avisoCard').forEach(card=>{if(card.querySelector('.ptCreateFromAviso'))return;let ac=card.querySelector('.actions'),id='';if(!ac)return;ac.querySelectorAll('button').forEach(b=>{let m=S(b.getAttribute('onclick')).match(/(?:editarAviso|duplicarAviso|eliminarAviso)\((\d+)\)/);if(m)id=m[1]});if(id){let b=w.document.createElement('button');b.className='ptCreateFromAviso';b.textContent='🧾 Crear parte de trabajo';b.onclick=ev=>{ev.preventDefault();A().make(id)};ac.appendChild(b)}})}
function hook(){let w=A().w;if(w.App&&!w.App.__p2){let old=w.App.show;w.App.show=function(id){let r=old.apply(w.App,arguments);setTimeout(()=>{avisobtn();if(id==='partes')show()},30);return r};w.App.__p2=1}}
function init(w){A().w=w;try{install();nav();newp();hist();avisobtn();hook();let b=D('listaAvisos');if(b&&!O){O=new MutationObserver(avisobtn);O.observe(b,{childList:1,subtree:1})}setInterval(()=>{try{nav();avisobtn()}catch(e){}},3000)}catch(e){console.error('PARTES UI B2',e)}}
window.P2UI={init,show,form,auto,hist};window.Soltec134Parts={init,show:(w)=>{if(w&&w.document)A().w=w;show()},createFromNotice:id=>A().make(id),version:A().B};
})();
