(function(){'use strict';
const B='V135-FINAL1',K='APP_AVISOS_PARTES_V134',CFG='APP_AVISOS_PARTES_CONFIG_V134';
function A(){return window.P2||null}function W(){let a=A();return a&&a.w?a.w:null}function S(v){return v==null?'':String(v)}function J(v,d){try{return JSON.parse(v||'')||d}catch(e){return d}}function E(v){let a=A();return a&&a.E?a.E(v):S(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function mark(){let w=W();if(w)try{w.localStorage.setItem('SOLTEC_SYNC_PENDING_V134','1')}catch(e){}}
function patchData(){let a=A();if(!a||a.__stableData)return;let old=a.norm;a.norm=function(p){let r=old(p||{});r.build=B;r.parentPartId=S((p||{}).parentPartId);r.originalPartNo=S((p||{}).originalPartNo);r.revisionNo=(p||{}).revisionNo||'';r.revisionReason=S((p||{}).revisionReason);r.sentAt=S((p||{}).sentAt);r.sentVia=S((p||{}).sentVia);return r};a.__stableData=1}
function cfg(){let w=W(),base={mailText:'Buenos días,\n\nAdjuntamos el parte de trabajo Nº {numero}, correspondiente al aviso {aviso}.\n\nCliente: {cliente}\nResultado: {resultado}\n\nUn saludo.',waText:'Buenos días. Enviamos el parte de trabajo Nº {numero} del aviso {aviso}. Cliente: {cliente}. Resultado: {resultado}.',legalText:'Cliente conforme con el trabajo realizado.',pdfFooter:'Parte de trabajo generado por SOLTEC SAT.'};return Object.assign(base,w?J(w.localStorage.getItem(CFG),{}):{})}
function saveCfg(c){let w=W();if(!w)return;w.localStorage.setItem(CFG,JSON.stringify(Object.assign(cfg(),c)));mark()}
function fill(t,p){p=A().norm(p);return S(t).replaceAll('{numero}',S(p.partNo)).replaceAll('{cliente}',S(p.cliente)).replaceAll('{aviso}',S(p.avisoNo||p.avisoId)).replaceAll('{resultado}',S(p.resultado)).replaceAll('{tecnico}',S(p.tecnico))}
function send(via,p){let w=W(),a=A(),c=cfg();if(!w||!a||!p)return;p=a.norm(p);let subject='Parte de trabajo Nº '+S(p.partNo),body=fill(via==='wa'?c.waText:c.mailText,p);try{if(via==='mail'){w.location.href='mailto:'+encodeURIComponent(S(p.email))+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);markSent(p,'Correo');return}if(via==='wa'){let ph=S(p.telefono).replace(/\D/g,'');w.open('https://wa.me/'+ph+'?text='+encodeURIComponent(body),'_blank');markSent(p,'WhatsApp');return}if(via==='share'&&w.navigator.share){w.navigator.share({title:subject,text:body});markSent(p,'Compartido');return}}catch(e){w.alert('No se pudo preparar el envío: '+S(e&&e.message||e))}}
function markSent(p,via){let a=A();if(!a)return;p=a.norm(p);p.status='sent';p.locked=true;p.sentAt=new Date().toISOString();p.sentVia=via;a.set&&a.set(a.put(p));if(window.P2UI)setTimeout(()=>{try{P2UI.form();P2UI.hist();addButtons()}catch(e){}},120)}
function revNo(base){let a=A(),n=1;if(!a)return 2;(a.parts()||[]).forEach(p=>{if(S(p.parentPartId)===S(base.id)||S(p.originalPartNo)===S(base.partNo)){let r=parseInt(S(p.revisionNo).replace(/\D/g,''),10);if(r>=n)n=r}});return n+1}
function createRevision(base){patchData();let a=A(),w=W();if(!a||!base)return;base=a.norm(base);let r=revNo(base),p=JSON.parse(JSON.stringify(base));p.id='PTREV'+Date.now()+Math.random().toString(36).slice(2,6);p.parentPartId=base.id;p.originalPartNo=base.originalPartNo||base.partNo;p.revisionNo=r;p.partNo=(base.originalPartNo||base.partNo)+'-R'+r;p.status='draft';p.locked=false;p.conformidad=false;p.firmante='';p.nif='';p.firma='';p.firmaTec='';p.sentAt='';p.sentVia='';p.signedAt='';p.revisionReason='Corrección / revisión del parte '+base.partNo;p.updatedAt=new Date().toISOString();a.set(a.put(p));if(window.P2UI){P2UI.form();P2UI.hist()}try{w.alert('Revisión creada: '+p.partNo+'. El original queda bloqueado.')}catch(e){}}
function images(p){let out='';['antes','durante','despues'].forEach(k=>{let arr=((p.fotos||{})[k]||[]).filter(f=>f&&f.data&&f.includePdf!==false);if(arr.length){out+='<h2>Fotos '+(k==='antes'?'antes':k==='durante'?'durante':'después')+'</h2><div class="imgs">'+arr.map(f=>'<img src="'+E(f.data)+'">').join('')+'</div>'}});return out}
function openPdf(p){let w=W();if(!w||!p)return;p=A().norm(p);let c=cfg(),win=w.open('','_blank');if(!win)return w.alert('El navegador bloqueó la vista. Permite ventanas emergentes.');let html='<!doctype html><html><head><meta charset="utf-8"><title>'+E(p.partNo)+'</title><style>@page{size:A4;margin:12mm}body{font-family:Arial;color:#111}.top{border-bottom:2px solid #111;padding-bottom:10px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.box{border:1px solid #ddd;border-radius:8px;padding:8px;margin:4px 0}.imgs{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.imgs img{width:100%;height:115px;object-fit:cover}.sig{display:grid;grid-template-columns:1fr 1fr;gap:20px}.sg{height:110px;border-bottom:1px solid #111}.sg polyline{fill:none;stroke:#111;stroke-width:4;stroke-linecap:round;stroke-linejoin:round}.foot{border-top:1px solid #ddd;margin-top:20px;padding-top:8px;font-size:11px;color:#555}.np{position:fixed;right:15px;top:15px}@media print{.np{display:none}}</style></head><body><button class="np" onclick="print()">Guardar como PDF / imprimir</button><div class="top"><h1>PARTE DE TRABAJO</h1><b>Nº '+E(p.partNo)+'</b> · Aviso '+E(p.avisoNo||p.avisoId)+(p.originalPartNo?' · Revisión de '+E(p.originalPartNo):'')+'</div><h2>Cliente</h2><div class="grid"><div class="box">'+E(p.cliente)+'</div><div class="box">'+E(p.telefono)+' '+E(p.email)+'</div><div class="box">'+E(p.direccion)+'</div><div class="box">'+E(p.contacto)+'</div></div><h2>Trabajos realizados</h2><p>'+E(p.trabajos).replace(/\n/g,'<br>')+'</p><h2>Material empleado</h2><p>'+E(p.material).replace(/\n/g,'<br>')+'</p><h2>Resultado</h2><p><b>'+E(p.resultado)+'</b></p>'+images(p)+'<h2>Conformidad</h2><p>'+E(c.legalText).replace(/\n/g,'<br>')+'</p><h2>Firmas</h2><div class="sig"><div><b>Cliente</b><br><svg class="sg" viewBox="0 0 900 240">'+S(p.firma)+'</svg><br>'+E(p.firmante)+' '+E(p.nif)+'</div><div><b>Técnico</b><br><svg class="sg" viewBox="0 0 900 210">'+S(p.firmaTec)+'</svg><br>'+E(p.tecnico)+'</div></div><div class="foot">'+E(c.pdfFooter).replace(/\n/g,'<br>')+'</div></body></html>';win.document.open();win.document.write(html);win.document.close()}
function injectCfg(){let w=W(),d=w&&w.document;if(!d)return;let card=d.querySelector('#partes .card');if(!card||d.getElementById('ptEnvioCfg'))return;let c=cfg(),box=d.createElement('div');box.id='ptEnvioCfg';box.className='ptBox';box.innerHTML='<details><summary><b>⚙ Configuración de partes de trabajo</b></summary><label>Texto del correo<textarea id="ptMailText" rows="6"></textarea></label><label>Texto de WhatsApp<textarea id="ptWaText" rows="4"></textarea></label><label>Texto legal / conformidad<textarea id="ptLegalText" rows="3"></textarea></label><label>Pie del PDF<textarea id="ptPdfFooter" rows="2"></textarea></label><div class="ptSmall">Campos: {numero}, {cliente}, {aviso}, {resultado}, {tecnico}</div><button type="button" id="ptSaveEnvioCfg">Guardar configuración</button></details>';let ref=d.getElementById('pNew')||d.getElementById('ptPaneNuevo');card.insertBefore(box,ref);d.getElementById('ptMailText').value=c.mailText;d.getElementById('ptWaText').value=c.waText;d.getElementById('ptLegalText').value=c.legalText;d.getElementById('ptPdfFooter').value=c.pdfFooter;d.getElementById('ptSaveEnvioCfg').onclick=function(){saveCfg({mailText:d.getElementById('ptMailText').value,waText:d.getElementById('ptWaText').value,legalText:d.getElementById('ptLegalText').value,pdfFooter:d.getElementById('ptPdfFooter').value});w.alert('Configuración guardada.')}}
function addButtons(){patchData();let a=A(),w=W(),d=w&&w.document;if(!a||!d)return;injectCfg();if(window.Soltec134PartsPdf){window.Soltec134PartsPdf.open=openPdf;window.Soltec134PartsPdf.send=send;window.Soltec134PartsPdf.version=B}let c=a.get&&a.get(),box=d.getElementById('pNew');if(c&&box&&c.status!=='draft'&&!d.getElementById('revPartBtn')){let b=d.createElement('button');b.id='revPartBtn';b.type='button';b.textContent='Crear revisión / corrección';b.onclick=()=>createRevision(a.get());(box.querySelector('.ptActions')||box).appendChild(b)}let pdf=d.getElementById('pdf2');if(pdf){pdf.textContent='Ver PDF y abrir correo';pdf.onclick=function(){openPdf(a.get());setTimeout(()=>send('mail',a.get()),500)}}let m=d.getElementById('mail2');if(m)m.onclick=()=>send('mail',a.get());let wa=d.getElementById('wa2');if(wa)wa.onclick=()=>send('wa',a.get());let sh=d.getElementById('share2');if(sh)sh.onclick=()=>send('share',a.get());let h=d.getElementById('pHist');if(h){h.querySelectorAll('[data-pdf]').forEach(x=>x.onclick=()=>openPdf(a.parts().find(p=>p.id===x.dataset.pdf)));h.querySelectorAll('[data-open]').forEach(open=>{let p=a.parts().find(x=>x.id===open.dataset.open),wrap=open.parentElement;if(p&&p.status!=='draft'&&wrap&&!wrap.querySelector('[data-rev="'+p.id+'"]')){let b=d.createElement('button');b.textContent='Crear revisión';b.dataset.rev=p.id;b.onclick=()=>createRevision(a.parts().find(x=>x.id===b.dataset.rev));wrap.appendChild(b)}});h.querySelectorAll('[data-mail]').forEach(x=>x.onclick=()=>send('mail',a.parts().find(p=>p.id===x.dataset.mail)));h.querySelectorAll('[data-wa]').forEach(x=>x.onclick=()=>send('wa',a.parts().find(p=>p.id===x.dataset.wa)));h.querySelectorAll('[data-share]').forEach(x=>x.onclick=()=>send('share',a.parts().find(p=>p.id===x.dataset.share)))}}
function patch(){try{if(window.P2UI&&!window.P2UI.__final1){['form','hist','show'].forEach(k=>{let old=window.P2UI[k];if(typeof old==='function')window.P2UI[k]=function(){let r=old.apply(this,arguments);setTimeout(addButtons,120);return r}});window.P2UI.__final1=1}addButtons()}catch(e){console.error('PARTES FINAL1',e)}}
function init(){patch();setInterval(patch,1200)}
window.Soltec135Stable={init,version:B,createRevision:createRevision};init();
})();
