(function(){'use strict';
const B='V135-PARTES-NUEVO1';let timer=0;
function A(){return window.P2||null}function W(){let a=A();return a&&a.w?a.w:null}function S(v){return v==null?'':String(v)}
function nextNo(){let a=A(),y=String(new Date().getFullYear()),m=0;if(!a||!a.parts)return 'PT-'+y+'-00001';(a.parts()||[]).forEach(p=>{let r=S(p&&p.partNo).match(/^PT-(\d{4})-(\d+)/);if(r&&r[1]===y)m=Math.max(m,Number(r[2])||0)});return 'PT-'+y+'-'+String(m+1).padStart(5,'0')}
function makeNew(id){let a=A(),w=W();if(!a||!w)return null;let av=(a.av?a.av():[]).find(x=>S(x&&x.id)===S(id));if(!av){try{w.alert('No se encuentra el aviso seleccionado.')}catch(e){}return null}let m=a.main?a.main():{},te=S(m&&m.tecnico&&m.tecnico.nombre),n=new Date().toISOString(),p={id:'PT'+Date.now()+Math.random().toString(36).slice(2,7),partNo:nextNo(),avisoId:S(av.id),avisoNo:S(av.id),cliente:S(av.cliente),direccion:S(av.direccion),contacto:S(av.contacto),telefono:S(av.telefono),email:S(av.email),fecha:n.slice(0,10),tecnico:te,trabajos:'',material:'',resultado:'',notasInternas:'',fotos:{antes:[],durante:[],despues:[]},conformidad:false,firmante:'',nif:'',firma:'',firmaTec:'',status:'draft',locked:false,createdAt:n,updatedAt:n};p=a.norm?a.norm(p):p;p.id=S(p.id)||('PT'+Date.now());p.partNo=S(p.partNo)||nextNo();p.status='draft';p.locked=false;p.conformidad=false;p.firmante='';p.nif='';p.firma='';p.firmaTec='';p.sentAt='';p.sentVia='';p.signedAt='';p=a.put?a.put(p):p;if(a.set)a.set(p);if(window.P2UI&&typeof window.P2UI.show==='function')window.P2UI.show();setTimeout(fix,120);return p}
function showNew(w){let a=A();if(!a)return;if(w&&w.document)a.w=w;if(a.set)a.set(null);if(window.P2UI&&typeof window.P2UI.show==='function')window.P2UI.show();setTimeout(fix,120)}
function companyPdf(p){try{if(window.P2Extra&&typeof window.P2Extra.pdf==='function'){window.P2Extra.pdf(p);return}if(window.Soltec134PartsPdf&&typeof window.Soltec134PartsPdf.open==='function')window.Soltec134PartsPdf.open(p)}catch(e){let w=W();if(w)w.alert('No se pudo abrir el PDF: '+S(e&&e.message||e))}}
function hookUi(){let u=window.P2UI;if(!u)return;['form','hist','show'].forEach(k=>{let old=u[k];if(typeof old!=='function'||old.__nuevo1)return;let f=function(){let r=old.apply(this,arguments);setTimeout(fix,80);return r};f.__nuevo1=1;u[k]=f})}
function fixPdf(d,a){let old=d.getElementById('pdf2');if(old){old.style.display='none';let b=d.getElementById('pdfEmpresa2');if(!b){b=d.createElement('button');b.type='button';b.id='pdfEmpresa2';b.textContent='Ver / guardar PDF';old.parentNode.insertBefore(b,old)}b.onclick=function(){companyPdf(a.get&&a.get())}}d.querySelectorAll('#pHist [data-pdf]').forEach(oldb=>{let id=S(oldb.dataset.pdf);oldb.style.display='none';let par=oldb.parentElement;if(!par||par.querySelector('[data-pdfempresa="'+id+'"]'))return;let b=d.createElement('button');b.type='button';b.dataset.pdfempresa=id;b.textContent='Ver PDF';b.onclick=function(){let p=(a.parts?a.parts():[]).find(x=>S(x&&x.id)===id);companyPdf(p)};par.appendChild(b)})}
function fix(){try{let a=A(),w=W();if(!a||!w)return;if(!a.__nuevo1){a.makeAnterior=a.make;a.make=makeNew;a.makeNew=makeNew;a.newPart=function(){showNew(w)};a.__nuevo1=1}let s=window.Soltec134Parts;if(s){s.newPart=function(x){showNew(x&&x.document?x:w)};s.createFromNotice=makeNew;s.version=B}hookUi();let d=w.document,mk=d.getElementById('mk');if(mk)mk.textContent='Crear parte nuevo';let pc=d.getElementById('pCrear');if(pc){pc.textContent='➕ Crear parte';pc.onclick=function(){showNew(w)}}let direct=d.getElementById('ptBtnCrearDirect');if(direct)direct.onclick=function(){showNew(w)};let home=d.getElementById('h135Parte');if(home)home.onclick=function(){showNew(w)};d.querySelectorAll('#pHist [data-new]').forEach(b=>b.onclick=function(){makeNew(b.dataset.new)});fixPdf(d,a)}catch(e){console.error('PARTES NUEVO1',e)}}
function init(){fix();setTimeout(fix,300);setTimeout(fix,1000);if(!timer)timer=setInterval(fix,1500)}
window.Soltec135PartesNuevo={init:init,makeNew:makeNew,showNew:showNew,version:B};init();
})();
