(function(){'use strict';
const BUILD='V135-PARTES-FOTOS3',KEY='APP_AVISOS_PARTES_FOTOS_V135',MAX=6;let W=null,obs=null,timer=0,lastPart='';
function d(){return W&&W.document}function e(id){return d()&&d().getElementById(id)}
function norm(v){return String(v||'').trim()}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function read(){try{const x=JSON.parse(W.localStorage.getItem(KEY)||'{}');return x&&typeof x==='object'?x:{}}catch(_){return{}}}
function write(x){try{W.localStorage.setItem(KEY,JSON.stringify(x))}catch(err){if(err&&(err.name==='QuotaExceededError'||err.code===22))throw new Error('No queda espacio suficiente para guardar más fotografías en este dispositivo. Elimina alguna foto o parte antiguo.');throw err}try{W.localStorage.setItem('SOLTEC_SYNC_PENDING_V134','1')}catch(_){}try{W.dispatchEvent(new W.CustomEvent('soltec:datachange',{detail:{module:'partes',field:'fotos',at:new Date().toISOString()}}))}catch(_){}}
function partNo(){const n=d()&&d().querySelector('#pt135-editor .pt135-summary strong');return norm(n&&n.textContent)}
function isDraft(){return !!(d()&&d().querySelector('#pt135-editor .pt135-badge.draft'))}
function photos(part){const x=read(),a=x[part];return Array.isArray(a)?a.slice(0,MAX):[]}
function save(part,a){const x=read();if(a&&a.length)x[part]=a.slice(0,MAX);else delete x[part];write(x)}
function resize(file){return new Promise((resolve,reject)=>{const rd=new FileReader();rd.onerror=reject;rd.onload=()=>{const im=new Image();im.onerror=reject;im.onload=()=>{const max=1100,scale=Math.min(1,max/Math.max(im.width,im.height)),cv=d().createElement('canvas');cv.width=Math.max(1,Math.round(im.width*scale));cv.height=Math.max(1,Math.round(im.height*scale));const ctx=cv.getContext('2d');ctx.drawImage(im,0,0,cv.width,cv.height);resolve(cv.toDataURL('image/jpeg',.62))};im.src=rd.result};rd.readAsDataURL(file)})}
function style(){if(e('pt135-photo-style'))return;const s=d().createElement('style');s.id='pt135-photo-style';s.textContent='#pt135-photo-wrap{margin:14px 0;border:1px solid #dbe3ee;border-radius:13px;padding:11px;background:#fff}#pt135-photo-wrap .pt135-photo-head{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}#pt135-photo-wrap .pt135-photo-warning{font-size:12px;color:#b42318;font-weight:800;margin-top:5px}.pt135-photo-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}.pt135-photo{position:relative;aspect-ratio:4/3;border:1px solid #dbe3ee;border-radius:10px;overflow:hidden;background:#f8fafc}.pt135-photo img{width:100%;height:100%;object-fit:cover;display:block}.pt135-photo button{border:0;border-radius:999px;background:rgba(255,255,255,.94);font-weight:900}.pt135-photo-num{position:absolute;left:5px;top:5px;min-width:28px;height:28px;padding:0 7px;border-radius:999px;background:rgba(23,43,77,.88);color:#fff;display:grid;place-items:center;font-size:12px;font-weight:900}.pt135-photo-tools{position:absolute;right:5px;top:5px;display:flex;gap:4px}.pt135-photo-tools button{position:static;width:30px;height:30px;color:#172b4d}.pt135-photo-tools .pt135-photo-del{color:#b42318}.pt135-photo img{cursor:zoom-in}.pt135-photo-modal{position:fixed;inset:0;z-index:9999;background:rgba(15,23,42,.88);display:flex;align-items:center;justify-content:center;padding:18px}.pt135-photo-modal[hidden]{display:none}.pt135-photo-modal img{max-width:96vw;max-height:88vh;object-fit:contain;border-radius:10px}.pt135-photo-modal button{position:fixed;right:16px;top:16px;width:42px;height:42px;border:0;border-radius:999px;background:#fff;color:#172b4d;font-size:22px;font-weight:900}.pt135-photo-empty{padding:12px;text-align:center;color:#667085;font-size:12px}.pt135-history-photos{margin-top:4px;font-size:12px;color:#475467;font-weight:700}@media(max-width:520px){.pt135-photo-grid{grid-template-columns:repeat(2,1fr)}}';d().head.appendChild(s)}
function move(part,from,to){const a=photos(part);if(to<0||to>=a.length||from===to)return;const x=a.splice(from,1)[0];a.splice(to,0,x);save(part,a);render()}
function openPhoto(src){let m=e('pt135-photo-modal');if(!m){m=d().createElement('div');m.id='pt135-photo-modal';m.className='pt135-photo-modal';m.hidden=true;m.innerHTML='<button type="button" aria-label="Cerrar">×</button><img alt="Fotografía ampliada">';d().body.appendChild(m);m.querySelector('button').onclick=()=>m.hidden=true;m.onclick=ev=>{if(ev.target===m)m.hidden=true}}m.querySelector('img').src=src;m.hidden=false}
function render(){const part=partNo(),grid=e('pt135-photo-grid'),count=e('pt135-photo-count');if(!part||!grid)return;const a=photos(part),draft=isDraft();if(count)count.textContent=a.length+' / '+MAX;grid.innerHTML=a.length?a.map((src,i)=>'<div class="pt135-photo"><img src="'+esc(src)+'" alt="Foto '+(i+1)+'" data-view-photo="'+i+'"><span class="pt135-photo-num">'+(i+1)+'</span>'+(draft?'<div class="pt135-photo-tools">'+(i>0?'<button type="button" data-left-photo="'+i+'" aria-label="Mover antes">‹</button>':'')+(i<a.length-1?'<button type="button" data-right-photo="'+i+'" aria-label="Mover después">›</button>':'')+'<button type="button" class="pt135-photo-del" data-rm-photo="'+i+'" aria-label="Eliminar foto">×</button></div>':'')+'</div>').join(''):'<div class="pt135-photo-empty">Sin fotografías añadidas.</div>';grid.querySelectorAll('[data-view-photo]').forEach(n=>n.onclick=()=>openPhoto(a[Number(n.dataset.viewPhoto)]));grid.querySelectorAll('[data-left-photo]').forEach(b=>b.onclick=()=>move(part,Number(b.dataset.leftPhoto),Number(b.dataset.leftPhoto)-1));grid.querySelectorAll('[data-right-photo]').forEach(b=>b.onclick=()=>move(part,Number(b.dataset.rightPhoto),Number(b.dataset.rightPhoto)+1));grid.querySelectorAll('[data-rm-photo]').forEach(b=>b.onclick=()=>{const x=photos(part);x.splice(Number(b.dataset.rmPhoto),1);save(part,x);render();decorateHistory()})}
async function add(files){const part=partNo();if(!part||!isDraft())return;let a=photos(part),list=Array.from(files||[]);if(!list.length)return;const room=MAX-a.length;if(room<=0){W.alert('Máximo 6 fotografías por parte.');return}if(list.length>room){W.alert('Solo se pueden guardar 6 fotografías por parte. Se añadirán '+room+' de las seleccionadas.');list=list.slice(0,room)}for(const file of list){if(!String(file.type||'').startsWith('image/'))continue;try{const img=await resize(file),next=a.concat([img]);save(part,next);a=next}catch(err){W.alert(String(err&&err.message||'No se pudo guardar una fotografía.'));break}}render();decorateHistory();if(a.length>=MAX)W.alert('Has alcanzado el máximo de 6 fotografías en este parte.')}
function decorateHistory(){const box=e('pt135-history');if(!box||box.hidden)return;const all=read();box.querySelectorAll('.pt135-history').forEach(card=>{const strong=card.querySelector('strong'),part=norm(strong&&strong.textContent),n=Array.isArray(all[part])?Math.min(MAX,all[part].length):0;let badge=card.querySelector('.pt135-history-photos');if(n){if(!badge){badge=d().createElement('div');badge.className='pt135-history-photos';const help=card.querySelector('.pt135-help');if(help)help.insertAdjacentElement('afterend',badge);else card.prepend(badge)}badge.textContent='📷 '+n+' foto'+(n===1?'':'s')}else if(badge)badge.remove()})}
function inject(){if(!W||!d())return;style();const sh=e('pt135-share');if(sh)sh.textContent='Compartir PDF / WhatsApp';const ed=e('pt135-editor'),part=partNo();if(!ed||!part)return;if(e('pt135-photo-wrap')&&lastPart===part){render();return}const old=e('pt135-photo-wrap');if(old)old.remove();lastPart=part;const wrap=d().createElement('div');wrap.id='pt135-photo-wrap';wrap.innerHTML='<div class="pt135-photo-head"><div><strong>Fotografías del parte</strong><div class="pt135-photo-warning">Máximo 6 fotografías. Se reducen automáticamente para el PDF A4. El orden 1–6 será el mismo en el PDF.</div></div><span id="pt135-photo-count">0 / 6</span></div>'+(isDraft()?'<div style="margin-top:9px"><button type="button" id="pt135-photo-add">📷 Añadir fotos de la galería</button><input id="pt135-photo-input" type="file" accept="image/*" multiple hidden></div>':'')+'<div id="pt135-photo-grid" class="pt135-photo-grid"></div>';const obs=e('pt135-observaciones');const anchor=obs&&obs.closest('label');if(anchor&&anchor.parentNode)anchor.parentNode.insertBefore(wrap,anchor.nextSibling);else ed.appendChild(wrap);if(isDraft()&&e('pt135-photo-add')){e('pt135-photo-add').onclick=()=>e('pt135-photo-input').click();e('pt135-photo-input').onchange=ev=>{add(ev.target.files);ev.target.value=''}}render()}
function watch(){if(!d())return;decorateHistory();const ed=e('pt135-editor');if(ed&&(!obs||obs.__target!==ed)){if(obs)try{obs.disconnect()}catch(_){}obs=new W.MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(inject,80)});obs.observe(ed,{childList:true,subtree:true});obs.__target=ed}inject()}
function init(w){W=w||W;if(!W)return;watch();W.setInterval(watch,900)}
window.Soltec135PartesFotos={init,version:BUILD};
(function boot(){try{const f=document.getElementById('app134');if(f&&f.contentWindow&&f.contentWindow.document)return init(f.contentWindow)}catch(_){}setTimeout(boot,250)})();
})();