(function(){'use strict';
const B='V1.35-BETA2-20260913';
function api(){return window.P2}function S(v){return api().S(v)}function E(v){return api().E(v)}function D(id){return api().D(id)}function WW(){return D('partes').ownerDocument.defaultView}
function css(){let d=D('partes').ownerDocument;if(D('ptb2media'))return;let st=d.createElement('style');st.id='ptb2media';st.textContent='.ptPhoto{border:1px solid #dbe3ee;border-radius:14px;background:#fff;padding:10px;margin:8px 0}.ptThumbs{display:grid;grid-template-columns:1fr 1fr;gap:8px}.ptThumb img{width:100%;height:115px;object-fit:cover;border-radius:10px}.ptSign{width:100%;height:160px;background:#fff;border:1px dashed #94a3b8;border-radius:10px;touch-action:none}.ptSign polyline{fill:none;stroke:#111;stroke-width:4;stroke-linecap:round;stroke-linejoin:round}@media(min-width:700px){.ptThumbs{grid-template-columns:repeat(4,1fr)}}@media print{.np{display:none}}';d.head.appendChild(st)}
function html(p,l){css();return'<div class="sectionTitle">Fotografías</div>'+['antes:Antes','durante:Durante','despues:Después'].map(z=>{let [k,t]=z.split(':'),a=p.fotos[k]||[];return'<div class="ptPhoto"><b>'+t+'</b>'+(l?'':'<input type="file" id="f_'+k+'" accept="image/*" capture="environment" multiple>')+'<div class="ptThumbs">'+a.map((x,i)=>'<div class="ptThumb"><img src="'+E(x.data)+'"><label class="ptSmall"><input type="checkbox" data-inc="'+k+':'+i+'" '+(x.includePdf!==false?'checked':'')+' '+(l?'disabled':'')+'> PDF</label>'+(l?'':'<button data-del="'+k+':'+i+'">Quitar</button>')+'</div>').join('')+'</div></div>'}).join('')+'<div class="sectionTitle">Conformidad y firmas</div><label class="ptBox"><input id="conf" type="checkbox" '+(p.conformidad?'checked':'')+' '+(l?'disabled':'')+'> Cliente conforme con el trabajo realizado.</label><label>Nombre firmante<input id="firmante" value="'+E(p.firmante)+'" '+(l?'disabled':'')+'></label><label>DNI/NIF opcional<input id="nif" value="'+E(p.nif)+'" '+(l?'disabled':'')+'></label><div class="ptSmall">Firma cliente</div><svg id="sig" class="ptSign" viewBox="0 0 900 240">'+S(p.firma)+'</svg>'+(l?'':'<button id="clearsig">Limpiar firma</button>')+'<div class="ptSmall">Firma técnico opcional</div><svg id="sigT" class="ptSign" viewBox="0 0 900 210">'+S(p.firmaTec)+'</svg>'+(l?'':'<button id="clearT">Limpiar firma técnico</button>')+(l?'<div class="ptActions"><button id="pdf2" type="button">Ver / guardar PDF</button></div>':'')}
function read(p){p.conformidad=!!D('conf')?.checked;p.firmante=D('firmante')?.value||'';p.nif=D('nif')?.value||'';return p}
function validate(p){if(!p.conformidad)return'Falta conformidad.';if(!S(p.firmante))return'Falta nombre firmante.';if(!S(p.firma))return'Falta firma cliente.';return''}
function bind(p,l){if(l){let b=D('pdf2');if(b)b.onclick=()=>pdf(api().get());return}['antes','durante','despues'].forEach(k=>{let f=D('f_'+k);if(f)f.onchange=()=>add(k,f.files)});D('conf')&&(D('conf').onchange=api().auto);D('firmante')&&(D('firmante').oninput=api().auto);D('nif')&&(D('nif').oninput=api().auto);D('clearsig')&&(D('clearsig').onclick=()=>{let c=api().get();c.firma='';api().put(c);api().form()});D('clearT')&&(D('clearT').onclick=()=>{let c=api().get();c.firmaTec='';api().put(c);api().form()});D('pNew').querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{let [k,i]=b.dataset.del.split(':'),c=api().get();c.fotos[k].splice(+i,1);api().put(c);api().form()});D('pNew').querySelectorAll('[data-inc]').forEach(b=>b.onchange=()=>{let [k,i]=b.dataset.inc.split(':'),c=api().get();c.fotos[k][+i].includePdf=b.checked;api().put(c)});draw('sig','firma');draw('sigT','firmaTec')}
function draw(id,key){let s=D(id),down=0,pts=[];function pos(ev){let r=s.getBoundingClientRect(),p=ev.touches?ev.touches[0]:ev;return[(p.clientX-r.left)*900/r.width,(p.clientY-r.top)*(id==='sig'?240:210)/r.height].map(x=>Math.round(x))}s.onpointerdown=ev=>{ev.preventDefault();down=1;pts=[pos(ev)]};s.onpointermove=ev=>{if(!down)return;ev.preventDefault();pts.push(pos(ev));let pl=s.ownerDocument.createElementNS('http://www.w3.org/2000/svg','polyline');pl.setAttribute('points',pts.map(p=>p.join(',')).join(' '));s.appendChild(pl)};WW().addEventListener('pointerup',()=>{if(!down)return;down=0;let c=api().get();c[key]=s.innerHTML;api().set(c);api().auto()},{passive:true})}
function fotoFile(f){return new Promise(ok=>{let r=new FileReader();r.onload=()=>ok({data:String(r.result),includePdf:true,name:f.name,createdAt:new Date().toISOString()});r.readAsDataURL(f)})}
async function add(k,fs){let c=api().get();for(let f of Array.from(fs||[]).slice(0,5))c.fotos[k].push(await fotoFile(f));api().put(c);api().form()}
function doc(p){p=api().norm(p);let imgs=[];['antes','durante','despues'].forEach(k=>(p.fotos[k]||[]).forEach(f=>{if(f.includePdf!==false)imgs.push('<img src="'+E(f.data)+'">')}));let em=api().main().empresa||{};return'<!doctype html><html><head><meta charset=utf-8><title>'+E(p.partNo)+'</title><style>@page{size:A4;margin:12mm}body{font-family:Arial}.top{border-bottom:2px solid #111;padding-bottom:12px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.box{border:1px solid #ddd;padding:8px;border-radius:8px;margin:5px 0}.imgs{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.imgs img{width:100%;height:115px;object-fit:cover}.sig{display:grid;grid-template-columns:1fr 1fr;gap:20px}.sg{height:110px;border-bottom:1px solid #111}.sg polyline{fill:none;stroke:#111;stroke-width:4;stroke-linecap:round;stroke-linejoin:round}.np{position:fixed;right:15px;top:15px}@media print{.np{display:none}}</style></head><body><button class=np onclick=print()>Guardar como PDF / imprimir</button><div class=top><h1>PARTE DE TRABAJO</h1><b>'+E(em.nombre||em.nombreComercial||'SOLTEC')+'</b><br>Nº '+E(p.partNo)+' · Aviso '+E(p.avisoNo)+'</div><h2>Cliente</h2><div class=grid><div class=box>'+E(p.cliente)+'</div><div class=box>'+E(p.telefono)+' '+E(p.email)+'</div><div class=box>'+E(p.direccion)+'</div><div class=box>'+E(p.contacto)+'</div></div><h2>Trabajos realizados</h2><p>'+E(p.trabajos).replace(/\n/g,'<br>')+'</p><h2>Material empleado</h2><p>'+E(p.material).replace(/\n/g,'<br>')+'</p><h2>Resultado</h2><p><b>'+E(p.resultado)+'</b></p>'+(imgs.length?'<h2>Fotografías</h2><div class=imgs>'+imgs.join('')+'</div>':'')+'<h2>Firmas</h2><div class=sig><div><b>Cliente</b><br><svg class=sg viewBox="0 0 900 240">'+S(p.firma)+'</svg><br>'+E(p.firmante)+' '+E(p.nif)+'</div><div><b>Técnico</b><br><svg class=sg viewBox="0 0 900 210">'+S(p.firmaTec)+'</svg><br>'+E(p.tecnico)+'</div></div></body></html>'}
function pdf(p){let w=WW().open('','_blank');if(!w)return WW().alert('El navegador bloqueó la vista. Permite ventanas emergentes.');w.document.open();w.document.write(doc(p));w.document.close()}
function loadB2(w){window.P2Extra={html,read,validate,bind,pdf};let s=document.getElementById('parts135b2loader');if(window.P2UI&&window.Soltec134Parts&&window.Soltec134Parts.version===B){window.Soltec134Parts.init(w);return}if(s)return;s=document.createElement('script');s.id='parts135b2loader';s.src='./parts135b2.js?build='+encodeURIComponent(B)+'&t='+Date.now();s.onload=()=>{if(window.Soltec134Parts)window.Soltec134Parts.init(w)};document.head.appendChild(s)}
window.Soltec134PartsPdf={init:function(w){try{loadB2(w)}catch(e){console.error('PARTES MEDIA B2',e)}},open:pdf,version:B};
})();
