(function(){'use strict';
const BUILD='V135-PARTES-DELETE3',PARTS='APP_AVISOS_PARTES_V134',OBRAS='APP_AVISOS_PARTES_OBRAS_V135';let W=null,obs=null,timer=0;
function d(){return W&&W.document}function db(){return window.SoltecDB135}function text(v){return v==null?'':String(v)}
function parse(v,f){try{const x=JSON.parse(v||'');return x==null?f:x}catch(_){return f}}
function removeAux(part){try{const x=parse(W.localStorage.getItem(OBRAS),{values:[],byPart:{},presupuestoByPart:{}});if(part&&part.partNo){if(x&&x.byPart)delete x.byPart[part.partNo];if(x&&x.presupuestoByPart)delete x.presupuestoByPart[part.partNo];W.localStorage.setItem(OBRAS,JSON.stringify(x))}}catch(_){}}
function rawPartNo(x){return text(x&&(x.partNo||x.numero)).trim()}
function removePart(id){const api=db();if(!api||!id)return false;const part=api.partById(id);if(!part)return false;const raw=parse(W.localStorage.getItem(PARTS),[]),wrapped=!Array.isArray(raw)&&raw&&Array.isArray(raw.parts),rows=Array.isArray(raw)?raw:(wrapped?raw.parts:[]),targetNo=text(part.partNo).trim();const next=rows.filter(x=>{const sameId=text(x&&x.id)===text(id);const sameNo=targetNo&&rawPartNo(x)===targetNo;return !(sameId||sameNo)});if(next.length===rows.length)return false;if(wrapped){const out=Object.assign({},raw,{parts:next});W.localStorage.setItem(PARTS,JSON.stringify(out))}else W.localStorage.setItem(PARTS,JSON.stringify(next));removeAux(part);try{api.markChanged()}catch(_){}return !api.parts().some(p=>text(p.partNo).trim()===targetNo)}
function refresh(){const box=d()&&d().getElementById('pt135-history');if(!box)return;const search=d().getElementById('pt135-search');if(search){search.dispatchEvent(new W.Event('input',{bubbles:true}))}else{const tab=d().getElementById('pt135-list');if(tab)tab.click()}}
function inject(){const doc=d();if(!doc)return;doc.querySelectorAll('#pt135-history .pt135-history').forEach(card=>{if(card.querySelector('[data-delete-part]'))return;const open=card.querySelector('[data-open-part]'),actions=card.querySelector('.pt135-actions');if(!open||!actions)return;const id=open.getAttribute('data-open-part')||'',part=db()&&db().partById(id);if(!part)return;const b=doc.createElement('button');b.type='button';b.dataset.deletePart=id;b.className='danger pt135-delete';b.textContent='Eliminar';b.onclick=()=>{const current=db()&&db().partById(id)||part,name=current.partNo||'este parte';if(!W.confirm('¿Eliminar definitivamente '+name+'?\n\nEsta acción no se puede deshacer.'))return;if(removePart(id)){refresh()}else W.alert('No se pudo eliminar el parte.')};actions.appendChild(b)})}
function style(){const doc=d();if(!doc||doc.getElementById('pt135-delete-style'))return;const s=doc.createElement('style');s.id='pt135-delete-style';s.textContent='.pt135-delete{background:#fff!important;color:#b42318!important;border:1px solid #f1a7a1!important}.pt135-delete:hover{background:#fff3f2!important}';doc.head.appendChild(s)}
function watch(){const doc=d();if(!doc)return;style();inject();const box=doc.getElementById('pt135-history');if(box&&(!obs||obs.__target!==box)){if(obs)try{obs.disconnect()}catch(_){}obs=new W.MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(inject,40)});obs.observe(box,{childList:true,subtree:true});obs.__target=box}}
function init(w){W=w||W;if(!W)return;watch();W.setInterval(watch,800)}
window.Soltec135PartesDelete={init,version:BUILD};
(function boot(){try{const f=document.getElementById('app134');if(f&&f.contentWindow&&f.contentWindow.document)return init(f.contentWindow)}catch(_){}setTimeout(boot,250)})();
})();
