(function(){'use strict';
const B='V1.35-RC1-20260913',CFG='APP_AVISOS_PARTES_CONFIG_V134';
function A(){return window.P2||null}function W(){let a=A();return a&&a.w?a.w:null}function S(v){return v==null?'':String(v)}function J(v,d){try{return JSON.parse(v||'')||d}catch(e){return d}}
function mark(){let w=W();if(!w)return;try{w.localStorage.setItem('SOLTEC_SYNC_PENDING_V134','1')}catch(e){}}
function cfg(){let w=W(),base={mailText:'Buenos días,\n\nAdjuntamos el parte de trabajo Nº {numero}, correspondiente al aviso {aviso}.\n\nCliente: {cliente}\nResultado: {resultado}\n\nUn saludo.',waText:'Buenos días. Enviamos el parte de trabajo Nº {numero} del aviso {aviso}. Cliente: {cliente}. Resultado: {resultado}.',legalText:'Cliente conforme con el trabajo realizado.',pdfFooter:'Parte de trabajo generado por SOLTEC SAT.'};return Object.assign(base,w?J(w.localStorage.getItem(CFG),{}):{})}
function saveCfg(c){let w=W();if(!w)return;w.localStorage.setItem(CFG,JSON.stringify(Object.assign(cfg(),c)));mark()}
function revNo(base){let a=A(),n=1;if(!a)return 2;(a.parts()||[]).forEach(p=>{if(S(p.parentPartId)===S(base.id)||S(p.originalPartNo)===S(base.partNo)){let r=parseInt(S(p.revisionNo||'').replace(/\D/g,''),10);if(r>=n)n=r}});return n+1}
function createRevision(base){let a=A(),w=W();if(!a||!base)return;base=a.norm(base);let r=revNo(base),p=JSON.parse(JSON.stringify(base));p.id='PTREV'+Date.now()+Math.random().toString(36).slice(2,6);p.parentPartId=base.id;p.originalPartNo=base.originalPartNo||base.partNo;p.revisionNo=r;p.partNo=(base.originalPartNo||base.partNo)+'-R'+r;p.status='draft';p.locked=false;p.conformidad=false;p.firmante='';p.nif='';p.firma='';p.firmaTec='';p.sentAt='';p.sentVia='';p.signedAt='';p.updatedAt=new Date().toISOString();p.build=B;p.revisionReason='Corrección / revisión del parte '+base.partNo;a.set(a.put(p));if(window.P2UI){P2UI.form();P2UI.hist()}try{w.alert('Revisión creada: '+p.partNo+'. El parte original queda bloqueado.')}catch(e){}}
function addButtons(){let a=A(),w=W(),d=w&&w.document;if(!a||!d)return;let c=a.get&&a.get();let box=d.getElementById('pNew');if(c&&box&&c.status!=='draft'&&!d.getElementById('revPartBtn')){let b=d.createElement('button');b.id='revPartBtn';b.type='button';b.textContent='Crear revisión / corrección';b.onclick=()=>createRevision(a.get());let act=box.querySelector('.ptActions')||box;b.style.marginTop='8px';act.appendChild(b)}let h=d.getElementById('pHist');if(h){h.querySelectorAll('[data-open]').forEach(open=>{let p=a.parts().find(x=>x.id===open.dataset.open),wrap=open.parentElement;if(p&&p.status!=='draft'&&wrap&&!wrap.querySelector('[data-rev="'+p.id+'"]')){let b=d.createElement('button');b.textContent='Crear revisión';b.dataset.rev=p.id;b.onclick=()=>createRevision(a.parts().find(x=>x.id===b.dataset.rev));wrap.appendChild(b)}})}let cfgBox=d.getElementById('ptEnvioCfg');if(cfgBox&&!d.getElementById('ptLegalText')){let cc=cfg(),details=cfgBox.querySelector('details');if(details){let extra=d.createElement('div');extra.innerHTML='<label>Texto legal / conformidad<textarea id="ptLegalText" rows="3"></textarea></label><label>Pie del PDF<textarea id="ptPdfFooter" rows="2"></textarea></label>';let save=d.getElementById('ptSaveEnvioCfg');details.insertBefore(extra,save);d.getElementById('ptLegalText').value=cc.legalText;d.getElementById('ptPdfFooter').value=cc.pdfFooter;let old=save.onclick;save.onclick=function(){saveCfg({mailText:d.getElementById('ptMailText').value,waText:d.getElementById('ptWaText').value,legalText:d.getElementById('ptLegalText').value,pdfFooter:d.getElementById('ptPdfFooter').value});w.alert('Configuración de partes guardada.')}}}}
function patchDoc(){if(!window.Soltec134PartsPdf||window.Soltec134PartsPdf.__stableDoc)return;let oldOpen=window.Soltec134PartsPdf.open;if(typeof oldOpen==='function'){window.Soltec134PartsPdf.open=function(p){try{p=(A()&&A().norm)?A().norm(p):p;let c=cfg();let win=W().open('','_blank');if(!win)return oldOpen(p);let body='<!doctype html><html><head><meta charset="utf-8"><title>'+S(p.partNo)+'</title><style>@page{size:A4;margin:12mm}body{font-family:Arial;color:#111}.top{border-bottom:2px solid #111;padding-bottom:10px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.box{border:1px solid #ddd;border-radius:8px;padding:8px;margin:4px 0}.sig{display:grid;grid-template-columns:1fr 1fr;gap:20px}.sg{height:110px;border-bottom:1px solid #111}.sg polyline{fill:none;stroke:#111;stroke-width:4;stroke-linecap:round;stroke-linejoin:round}.foot{border-top:1px solid #ddd;margin-top:20px;padding-top:8px;font-size:11px;color:#555}.np{position:fixed;right:15px;top:15px}@media print{.np{display:none}}</style></head><body><button class="np" onclick="print()">Guardar como PDF / imprimir</button><div class="top"><h1>PARTE DE TRABAJO</h1><b>Nº '+S(p.partNo)+'</b> · Aviso '+S(p.avisoNo||p.avisoId)+(p.originalPartNo?' · Revisión de '+S(p.originalPartNo):'')+'</div><h2>Cliente</h2><div class="grid"><div class="box">'+S(p.cliente)+'</div><div class="box">'+S(p.telefono)+' '+S(p.email)+'</div><div class="box">'+S(p.direccion)+'</div><div class="box">'+S(p.contacto)+'</div></div><h2>Trabajos realizados</h2><p>'+S(p.trabajos).replace(/\n/g,'<br>')+'</p><h2>Material empleado</h2><p>'+S(p.material).replace(/\n/g,'<br>')+'</p><h2>Resultado</h2><p><b>'+S(p.resultado)+'</b></p><h2>Conformidad</h2><p>'+S(c.legalText).replace(/\n/g,'<br>')+'</p><h2>Firmas</h2><div class="sig"><div><b>Cliente</b><br><svg class="sg" viewBox="0 0 900 240">'+S(p.firma)+'</svg><br>'+S(p.firmante)+' '+S(p.nif)+'</div><div><b>Técnico</b><br><svg class="sg" viewBox="0 0 900 210">'+S(p.firmaTec)+'</svg><br>'+S(p.tecnico)+'</div></div><div class="foot">'+S(c.pdfFooter).replace(/\n/g,'<br>')+'</div></body></html>';win.document.open();win.document.write(body);win.document.close()}catch(e){oldOpen(p)}};window.Soltec134PartsPdf.__stableDoc=1}}
function patch(){try{patchDoc();if(window.P2UI&&!window.P2UI.__stable){['form','hist','show'].forEach(k=>{let old=window.P2UI[k];if(typeof old==='function')window.P2UI[k]=function(){let r=old.apply(this,arguments);setTimeout(addButtons,120);return r}});window.P2UI.__stable=1}addButtons()}catch(e){console.error('PARTES STABLE',e)}}
function init(){patch();setInterval(patch,1200)}
window.Soltec135Stable={init,version:B,createRevision:createRevision};init();
})();
