(function(){'use strict';
const PARTS='APP_AVISOS_PARTES_V134';
let W=null,previewUrl='',previewPart=null,observer=null;
function t(v){return v==null?'':String(v)}
function esc(v){return t(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function parse(v,d){try{const x=JSON.parse(String(v||''));return x&&typeof x==='object'?x:d}catch(e){return d}}
function el(id){return W&&W.document.getElementById(id)}
function loadParts(){const a=parse(W.localStorage.getItem(PARTS),[]);return Array.isArray(a)?a:[]}
function byId(id){return loadParts().find(p=>String(p.id)===String(id))||null}
function currentPart(){const h=el('ptFormHost');return h&&h.dataset.partId?byId(h.dataset.partId):null}
function fileName(p){const n=t(p&&p.partNo).replace(/[^A-Za-z0-9_-]+/g,'_')||'PARTE';const f=t(p&&p.fecha)||new Date().toISOString().slice(0,10);return 'PARTE_'+n+'_'+f+'.pdf'}
function shareText(p){return 'Parte de trabajo Nº '+t(p&&p.partNo)+(p&&p.cliente?' · '+t(p.cliente):'')+'.'}
function ensureUi(){if(!W||!W.document||el('ptPdfOverlay'))return;const d=W.document,st=d.createElement('style');st.id='ptPdfPreviewStyle';st.textContent='.ptPdfOverlay{position:fixed;inset:0;z-index:30000;background:rgba(15,23,42,.72);display:none;padding:12px}.ptPdfOverlay.show{display:flex;align-items:center;justify-content:center}.ptPdfBox{width:min(920px,100%);height:min(94dvh,1050px);background:#fff;border-radius:14px;display:flex;flex-direction:column;overflow:hidden;box-shadow:0 18px 60px rgba(0,0,0,.35)}.ptPdfHead{display:flex;align-items:center;gap:8px;padding:10px 12px;border-bottom:1px solid #dbe3ee}.ptPdfHead strong{flex:1}.ptPdfHead button{padding:7px 11px}.ptPdfInfo{font-size:12px;color:#667085;padding:7px 12px;background:#f8fafc;border-bottom:1px solid #e5e7eb}.ptPdfFrame{width:100%;flex:1;border:0;background:#eef2f7}.ptPdfActions{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;padding:9px;border-top:1px solid #dbe3ee}.ptPdfActions button{padding:10px 6px;font-size:12px}@media(max-width:520px){.ptPdfOverlay{padding:5px}.ptPdfBox{height:96dvh}.ptPdfActions{grid-template-columns:1fr 1fr}.ptPdfActions button:last-child{grid-column:1/-1}}';d.head.appendChild(st);const o=d.createElement('div');o.id='ptPdfOverlay';o.className='ptPdfOverlay';o.innerHTML='<div class="ptPdfBox"><div class="ptPdfHead"><strong id="ptPdfTitle">Vista previa del PDF</strong><button type="button" id="ptPdfClose">Cerrar</button></div><div class="ptPdfInfo" id="ptPdfInfo">Generando PDF…</div><iframe id="ptPdfFrame" class="ptPdfFrame" title="Vista previa del parte"></iframe><div class="ptPdfActions"><button type="button" id="ptPdfOpen">Abrir PDF</button><button type="button" id="ptPdfSave">Guardar PDF</button><button type="button" id="ptPdfShare">Enviar / compartir PDF</button></div></div>';d.body.appendChild(o);el('ptPdfClose').onclick=closePreview;o.addEventListener('click',ev=>{if(ev.target===o)closePreview()})}
function closePreview(){const o=el('ptPdfOverlay');if(o)o.classList.remove('show')}
function downloadBlob(blob,p){const d=W.document,a=d.createElement('a'),u=W.URL.createObjectURL(blob);a.href=u;a.download=fileName(p);d.body.appendChild(a);a.click();setTimeout(()=>{try{W.URL.revokeObjectURL(u)}catch(e){}a.remove()},1800)}
async function shareBlob(blob,p){try{const f=new File([blob],fileName(p),{type:'application/pdf'}),nav=W.navigator;if(nav.share&&(!nav.canShare||nav.canShare({files:[f]}))){await nav.share({title:'Parte de trabajo '+t(p.partNo),text:shareText(p),files:[f]});return}downloadBlob(blob,p);W.alert('Este dispositivo no permite adjuntar el PDF directamente desde SOLTEC. Se ha guardado el PDF para que puedas adjuntarlo en correo o WhatsApp.')}catch(e){if(e&&e.name==='AbortError')return;W.alert('No se pudo compartir el PDF: '+t(e&&e.message||e))}}
async function openPreview(p){if(!p||p.status==='pending'){W.alert('El parte debe estar firmado antes de generar el PDF.');return}ensureUi();previewPart=p;const o=el('ptPdfOverlay'),frame=el('ptPdfFrame'),info=el('ptPdfInfo');o.classList.add('show');el('ptPdfTitle').textContent='Parte '+t(p.partNo)+' · Vista previa PDF';info.textContent='Generando PDF…';frame.removeAttribute('src');try{const blob=await window.Soltec134Parts.makePdf(p);if(previewUrl){try{W.URL.revokeObjectURL(previewUrl)}catch(e){}}previewUrl=W.URL.createObjectURL(blob);frame.src=previewUrl+'#toolbar=1&navpanes=0&view=FitH';info.textContent='PDF preparado. Si el visor del móvil queda en blanco, pulsa “Abrir PDF”.';el('ptPdfOpen').onclick=function(){const x=W.open(previewUrl,'_blank');if(!x)W.alert('El navegador ha bloqueado la apertura. Pulsa “Guardar PDF” o “Enviar / compartir PDF”.')};el('ptPdfSave').onclick=function(){downloadBlob(blob,p)};el('ptPdfShare').onclick=function(){shareBlob(blob,p)}}catch(e){info.textContent='No se pudo generar el PDF: '+t(e&&e.message||e);frame.removeAttribute('src')}}
function hookForm(){if(!W||!W.document)return;ensureUi();const send=el('ptSendBox');if(send&&send.style.display!=='none'){const grid=send.querySelector('.ptActionGrid');if(grid&&!el('ptPreviewPdf')){const b=W.document.createElement('button');b.type='button';b.id='ptPreviewPdf';b.textContent='👁 Ver PDF';grid.insertBefore(b,grid.firstChild);b.onclick=function(){const p=currentPart();if(p)openPreview(p)}}const dl=el('ptDownload'),sh=el('ptShare'),em=el('ptEmail'),wa=el('ptWhats');if(dl)dl.textContent='⬇ Guardar PDF';if(sh)sh.textContent='↗ Enviar PDF';if(em)em.textContent='✉ Correo';if(wa)wa.textContent='◉ WhatsApp';let note=send.querySelector('.ptPdfSendNote');if(!note){note=W.document.createElement('div');note.className='ptNote ptPdfSendNote';note.style.marginTop='9px';note.textContent='Primero puedes revisar el PDF con “Ver PDF”. En móvil/tablet, Correo y WhatsApp usan el sistema de compartir archivos cuando está disponible, enviando el PDF como archivo adjunto.';send.appendChild(note)}}W.document.querySelectorAll('#ptPaneHist [data-pdf]').forEach(b=>{if(b.dataset.ptPdfPreview==='1')return;b.dataset.ptPdfPreview='1';b.textContent='Ver PDF';b.onclick=function(){const p=byId(b.dataset.pdf);if(p)openPreview(p)}})}
function startObserver(){if(observer)return;observer=new W.MutationObserver(()=>{setTimeout(hookForm,0)});observer.observe(W.document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['style']})}
window.Soltec134PartsPdf={init:function(w){W=w;try{hookForm();startObserver()}catch(e){console.error('V1.34 PDF PREVIEW',e)}},open:function(p){return openPreview(p)}};
})();
