(function(){'use strict';
const BUILD='V1.35-BETA1-20260913';
const MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE';
const PARTS='APP_AVISOS_PARTES_V134';
const VERSIONLOG='APP_AVISOS_VERSIONLOG_V135';
const PENDING='SOLTEC_SYNC_PENDING_V134';
let W=null,current=null,saveTimer=null,observer=null;
function t(v){return v==null?'':String(v)}
function parse(v,d){try{const x=JSON.parse(String(v||''));return x==null?d:x}catch(e){return d}}
function esc(v){return t(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function el(id){return W&&W.document.getElementById(id)}
function now(){return new Date().toISOString()}
function today(){return new Date().toISOString().slice(0,10)}
function dateES(v){if(!v)return'';try{return new Date(v.length===10?v+'T12:00:00':v).toLocaleDateString('es-ES')}catch(e){return v}}
function dateTimeES(v){if(!v)return'';try{return new Date(v).toLocaleString('es-ES')}catch(e){return v}}
function main(){return parse(W.localStorage.getItem(MAIN),{empresa:{},tecnico:{},solicitante:{},avisos:[],papelera:[]})}
function notices(){const p=main();return (Array.isArray(p.avisos)?p.avisos:[]).slice().sort((a,b)=>t(b.fecha||b.actualizado).localeCompare(t(a.fecha||a.actualizado))||Number(b.id||0)-Number(a.id||0))}
function noticeById(id){return notices().find(a=>String(a.id)===String(id))||null}
function company(){const p=main(),e=p.empresa||{},tec=p.tecnico||{};return{tecnico:t(tec.nombre),empresa:t(e.nombre||e.nombreComercial)}}
function markPending(){try{W.localStorage.setItem(PENDING,'1')}catch(e){}}
function normalizePart(p){p=p||{};const mats=Array.isArray(p.materiales)?p.materiales:(Array.isArray(p.materials)?p.materials:[]);return{schema:'PARTES_V1',build:p.build||BUILD,id:t(p.id)||('PT-'+Date.now()+'-'+Math.random().toString(36).slice(2,7)),partNo:t(p.partNo)||t(p.numero)||t(p.avisoId)||('PT-'+Date.now()),avisoId:t(p.avisoId||p.avisoNo),avisoNo:t(p.avisoNo||p.avisoId),createdAt:t(p.createdAt)||now(),updatedAt:t(p.updatedAt)||now(),status:p.status==='signed'||p.status==='firmado'?'signed':p.status==='sent'||p.status==='enviado'?'sent':'draft',cliente:t(p.cliente),direccion:t(p.direccion),contacto:t(p.contacto),telefono:t(p.telefono),email:t(p.email),fecha:t(p.fecha)||today(),tecnico:t(p.tecnico),trabajos:t(p.trabajos),materiales:mats.length?mats.map(m=>({cantidad:t(m.cantidad||m.qty),descripcion:t(m.descripcion||m.description),observaciones:t(m.observaciones||m.note)})):[{cantidad:'',descripcion:'',observaciones:''}],resultado:t(p.resultado),notasInternas:t(p.notasInternas||p.internalNotes),locked:!!p.locked,signedAt:t(p.signedAt),sentAt:t(p.sentAt),sentVia:t(p.sentVia),revisiones:Array.isArray(p.revisiones)?p.revisiones:[]}}
function loadParts(){const x=parse(W.localStorage.getItem(PARTS),[]),arr=Array.isArray(x)?x:(Array.isArray(x.parts)?x.parts:[]);return arr.map(normalizePart)}
function saveParts(arr){W.localStorage.setItem(PARTS,JSON.stringify(arr.map(normalizePart)));saveVersionMark();markPending()}
function saveVersionMark(){try{const log=parse(W.localStorage.getItem(VERSIONLOG),[]),arr=Array.isArray(log)?log:[];if(!arr.some(x=>x&&x.build===BUILD))arr.unshift({build:BUILD,module:'Partes de Trabajo',dataSchema:'PARTES_V1',at:now(),note:'Beta 1: base de partes, guardado automático e histórico'});W.localStorage.setItem(VERSIONLOG,JSON.stringify(arr.slice(0,50)))}catch(e){}}
function upsertPart(p){const arr=loadParts(),i=arr.findIndex(x=>x.id===p.id);p.updatedAt=now();p.build=BUILD;p.schema='PARTES_V1';if(i>=0)arr[i]=p;else arr.unshift(p);saveParts(arr);return p}
function nextPartNo(){const y=String(new Date().getFullYear()),arr=loadParts();let max=0;arr.forEach(p=>{const m=t(p.partNo).match(/^PT-(\d{4})-(\d+)$/);if(m&&m[1]===y)max=Math.max(max,Number(m[2])||0)});return 'PT-'+y+'-'+String(max+1).padStart(5,'0')}
function blankPartFromNotice(a){const co=company();return normalizePart({id:'PT-'+Date.now()+'-'+Math.random().toString(36).slice(2,8),partNo:nextPartNo(),avisoId:t(a.id),avisoNo:t(a.id),createdAt:now(),updatedAt:now(),status:'draft',cliente:t(a.cliente),direccion:t(a.direccion),contacto:t(a.contacto),telefono:t(a.telefono),email:t(a.email),fecha:today(),tecnico:co.tecnico,trabajos:'',materiales:[{cantidad:'',descripcion:'',observaciones:''}],resultado:'',notasInternas:''})}
function css(){return `
#soltecHomeModules{display:grid;grid-template-columns:1fr;gap:10px;margin:10px 0 12px}.soltecHomeBtn{width:100%;min-height:78px;border-radius:16px;text-align:left;display:block;background:#fff;border:1px solid #dbe3ee;color:#182033;padding:14px}.soltecHomeBtn strong{display:block;font-size:19px}.soltecHomeBtn span{display:block;color:#6f7b8f;font-size:12px;margin-top:5px}.soltecHomeBtn.primary{border-color:#0b5ed7;background:#eef5ff;color:#0b5ed7}
#partes .ptTabs{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:12px}#partes .ptTabs button.active{background:#0b5ed7;color:#fff}.ptGrid{display:grid;grid-template-columns:1fr;gap:0 10px}.ptWide{grid-column:1/-1}.ptReadonly{background:#f5f7fa!important;color:#182033}.ptReadonly input{background:#f5f7fa}.ptHeader{border:1px solid #dbe3ee;border-radius:14px;padding:10px;background:#fbfdff;margin-bottom:10px}.ptStateLine{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-bottom:10px}.ptBadge{border-radius:999px;padding:6px 9px;font-size:11px;font-weight:900;background:#fff7db;color:#8a5a00;white-space:nowrap}.ptBadge.signed{background:#e8f3ff;color:#174ea6}.ptBadge.sent{background:#eaf8ee;color:#166534}.ptSmall{font-size:12px;color:#667085;margin-top:4px}.ptAuto{font-size:12px;color:#15803d;font-weight:800;min-height:16px;margin-top:6px}.ptMaterial{display:grid;grid-template-columns:.55fr 1.3fr 1fr auto;gap:6px;align-items:end;border-bottom:1px solid #e5e7eb;padding:8px 0}.ptMaterial label{margin:0}.ptMaterial input{font-size:14px;padding:9px}.ptMaterial button{padding:8px 9px;margin-bottom:0;border-color:#b42318;color:#b42318}.ptResult{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:8px 0 12px}.ptResult label{border:1px solid #dbe3ee;border-radius:12px;background:#fff;padding:10px;color:#182033;font-size:14px;margin:0}.ptResult input{width:auto;margin:0 7px 0 0}.ptHistory{border:1px solid #dbe3ee;border-radius:14px;padding:12px;margin:9px 0;background:#fff}.ptHistoryTop{display:flex;justify-content:space-between;gap:8px}.ptHistoryActions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:9px}.ptHistoryActions button{font-size:13px;padding:9px 6px}.ptCreateFromAviso{grid-column:1/-1;border-color:#0b5ed7!important;color:#0b5ed7!important;background:#eef5ff!important}.ptNote{background:#fff8db;border:1px solid #f3d889;padding:10px;border-radius:11px;font-size:12px;color:#6f5400;margin:8px 0}.ptSearch{margin-bottom:10px}#pt_trabajos{min-height:230px;line-height:1.5}#pt_notasInternas{min-height:120px;line-height:1.45}@media(min-width:700px){#soltecHomeModules{grid-template-columns:1fr 1fr}.ptGrid{grid-template-columns:1fr 1fr}.ptResult{grid-template-columns:repeat(4,1fr)}}@media(max-width:520px){.ptMaterial{grid-template-columns:1fr}.ptMaterial button{width:100%}.ptResult{grid-template-columns:1fr}}
`}
function inject(){const d=W.document;if(!el('pt135Style')){const st=d.createElement('style');st.id='pt135Style';st.textContent=css();d.head.appendChild(st)}ensureSection();ensureNav();ensureHome();observeAvisos();renderAll();saveVersionMark()}
function ensureSection(){const d=W.document;if(el('partes'))return;const mainEl=d.querySelector('main');if(!mainEl)return;const s=d.createElement('section');s.id='partes';s.className='screen';s.innerHTML='<div class="card"><div class="ptStateLine"><h2 style="margin:0">Partes de trabajo</h2><span class="ptBadge">V1.35 BETA 1</span></div><div class="ptTabs"><button type="button" id="ptTabNuevo" class="active">Nuevo / editar</button><button type="button" id="ptTabHist">Histórico</button></div><div id="ptPaneNuevo"></div><div id="ptPaneHist" style="display:none"></div></div>';mainEl.appendChild(s);el('ptTabNuevo').onclick=function(){tab('nuevo')};el('ptTabHist').onclick=function(){tab('hist')};}
function ensureNav(){const d=W.document,nav=d.querySelector('nav.bottom');if(!nav)return;let b=el('navPartes');if(!b){b=d.createElement('button');b.type='button';b.id='navPartes';b.innerHTML='🧾<br>Partes';const fin=el('navFinalizar');nav.insertBefore(b,fin||null)}b.onclick=function(){showParts()};}
function ensureHome(){const d=W.document,ini=el('inicio'),res=el('resumenInicio');if(!ini||el('soltecHomeModules'))return;const box=d.createElement('div');box.id='soltecHomeModules';box.innerHTML='<button type="button" class="soltecHomeBtn primary" id="homeAvisos"><strong>📝 Avisos</strong><span>Crear y gestionar avisos</span></button><button type="button" class="soltecHomeBtn" id="homePartes"><strong>🧾 Partes de trabajo</strong><span>Crear, continuar y consultar partes</span></button>';if(res&&res.parentNode)res.parentNode.insertBefore(box,res);else ini.querySelector('.card')?.appendChild(box);el('homeAvisos').onclick=function(){if(W.App&&W.App.show)W.App.show('avisos')};el('homePartes').onclick=function(){showParts()}}
function activate(id){const d=W.document;d.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));const s=el(id);if(s)s.classList.add('active');d.querySelectorAll('nav.bottom button').forEach(x=>x.classList.remove('active'));const navId=id==='inicio'?'navInicio':id==='avisos'?'navAvisos':id==='config'?'navConfig':id==='partes'?'navPartes':'';const b=navId&&el(navId);if(b)b.classList.add('active');try{W.scrollTo(0,0)}catch(e){}}
function showParts(partId){ensureSection();activate('partes');if(partId){const p=loadParts().find(x=>x.id===partId);if(p){current=p;tab('nuevo');renderForm();return}}tab('nuevo');renderNewPane();renderHistory()}
function tab(which){const n=el('ptPaneNuevo'),h=el('ptPaneHist'),bn=el('ptTabNuevo'),bh=el('ptTabHist');if(n)n.style.display=which==='nuevo'?'block':'none';if(h)h.style.display=which==='hist'?'block':'none';if(bn)bn.classList.toggle('active',which==='nuevo');if(bh)bh.classList.toggle('active',which==='hist');if(which==='hist')renderHistory();else renderNewPane()}
function renderAll(){renderNewPane();renderHistory();enhanceAvisos()}
function renderNewPane(){const h=el('ptPaneNuevo');if(!h)return;if(current){renderForm();return}const list=notices();h.innerHTML='<div class="sectionTitle">Crear parte desde aviso</div><p class="muted">Selecciona un aviso. El parte copiará cliente, dirección, contacto, teléfono y correo. La referencia catastral no se incluye.</p><label>Aviso / cliente<select id="ptAvisoSelect"><option value="">Seleccionar…</option>'+list.map(a=>'<option value="'+esc(a.id)+'">'+esc(a.id)+' · '+esc(a.cliente||'Sin cliente')+' · '+esc(a.direccion||'Sin dirección')+'</option>').join('')+'</select></label><button type="button" class="primary full" id="ptCreateSelected">Crear / continuar parte</button><div class="ptNote">Beta 1: guardado automático e histórico. PDF, firmas, fotos, correo y WhatsApp entran en la siguiente beta.</div>';el('ptCreateSelected').onclick=function(){const id=el('ptAvisoSelect').value;if(id)createOrOpenFromNotice(id)}}
function createOrOpenFromNotice(id){const a=noticeById(id);if(!a)return;const arr=loadParts(),existing=arr.find(p=>String(p.avisoId)===String(id)&&p.status==='draft');current=existing||upsertPart(blankPartFromNotice(a));showParts(current.id)}
function addBlankMaterial(){if(!current)return;current.materiales=current.materiales||[];current.materiales.push({cantidad:'',descripcion:'',observaciones:''});renderForm();scheduleSave()}
function readForm(){if(!current)return null;const p=Object.assign({},current);['trabajos','resultado','notasInternas'].forEach(k=>{const x=el('pt_'+k);if(x)p[k]=x.value});p.materiales=[];let i=0;while(el('pt_mat_cantidad_'+i)||el('pt_mat_desc_'+i)||el('pt_mat_obs_'+i)){p.materiales.push({cantidad:t(el('pt_mat_cantidad_'+i)?.value),descripcion:t(el('pt_mat_desc_'+i)?.value),observaciones:t(el('pt_mat_obs_'+i)?.value)});i++}if(!p.materiales.length)p.materiales=[{cantidad:'',descripcion:'',observaciones:''}];return normalizePart(p)}
function scheduleSave(){if(!current||current.status!=='draft')return;clearTimeout(saveTimer);const m=el('ptAutoSave');if(m)m.textContent='Guardando…';saveTimer=setTimeout(()=>{current=readForm()||current;upsertPart(current);renderHistory();const mm=el('ptAutoSave');if(mm)mm.textContent='Guardado automático: '+new Date().toLocaleTimeString('es-ES')},500)}
function removeMaterial(i){if(!current)return;current=readForm()||current;current.materiales.splice(i,1);if(!current.materiales.length)current.materiales.push({cantidad:'',descripcion:'',observaciones:''});upsertPart(current);renderForm();renderHistory()}
function materialHtml(m,i,locked){return '<div class="ptMaterial"><label>Cantidad<input id="pt_mat_cantidad_'+i+'" value="'+esc(m.cantidad)+'" '+(locked?'disabled':'')+'></label><label>Descripción<input id="pt_mat_desc_'+i+'" value="'+esc(m.descripcion)+'" '+(locked?'disabled':'')+'></label><label>Observaciones<input id="pt_mat_obs_'+i+'" value="'+esc(m.observaciones)+'" '+(locked?'disabled':'')+'></label><button type="button" data-delmat="'+i+'" '+(locked?'disabled':'')+'>Quitar</button></div>'}
function renderForm(){const h=el('ptPaneNuevo');if(!h||!current)return;current=normalizePart(current);const p=current,locked=p.status!=='draft';h.innerHTML='<div class="ptHeader"><div class="ptStateLine"><strong>Parte '+esc(p.partNo)+'</strong><span class="ptBadge '+(p.status==='sent'?'sent':p.status==='signed'?'signed':'')+'">'+esc(statusText(p.status))+'</span></div><div class="ptGrid"><label>Nº parte<input class="ptReadonly" value="'+esc(p.partNo)+'" readonly></label><label>Nº aviso<input class="ptReadonly" value="'+esc(p.avisoNo||p.avisoId)+'" readonly></label><label>Cliente<input class="ptReadonly" value="'+esc(p.cliente)+'" readonly></label><label>Fecha<input class="ptReadonly" value="'+esc(dateES(p.fecha))+'" readonly></label><label class="ptWide">Dirección<input class="ptReadonly" value="'+esc(p.direccion)+'" readonly></label><label>Contacto<input class="ptReadonly" value="'+esc(p.contacto)+'" readonly></label><label>Teléfono<input class="ptReadonly" value="'+esc(p.telefono)+'" readonly></label><label>Correo<input class="ptReadonly" value="'+esc(p.email)+'" readonly></label><label class="ptWide">Técnico<input class="ptReadonly" value="'+esc(p.tecnico)+'" readonly></label></div><div class="ptSmall">Referencia catastral fuera del parte.</div></div><div class="sectionTitle">Trabajos realizados</div><label>Descripción del trabajo<textarea id="pt_trabajos" rows="10" '+(locked?'disabled':'')+' placeholder="Describe aquí los trabajos realizados">'+esc(p.trabajos)+'</textarea></label><div class="sectionTitle">Material empleado</div><div id="ptMateriales">'+(p.materiales||[]).map((m,i)=>materialHtml(m,i,locked)).join('')+'</div>'+(locked?'':'<button type="button" id="ptAddMaterial" class="full">+ Añadir material</button>')+'<div class="sectionTitle" style="margin-top:14px">Resultado del trabajo</div><div class="ptResult">'+['Resuelto','Pendiente','Nueva visita','Requiere presupuesto'].map(r=>'<label><input type="radio" name="pt_resultado_radio" value="'+esc(r)+'" '+(p.resultado===r?'checked':'')+' '+(locked?'disabled':'')+'> '+esc(r)+'</label>').join('')+'</div><input type="hidden" id="pt_resultado" value="'+esc(p.resultado)+'"><div class="sectionTitle">Notas internas</div><label>Notas solo visibles en SOLTEC<textarea id="pt_notasInternas" '+(locked?'disabled':'')+' placeholder="Notas internas. No saldrán en el PDF del cliente.">'+esc(p.notasInternas)+'</textarea></label><div id="ptAutoSave" class="ptAuto">Guardado automático activo</div><div class="row" style="margin-top:10px"><button type="button" id="ptBackList">Histórico</button><button type="button" id="ptClosePart">Cerrar parte</button></div><div class="ptNote">Beta 1 guarda el borrador y el histórico. En Beta 2 añadiremos fotos, firmas, PDF, correo y WhatsApp.</div>';
if(!locked){h.querySelectorAll('textarea,input').forEach(x=>{if(!x.classList.contains('ptReadonly'))x.addEventListener('input',scheduleSave)});h.querySelectorAll('input[name="pt_resultado_radio"]').forEach(x=>x.addEventListener('change',()=>{const r=el('pt_resultado');if(r)r.value=x.value;scheduleSave()}));const add=el('ptAddMaterial');if(add)add.onclick=addBlankMaterial;h.querySelectorAll('[data-delmat]').forEach(b=>b.onclick=()=>removeMaterial(Number(b.dataset.delmat)))}
el('ptBackList').onclick=function(){current=readForm()||current;upsertPart(current);current=null;tab('hist')};el('ptClosePart').onclick=function(){current=readForm()||current;upsertPart(current);current=null;renderNewPane()};}
function statusText(s){return s==='sent'?'ENVIADO':s==='signed'?'FIRMADO':'BORRADOR'}
function renderHistory(){const h=el('ptPaneHist');if(!h)return;const q=t(el('ptSearch')&&el('ptSearch').value).toLowerCase().trim();let arr=loadParts();if(q)arr=arr.filter(p=>[p.partNo,p.avisoNo,p.cliente,p.direccion,p.tecnico,p.status,p.resultado].join(' ').toLowerCase().includes(q));arr.sort((a,b)=>t(b.updatedAt).localeCompare(t(a.updatedAt)));h.innerHTML='<div class="sectionTitle">Histórico de partes</div><label class="ptSearch">Buscar parte<input id="ptSearch" type="search" placeholder="Nº parte, cliente, aviso, técnico o estado" value="'+esc(q)+'"></label><div class="counter">'+arr.length+' parte(s)</div>'+(arr.length?arr.map(p=>'<div class="ptHistory"><div class="ptHistoryTop"><div><strong>'+esc(p.partNo)+'</strong><div class="ptSmall">Aviso '+esc(p.avisoNo||p.avisoId)+' · '+esc(p.cliente||'Sin cliente')+'</div><div class="ptSmall">'+esc(dateES(p.fecha))+' · '+esc(p.tecnico||'Sin técnico')+'</div></div><span class="ptBadge '+(p.status==='sent'?'sent':p.status==='signed'?'signed':'')+'">'+esc(statusText(p.status))+'</span></div>'+(p.resultado?'<div class="ptSmall">Resultado: '+esc(p.resultado)+'</div>':'')+'<div class="ptHistoryActions"><button type="button" data-openpart="'+esc(p.id)+'">Abrir</button><button type="button" data-newfrom="'+esc(p.avisoId)+'">Nuevo parte del aviso</button></div></div>').join(''):'<div class="empty">Todavía no hay partes de trabajo.</div>');const s=el('ptSearch');if(s)s.oninput=()=>renderHistory();h.querySelectorAll('[data-openpart]').forEach(b=>b.onclick=()=>{const p=loadParts().find(x=>x.id===b.dataset.openpart);if(p){current=p;tab('nuevo')}});h.querySelectorAll('[data-newfrom]').forEach(b=>b.onclick=()=>createOrOpenFromNotice(b.dataset.newfrom))}
function enhanceAvisos(){const d=W&&W.document;if(!d)return;d.querySelectorAll('#listaAvisos .avisoCard').forEach(card=>{if(card.querySelector('.ptCreateFromAviso'))return;const actions=card.querySelector('.actions');if(!actions)return;let id='';actions.querySelectorAll('button').forEach(b=>{const s=t(b.getAttribute('onclick'));const m=s.match(/(?:editarAviso|duplicarAviso|eliminarAviso)\((\d+)\)/);if(m&&!id)id=m[1]});if(!id)return;const btn=d.createElement('button');btn.type='button';btn.className='ptCreateFromAviso';btn.textContent='🧾 Crear parte de trabajo';btn.onclick=function(ev){ev.preventDefault();ev.stopPropagation();createOrOpenFromNotice(id)};actions.appendChild(btn);try{actions.style.gridTemplateColumns='1fr 1fr'}catch(e){}})}
function observeAvisos(){const box=el('listaAvisos');if(!box||observer)return;observer=new MutationObserver(()=>enhanceAvisos());observer.observe(box,{childList:true,subtree:true});enhanceAvisos();}
function hookApp(){if(!W||!W.App||W.App.__pt135Hooked)return;const app=W.App,oldShow=app.show;app.show=function(id){const r=oldShow.apply(app,arguments);setTimeout(()=>{ensureHome();observeAvisos();enhanceAvisos();if(id==='partes')showParts()},30);return r};app.__pt135Hooked=true;}
function init(w){W=w;try{inject();hookApp();setTimeout(()=>{inject();hookApp()},250);setTimeout(()=>{ensureHome();enhanceAvisos()},1200);setInterval(()=>{try{ensureNav();ensureHome();enhanceAvisos()}catch(e){}},3000)}catch(e){console.error('SOLTEC PARTES V1.35',e)}}
window.Soltec134Parts={init,show:function(wOrId,id){if(wOrId&&wOrId.document)W=wOrId;showParts(typeof wOrId==='string'?wOrId:id)},createFromNotice:function(id){createOrOpenFromNotice(id)},version:BUILD};
})();
