(function(){'use strict';
const BUILD='V135-PARTES-OBRA1';
const KEY='APP_AVISOS_PARTES_OBRAS_V135';
const PENDING='SOLTEC_SYNC_PENDING_V134';
let W=null,obs=null,timer=0,lastPart='';
function d(){return W&&W.document}function e(id){return d()&&d().getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function norm(v){return String(v||'').trim().replace(/\s+/g,' ')}
function read(){try{const x=JSON.parse(W.localStorage.getItem(KEY)||'null');if(x&&typeof x==='object')return{values:Array.isArray(x.values)?x.values:[],byPart:x.byPart&&typeof x.byPart==='object'?x.byPart:{}}}catch(_){ }return{values:[],byPart:{}}}
function write(x){try{W.localStorage.setItem(KEY,JSON.stringify(x));W.localStorage.setItem(PENDING,'1');const detail={module:'partes',field:'obraDenominacion',at:new Date().toISOString()};try{W.dispatchEvent(new W.CustomEvent('soltec:datachange',{detail}))}catch(_){}}catch(_){}}
function partNo(){const s=d()&&d().querySelector('#pt135-editor .pt135-summary strong');return norm(s&&s.textContent)}
function isDraft(){return !!(d()&&d().querySelector('#pt135-editor .pt135-badge.draft'))}
function learn(part,value){value=norm(value);if(!part||!value)return;const x=read(),now=new Date().toISOString(),prev=norm(x.byPart[part]||'');x.byPart[part]=value;let row=x.values.find(r=>norm(r&&r.name).toLocaleLowerCase('es')===value.toLocaleLowerCase('es'));if(!row){row={name:value,count:0,lastUsed:''};x.values.push(row)}row.name=value;if(prev.toLocaleLowerCase('es')!==value.toLocaleLowerCase('es'))row.count=(Number(row.count)||0)+1;row.lastUsed=now;x.values=x.values.filter(r=>norm(r&&r.name)).sort((a,b)=>(Number(b.count)||0)-(Number(a.count)||0)||String(b.lastUsed||'').localeCompare(String(a.lastUsed||''))).slice(0,80);write(x)}
function suggestions(q){q=norm(q).toLocaleLowerCase('es');const x=read();return x.values.filter(r=>!q||norm(r.name).toLocaleLowerCase('es').includes(q)).slice(0,20)}
function close(){const p=e('pt135-obra-panel');if(p)p.hidden=true}
function open(){const p=e('pt135-obra-panel');if(p){renderList();p.hidden=false}}
function renderList(){const p=e('pt135-obra-list'),inp=e('pt135-obra');if(!p)return;const arr=suggestions(inp&&inp.value);p.innerHTML=arr.length?arr.map(r=>'<button type="button" class="pt135-obra-option" data-obra="'+esc(r.name)+'"><strong>'+esc(r.name)+'</strong><small>Usada '+(Number(r.count)||1)+' vez'+((Number(r.count)||1)===1?'':'es')+'</small></button>').join(''):'<div class="pt135-obra-empty">Escribe una nueva obra o denominación. Se guardará para próximos partes.</div>';p.querySelectorAll('[data-obra]').forEach(b=>b.onclick=()=>{if(!isDraft())return;inp.value=b.getAttribute('data-obra')||'';learn(partNo(),inp.value);close()})}
function ensureStyle(){if(e('pt135-obra-style'))return;const s=d().createElement('style');s.id='pt135-obra-style';s.textContent='#pt135-obra-wrap{position:relative;margin:10px 0 14px}#pt135-obra-wrap label{margin-bottom:5px}#pt135-obra-actions{display:flex;gap:7px;margin-top:6px}#pt135-obra-actions button{flex:1;padding:9px 10px;font-size:12px}#pt135-obra-panel{margin-top:7px;border:1px solid #dbe3ee;border-radius:12px;background:#fff;padding:7px;max-height:260px;overflow:auto;box-shadow:0 8px 22px rgba(15,23,42,.10)}.pt135-obra-option{display:block;width:100%;text-align:left;border:0;border-bottom:1px solid #eef2f6;border-radius:8px;background:#fff;color:#182033;padding:10px}.pt135-obra-option:last-child{border-bottom:0}.pt135-obra-option strong{display:block;font-size:14px}.pt135-obra-option small{display:block;margin-top:3px;color:#6f7b8f;font-weight:400}.pt135-obra-empty{padding:10px;color:#6f7b8f;font-size:12px}';d().head.appendChild(s)}
function inject(){if(!W||!d())return;ensureStyle();const ed=e('pt135-editor'),part=partNo();if(!ed||!part)return;if(e('pt135-obra-wrap')&&lastPart===part)return;const old=e('pt135-obra-wrap');if(old)old.remove();lastPart=part;const x=read(),value=norm(x.byPart[part]||'');const wrap=d().createElement('div');wrap.id='pt135-obra-wrap';wrap.innerHTML='<label>Obra / denominación<input id="pt135-obra" autocomplete="off" placeholder="Ej.: Reforma vivienda, Nave Polígono…" value="'+esc(value)+'" '+(isDraft()?'':'readonly')+'></label>'+(isDraft()?'<div id="pt135-obra-actions"><button type="button" id="pt135-obra-open">▼ Denominaciones guardadas</button><button type="button" id="pt135-obra-save" class="primary">Guardar denominación</button></div><div id="pt135-obra-panel" hidden><div id="pt135-obra-list"></div></div>':'');const summary=ed.querySelector('.pt135-summary');if(summary)summary.insertAdjacentElement('afterend',wrap);else ed.insertBefore(wrap,ed.firstChild);const inp=e('pt135-obra');if(!isDraft()||!inp)return;inp.addEventListener('focus',open);inp.addEventListener('input',()=>{renderList();const p=e('pt135-obra-panel');if(p)p.hidden=false});inp.addEventListener('change',()=>learn(part,inp.value));inp.addEventListener('blur',()=>{setTimeout(()=>{learn(part,inp.value)},120)});e('pt135-obra-open').onclick=()=>{const p=e('pt135-obra-panel');if(p&&p.hidden)open();else close()};e('pt135-obra-save').onclick=()=>{learn(part,inp.value);close()}}
function watch(){if(!d())return;const ed=e('pt135-editor');if(ed&&(!obs||obs.__target!==ed)){if(obs)try{obs.disconnect()}catch(_){ }obs=new W.MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(inject,60)});obs.observe(ed,{childList:true,subtree:true});obs.__target=ed}inject()}
function init(w){W=w||W;if(!W)return;watch();W.setInterval(watch,900)}
window.Soltec135PartesObra={init,version:BUILD};
(function boot(){const f=document.getElementById('app134');if(f&&f.contentWindow&&f.contentWindow.document){init(f.contentWindow)}else setTimeout(boot,250)})();
})();
