(function(){'use strict';
const MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado',PREFIX='APP_AVISOS_FOTOS_V123_';
let urls=[];
function jget(k,d){try{const x=JSON.parse(localStorage.getItem(k)||'null');return x&&typeof x==='object'?x:d}catch(e){return d}}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]))}
function data(){return jget(MAIN,{avisos:[]})}
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains('planos'))q.createObjectStore('planos')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function get(k){return openDb().then(q=>new Promise((ok,no)=>{const r=q.transaction(STATE,'readonly').objectStore(STATE).get(String(k));r.onsuccess=()=>{const v=r.result;q.close();ok(v==null?null:v)};r.onerror=()=>{const e=r.error;q.close();no(e)}}))}
function put(k,v){return openDb().then(q=>new Promise((ok,no)=>{const t=q.transaction(STATE,'readwrite');t.objectStore(STATE).put(v,String(k));t.oncomplete=()=>{q.close();ok()};t.onerror=()=>{const e=t.error;q.close();no(e)}}))}
function revoke(){urls.forEach(u=>{try{URL.revokeObjectURL(u)}catch(e){}});urls=[]}
function objUrl(b){const u=URL.createObjectURL(b);urls.push(u);return u}
function resize(file){return new Promise((ok,no)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{try{const max=1800,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);c.toBlob(b=>{URL.revokeObjectURL(u);if(!b)return no(new Error('NO SE PUDO PROCESAR LA FOTOGRAFÍA'));ok({blob:b,nombre:file.name||('foto_'+Date.now()+'.jpg'),creadaEn:new Date().toISOString(),cgp:false})},'image/jpeg',.86)}catch(e){URL.revokeObjectURL(u);no(e)}};im.onerror=()=>{URL.revokeObjectURL(u);no(new Error('FOTOGRAFÍA NO VÁLIDA'))};im.src=u})}
function style(d){if(d.getElementById('s133PhotoStyle'))return;const s=d.createElement('style');s.id='s133PhotoStyle';s.textContent=`.s133-photo-top{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:end}.s133-photo-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px;margin-top:10px}.s133-photo{border:1px solid #dbe3ee;border-radius:12px;padding:7px;background:#fff;position:relative}.s133-photo.cgp{border:2px solid #15803d;background:#f4fbf6}.s133-photo img{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:8px;cursor:pointer}.s133-photo-name{font-size:10px;color:#667085;margin:5px 0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.s133-photo-actions{display:grid;grid-template-columns:1fr 1fr;gap:5px}.s133-photo-actions button{padding:7px 5px!important;font-size:10px!important}.s133-photo-badge{position:absolute;top:12px;left:12px;background:#15803d;color:#fff;border-radius:999px;padding:4px 7px;font-size:9px;font-weight:900}.s133-photo-status{font-size:11px;color:#667085;margin-top:8px;line-height:1.45}.s133-photo-short{grid-column:1/-1;border:1px solid #dbe3ee;border-radius:12px;padding:10px;background:#f8fafc;margin:7px 0}.s133-photo-short button{width:100%}@media(max-width:560px){.s133-photo-top,.s133-photo-grid{grid-template-columns:1fr}.s133-photo-actions{grid-template-columns:1fr 1fr}}`;d.head.appendChild(s)}
function fill(d,preferred){const s=d.getElementById('s133PhotoSel');if(!s)return;const old=preferred||s.value,a=(data().avisos||[]).slice().sort((x,y)=>Number(y.id)-Number(x.id));s.innerHTML='<option value="">SELECCIONAR…</option>'+a.map(x=>'<option value="'+Number(x.id)+'">'+esc((x.direccion||'SIN DIRECCIÓN')+' · AVISO '+Number(x.id)+(x.cliente?' · '+x.cliente:''))+'</option>').join('');if(old&&a.some(x=>String(x.id)===String(old)))s.value=String(old)}
async function render(d){revoke();const id=Number((d.getElementById('s133PhotoSel')||{}).value)||0,grid=d.getElementById('s133PhotoGrid'),st=d.getElementById('s133PhotoStatus');if(!grid||!st)return;grid.innerHTML='';if(!id){st.textContent='SELECCIONA UN AVISO PARA VER O AÑADIR FOTOGRAFÍAS.';return}let arr=await get(PREFIX+id).catch(()=>[]);if(!Array.isArray(arr))arr=[];const cgp=arr.findIndex(x=>x&&x.cgp===true);st.textContent=arr.length?arr.length+' FOTOGRAFÍA(S) GUARDADA(S). '+(cgp>=0?'FOTO CGP SELECCIONADA.':'FALTA SELECCIONAR FOTO CGP SI PROCEDE.'):'SIN FOTOGRAFÍAS GUARDADAS.';arr.forEach((p,i)=>{if(!p||!p.blob)return;const u=objUrl(p.blob),card=d.createElement('div');card.className='s133-photo'+(p.cgp?' cgp':'');card.innerHTML=(p.cgp?'<div class="s133-photo-badge">FOTO CGP</div>':'')+'<img src="'+u+'" alt="Fotografía '+(i+1)+'"><div class="s133-photo-name">'+esc(p.nombre||('FOTO '+(i+1)))+'</div><div class="s133-photo-actions"><button type="button" data-cgp>'+(p.cgp?'✓ CGP':'MARCAR CGP')+'</button><button type="button" class="danger" data-del>ELIMINAR</button></div>';card.querySelector('img').onclick=()=>{const v=URL.createObjectURL(p.blob);d.defaultView.open(v,'_blank');setTimeout(()=>URL.revokeObjectURL(v),60000)};card.querySelector('[data-cgp]').onclick=async()=>{let a=await get(PREFIX+id).catch(()=>[])||[];a=a.map((x,n)=>Object.assign({},x,{cgp:n===i}));await put(PREFIX+id,a);render(d)};card.querySelector('[data-del]').onclick=async()=>{if(!confirm('¿ELIMINAR ESTA FOTOGRAFÍA DEL AVISO?'))return;let a=await get(PREFIX+id).catch(()=>[])||[];a.splice(i,1);await put(PREFIX+id,a);render(d)};grid.appendChild(card)})}
async function add(d,files){const id=Number((d.getElementById('s133PhotoSel')||{}).value)||0;if(!id){alert('SELECCIONA PRIMERO UN AVISO.');return}const fs=Array.from(files||[]);if(!fs.length)return;const st=d.getElementById('s133PhotoStatus');st.textContent='PROCESANDO '+fs.length+' FOTOGRAFÍA(S)…';const neu=[];for(const f of fs)neu.push(await resize(f));let old=await get(PREFIX+id).catch(()=>[])||[];if(!Array.isArray(old))old=[];await put(PREFIX+id,old.concat(neu));await render(d)}
function injectScreen(w,d){if(d.getElementById('photos133'))return;style(d);const main=d.querySelector('main'),nav=d.querySelector('nav.bottom');if(!main||!nav)return;const sec=d.createElement('section');sec.id='photos133';sec.className='screen';sec.innerHTML='<div class="card"><h2>Fotografías del aviso</h2><p class="muted">Las fotografías quedan guardadas en el expediente del aviso. Marca una como FOTO CGP para incorporarla en su apartado específico de la memoria RES-CNMC.</p><div class="s133-photo-top"><label style="margin:0">Aviso<select id="s133PhotoSel"></select></label><label style="margin:0"><span class="muted">Añadir</span><input id="s133PhotoFiles" type="file" accept="image/*" multiple></label></div><div id="s133PhotoStatus" class="s133-photo-status"></div><div id="s133PhotoGrid" class="s133-photo-grid"></div></div>';main.appendChild(sec);nav.style.gridTemplateColumns='repeat(6,1fr)';const b=d.createElement('button');b.type='button';b.id='navPhotos133';b.innerHTML='📷<br>Fotos';const cfg=d.getElementById('navConfig');nav.insertBefore(b,cfg);const oldShow=w.App.show.bind(w.App);w.App.show=function(id){if(id==='photos133'){['inicio','avisos','config','exp132','mem132','photos133'].forEach(x=>{const e=d.getElementById(x);if(e)e.className='screen'+(x===id?' active':'')});Array.from(nav.querySelectorAll('button')).forEach(x=>x.classList.remove('active'));b.classList.add('active');fill(d);render(d);w.scrollTo(0,0);return}return oldShow(id)};b.onclick=()=>w.App.show('photos133');d.getElementById('s133PhotoSel').onchange=()=>render(d);d.getElementById('s133PhotoFiles').onchange=function(){const fs=this.files;this.value='';add(d,fs).catch(e=>alert(e.message))};fill(d)}
function injectShortcut(w,d){if(d.getElementById('s133PhotoShort'))return;const grid=d.querySelector('#formAviso .grid2');if(!grid)return;const target=Array.from(grid.querySelectorAll('.sectionTitle')).find(x=>/DATOS DEL AVISO/i.test(x.textContent||''));const box=d.createElement('div');box.id='s133PhotoShort';box.className='s133-photo-short';box.innerHTML='<b>FOTOGRAFÍAS DEL AVISO</b><div class="muted" style="margin:4px 0 8px">Galería general y fotografía CGP para la memoria RES-CNMC.</div><button type="button" id="s133OpenPhotos">📷 GESTIONAR FOTOGRAFÍAS</button>';if(target)grid.insertBefore(box,target);else grid.appendChild(box);d.getElementById('s133OpenPhotos').onclick=()=>{const id=Number((d.getElementById('avId')||{}).value)||0;if(!id){alert('GUARDA PRIMERO EL AVISO. DESPUÉS PODRÁS AÑADIR FOTOGRAFÍAS.');return}w.App.show('photos133');fill(d,id);d.getElementById('s133PhotoSel').value=String(id);render(d)}}
function hook(w,d){if(w.__s133photos)return;w.__s133photos=true;const A=w.App,sa=A.guardarAviso,e=A.editarAviso;A.guardarAviso=function(){const r=sa.apply(A,arguments);setTimeout(()=>fill(d),30);return r};A.editarAviso=function(id){const r=e.apply(A,arguments);return r}}
window.Soltec133Photos={init:function(w){try{const d=w.document;injectScreen(w,d);injectShortcut(w,d);hook(w,d)}catch(e){console.error('V1.33 FOTOS',e);alert('ERROR EN FOTOGRAFÍAS V1.33: '+e.message)}}};
})();