(function(){'use strict';
const MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',FLAGS='APP_AVISOS_FLAGS_V120',CFG='APP_AVISOS_CONFIG_V127',DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado',PLANS='planos',PHOTOS='APP_AVISOS_FOTOS_V123_';
const urls=[];
function j(k,d){try{const x=JSON.parse(localStorage.getItem(k)||'null');return x&&typeof x==='object'?x:d}catch(e){return d}}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function data(){return j(MAIN,{avisos:[],empresa:{},tecnico:{},solicitante:{}})}
function flags(id){return (j(FLAGS,{})[String(id)]||{})}
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains(PLANS))q.createObjectStore(PLANS)};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error||new Error('No se pudo abrir la base de datos'))})}
function get(store,key){return openDb().then(q=>new Promise((ok,no)=>{let r;try{r=q.transaction(store,'readonly').objectStore(store).get(String(key))}catch(e){q.close();no(e);return}r.onsuccess=()=>{const v=r.result;q.close();ok(v==null?null:v)};r.onerror=()=>{const e=r.error;q.close();no(e)}}))}
function objUrl(b){if(!b)return'';const u=URL.createObjectURL(b);urls.push(u);return u}
function field(k,v,key){return '<div class="cnmc-field'+(key?' cnmc-key':'')+'"><span>'+esc(k)+'</span><strong>'+esc(v||'—')+'</strong></div>'}
function head(e,title,sub){const logo=e.logoData||'';return '<div class="cnmc-head">'+(logo?'<img class="cnmc-logo" src="'+logo+'" alt="Logo">':'')+'<div><h1>'+esc(title||'MEMORIA TÉCNICA DESCRIPTIVA')+'</h1><p>'+esc(sub||'RES-CNMC · INSTALACIONES EN BAJA TENSIÓN')+'</p></div></div>'}
function waitImages(){const imgs=Array.from(document.querySelectorAll('#pages img'));return Promise.all(imgs.map(im=>{if(im.complete)return Promise.resolve();return new Promise(ok=>{const done=()=>ok();im.addEventListener('load',done,{once:true});im.addEventListener('error',done,{once:true});setTimeout(done,4000)})}))}
async function render(){const id=Number(new URLSearchParams(location.search).get('id'))||0,p=data(),a=(p.avisos||[]).find(x=>Number(x.id)===id),box=document.getElementById('pages'),st=document.getElementById('status');if(!id||!a){box.innerHTML='<div class="fatal">No se ha encontrado el aviso para generar la memoria. Vuelve a SOLTEC y selecciona de nuevo el aviso.</div>';st.textContent='No se pudo generar la memoria.';document.getElementById('printBtn').disabled=true;return}
const e=p.empresa||{},t=p.tecnico||{},s=p.solicitante||{},f=flags(id),cfg=j(CFG,{}),plan=await get(PLANS,id).catch(()=>null),photos=(await get(STATE,PHOTOS+id).catch(()=>[]))||[],arr=Array.isArray(photos)?photos:[],cgp=arr.find(x=>x&&x.cgp===true),others=arr.filter(x=>x&&x!==cgp&&x.blob),dir=[a.direccion,a.cp,a.localidad,a.provincia].filter(Boolean).join(' · '),coords=a.latitud&&a.longitud?a.latitud+', '+a.longitud:'—',pot=a.potenciaSolicitada||'',date=new Date().toLocaleDateString('es-ES');
const fileName=('MEMORIA_RES_CNMC_'+(a.direccion||id)).toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,'');document.title=fileName;
const planHtml=plan&&plan.blob?'<div class="cnmc-photo"><img src="'+objUrl(plan.blob)+'" alt="Plano de situación"><div class="cnmc-cap">PLANO DE SITUACIÓN · '+esc(plan.nombre||'PLANO GUARDADO')+' · '+esc(coords)+'</div></div>':'<div class="cnmc-placeholder">PLANO DE SITUACIÓN NO ADJUNTO<br>COORDENADAS: '+esc(coords)+'</div>';
const cgpHtml=cgp&&cgp.blob?'<div class="cnmc-photo"><img src="'+objUrl(cgp.blob)+'" alt="Fotografía CGP"><div class="cnmc-cap">FOTOGRAFÍA PROPUESTA DE UBICACIÓN DE LA CGP · '+esc(cgp.nombre||'FOTO CGP')+'</div></div>':'<div class="cnmc-placeholder">NO HAY FOTOGRAFÍA CGP SELECCIONADA.</div>';
const annex=others.length?'<div class="cnmc-annex">'+others.map((q,i)=>'<div class="cnmc-photo"><img src="'+objUrl(q.blob)+'" alt="Fotografía '+(i+1)+'"><div class="cnmc-cap">'+(i+1)+'. '+esc(q.nombre||'FOTOGRAFÍA')+'</div></div>').join('')+'</div>':'<div class="cnmc-placeholder">NO HAY OTRAS FOTOGRAFÍAS ADJUNTAS.</div>';
box.innerHTML='<section class="cnmc-page">'+head(e)+'<div class="cnmc-sec">1. CARACTERÍSTICAS DE LA SOLICITUD</div><div class="cnmc-grid">'+field('Condiciones de suministro',f.condicionesSuministro?'SÍ':'NO')+field('Nivel de tensión',a.tension,true)+field('Potencia máxima solicitada',pot?pot+' kW':'—',true)+field('Concepto',a.concepto)+'</div><div class="cnmc-sec">2. SOLICITANTE</div><div class="cnmc-grid">'+field('Razón social / Nombre',s.nombre)+field('CIF / NIF',s.nif)+field('Dirección',[s.direccion,s.cp,s.localidad,s.provincia].filter(Boolean).join(' · '))+field('Teléfono',s.telefono)+field('Correo electrónico',s.email)+'</div><div class="cnmc-sec">3. UBICACIÓN DEL SUMINISTRO</div><div class="cnmc-grid">'+field('Cliente / Razón social',a.cliente)+field('Persona de contacto',a.contacto)+field('Dirección postal',dir)+field('Ref. catastral',a.refCatastral)+field('CUPS electricidad',a.cupsE)+field('CUPS gas',a.cupsG)+field('Coordenadas WGS84',coords)+'</div><div class="cnmc-sec">4. DATOS TÉCNICOS DE LA PETICIÓN</div><table class="cnmc-table"><thead><tr><th>CONCEPTO</th><th>TENSIÓN</th><th>POTENCIA SOLICITADA</th></tr></thead><tbody><tr><td>'+esc(a.concepto||'—')+'</td><td>'+esc(a.tension||'—')+'</td><td>'+esc(pot?pot+' kW':'—')+'</td></tr></tbody></table><div class="cnmc-sec">5. OBSERVACIONES</div><div>'+esc(a.observaciones||'—')+'</div><div class="cnmc-foot">SOLTEC · MEMORIA RES-CNMC · Página 1</div></section>'+
'<section class="cnmc-page">'+head(e)+'<div class="cnmc-sec">6. PLANO DE SITUACIÓN</div>'+planHtml+'<div class="cnmc-sec">7. FOTOGRAFÍA PROPUESTA DE UBICACIÓN DE LA CGP</div>'+cgpHtml+'<div class="cnmc-foot">SOLTEC · MEMORIA RES-CNMC · Página 2</div></section>'+
'<section class="cnmc-page">'+head(e)+'<div class="cnmc-sec">8. ANEXO FOTOGRÁFICO</div>'+annex+'<div class="cnmc-foot">SOLTEC · MEMORIA RES-CNMC · Página 3</div></section>'+
'<section class="cnmc-page">'+head(e,'FIRMA Y SELLO','MEMORIA TÉCNICA RES-CNMC')+'<div class="cnmc-sign"><div class="cnmc-signbox">'+field('Empresa',e.nombre||e.nombreComercial)+field('CIF / NIF',e.nif)+field('Técnico',t.nombre)+field('Nº instalador / habilitación',t.numero)+field('Fecha',date)+'</div><div class="cnmc-signbox"><div class="cnmc-signimgs"><div><b>FIRMA</b>'+(cfg.firmaData?'<img src="'+cfg.firmaData+'" alt="Firma">':'<div class="cnmc-placeholder">SIN FIRMA CONFIGURADA</div>')+'</div><div><b>SELLO</b>'+(cfg.selloData?'<img src="'+cfg.selloData+'" alt="Sello">':'<div class="cnmc-placeholder">SIN SELLO CONFIGURADO</div>')+'</div></div></div></div><div class="cnmc-sec">AUDITORÍA DE GENERACIÓN</div><div class="cnmc-grid">'+field('Dirección',dir)+field('CUPS',a.cupsE)+field('Referencia catastral',a.refCatastral)+field('Coordenadas',coords)+field('Plano incorporado',plan&&plan.blob?'SÍ':'NO')+field('Fotografías incorporadas',String(arr.filter(x=>x&&x.blob).length))+field('Foto CGP seleccionada',cgp&&cgp.blob?'SÍ':'NO')+'</div><div class="cnmc-foot">SOLTEC · MEMORIA RES-CNMC · Página 4</div></section>';
await waitImages();st.textContent='Memoria preparada. Pulsa IMPRIMIR / GUARDAR PDF.';document.getElementById('printBtn').disabled=false}
document.getElementById('printBtn').disabled=true;document.getElementById('printBtn').onclick=async()=>{const b=document.getElementById('printBtn'),old=b.textContent;b.disabled=true;b.textContent='PREPARANDO IMPRESIÓN…';try{await waitImages();window.print()}finally{setTimeout(()=>{b.disabled=false;b.textContent=old},500)}};document.getElementById('backBtn').onclick=()=>{location.href='./'};render().catch(e=>{document.getElementById('pages').innerHTML='<div class="fatal">Error al preparar la memoria: '+esc(e&&e.message?e.message:e)+'</div>';document.getElementById('status').textContent='Error al preparar la memoria.'});window.addEventListener('beforeunload',()=>urls.forEach(u=>{try{URL.revokeObjectURL(u)}catch(e){}}));
})();