(function(){'use strict';
const B='V135-ONECLICK1',EXIT='SOLTEC_SAFE_EXIT_V135';let running=false,resumeTimer=0;
function frame(){try{let f=document.getElementById('app134');return f&&f.contentWindow&&f.contentWindow.document?f.contentWindow:null}catch(e){return null}}
function S(v){return String(v==null?'':v)}
function box(w){let d=w.document,b=d.getElementById('safeExit135Box');if(!d.getElementById('safeExit135Style')){let st=d.createElement('style');st.id='safeExit135Style';st.textContent='#safeExit135Box{position:fixed;left:12px;right:12px;bottom:86px;z-index:99999;background:#fff;border:2px solid #0b5ed7;border-radius:16px;padding:14px;box-shadow:0 8px 28px #0003;font-size:14px;color:#182033}#safeExit135Box strong{display:block;font-size:16px;margin-bottom:5px}#safeExit135Box.ok{border-color:#15803d}#safeExit135Box.warn{border-color:#b42318}';d.head.appendChild(st)}if(!b){b=d.createElement('div');b.id='safeExit135Box';b.style.display='none';d.body.appendChild(b)}return b}
function say(w,cls,title,msg){let b=box(w);b.className=cls||'';b.innerHTML='<strong>'+title+'</strong><div>'+msg+'</div>';b.style.display='block'}
function setFlag(w,on){try{if(on)localStorage.setItem(EXIT,JSON.stringify({at:Date.now()}));else localStorage.removeItem(EXIT)}catch(e){}try{if(on)w.localStorage.setItem(EXIT,JSON.stringify({at:Date.now()}));else w.localStorage.removeItem(EXIT)}catch(e){}}
function hasFlag(w){try{if(localStorage.getItem(EXIT))return true}catch(e){}try{return !!w.localStorage.getItem(EXIT)}catch(e){return false}}
function delay(ms){return new Promise(r=>setTimeout(r,ms))}
async function waitRecovery(){for(let i=0;i<40;i++){if(window.Soltec134Recovery&&typeof window.Soltec134Recovery.backupRecoverVerify==='function')return window.Soltec134Recovery;try{if(window.Soltec134AppUpdate&&typeof window.Soltec134AppUpdate.loadRecovery==='function')window.Soltec134AppUpdate.loadRecovery()}catch(e){}await delay(250)}throw new Error('Sistema automático de copia no disponible')}
async function finish(w){say(w,'','Protegiendo y verificando…','No cierres SOLTEC. Haciendo copia de seguridad y comprobando el PC central.');const rec=await waitRecovery(),r=await rec.backupRecoverVerify();if(!r||!r.ok)throw new Error('No se pudo verificar la salida');setFlag(w,false);say(w,'ok','YA PUEDES CERRAR SOLTEC','Copia de seguridad hecha · sincronización verificada · PC central REV. '+r.revision+' · '+r.avisos+' aviso(s).');return r}
async function salirSeguro(w){if(running)return;running=true;let btn=w.document.getElementById('navFinalizar');try{if(btn)btn.disabled=true;setFlag(w,true);say(w,'','Guardando…','No cierres SOLTEC. Guardando el trabajo y sincronizando.');let eng=window.Soltec134Engine;if(!eng||typeof eng.finalizar!=='function')throw new Error('Motor de sincronización no disponible');await Promise.resolve(eng.finalizar(w));await delay(700);await finish(w)}catch(e){setFlag(w,false);say(w,'warn','NO CIERRES TODAVÍA','Salida detenida por seguridad: '+S(e&&e.message||e)+'. Los datos locales no se han sustituido.');}finally{running=false;if(btn)btn.disabled=false;patch()}}
function resume(w){if(running||!hasFlag(w))return;clearTimeout(resumeTimer);resumeTimer=setTimeout(async function(){if(running||!hasFlag(w))return;running=true;let btn=w.document.getElementById('navFinalizar');try{if(btn)btn.disabled=true;await finish(w)}catch(e){setFlag(w,false);say(w,'warn','NO CIERRES TODAVÍA','Salida detenida por seguridad: '+S(e&&e.message||e)+'. Los datos locales no se han sustituido.')}finally{running=false;if(btn)btn.disabled=false;patch()}},1200)}
function patch(){let w=frame();if(!w)return;let d=w.document,b=d.getElementById('navFinalizar');let old=d.getElementById('s134Recovery');if(old)old.remove();let hint=d.getElementById('safeExit135Hint');if(hint)hint.remove();if(!b){resume(w);return}b.innerHTML='✅<br>Salir';b.title='Un clic: guardar, copia de seguridad, sincronizar y verificar';b.onclick=function(ev){if(ev&&ev.preventDefault)ev.preventDefault();salirSeguro(w);return false};resume(w)}
function init(){patch();setTimeout(patch,300);setTimeout(patch,1200);setTimeout(patch,3000);setInterval(patch,2500)}
window.Soltec135SafeExit={init:init,version:B,salir:function(){let w=frame();if(w)return salirSeguro(w)}};init();
})();