(function(){'use strict';
const B='V135-SAFEEXIT1',CFG='SOLTEC_SYNC_CONFIG_V134',PENDING='SOLTEC_SYNC_PENDING_V134',DRAFT='APP_AVISOS_WEB_BORRADOR_V116';let running=false;
function frame(){try{let f=document.getElementById('app134');return f&&f.contentWindow&&f.contentWindow.document?f.contentWindow:null}catch(e){return null}}
function S(v){return String(v==null?'':v)}
function J(v,d){try{let x=JSON.parse(S(v)||'{}');return x&&typeof x==='object'?x:d}catch(e){return d}}
function cfg(w){let c={};try{Object.assign(c,J(localStorage.getItem(CFG),{}))}catch(e){}try{Object.assign(c,J(w.localStorage.getItem(CFG),{}))}catch(e){}return c}
function clean(v){return S(v).trim().replace(/\/+$/,'')}
function configured(c){return !!(clean(c.serverUrl)&&S(c.key).trim())}
function box(w){let d=w.document,b=d.getElementById('safeExit135Box');if(!d.getElementById('safeExit135Style')){let st=d.createElement('style');st.id='safeExit135Style';st.textContent='#safeExit135Box{position:fixed;left:12px;right:12px;bottom:86px;z-index:99999;background:#fff;border:2px solid #0b5ed7;border-radius:16px;padding:14px;box-shadow:0 8px 28px #0003;font-size:14px;color:#182033}#safeExit135Box strong{display:block;font-size:16px;margin-bottom:5px}#safeExit135Box.ok{border-color:#15803d}#safeExit135Box.warn{border-color:#b42318}#safeExit135Box small{display:block;color:#667085;margin-top:6px}';d.head.appendChild(st)}if(!b){b=d.createElement('div');b.id='safeExit135Box';b.style.display='none';d.body.appendChild(b)}return b}
function say(w,cls,title,msg){let b=box(w);b.className=cls||'';b.innerHTML='<strong>'+title+'</strong><div>'+msg+'</div>';b.style.display='block'}
function has(w,k){try{return w.localStorage.getItem(k)==='1'}catch(e){return false}}
async function pcStatus(w,c){let ctl=new w.AbortController(),tm=w.setTimeout(()=>ctl.abort(),12000);try{let r=await w.fetch(clean(c.serverUrl)+'/api/status',{cache:'no-store',headers:{'X-Soltec-Key':S(c.key)},signal:ctl.signal});let j=null;try{j=await r.json()}catch(e){}if(!r.ok)throw new Error(j&&j.error?j.error:'Error PC '+r.status);return j||{}}finally{w.clearTimeout(tm)}}
async function checkSafe(w){let c=cfg(w),lr=Number(c.lastRevision)||0;if(!configured(c))return{ok:false,msg:'PC central no configurado.'};if(has(w,PENDING))return{ok:false,msg:'Quedan trabajos sin sincronizar en este dispositivo.'};try{if(w.localStorage.getItem(DRAFT))return{ok:false,msg:'Hay un borrador pendiente. Guarda el aviso antes de salir.'}}catch(e){}let st;try{st=await pcStatus(w,c)}catch(e){return{ok:false,msg:'No se pudo comprobar el PC central. Mantén SOLTEC abierto y revisa conexión.'}}let rr=Number(st.revision)||0;if(lr&&rr&&lr===rr)return{ok:true,rev:lr};if(!lr&&rr)return{ok:false,msg:'El PC central tiene una revisión que este dispositivo no ha recibido todavía.'};if(lr&&rr&&lr!==rr)return{ok:false,msg:'La revisión local ('+lr+') no coincide con el PC central ('+rr+'). Revisa auditoría.'};return{ok:false,msg:'No se pudo confirmar una revisión válida en el PC central.'}}
async function salirSeguro(w){if(running)return;running=true;let btn=w.document.getElementById('navFinalizar');try{if(btn)btn.disabled=true;say(w,'','Guardando y sincronizando…','No cierres SOLTEC. Estoy pasando los datos al PC central.');let eng=window.Soltec134Engine;if(!eng||typeof eng.finalizar!=='function')throw new Error('Motor de sincronización no disponible');await Promise.resolve(eng.finalizar(w));await new Promise(r=>setTimeout(r,1800));let r=await checkSafe(w);if(r.ok){say(w,'ok','YA PUEDES CERRAR SOLTEC','Datos guardados en el PC central · REV. '+r.rev+'.');}else{say(w,'warn','NO CIERRES TODAVÍA',r.msg+' Pulsa Auditoría o Sincronizar ahora antes de cerrar.')}}catch(e){say(w,'warn','NO CIERRES TODAVÍA','No se pudo completar la salida segura: '+S(e&&e.message||e));}finally{running=false;if(btn)btn.disabled=false;patch()}}
function patch(){let w=frame();if(!w)return;let d=w.document,b=d.getElementById('navFinalizar');if(!b)return;b.innerHTML='✅<br>Salir';b.title='Guardar, sincronizar con PC central y avisar cuando puedas cerrar';b.onclick=function(ev){if(ev&&ev.preventDefault)ev.preventDefault();salirSeguro(w);return false};if(!d.getElementById('safeExit135Hint')){let cfgCard=d.getElementById('s134Engine')||d.querySelector('#config .card');if(cfgCard){let p=d.createElement('p');p.id='safeExit135Hint';p.className='muted';p.style.margin='8px 0 0';p.innerHTML='<b>Salida segura:</b> el botón Salir guarda, sincroniza con el PC central y avisa cuando puedes cerrar.';cfgCard.appendChild(p)}}}
function init(){patch();setTimeout(patch,300);setTimeout(patch,1200);setTimeout(patch,3000);setInterval(patch,2500)}
window.Soltec135SafeExit={init:init,version:B};init();
})();