(function(){'use strict';
const CFG='SOLTEC_SYNC_CONFIG_V134',PENDING='SOLTEC_SYNC_PENDING_V134';
const MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',DRAFT='APP_AVISOS_WEB_BORRADOR_V116';
const DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado';
const OUT=window,GEN='UNIFIED-1';
let W=null,busy=false,pendingConflict=null,lastAutoAt=0;
function e(d,id){return d.getElementById(id)}
function delay(ms){return new Promise(r=>setTimeout(r,ms))}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function parse(v,d){try{const x=JSON.parse(String(v||''));return x&&typeof x==='object'?x:d}catch(x){return d}}
function uid(){try{return (W&&W.crypto?W.crypto:crypto).randomUUID()}catch(x){return'DEV-'+Date.now()+'-'+Math.random().toString(36).slice(2)}}
function loadCfg(){let c={};try{c=parse(W.localStorage.getItem(CFG),{})}catch(x){}try{const o=parse(OUT.localStorage.getItem(CFG),{});['serverUrl','key','deviceId','deviceName','lastRevision','lastHash','lastSyncAt','engineGeneration'].forEach(k=>{if((c[k]==null||c[k]==='')&&o[k]!=null&&o[k]!=='')c[k]=o[k]})}catch(x){}if(!c.deviceId)c.deviceId=uid();if(!c.deviceName)c.deviceName='DISPOSITIVO SOLTEC';return c}
function saveCfg(c){try{W.localStorage.setItem(CFG,JSON.stringify(c))}catch(x){}try{OUT.localStorage.setItem(CFG,JSON.stringify(c))}catch(x){}}
function configured(c){return !!(String(c.serverUrl||'').trim()&&String(c.key||'').trim())}
function clean(v){return String(v||'').trim().replace(/\/+$/,'')}
function setPending(on){try{if(on)W.localStorage.setItem(PENDING,'1');else W.localStorage.removeItem(PENDING)}catch(x){}updateBadge()}
function hasDraft(){try{return !!W.localStorage.getItem(DRAFT)}catch(x){return false}}
function status(msg,err){const x=W&&e(W.document,'s134EngineStatus');if(x){x.textContent=msg||'';x.style.color=err?'#b42318':'#667085'}const y=W&&e(W.document,'s134SyncStatus');if(y&&y!==x){y.textContent=msg||'';y.style.color=err?'#b42318':'#667085'}}
function lastText(){const c=loadCfg(),x=W&&e(W.document,'s134EngineLast');if(x)x.textContent=c.lastSyncAt?'ÚLTIMA SINCRONIZACIÓN: '+new Date(c.lastSyncAt).toLocaleString('es-ES')+' · REV. '+(Number(c.lastRevision)||0):'TODAVÍA NO SE HA SINCRONIZADO ESTE DISPOSITIVO.'}
function badgeNode(){if(!W)return null;const d=W.document,host=d.querySelector('header .headerText')||d.querySelector('header');if(!host)return null;let b=e(d,'s134EngineBadge');if(!b){b=d.createElement('div');b.id='s134EngineBadge';b.style.cssText='margin-top:4px;font-size:10px;font-weight:900;letter-spacing:.2px';host.appendChild(b)}return b}
function badge(text,kind){const b=badgeNode();if(!b)return;b.textContent=text||'';b.style.color=kind==='ok'?'#15803d':kind==='wait'?'#8a5a00':kind==='err'?'#b42318':'#667085'}
function updateBadge(){if(!W)return;const c=loadCfg();if(!configured(c)){badge('PC CENTRAL NO CONFIGURADO','muted');return}if(hasDraft()){badge('BORRADOR LOCAL PENDIENTE','wait');return}let p=false;try{p=W.localStorage.getItem(PENDING)==='1'}catch(x){}if(p)badge('CAMBIOS LOCALES PENDIENTES DE SINCRONIZAR','wait');else if(c.lastSyncAt)badge('TODO SINCRONIZADO · REV. '+(Number(c.lastRevision)||0),'ok');else badge('PREPARADO PARA SINCRONIZAR','muted')}
function openDb(){return new Promise((ok,no)=>{if(!W||!W.indexedDB){no(new Error('IndexedDB no disponible'));return}const r=W.indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains('planos'))q.createObjectStore('planos')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error||new Error('No se pudo abrir IndexedDB'))})}
function req(r){return new Promise((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error||new Error('Error IndexedDB'))})}
function isBlob(v){return !!(v&&typeof v==='object'&&typeof v.size==='number'&&typeof v.type==='string'&&typeof v.arrayBuffer==='function')}
function blobData(b){return new Promise((ok,no)=>{const r=new W.FileReader();r.onload=()=>ok(String(r.result));r.onerror=()=>no(r.error);r.readAsDataURL(b)})}
async function enc(v){if(isBlob(v))return{__soltecBlob:1,mime:v.type||'',name:v.name||'',data:await blobData(v)};if(Array.isArray(v)){const a=[];for(const x of v)a.push(await enc(x));return a}if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v).sort())o[k]=await enc(v[k]);return o}return v}
function dec(v){if(Array.isArray(v))return v.map(dec);if(v&&typeof v==='object'){if(v.__soltecBlob===1){const p=String(v.data||'').split(','),bin=W.atob(p[1]||''),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);const b=new W.Blob([u],{type:v.mime||'application/octet-stream'});if(v.name&&W.File)try{return new W.File([b],v.name,{type:b.type})}catch(x){}return b}const o={};for(const k of Object.keys(v).sort())o[k]=dec(v[k]);return o}return v}
function canonical(v){if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v).sort())o[k]=canonical(v[k]);return o}return v}
async function hashText(t){try{if(W.crypto&&W.crypto.subtle){const b=new W.TextEncoder().encode(String(t)),h=await W.crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,'0')).join('')}}catch(x){}let h=2166136261,t0=String(t);for(let i=0;i<t0.length;i++){h^=t0.charCodeAt(i);h=Math.imul(h,16777619)}return'f'+(h>>>0).toString(16)}
async function hashSnapshot(s){return hashText(JSON.stringify(canonical(s)))}
function mainRawFromSnapshot(s){if(s&&s.localStorage&&s.localStorage[MAIN]!=null)return String(s.localStorage[MAIN]);const a=s&&s.indexedDB&&s.indexedDB.stores&&s.indexedDB.stores[STATE];if(Array.isArray(a)){const z=a.find(x=>String(x&&x.key)===MAIN);if(z&&typeof z.value==='string')return z.value}return''}
function mainData(raw){return parse(raw,{avisos:[],papelera:[],empresa:{},tecnico:{},solicitante:{}})}
function meaningful(s){const raw=mainRawFromSnapshot(s),p=mainData(raw);if((p.avisos||[]).length||(p.papelera||[]).length)return true;if(p.empresa&&Object.values(p.empresa).some(Boolean))return true;if(p.tecnico&&Object.values(p.tecnico).some(Boolean))return true;if(p.solicitante&&Object.values(p.solicitante).some(Boolean))return true;const st=s&&s.indexedDB&&s.indexedDB.stores||{};for(const n of Object.keys(st)){for(const z of(st[n]||[])){const k=String(z&&z.key!=null?z.key:'');if(n===STATE&&(k===MAIN||k===DRAFT))continue;if(k)return true}}return false}
async function forceMainIdb(raw){if(!raw)return;const db=await openDb();if(db.objectStoreNames.contains(STATE))await new Promise((ok,no)=>{const t=db.transaction(STATE,'readwrite');t.objectStore(STATE).put(raw,MAIN);t.oncomplete=ok;t.onerror=()=>no(t.error)});db.close()}
async function snapshot(){const rawMain=String(W.localStorage.getItem(MAIN)||'');if(rawMain)await forceMainIdb(rawMain);const ls={},keys=[];for(let i=0;i<W.localStorage.length;i++){const k=W.localStorage.key(i);if(k&&k.startsWith('APP_AVISOS_')&&k!==DRAFT)keys.push(k)}keys.sort();for(const k of keys)ls[k]=W.localStorage.getItem(k);const db=await openDb(),stores={};for(const name of Array.from(db.objectStoreNames).sort()){const os=db.transaction(name,'readonly').objectStore(name),ks=await req(os.getAllKeys()),vs=await req(os.getAll()),a=[];for(let i=0;i<ks.length;i++){const key=String(ks[i]);if(name===STATE&&key===DRAFT)continue;let value=vs[i];if(name===STATE&&key===MAIN&&Object.prototype.hasOwnProperty.call(ls,MAIN))value=ls[MAIN];a.push({key:await enc(ks[i]),value:await enc(value)})}a.sort((x,y)=>JSON.stringify(canonical(x.key)).localeCompare(JSON.stringify(canonical(y.key))));stores[name]=a}db.close();return{schema:'SOLTEC_SYNC_SNAPSHOT_V134',localStorage:ls,indexedDB:{name:DB,version:DBV,stores}}}
async function stableSnapshot(){let prev=null,prevHash='';for(let i=0;i<5;i++){const s=await snapshot(),h=await hashSnapshot(s);if(prevHash&&h===prevHash)return{s,hash:h};prev=s;prevHash=h;await delay(250)}return{s:prev,hash:prevHash}}
async function applySnapshot(s){if(!s||s.schema!=='SOLTEC_SYNC_SNAPSHOT_V134')throw new Error('La copia recibida del PC no es válida.');const rawMain=mainRawFromSnapshot(s);if(!rawMain)throw new Error('La copia recibida no contiene la base principal de avisos.');const draft=W.localStorage.getItem(DRAFT),rm=[];for(let i=0;i<W.localStorage.length;i++){const k=W.localStorage.key(i);if(k&&k.startsWith('APP_AVISOS_'))rm.push(k)}rm.forEach(k=>W.localStorage.removeItem(k));for(const k of Object.keys(s.localStorage||{}).sort())if(k.startsWith('APP_AVISOS_')&&k!==DRAFT)W.localStorage.setItem(k,String(s.localStorage[k]));W.localStorage.setItem(MAIN,rawMain);if(draft)W.localStorage.setItem(DRAFT,draft);
const db=await openDb(),src=s.indexedDB&&s.indexedDB.stores||{};let draftIdb=null;if(db.objectStoreNames.contains(STATE))draftIdb=await new Promise(ok=>{const q=db.transaction(STATE,'readonly').objectStore(STATE).get(DRAFT);q.onsuccess=()=>ok(q.result);q.onerror=()=>ok(null)});for(const name of Array.from(db.objectStoreNames)){await new Promise((ok,no)=>{const t=db.transaction(name,'readwrite');t.objectStore(name).clear();t.oncomplete=ok;t.onerror=()=>no(t.error)});if(Array.isArray(src[name]))await new Promise((ok,no)=>{const t=db.transaction(name,'readwrite'),os=t.objectStore(name);for(const z of src[name])os.put(dec(z.value),dec(z.key));t.oncomplete=ok;t.onerror=()=>no(t.error)})}if(db.objectStoreNames.contains(STATE))await new Promise((ok,no)=>{const t=db.transaction(STATE,'readwrite'),os=t.objectStore(STATE);os.put(rawMain,MAIN);if(draftIdb!=null)os.put(draftIdb,DRAFT);t.oncomplete=ok;t.onerror=()=>no(t.error)});db.close()}
function headers(c,json){const h={'X-Soltec-Key':String(c.key||'')};if(json)h['Content-Type']='application/json';return h}
async function api(c,path,opt,timeoutMs){const url=clean(c.serverUrl);if(!url)throw new Error('PC SOLTEC no configurado.');const ctl=new W.AbortController(),tm=W.setTimeout(()=>ctl.abort(),timeoutMs||15000);try{const r=await W.fetch(url+path,Object.assign({cache:'no-store',headers:headers(c,false),signal:ctl.signal},opt||{}));let body=null;try{body=await r.json()}catch(x){}if(!r.ok){const er=new Error(body&&body.error?body.error:'Error del servidor ('+r.status+')');er.status=r.status;er.body=body;throw er}return body||{}}catch(x){if(x&&x.name==='AbortError'){const er=new Error('OFFLINE');er.offline=true;throw er}if(x instanceof TypeError){x.offline=true}throw x}finally{W.clearTimeout(tm)}}
async function getStatus(c){return api(c,'/api/status',null,10000)}
async function getRemote(c){return api(c,'/api/snapshot',null,90000)}
async function putRemote(c,s,rev){return api(c,'/api/snapshot',{method:'POST',headers:headers(c,true),body:JSON.stringify({ifRevision:Number(rev)||0,deviceId:c.deviceId,deviceName:c.deviceName,snapshot:s})},240000)}
async function backupLocal(c,s){return api(c,'/api/backup',{method:'POST',headers:headers(c,true),body:JSON.stringify({deviceId:c.deviceId,deviceName:c.deviceName,snapshot:s})},240000)}
function showConflict(show){const x=W&&e(W.document,'s134EngineConflict');if(x)x.style.display=show?'block':'none'}
function setBusy(on){busy=on;if(!W)return;['s134EngineSave','s134EngineTest','s134EngineSync','s134EngineUseLocal','s134EngineUsePc','navFinalizar'].forEach(id=>{const b=e(W.document,id);if(b)b.disabled=!!on})}
function markSynced(c,rev,hash){c.engineGeneration=GEN;c.lastRevision=Number(rev)||0;c.lastHash=hash||'';c.lastSyncAt=new Date().toISOString();saveCfg(c);setPending(false);lastText()}
async function upload(c,local,localHash,rev){status('ENVIANDO CAMBIOS AL PC CENTRAL…');const r=await putRemote(c,local,rev);markSynced(c,r.revision,localHash);status('TODO GUARDADO Y SINCRONIZADO · REV. '+c.lastRevision);badge('TODO SINCRONIZADO · REV. '+c.lastRevision,'ok');return{state:'uploaded',revision:c.lastRevision}}
async function adopt(c,remote,remoteHash){status('RECIBIENDO ÚLTIMA REVISIÓN DEL PC…');await applySnapshot(remote.snapshot);markSynced(c,remote.revision,remoteHash);status('DATOS ACTUALIZADOS DESDE EL PC · REV. '+c.lastRevision+' · REINICIANDO…');badge('DATOS ACTUALIZADOS · REV. '+c.lastRevision,'ok');W.setTimeout(()=>{try{W.top.location.reload()}catch(x){W.location.reload()}},450);return{state:'received',revision:c.lastRevision}}
function conflict(c,local,localHash,remote,remoteHash,msg){pendingConflict={c,local,localHash,remote,remoteHash};setPending(true);showConflict(true);status(msg||'CONFLICTO: EL PC Y ESTE DISPOSITIVO TIENEN CAMBIOS DISTINTOS. NO SE HA SOBRESCRITO NADA.',true);badge('CONFLICTO DE SINCRONIZACIÓN · REVISAR','err');return{state:'conflict'}}
async function syncCore(mode,prepared){if(busy)return{state:'busy'};const c=loadCfg();saveCfg(c);if(!configured(c)){updateBadge();if(mode!=='open'&&mode!=='reconnect')status('CONFIGURA PRIMERO EL PC CENTRAL Y LA CLAVE.',true);return{state:'no-config'}};if((mode==='open'||mode==='reconnect')&&hasDraft()){setPending(true);badge('BORRADOR LOCAL PENDIENTE · NO SE HA SUSTITUIDO','wait');status('HAY UN BORRADOR LOCAL PENDIENTE. SE CONSERVA SIN SOBRESCRIBIR.');return{state:'draft'}};setBusy(true);showConflict(false);pendingConflict=null;try{status(mode==='open'?'COMPROBANDO ÚLTIMA REVISIÓN…':'PREPARANDO DATOS…');const pack=prepared||await stableSnapshot(),local=pack.s,localHash=pack.hash;let st;try{st=await getStatus(c)}catch(x){const changed=!!(c.lastHash&&localHash!==c.lastHash)||(!c.lastHash&&meaningful(local));setPending(changed);badge(changed?'TRABAJO LOCAL · SINCRONIZACIÓN PENDIENTE':'MODO LOCAL · DATOS DISPONIBLES','wait');if(mode!=='open'&&mode!=='reconnect')status('DATOS GUARDADOS LOCALMENTE · PC NO DISPONIBLE.');return{state:'offline'}}const rr=Number(st.revision)||0,lr=Number(c.lastRevision)||0,lh=String(c.lastHash||'');
if(c.engineGeneration!==GEN&&st.hasSnapshot){const remote=await getRemote(c);if(!remote.snapshot)throw new Error('El PC indica que hay datos pero no ha devuelto la copia central.');const remoteHash=await hashSnapshot(remote.snapshot);if(localHash===remoteHash){markSynced(c,remote.revision,remoteHash);status('BASE DE SINCRONIZACIÓN VERIFICADA · REV. '+(Number(remote.revision)||0));badge('TODO SINCRONIZADO · REV. '+(Number(remote.revision)||0),'ok');return{state:'current',revision:Number(remote.revision)||0}}if(!meaningful(local))return await adopt(c,remote,remoteHash);return conflict(c,local,localHash,remote,remoteHash,'PUESTA EN MARCHA DEL MOTOR ÚNICO: ESTE DISPOSITIVO Y EL PC CENTRAL TIENEN DATOS DISTINTOS. POR SEGURIDAD, ELIGE UNA SOLA VEZ QUÉ COPIA ES LA CORRECTA.')}
if(!st.hasSnapshot){if(lr>0){setPending(true);status('SEGURIDAD: EL PC CENTRAL APARECE VACÍO PERO ESTE DISPOSITIVO CONOCE LA REV. '+lr+'. NO SE HA ENVIADO NADA.',true);badge('PC CENTRAL INCONSISTENTE · REVISAR','err');return{state:'server-empty'}}if(meaningful(local)){return await upload(c,local,localHash,rr)}markSynced(c,rr,localHash);status('SIN DATOS PENDIENTES · REV. '+rr);return{state:'current',revision:rr}}
if(rr<lr){setPending(true);status('SEGURIDAD: EL PC CENTRAL ESTÁ EN REV. '+rr+' Y ESTE DISPOSITIVO CONOCE LA REV. '+lr+'. NO SE HA MODIFICADO NADA.',true);badge('REVISIÓN DEL PC ANTERIOR · REVISAR','err');return{state:'server-older'}}
if(lh&&rr===lr&&localHash===lh){c.lastSyncAt=new Date().toISOString();saveCfg(c);setPending(false);lastText();status('TODO ESTÁ ACTUALIZADO · REV. '+rr);badge('TODO SINCRONIZADO · REV. '+rr,'ok');return{state:'current',revision:rr}}
if(lh&&rr===lr&&localHash!==lh){setPending(true);return await upload(c,local,localHash,rr)}
const remote=await getRemote(c);if(!remote.snapshot)throw new Error('El PC indica que hay datos pero no ha devuelto la copia central.');const remoteHash=await hashSnapshot(remote.snapshot);
if(localHash===remoteHash){markSynced(c,remote.revision,remoteHash);status('TODO ESTÁ ACTUALIZADO · REV. '+(Number(remote.revision)||0));badge('TODO SINCRONIZADO · REV. '+(Number(remote.revision)||0),'ok');return{state:'current',revision:Number(remote.revision)||0}}
if(!lh||!lr){if(!meaningful(local))return await adopt(c,remote,remoteHash);return conflict(c,local,localHash,remote,remoteHash,'PRIMERA SINCRONIZACIÓN: EL PC Y ESTE DISPOSITIVO TIENEN DATOS DISTINTOS. NO SE HA ELEGIDO NINGUNA COPIA AUTOMÁTICAMENTE.')}
if(Number(remote.revision)>lr&&localHash===lh)return await adopt(c,remote,remoteHash);
if(Number(remote.revision)>lr&&localHash!==lh)return conflict(c,local,localHash,remote,remoteHash);
if(Number(remote.revision)===lr&&localHash!==lh)return await upload(c,local,localHash,lr);
return conflict(c,local,localHash,remote,remoteHash)
}catch(x){if(x&&x.status===409){status('LA REVISIÓN CENTRAL CAMBIÓ DURANTE LA SINCRONIZACIÓN. NO SE HA SOBRESCRITO NADA.',true);badge('REVISIÓN CAMBIÓ · VOLVER A SINCRONIZAR','err');setPending(true);return{state:'revision-changed'}}if(x&&x.offline){badge('MODO LOCAL · DATOS DISPONIBLES','wait');return{state:'offline'}}status('ERROR DE SINCRONIZACIÓN: '+(x.message||String(x)),true);badge('SINCRONIZACIÓN PENDIENTE','wait');setPending(true);return{state:'error',error:x}}finally{setBusy(false)}}
async function useLocal(){if(!pendingConflict||busy)return;setBusy(true);try{const p=pendingConflict,latest=await getRemote(p.c);await upload(p.c,p.local,p.localHash,Number(latest.revision)||0);showConflict(false);pendingConflict=null}catch(x){status('NO SE PUDO CONSERVAR ESTE DISPOSITIVO: '+(x.message||String(x)),true)}finally{setBusy(false)}}
async function usePc(){if(!pendingConflict||busy)return;setBusy(true);try{const p=pendingConflict;status('GUARDANDO COPIA DE SEGURIDAD DE ESTE DISPOSITIVO…');await backupLocal(p.c,p.local);const latest=await getRemote(p.c),h=await hashSnapshot(latest.snapshot);await adopt(p.c,latest,h);showConflict(false);pendingConflict=null}catch(x){status('NO SE PUDO RECIBIR LA COPIA CENTRAL: '+(x.message||String(x)),true);setBusy(false)}}
async function test(){if(busy)return;const c=readForm();setBusy(true);status('COMPROBANDO CONEXIÓN CON EL PC…');try{const s=await getStatus(c);status('PC CENTRAL CONECTADO · REV. '+(Number(s.revision)||0)+(s.updatedAt?' · '+new Date(s.updatedAt).toLocaleString('es-ES'):''))}catch(x){status('PC NO DISPONIBLE.',true)}finally{setBusy(false)}}
function readForm(){const d=W.document,c=loadCfg();c.deviceName=String(e(d,'s134EngineDevice')?.value||'').trim()||'DISPOSITIVO SOLTEC';c.serverUrl=clean(e(d,'s134EngineUrl')?.value);c.key=String(e(d,'s134EngineKey')?.value||'').trim();saveCfg(c);return c}
function inject(){const d=W.document,card=d.querySelector('#config .card');if(!card||e(d,'s134Engine'))return;const c=loadCfg(),box=d.createElement('details');box.id='s134Engine';box.className='s132acc';box.open=true;box.innerHTML='<summary>🔄 SINCRONIZACIÓN CENTRAL · V1.34</summary><div class="s132body"><p class="muted">Un solo motor: al abrir recibe la última revisión; si este dispositivo tiene cambios y el PC no ha cambiado, los envía. FINALIZAR guarda y sincroniza. Sin conexión sigue trabajando localmente.</p><label>NOMBRE DE ESTE DISPOSITIVO<input id="s134EngineDevice" value="'+esc(c.deviceName||'')+'" placeholder="Ej.: MÓVIL, TABLET, PC CASA"></label><label>DIRECCIÓN SEGURA DEL PC<input id="s134EngineUrl" value="'+esc(c.serverUrl||'')+'" placeholder="https://pc-casa.xxxxx.ts.net"></label><label>CLAVE DE SINCRONIZACIÓN<input id="s134EngineKey" type="password" value="'+esc(c.key||'')+'" autocomplete="off"></label><div id="s134EngineLast" class="muted" style="margin:8px 0"></div><div id="s134EngineStatus" class="status" style="min-height:34px"></div><div class="s132actions"><button type="button" id="s134EngineSave">GUARDAR CONFIGURACIÓN</button><button type="button" id="s134EngineTest">PROBAR CONEXIÓN</button></div><button type="button" id="s134EngineSync" class="primary full" style="margin-top:8px">🔄 SINCRONIZAR AHORA</button><div id="s134EngineConflict" style="display:none;border:2px solid #f0b4ae;border-radius:12px;padding:10px;margin-top:10px;background:#fff8f7"><b>CONFLICTO DE SINCRONIZACIÓN</b><p class="muted">Solo aparece si dos dispositivos han cambiado desde la misma revisión. No se sobrescribe nada automáticamente.</p><div class="s132actions"><button type="button" id="s134EngineUseLocal">CONSERVAR ESTE DISPOSITIVO</button><button type="button" id="s134EngineUsePc">CONSERVAR PC CENTRAL</button></div></div></div>';card.appendChild(box);lastText();e(d,'s134EngineSave').onclick=()=>{const x=readForm();lastText();status('CONFIGURACIÓN GUARDADA.');updateBadge();autoSoon(300)};e(d,'s134EngineTest').onclick=()=>test();e(d,'s134EngineSync').onclick=()=>syncCore('manual');e(d,'s134EngineUseLocal').onclick=()=>useLocal();e(d,'s134EngineUsePc').onclick=()=>usePc()}
async function saveDraft(){try{const d=W.document,f=e(d,'formAviso');if(!f||f.style.display==='none')return false;const ids=['avId','avFecha','avEstado','avCliente','avContacto','avNif','avTelefono','avEmail','avRefCatastral','avDireccion','avCp','avLocalidad','avProvincia','avLatitud','avLongitud','avCupsE','avCupsG','avTension','avIga','avPotenciaCalculada','avPotenciaSolicitada','avConcepto','avObservaciones'],values={};let has=false;for(const id of ids){const n=e(d,id),v=n?String(n.value==null?'':n.value):'';values[id]=v;if(v&&id!=='avFecha'&&id!=='avEstado'&&id!=='avTension')has=true}if(!has)return false;const raw=JSON.stringify({at:new Date().toISOString(),values});W.localStorage.setItem(DRAFT,raw);const db=await openDb();if(db.objectStoreNames.contains(STATE))await new Promise((ok,no)=>{const t=db.transaction(STATE,'readwrite');t.objectStore(STATE).put(raw,DRAFT);t.oncomplete=ok;t.onerror=()=>no(t.error)});db.close();return true}catch(x){return false}}
async function commitOpenAviso(){const d=W.document,f=e(d,'formAviso');if(!f||f.style.display==='none')return true;await saveDraft();if(!W.App||typeof W.App.guardarAviso!=='function')return false;try{W.App.guardarAviso();await delay(200);return f.style.display==='none'}catch(x){return false}}
async function finalizar(){if(busy)return;const b=e(W.document,'navFinalizar');if(b)b.innerHTML='⏳<br>Guardando';const saved=await commitOpenAviso();if(!saved){setPending(true);badge('BORRADOR LOCAL PENDIENTE','wait');status('EL AVISO ABIERTO NO SE HA PODIDO GUARDAR. CORRIGE LOS DATOS INDICADOS ANTES DE FINALIZAR.',true);if(b)b.innerHTML='⚠️<br>Revisar';return}setPending(true);const pack=await stableSnapshot(),r=await syncCore('finish',pack);if(b){if(r&&['uploaded','current','received'].includes(r.state))b.innerHTML='✅<br>Listo';else b.innerHTML='💾<br>Guardado';W.setTimeout(()=>{if(b)b.innerHTML='✅<br>Finalizar'},2200)}}
function dataHooks(){const d=W.document;d.addEventListener('input',ev=>{const t=ev.target;if(t&&t.closest&&t.closest('#formAviso'))setPending(true)},true);d.addEventListener('change',ev=>{const t=ev.target;if(t&&((t.closest&&t.closest('#formAviso'))||String(t.type||'').toLowerCase()==='file'))setPending(true)},true);d.addEventListener('click',ev=>{const b=ev.target&&ev.target.closest?ev.target.closest('button'):null;if(!b)return;const id=b.id||'',txt=String(b.textContent||'').toUpperCase();if(/^s134Engine|^nav/.test(id))return;if(/GUARDAR|ELIMINAR|QUITAR|GENERAR|MARCAR CGP|RESTAURAR|BORRAR/.test(txt))setPending(true)},true)}
function autoSoon(ms){W.setTimeout(()=>autoOpen(),ms||800)}
async function autoOpen(){if(busy)return;const now=Date.now();if(now-lastAutoAt<2500)return;lastAutoAt=now;try{if(OUT.Soltec134AppUpdate&&typeof OUT.Soltec134AppUpdate.check==='function'){const updating=await OUT.Soltec134AppUpdate.check();if(updating)return}}catch(x){}await syncCore('open')}
function init(w){if(W===w&&e(w.document,'s134Engine'))return;W=w;const c=loadCfg();saveCfg(c);inject();dataHooks();updateBadge();autoSoon(1500);try{W.addEventListener('online',()=>autoSoon(1000));W.document.addEventListener('visibilitychange',()=>{if(W.document.visibilityState==='hidden')saveDraft();else autoSoon(900)})}catch(x){}}
OUT.Soltec134Engine={init,finalizar,syncNow:function(w){if(w)W=w;return syncCore('manual')},autoOpen:function(w){if(w)W=w;return autoOpen()}};
})();
