(function(){
'use strict';
const BUILD='V135-ONECLICK1',CFG='SOLTEC_SYNC_CONFIG_V134',PENDING='SOLTEC_SYNC_PENDING_V134',REC='SOLTEC_SYNC_RECOVERY_V134',MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',DRAFT='APP_AVISOS_WEB_BORRADOR_V116',DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado',GEN='UNIFIED-1';
let W=null,busy=false;
function frame(){try{const f=document.getElementById('app134');return f&&f.contentWindow&&f.contentWindow.document?f.contentWindow:null}catch(e){return null}}
function parse(v,d){try{const x=JSON.parse(String(v||''));return x&&typeof x==='object'?x:d}catch(e){return d}}
function clean(v){return String(v||'').trim().replace(/\/+$/,'')}
function loadCfg(){let c={};try{c=parse(W.localStorage.getItem(CFG),{})}catch(e){}try{const o=parse(window.localStorage.getItem(CFG),{});['serverUrl','key','deviceId','deviceName','lastRevision','lastHash','lastSyncAt','engineGeneration'].forEach(k=>{if((c[k]==null||c[k]==='')&&o[k]!=null&&o[k]!=='')c[k]=o[k]})}catch(e){}return c}
function saveCfg(c){try{W.localStorage.setItem(CFG,JSON.stringify(c))}catch(e){}try{window.localStorage.setItem(CFG,JSON.stringify(c))}catch(e){}}
function configured(c){return !!(clean(c.serverUrl)&&String(c.key||'').trim())}
function hasDraft(){try{return !!W.localStorage.getItem(DRAFT)}catch(e){return false}}
function saveRec(r){try{W.localStorage.setItem(REC,JSON.stringify(r))}catch(e){}try{window.localStorage.setItem(REC,JSON.stringify(r))}catch(e){}}
function clearRec(){try{W.localStorage.removeItem(REC)}catch(e){}try{window.localStorage.removeItem(REC)}catch(e){}}
function openDb(){return new Promise((ok,no)=>{const r=W.indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains('planos'))q.createObjectStore('planos')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error||new Error('No se pudo abrir IndexedDB'))})}
function req(r){return new Promise((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error||new Error('Error IndexedDB'))})}
function isBlob(v){return !!(v&&typeof v==='object'&&typeof v.size==='number'&&typeof v.type==='string'&&typeof v.arrayBuffer==='function')}
function blobData(b){return new Promise((ok,no)=>{const r=new W.FileReader();r.onload=()=>ok(String(r.result));r.onerror=()=>no(r.error);r.readAsDataURL(b)})}
async function enc(v){if(isBlob(v))return{__soltecBlob:1,mime:v.type||'',name:v.name||'',data:await blobData(v)};if(Array.isArray(v)){const a=[];for(const x of v)a.push(await enc(x));return a}if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v).sort())o[k]=await enc(v[k]);return o}return v}
function canonical(v){if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v).sort())o[k]=canonical(v[k]);return o}return v}
async function hashText(t){try{if(W.crypto&&W.crypto.subtle){const b=new W.TextEncoder().encode(String(t)),h=await W.crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,'0')).join('')}}catch(e){}let h=2166136261,t0=String(t);for(let i=0;i<t0.length;i++){h^=t0.charCodeAt(i);h=Math.imul(h,16777619)}return'f'+(h>>>0).toString(16)}
async function hashSnapshot(s){return hashText(JSON.stringify(canonical(s)))}
async function forceMainIdb(raw){if(!raw)return;const db=await openDb();if(db.objectStoreNames.contains(STATE))await new Promise((ok,no)=>{const t=db.transaction(STATE,'readwrite');t.objectStore(STATE).put(raw,MAIN);t.oncomplete=ok;t.onerror=()=>no(t.error)});db.close()}
async function snapshot(){const rawMain=String(W.localStorage.getItem(MAIN)||'');if(rawMain)await forceMainIdb(rawMain);const ls={},keys=[];for(let i=0;i<W.localStorage.length;i++){const k=W.localStorage.key(i);if(k&&k.startsWith('APP_AVISOS_')&&k!==DRAFT)keys.push(k)}keys.sort();for(const k of keys)ls[k]=W.localStorage.getItem(k);const db=await openDb(),stores={};for(const name of Array.from(db.objectStoreNames).sort()){const os=db.transaction(name,'readonly').objectStore(name),ks=await req(os.getAllKeys()),vs=await req(os.getAll()),a=[];for(let i=0;i<ks.length;i++){const key=String(ks[i]);if(name===STATE&&key===DRAFT)continue;let value=vs[i];if(name===STATE&&key===MAIN&&Object.prototype.hasOwnProperty.call(ls,MAIN))value=ls[MAIN];a.push({key:await enc(ks[i]),value:await enc(value)})}a.sort((x,y)=>JSON.stringify(canonical(x.key)).localeCompare(JSON.stringify(canonical(y.key))));stores[name]=a}db.close();return{schema:'SOLTEC_SYNC_SNAPSHOT_V134',localStorage:ls,indexedDB:{name:DB,version:DBV,stores}}}
async function stableSnapshot(){let prev=null,ph='';for(let i=0;i<5;i++){const s=await snapshot(),h=await hashSnapshot(s);if(ph&&h===ph)return{s,hash:h};prev=s;ph=h;await new Promise(r=>setTimeout(r,250))}return{s:prev,hash:ph}}
function mainRaw(s){if(s&&s.localStorage&&s.localStorage[MAIN]!=null)return String(s.localStorage[MAIN]);const a=s&&s.indexedDB&&s.indexedDB.stores&&s.indexedDB.stores[STATE];if(Array.isArray(a)){const z=a.find(x=>String(x&&x.key)===MAIN);if(z&&typeof z.value==='string')return z.value}return''}
function summary(s){const p=parse(mainRaw(s),{avisos:[],papelera:[]});return{avisos:Array.isArray(p.avisos)?p.avisos.length:0,papelera:Array.isArray(p.papelera)?p.papelera.length:0}}
function meaningful(s){const q=summary(s);if(q.avisos||q.papelera)return true;const p=parse(mainRaw(s),{empresa:{},tecnico:{},solicitante:{}});if(p.empresa&&Object.values(p.empresa).some(Boolean))return true;if(p.tecnico&&Object.values(p.tecnico).some(Boolean))return true;if(p.solicitante&&Object.values(p.solicitante).some(Boolean))return true;const st=s&&s.indexedDB&&s.indexedDB.stores||{};for(const n of Object.keys(st))for(const z of(st[n]||[])){const k=String(z&&z.key!=null?z.key:'');if(n===STATE&&(k===MAIN||k===DRAFT))continue;if(k)return true}return false}
function headers(c,json){const h={'X-Soltec-Key':String(c.key||'')};if(json)h['Content-Type']='application/json';return h}
async function api(c,path,opt,timeoutMs){const ctl=new W.AbortController(),tm=W.setTimeout(()=>ctl.abort(),timeoutMs||15000);try{const r=await W.fetch(clean(c.serverUrl)+path,Object.assign({cache:'no-store',headers:headers(c,false),signal:ctl.signal},opt||{}));let body=null;try{body=await r.json()}catch(e){}if(!r.ok){const x=new Error(body&&body.error?body.error:'Error del servidor ('+r.status+')');x.status=r.status;x.body=body;throw x}return body||{}}catch(x){if(x&&x.name==='AbortError'){const y=new Error('PC central sin conexión');y.offline=true;throw y}if(x instanceof TypeError)x.offline=true;throw x}finally{W.clearTimeout(tm)}}
async function getStatus(c){return api(c,'/api/status',null,12000)}
async function getRemote(c){return api(c,'/api/snapshot',null,90000)}
async function putRemote(c,s,rev){return api(c,'/api/snapshot',{method:'POST',headers:headers(c,true),body:JSON.stringify({ifRevision:Number(rev)||0,deviceId:c.deviceId,deviceName:c.deviceName,snapshot:s})},240000)}
async function backupLocal(c,s){return api(c,'/api/backup',{method:'POST',headers:headers(c,true),body:JSON.stringify({deviceId:c.deviceId,deviceName:c.deviceName,snapshot:s})},240000)}
function markSynced(c,rev,hash){c.engineGeneration=GEN;c.lastRevision=Number(rev)||0;c.lastHash=hash||'';c.lastSyncAt=new Date().toISOString();saveCfg(c);try{W.localStorage.removeItem(PENDING)}catch(e){}}
function removeOldUi(){try{const d=W.document,n=d.getElementById('s134Recovery');if(n)n.remove();const h=d.getElementById('safeExit135Hint');if(h)h.remove()}catch(e){}}
async function verifyRemote(c,pack){const remote=await getRemote(c);if(!remote||!remote.snapshot)throw new Error('El PC central no devolvió la copia para verificar');const rh=await hashSnapshot(remote.snapshot);if(rh!==pack.hash)throw new Error('La copia del PC central no coincide con este dispositivo');const a=summary(pack.s),b=summary(remote.snapshot);if(a.avisos!==b.avisos||a.papelera!==b.papelera)throw new Error('La verificación de avisos no coincide');return{revision:Number(remote.revision)||0,avisos:b.avisos,papelera:b.papelera}}
async function advanceTo(c,pack,start,target){let cur=Number(start)||0;saveRec({hash:pack.hash,target:Number(target)||0,startedAt:new Date().toISOString()});while(cur<target){const st=await getStatus(c);const rr=Number(st.revision)||0;if(rr!==cur)throw new Error('La revisión central cambió durante la recuperación');if(st.hasSnapshot){const r=await getRemote(c),h=r&&r.snapshot?await hashSnapshot(r.snapshot):'';if(h!==pack.hash)throw new Error('El PC central contiene datos distintos; recuperación detenida')}const w=await putRemote(c,pack.s,cur),next=Number(w.revision)||0;if(next<=cur)throw new Error('El servidor no avanzó de revisión');cur=next}return cur}
async function backupRecoverVerify(){if(busy)throw new Error('Proceso de salida ya en curso');busy=true;try{W=frame();if(!W)throw new Error('Aplicación no disponible');removeOldUi();const c=loadCfg();if(!configured(c))throw new Error('PC central no configurado');if(hasDraft())throw new Error('Hay un borrador pendiente');const pack=await stableSnapshot();if(!pack.s||!meaningful(pack.s))throw new Error('No hay una copia local válida para proteger');const localSum=summary(pack.s);await backupLocal(c,pack.s);let st=await getStatus(c),rr=Number(st.revision)||0,lr=Number(c.lastRevision)||0,recovered=false;if(st.hasSnapshot){const remote=await getRemote(c),rh=remote&&remote.snapshot?await hashSnapshot(remote.snapshot):'';if(rh!==pack.hash)throw new Error('PC central y este dispositivo tienen cambios distintos; no se ha sobrescrito nada');if(rr<lr){const target=lr+1;rr=await advanceTo(c,pack,rr,target);recovered=true}}else{const target=lr>0?Math.max(lr,rr)+1:rr+1;rr=await advanceTo(c,pack,rr,target);recovered=true}const v=await verifyRemote(c,pack);if(v.revision<rr)throw new Error('La revisión final del PC no es válida');markSynced(c,v.revision,pack.hash);clearRec();return{ok:true,revision:v.revision,avisos:v.avisos,papelera:v.papelera,backup:true,recovered:recovered,localAvisos:localSum.avisos}}finally{busy=false}}
function init(){W=frame();if(!W){setTimeout(init,500);return}removeOldUi()}
window.Soltec134Recovery={init,backupRecoverVerify,version:BUILD};
init();
})();