(function(){'use strict';
const CFG='SOLTEC_SYNC_CONFIG_V134';
const PENDING='SOLTEC_SYNC_PENDING_V134';
const DRAFT='APP_AVISOS_WEB_BORRADOR_V116';
const DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado';
const DRAFT_FIELDS=['avId','avFecha','avEstado','avCliente','avContacto','avNif','avTelefono','avEmail','avRefCatastral','avDireccion','avCp','avLocalidad','avProvincia','avLatitud','avLongitud','avCupsE','avCupsG','avTension','avIga','avPotenciaCalculada','avPotenciaSolicitada','avConcepto','avObservaciones'];
const CTX=new WeakMap();
function e(d,id){return d.getElementById(id)}
function delay(ms){return new Promise(r=>setTimeout(r,ms))}
function loadCfg(w){try{return JSON.parse(w.localStorage.getItem(CFG)||'null')||{}}catch(x){return{}}}
function configured(c){return !!(String(c.serverUrl||'').trim()&&String(c.key||'').trim())}
function clean(v){return String(v||'').trim().replace(/\/+$/,'')}
function hasDraft(w){try{return !!w.localStorage.getItem(DRAFT)}catch(x){return false}}
function isPending(w){try{return w.localStorage.getItem(PENDING)==='1'}catch(x){return false}}
function setPending(w,on){try{if(on)w.localStorage.setItem(PENDING,'1');else w.localStorage.removeItem(PENDING)}catch(x){}updateBadge(w)}
function badgeNode(w){const d=w.document;let b=e(d,'s134AutoBadge');if(b)return b;const host=d.querySelector('header .headerText')||d.querySelector('header');if(!host)return null;b=d.createElement('div');b.id='s134AutoBadge';b.style.cssText='margin-top:4px;font-size:10px;font-weight:900;letter-spacing:.2px';host.appendChild(b);return b}
function badge(w,text,kind){const b=badgeNode(w);if(!b)return;b.textContent=text||'';b.style.color=kind==='ok'?'#15803d':kind==='wait'?'#8a5a00':kind==='err'?'#b42318':'#667085'}
function updateBadge(w){const c=loadCfg(w);if(!configured(c)){badge(w,'SINCRONIZACIÓN PC NO CONFIGURADA','muted');return}if(hasDraft(w)){badge(w,'BORRADOR GUARDADO EN ESTE DISPOSITIVO','wait');return}if(isPending(w))badge(w,'CAMBIOS GUARDADOS · SINCRONIZACIÓN PENDIENTE','wait');else if(c.lastSyncAt)badge(w,'TODO SINCRONIZADO · REV. '+(c.lastRevision||0),'ok');else badge(w,'PREPARADO PARA SINCRONIZAR','muted')}
function openDb(w){return new Promise((ok,no)=>{if(!w.indexedDB){no(new Error('IndexedDB no disponible'));return}const r=w.indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains('planos'))q.createObjectStore('planos')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error||new Error('No se pudo abrir IndexedDB'))})}
async function putDraftIdb(w,raw){try{const db=await openDb(w);await new Promise((ok,no)=>{const t=db.transaction(STATE,'readwrite');t.objectStore(STATE).put(raw,DRAFT);t.oncomplete=ok;t.onerror=()=>no(t.error)});db.close()}catch(x){}}
async function saveDraft(w){try{const d=w.document,form=e(d,'formAviso');if(!form||form.style.display==='none')return false;const values={};let has=false;for(const id of DRAFT_FIELDS){const n=e(d,id);const v=n?String(n.value==null?'':n.value):'';values[id]=v;if(v&&id!=='avFecha'&&id!=='avEstado'&&id!=='avTension')has=true}if(!has)return false;const raw=JSON.stringify({at:new Date().toISOString(),values});w.localStorage.setItem(DRAFT,raw);await putDraftIdb(w,raw);return true}catch(x){return false}}
async function commitOpenAviso(w){const d=w.document,form=e(d,'formAviso');if(!form||form.style.display==='none')return{hadForm:false,saved:true};await saveDraft(w);const enough=['avDireccion','avCliente','avConcepto'].some(id=>{const n=e(d,id);return !!(n&&String(n.value||'').trim())});if(!enough||!w.App||typeof w.App.guardarAviso!=='function')return{hadForm:true,saved:false};try{w.App.guardarAviso();await delay(120);return{hadForm:true,saved:form.style.display==='none'}}catch(x){return{hadForm:true,saved:false}}}
async function probe(w,timeout){const c=loadCfg(w);if(!configured(c))return false;const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),timeout||4000);try{const r=await w.fetch(clean(c.serverUrl)+'/api/status',{cache:'no-store',headers:{'X-Soltec-Key':String(c.key||'')},signal:ctl.signal});return !!r.ok}catch(x){return false}finally{clearTimeout(tm)}}
function syncStatus(w){const x=e(w.document,'s134SyncStatus');return x?String(x.textContent||'').trim():''}
function conflictVisible(w){const x=e(w.document,'s134Conflict');return !!(x&&x.style.display!=='none')}
function classify(t){t=String(t||'').toUpperCase();if(t.includes('TODO ESTÁ ACTUALIZADO')||t.includes('SINCRONIZACIÓN COMPLETADA')||t.includes('DATOS DEL PC RECIBIDOS')||t.includes('PC ACTUALIZADO'))return'ok';if(t.includes('CONFLICTO')||t.includes('PRIMERA SINCRONIZACIÓN'))return'conflict';if(t.includes('NO RESPONDE')||t.includes('ERROR DEL SERVIDOR')||t.includes('FAILED TO FETCH')||t.includes('NETWORKERROR'))return'offline';return''}
function watchStatus(w){const x=e(w.document,'s134SyncStatus');if(!x)return;const apply=()=>{const k=classify(x.textContent);if(k==='ok'){if(hasDraft(w)){setPending(w,true);badge(w,'SINCRONIZADO · BORRADOR GUARDADO SOLO EN ESTE DISPOSITIVO','wait')}else{setPending(w,false);const c=loadCfg(w);badge(w,'TODO SINCRONIZADO · REV. '+(c.lastRevision||0),'ok')}}else if(k==='conflict'){setPending(w,true);badge(w,'CONFLICTO DE SINCRONIZACIÓN · REVISAR','err')}else if(k==='offline'){badge(w,'TRABAJO LOCAL · SINCRONIZACIÓN PENDIENTE','wait')}};new MutationObserver(apply).observe(x,{childList:true,characterData:true,subtree:true});apply()}
async function waitIdleButton(w,maxMs){const start=Date.now();while(Date.now()-start<(maxMs||15000)){const b=e(w.document,'s134SyncNow');if(b&&!b.disabled)return b;await delay(250)}return e(w.document,'s134SyncNow')}
async function triggerSync(w,quiet){const c=loadCfg(w);if(!configured(c))return'no-config';if(conflictVisible(w))return'conflict';const b=await waitIdleButton(w,15000);if(!b)return'no-button';if(!(await probe(w,quiet?3500:6000)))return'offline';await saveDraft(w);badge(w,'SINCRONIZANDO CON PC…','muted');b.click();return'started'}
async function autoOpen(w){const c=CTX.get(w);if(!c||c.autoBusy)return;const now=Date.now();if(c.lastAttempt&&now-c.lastAttempt<8000)return;c.lastAttempt=now;c.autoBusy=true;try{const r=await triggerSync(w,true);if(r==='offline'){if(isPending(w)||hasDraft(w))badge(w,'CAMBIOS GUARDADOS · SINCRONIZACIÓN PENDIENTE','wait');else badge(w,'MODO LOCAL · DATOS GUARDADOS EN ESTE DISPOSITIVO','muted')}else if(r==='conflict'){badge(w,'CONFLICTO DE SINCRONIZACIÓN · REVISAR','err')}}finally{c.autoBusy=false}}
function markDirty(w,ev){const t=ev&&ev.target;if(t&&String(t.id||'').startsWith('s134'))return;setPending(w,true)}
function localSaveHooks(w){const d=w.document;d.addEventListener('input',ev=>markDirty(w,ev),true);d.addEventListener('change',ev=>markDirty(w,ev),true);d.addEventListener('click',ev=>{const t=ev.target;if(!t||t.closest&&t.closest('#s134Sync'))return;const b=t.closest?t.closest('button'):null;if(!b)return;if(['navInicio','navAvisos','navConfig','navFinalizar'].includes(b.id))return;setPending(w,true)},true);d.addEventListener('visibilitychange',()=>{if(d.visibilityState==='hidden'){saveDraft(w)}else if(d.visibilityState==='visible'){setTimeout(()=>autoOpen(w),700)}});w.addEventListener('online',()=>setTimeout(()=>autoOpen(w),1200))}
function finishMessage(w,text,kind){badge(w,text,kind);const b=e(w.document,'navFinalizar');if(b){b.disabled=false;b.innerHTML=kind==='ok'?'✅<br>Listo':'💾<br>Guardado';setTimeout(()=>{if(b){b.innerHTML='✅<br>Finalizar';b.disabled=false}},2200)}}
async function waitSyncResult(w,maxMs){const start=Date.now();let seen=false;while(Date.now()-start<(maxMs||185000)){const t=syncStatus(w),k=classify(t);if(t)seen=true;if(k==='ok')return'ok';if(k==='conflict'||conflictVisible(w))return'conflict';if(k==='offline')return'offline';const b=e(w.document,'s134SyncNow');if(seen&&b&&!b.disabled&&t&&!t.toUpperCase().includes('PREPARANDO')&&!t.toUpperCase().includes('CONSULTANDO')&&!t.toUpperCase().includes('ENVIANDO')&&!t.toUpperCase().includes('RECIBIENDO')){if(t.toUpperCase().includes('ACTUALIZADO'))return'ok'}await delay(300)}return'timeout'}
async function finalizar(w){const c=CTX.get(w)||{};if(c.finishBusy)return;c.finishBusy=true;CTX.set(w,c);const b=e(w.document,'navFinalizar');if(b){b.disabled=true;b.innerHTML='⏳<br>Guardando'};let formResult={hadForm:false,saved:true};try{formResult=await commitOpenAviso(w);setPending(w,true);const cfg=loadCfg(w);if(!configured(cfg)){finishMessage(w,formResult.saved?'DATOS GUARDADOS EN ESTE DISPOSITIVO':'BORRADOR GUARDADO EN ESTE DISPOSITIVO','wait');return}if(!(await probe(w,5000))){finishMessage(w,formResult.saved?'DATOS GUARDADOS LOCALMENTE · SE SINCRONIZARÁ AL CONECTAR':'BORRADOR GUARDADO LOCALMENTE · SE SINCRONIZARÁ CUANDO LO GUARDES','wait');return}const syncBtn=await waitIdleButton(w,20000);if(!syncBtn){finishMessage(w,'DATOS GUARDADOS LOCALMENTE','wait');return}badge(w,'GUARDADO LOCAL · SINCRONIZANDO CON PC…','muted');syncBtn.click();const r=await waitSyncResult(w,185000);if(r==='ok'){if(formResult.saved&&!hasDraft(w)){setPending(w,false);finishMessage(w,'TODO GUARDADO Y SINCRONIZADO · YA PUEDES CERRAR SOLTEC','ok')}else{setPending(w,true);finishMessage(w,'RESTO SINCRONIZADO · BORRADOR GUARDADO SOLO EN ESTE DISPOSITIVO','wait')}}else if(r==='conflict'){badge(w,'DATOS GUARDADOS · CONFLICTO: REVISA SINCRONIZACIÓN','err');if(b){b.disabled=false;b.innerHTML='⚠️<br>Revisar'}}else{finishMessage(w,'DATOS GUARDADOS LOCALMENTE · SINCRONIZACIÓN PENDIENTE','wait')}}catch(x){finishMessage(w,'DATOS GUARDADOS LOCALMENTE · SINCRONIZACIÓN PENDIENTE','wait')}finally{c.finishBusy=false}}
function init(w){if(CTX.has(w))return;CTX.set(w,{autoBusy:false,finishBusy:false,lastAttempt:0});updateBadge(w);watchStatus(w);localSaveHooks(w);setTimeout(()=>autoOpen(w),1400)}
window.Soltec134Auto={init,finalizar};
})();