(function(){'use strict';
const CFG='SOLTEC_SYNC_CONFIG_V134',PENDING='SOLTEC_SYNC_PENDING_V134',MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',DRAFT='APP_AVISOS_WEB_BORRADOR_V116',DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado';
let W=null,busy=false;
function e(d,id){return d.getElementById(id)}
function cfg(){try{return JSON.parse(W.localStorage.getItem(CFG)||'null')||{}}catch(x){return{}}}
function saveCfg(c){W.localStorage.setItem(CFG,JSON.stringify(c))}
function clean(v){return String(v||'').trim().replace(/\/+$/,'')}
function status(d,t,err){const x=e(d,'s134SyncStatus');if(x){x.textContent=t;x.style.color=err?'#b42318':'#667085'}}
function countRaw(raw){try{const p=JSON.parse(String(raw||''));return p&&Array.isArray(p.avisos)?p.avisos.length:0}catch(x){return 0}}
function localMain(){try{return String(W.localStorage.getItem(MAIN)||'')}catch(x){return''}}
function localCount(){return countRaw(localMain())}
function remoteMain(s){if(s&&s.localStorage&&s.localStorage[MAIN]!=null)return String(s.localStorage[MAIN]);const a=s&&s.indexedDB&&s.indexedDB.stores&&s.indexedDB.stores[STATE];if(Array.isArray(a)){const z=a.find(x=>String(x&&x.key)==MAIN);if(z&&typeof z.value==='string')return z.value}return''}
function openDb(){return new Promise((ok,no)=>{const r=W.indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains('planos'))q.createObjectStore('planos')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error||new Error('No se pudo abrir IndexedDB'))})}
function dec(v){if(Array.isArray(v))return v.map(dec);if(v&&typeof v==='object'){if(v.__soltecBlob===1){const p=String(v.data||'').split(','),bin=W.atob(p[1]||''),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);const b=new W.Blob([u],{type:v.mime||'application/octet-stream'});if(v.name&&W.File)try{return new W.File([b],v.name,{type:b.type})}catch(x){}return b}const o={};for(const k of Object.keys(v))o[k]=dec(v[k]);return o}return v}
async function hashText(t){try{if(W.crypto&&W.crypto.subtle){const b=new W.TextEncoder().encode(t),h=await W.crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,'0')).join('')}}catch(x){}let h=2166136261;for(let i=0;i<t.length;i++){h^=t.charCodeAt(i);h=Math.imul(h,16777619)}return'f'+(h>>>0).toString(16)}
async function apply(s){if(!s||s.schema!=='SOLTEC_SYNC_SNAPSHOT_V134')throw new Error('La copia del PC no es válida.');const rawMain=remoteMain(s);if(!rawMain)throw new Error('La copia central no contiene la base principal de avisos.');const draft=W.localStorage.getItem(DRAFT);const rm=[];for(let i=0;i<W.localStorage.length;i++){const k=W.localStorage.key(i);if(k&&k.startsWith('APP_AVISOS_'))rm.push(k)}rm.forEach(k=>W.localStorage.removeItem(k));Object.keys(s.localStorage||{}).forEach(k=>{if(k.startsWith('APP_AVISOS_')&&k!==DRAFT)W.localStorage.setItem(k,String(s.localStorage[k]))});W.localStorage.setItem(MAIN,rawMain);if(draft)W.localStorage.setItem(DRAFT,draft);
const db=await openDb(),src=s.indexedDB&&s.indexedDB.stores||{};let draftIdb=null;if(db.objectStoreNames.contains(STATE))draftIdb=await new Promise(ok=>{const r=db.transaction(STATE,'readonly').objectStore(STATE).get(DRAFT);r.onsuccess=()=>ok(r.result);r.onerror=()=>ok(null)});for(const name of Array.from(db.objectStoreNames)){await new Promise((ok,no)=>{const t=db.transaction(name,'readwrite');t.objectStore(name).clear();t.oncomplete=ok;t.onerror=()=>no(t.error)});if(Array.isArray(src[name]))await new Promise((ok,no)=>{const t=db.transaction(name,'readwrite'),os=t.objectStore(name);for(const z of src[name])os.put(dec(z.value),dec(z.key));t.oncomplete=ok;t.onerror=()=>no(t.error)})}if(db.objectStoreNames.contains(STATE)){await new Promise((ok,no)=>{const t=db.transaction(STATE,'readwrite'),os=t.objectStore(STATE);os.put(rawMain,MAIN);if(draftIdb!=null)os.put(draftIdb,DRAFT);t.oncomplete=ok;t.onerror=()=>no(t.error)})}db.close();return countRaw(rawMain)}
async function fetchCentral(c,timeoutMs){const url=clean(c.serverUrl),key=String(c.key||'');if(!url||!key)throw new Error('CONFIGURACIÓN INCOMPLETA');const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),timeoutMs||12000);try{const r=await W.fetch(url+'/api/snapshot',{cache:'no-store',headers:{'X-Soltec-Key':key},signal:ctl.signal});let x=null;try{x=await r.json()}catch(q){}if(!r.ok)throw new Error(x&&x.error?x.error:'Error del servidor ('+r.status+')');return x||{}}finally{clearTimeout(tm)}}
async function receive(d){if(busy)return;const c=cfg(),url=clean(c.serverUrl),key=String(c.key||'');if(!url||!key){status(d,'CONFIGURA PRIMERO LA DIRECCIÓN Y LA CLAVE DEL PC.',true);return}const lc=localCount();if(lc>0){status(d,'ESTE DISPOSITIVO YA TIENE '+lc+' AVISO(S). PARA NO SOBRESCRIBIRLOS, USA SINCRONIZAR AHORA.',true);return}busy=true;const b=e(d,'s134ReceivePc');if(b)b.disabled=true;status(d,'DESCARGANDO COPIA CENTRAL DEL PC…');try{const x=await fetchCentral(c,60000);if(!x.snapshot)throw new Error('El PC todavía no tiene una copia central.');const rc=countRaw(remoteMain(x.snapshot));if(!rc)throw new Error('La copia central del PC no contiene avisos. No se ha modificado la tablet.');const got=await apply(x.snapshot);if(got!==rc)throw new Error('La comprobación de avisos recibidos no coincide. No cierres SOLTEC.');c.lastRevision=Number(x.revision)||0;c.lastHash=await hashText(JSON.stringify(x.snapshot));c.lastSyncAt=new Date().toISOString();saveCfg(c);W.localStorage.removeItem(PENDING);status(d,'RECIBIDOS '+got+' AVISO(S) DEL PC · REV. '+c.lastRevision+' · REINICIANDO SOLTEC…');setTimeout(()=>{try{W.top.location.reload()}catch(q){W.location.reload()}},500)}catch(x){status(d,x.message||String(x),true);busy=false;if(b)b.disabled=false}}
async function autoPull(w){W=w;const c=cfg(),url=clean(c.serverUrl),key=String(c.key||'');if(!url||!key)return{state:'no-config'};if(W.localStorage.getItem(PENDING)==='1'||W.localStorage.getItem(DRAFT))return{state:'local-pending'};let x;try{x=await fetchCentral(c,9000)}catch(err){return{state:'offline'}}if(!x||!x.snapshot)return{state:'no-remote'};const rr=Number(x.revision)||0,lr=Number(c.lastRevision)||0,rawRemote=remoteMain(x.snapshot),rawLocal=localMain();if(!rawRemote)return{state:'no-remote'};if(rr<lr)return{state:'server-older',remoteRevision:rr,localRevision:lr};const mustApply=(rr>lr)||(rawRemote!==rawLocal)||(!lr&&countRaw(rawRemote)>0&&!countRaw(rawLocal));if(mustApply){const got=await apply(x.snapshot);c.lastRevision=rr;c.lastHash=await hashText(JSON.stringify(x.snapshot));c.lastSyncAt=new Date().toISOString();saveCfg(c);W.localStorage.removeItem(PENDING);setTimeout(()=>{try{W.top.location.reload()}catch(q){W.location.reload()}},350);return{state:'received',revision:rr,count:got}}c.lastRevision=rr;c.lastHash=await hashText(JSON.stringify(x.snapshot));c.lastSyncAt=new Date().toISOString();saveCfg(c);return{state:'current',revision:rr,count:countRaw(rawRemote)}}
function inject(w){W=w;const d=w.document,now=e(d,'s134SyncNow');if(!now||e(d,'s134ReceivePc'))return;const b=d.createElement('button');b.type='button';b.id='s134ReceivePc';b.className='full';b.style.marginTop='8px';b.textContent='⬇ RECIBIR DATOS DEL PC';now.insertAdjacentElement('afterend',b);const p=d.createElement('div');p.className='muted';p.style.marginTop='6px';p.textContent='Recuperación para un dispositivo vacío: descarga la copia central sin enviar nada al PC.';b.insertAdjacentElement('afterend',p);b.onclick=()=>receive(d)}
window.Soltec134ReceiveFix={init:function(w){try{inject(w)}catch(x){console.error('V1.34 RECEIVE FIX',x)}},autoPull:autoPull};
})();