(function(){'use strict';
const CFG='SOLTEC_SYNC_CONFIG_V134',PENDING='SOLTEC_SYNC_PENDING_V134',DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado',DRAFT='APP_AVISOS_WEB_BORRADOR_V116',MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE';
const OUT=window;let W=null,pendingConflict=null,busy=false;
function e(d,id){return d.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function uid(){try{return (W&&W.crypto?W.crypto:crypto).randomUUID()}catch(x){return'DEV-'+Date.now()+'-'+Math.random().toString(36).slice(2,9)}}
function parseCfg(raw){try{return JSON.parse(raw||'null')||{}}catch(x){return{}}}
function loadCfg(){let c={};try{c=parseCfg(W.localStorage.getItem(CFG))}catch(x){}try{const o=parseCfg(OUT.localStorage.getItem(CFG));['serverUrl','key','deviceId','deviceName','lastRevision','lastHash','lastSyncAt'].forEach(k=>{if((c[k]==null||c[k]==='')&&o[k]!=null&&o[k]!=='')c[k]=o[k]})}catch(x){}if(!c.deviceId)c.deviceId=uid();if(!c.deviceName)c.deviceName='DISPOSITIVO SOLTEC';return c}
function saveCfg(c){try{W.localStorage.setItem(CFG,JSON.stringify(c))}catch(x){}try{OUT.localStorage.setItem(CFG,JSON.stringify(c))}catch(x){}}
function cleanUrl(v){return String(v||'').trim().replace(/\/+$/,'')}
function status(d,msg,err){const x=e(d,'s134SyncStatus');if(x){x.textContent=msg||'';x.style.color=err?'#b42318':'#667085'}}
function last(d,c){const x=e(d,'s134SyncLast');if(x)x.textContent=c.lastSyncAt?'ÚLTIMA SINCRONIZACIÓN: '+new Date(c.lastSyncAt).toLocaleString('es-ES')+(c.lastRevision!=null?' · REV. '+c.lastRevision:''):'TODAVÍA NO SE HA SINCRONIZADO ESTE DISPOSITIVO.'}
function clearPendingIfSafe(){try{if(!W.localStorage.getItem(DRAFT))W.localStorage.removeItem(PENDING)}catch(x){}}
function openDb(){return new Promise((ok,no)=>{if(!W||!W.indexedDB){no(new Error('IndexedDB no disponible'));return}const r=W.indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains('planos'))q.createObjectStore('planos')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error||new Error('No se pudo abrir IndexedDB'))})}
function req(r){return new Promise((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function blobData(b){return new Promise((ok,no)=>{const r=new W.FileReader();r.onload=()=>ok(String(r.result));r.onerror=()=>no(r.error);r.readAsDataURL(b)})}
function isBlob(v){return !!(v&&typeof v==='object'&&typeof v.size==='number'&&typeof v.type==='string'&&typeof v.arrayBuffer==='function')}
async function enc(v){if(isBlob(v))return{__soltecBlob:1,mime:v.type||'',name:v.name||'',data:await blobData(v)};if(Array.isArray(v)){const a=[];for(const x of v)a.push(await enc(x));return a}if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v))o[k]=await enc(v[k]);return o}return v}
function dec(v){if(Array.isArray(v))return v.map(dec);if(v&&typeof v==='object'){if(v.__soltecBlob===1){const p=String(v.data||'').split(','),bin=W.atob(p[1]||''),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);const b=new W.Blob([u],{type:v.mime||'application/octet-stream'});if(v.name&&W.File)try{return new W.File([b],v.name,{type:b.type})}catch(x){}return b}const o={};for(const k of Object.keys(v))o[k]=dec(v[k]);return o}return v}
async function snapshot(){const ls={};for(let i=0;i<W.localStorage.length;i++){const k=W.localStorage.key(i);if(k&&k.startsWith('APP_AVISOS_')&&k!==DRAFT)ls[k]=W.localStorage.getItem(k)}const db=await openDb(),stores={};for(const name of Array.from(db.objectStoreNames)){const os=db.transaction(name,'readonly').objectStore(name),ks=await req(os.getAllKeys()),vs=await req(os.getAll()),a=[];for(let i=0;i<ks.length;i++){const key=String(ks[i]);if(name===STATE&&key===DRAFT)continue;let value=vs[i];if(name===STATE&&key===MAIN&&Object.prototype.hasOwnProperty.call(ls,MAIN))value=ls[MAIN];if(name===STATE&&key===MAIN&&!Object.prototype.hasOwnProperty.call(ls,MAIN)&&typeof value==='string')ls[MAIN]=value;a.push({key:await enc(ks[i]),value:await enc(value)})}stores[name]=a}db.close();return{schema:'SOLTEC_SYNC_SNAPSHOT_V134',localStorage:ls,indexedDB:{name:DB,version:DBV,stores}}}
function stableString(s){return JSON.stringify(s)}
async function hashText(t){try{if(W.crypto&&W.crypto.subtle){const b=new W.TextEncoder().encode(t),h=await W.crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,'0')).join('')}}catch(x){}let h=2166136261;for(let i=0;i<t.length;i++){h^=t.charCodeAt(i);h=Math.imul(h,16777619)}return'f'+(h>>>0).toString(16)}
async function hashSnapshot(s){return hashText(stableString(s))}
function remoteMain(s){if(s&&s.localStorage&&s.localStorage[MAIN]!=null)return String(s.localStorage[MAIN]);const a=s&&s.indexedDB&&s.indexedDB.stores&&s.indexedDB.stores[STATE];if(Array.isArray(a)){const z=a.find(x=>String(x&&x.key)==MAIN);if(z&&typeof z.value==='string')return z.value}return''}
function countRaw(raw){try{const p=JSON.parse(String(raw||''));return p&&Array.isArray(p.avisos)?p.avisos.length:0}catch(x){return 0}}
function isEmpty(s){try{if(countRaw(remoteMain(s))>0)return false;const stores=s&&s.indexedDB&&s.indexedDB.stores||{};for(const n of Object.keys(stores)){for(const z of(stores[n]||[])){const k=String(z&&z.key!=null?z.key:'');if(n===STATE&&k===MAIN)continue;if(n===STATE&&k===DRAFT)continue;if(k)return false}}return true}catch(x){return false}}
function headers(c,json){const h={'X-Soltec-Key':String(c.key||'')};if(json)h['Content-Type']='application/json';return h}
async function api(c,path,opt,timeoutMs){if(!c.serverUrl)throw new Error('Configura primero la dirección del PC SOLTEC.');const url=cleanUrl(c.serverUrl)+path,ctl=new W.AbortController(),tm=W.setTimeout(()=>ctl.abort(),timeoutMs||15000);try{const r=await W.fetch(url,Object.assign({cache:'no-store',headers:headers(c,false),signal:ctl.signal},opt||{}));let body=null;try{body=await r.json()}catch(x){}if(!r.ok){const er=new Error(body&&body.error?body.error:('Error del servidor ('+r.status+')'));er.status=r.status;er.body=body;throw er}return body||{}}catch(x){if(x&&x.name==='AbortError')throw new Error('El PC SOLTEC no responde o la transferencia ha tardado demasiado.');throw x}finally{W.clearTimeout(tm)}}
async function getRemote(c){return api(c,'/api/snapshot',null,60000)}
async function putRemote(c,s,rev){return api(c,'/api/snapshot',{method:'POST',headers:headers(c,true),body:JSON.stringify({ifRevision:Number(rev)||0,deviceId:c.deviceId,deviceName:c.deviceName,snapshot:s})},180000)}
async function backupLocal(c,s){return api(c,'/api/backup',{method:'POST',headers:headers(c,true),body:JSON.stringify({deviceId:c.deviceId,deviceName:c.deviceName,snapshot:s})},180000)}
async function applySnapshot(s){if(!s||s.schema!=='SOLTEC_SYNC_SNAPSHOT_V134')throw new Error('La copia recibida del PC no es válida.');const rawMain=remoteMain(s);if(!rawMain)throw new Error('La copia recibida no contiene la base principal de avisos.');let draft=null;try{draft=W.localStorage.getItem(DRAFT)}catch(x){}const rm=[];for(let i=0;i<W.localStorage.length;i++){const k=W.localStorage.key(i);if(k&&k.startsWith('APP_AVISOS_'))rm.push(k)}rm.forEach(k=>W.localStorage.removeItem(k));Object.keys(s.localStorage||{}).forEach(k=>{if(k.startsWith('APP_AVISOS_')&&k!==DRAFT)W.localStorage.setItem(k,String(s.localStorage[k]))});W.localStorage.setItem(MAIN,rawMain);if(draft)W.localStorage.setItem(DRAFT,draft);
const db=await openDb(),src=s.indexedDB&&s.indexedDB.stores||{};let draftIdb=null;if(db.objectStoreNames.contains(STATE))draftIdb=await new Promise(ok=>{const q=db.transaction(STATE,'readonly').objectStore(STATE).get(DRAFT);q.onsuccess=()=>ok(q.result);q.onerror=()=>ok(null)});for(const name of Array.from(db.objectStoreNames)){await new Promise((ok,no)=>{const t=db.transaction(name,'readwrite');t.objectStore(name).clear();t.oncomplete=ok;t.onerror=()=>no(t.error)});if(Array.isArray(src[name]))await new Promise((ok,no)=>{const t=db.transaction(name,'readwrite'),os=t.objectStore(name);for(const z of src[name])os.put(dec(z.value),dec(z.key));t.oncomplete=ok;t.onerror=()=>no(t.error)})}if(db.objectStoreNames.contains(STATE))await new Promise((ok,no)=>{const t=db.transaction(STATE,'readwrite'),os=t.objectStore(STATE);os.put(rawMain,MAIN);if(draftIdb!=null)os.put(draftIdb,DRAFT);t.oncomplete=ok;t.onerror=()=>no(t.error)});db.close()}
function readForm(d){const c=loadCfg();c.deviceName=String(e(d,'s134DeviceName')?.value||'').trim()||'DISPOSITIVO SOLTEC';c.serverUrl=cleanUrl(e(d,'s134ServerUrl')?.value);c.key=String(e(d,'s134SyncKey')?.value||'').trim();saveCfg(c);return c}
function setBusy(d,on){busy=on;['s134SyncSave','s134SyncTest','s134SyncNow','s134UseLocal','s134UsePc','s134ReceivePc','s134CentralFromHere'].forEach(id=>{const b=e(d,id);if(b)b.disabled=!!on})}
function showConflict(d,show){const b=e(d,'s134Conflict');if(b)b.style.display=show?'block':'none'}
async function test(d){if(busy)return;const c=readForm(d);setBusy(d,true);status(d,'COMPROBANDO CONEXIÓN CON EL PC…');try{const x=await api(c,'/api/status');status(d,'PC SOLTEC CONECTADO · REV. '+(x.revision||0)+(x.updatedAt?' · '+new Date(x.updatedAt).toLocaleString('es-ES'):''))}catch(x){status(d,x.message||String(x),true)}finally{setBusy(d,false)}}
async function adoptRemote(d,c,remote){status(d,'RECIBIENDO DATOS DEL PC…');await applySnapshot(remote.snapshot);const h=await hashSnapshot(remote.snapshot);c.lastRevision=Number(remote.revision)||0;c.lastHash=h;c.lastSyncAt=new Date().toISOString();saveCfg(c);clearPendingIfSafe();last(d,c);status(d,'DATOS DEL PC RECIBIDOS · REV. '+c.lastRevision+' · REINICIANDO…');W.setTimeout(()=>{try{W.top.location.reload()}catch(x){W.location.reload()}},500)}
async function uploadLocal(d,c,local,remoteRev){status(d,'ENVIANDO DATOS AL PC…');const r=await putRemote(c,local,remoteRev),h=await hashSnapshot(local);c.lastRevision=Number(r.revision)||0;c.lastHash=h;c.lastSyncAt=new Date().toISOString();saveCfg(c);clearPendingIfSafe();last(d,c);status(d,'SINCRONIZACIÓN COMPLETADA · PC ACTUALIZADO · REV. '+c.lastRevision);showConflict(d,false);pendingConflict=null}
async function sync(d){if(busy)return;const c=readForm(d);setBusy(d,true);showConflict(d,false);pendingConflict=null;status(d,'PREPARANDO DATOS REALES DE SOLTEC…');try{const local=await snapshot(),localHash=await hashSnapshot(local);status(d,'CONSULTANDO PC SOLTEC…');const remote=await getRemote(c),rr=Number(remote.revision)||0;if(!remote.snapshot){await uploadLocal(d,c,local,rr);return}const remoteHash=await hashSnapshot(remote.snapshot);if(localHash===remoteHash){c.lastRevision=rr;c.lastHash=localHash;c.lastSyncAt=new Date().toISOString();saveCfg(c);clearPendingIfSafe();last(d,c);status(d,'TODO ESTÁ ACTUALIZADO · REV. '+rr);return}if(!c.lastRevision){if(isEmpty(local)){await adoptRemote(d,c,remote);return}pendingConflict={c,local,localHash,remote,remoteHash};showConflict(d,true);status(d,'PRIMERA SINCRONIZACIÓN: EL PC Y ESTE DISPOSITIVO TIENEN DATOS DISTINTOS. ELIGE QUÉ COPIA CONSERVAR.',true);return}if(rr===Number(c.lastRevision)){await uploadLocal(d,c,local,rr);return}if(c.lastHash&&localHash===c.lastHash){await adoptRemote(d,c,remote);return}pendingConflict={c,local,localHash,remote,remoteHash};showConflict(d,true);status(d,'CONFLICTO SEGURO: HAN CAMBIADO EL PC Y ESTE DISPOSITIVO DESDE LA ÚLTIMA SINCRONIZACIÓN. NO SE HA SOBRESCRITO NADA.',true)}catch(x){status(d,x.message||String(x),true)}finally{setBusy(d,false)}}
async function useLocal(d){if(!pendingConflict||busy)return;setBusy(d,true);try{const p=pendingConflict,latest=await getRemote(p.c);await uploadLocal(d,p.c,p.local,Number(latest.revision)||0)}catch(x){status(d,x.message||String(x),true)}finally{setBusy(d,false)}}
async function usePc(d){if(!pendingConflict||busy)return;setBusy(d,true);try{const p=pendingConflict;status(d,'GUARDANDO COPIA DE RECUPERACIÓN DE ESTE DISPOSITIVO EN EL PC…');await backupLocal(p.c,p.local);const latest=await getRemote(p.c);if(!latest.snapshot)throw new Error('El PC ya no tiene una copia disponible.');await adoptRemote(d,p.c,latest)}catch(x){status(d,x.message||String(x),true);setBusy(d,false)}}
function inject(d){const card=d.querySelector('#config .card');if(!card||e(d,'s134Sync'))return;const c=loadCfg(),box=d.createElement('details');box.id='s134Sync';box.className='s132acc';box.open=true;box.innerHTML='<summary>🔄 SINCRONIZACIÓN CON PC DE CASA · V1.34</summary><div class="s132body"><p class="muted">SOLTEC sincroniza la base real de avisos, fotos, planos y documentos con el PC de casa. Sin conexión puedes seguir trabajando normalmente.</p><label>NOMBRE DE ESTE DISPOSITIVO<input id="s134DeviceName" value="'+esc(c.deviceName||'')+'" placeholder="Ej.: MÓVIL, TABLET, PC CASA"></label><label>DIRECCIÓN SEGURA DEL PC SOLTEC<input id="s134ServerUrl" value="'+esc(c.serverUrl||'')+'" placeholder="https://pc-casa.xxxxx.ts.net"></label><label>CLAVE DE SINCRONIZACIÓN<input id="s134SyncKey" type="password" value="'+esc(c.key||'')+'" autocomplete="off"></label><div id="s134SyncLast" class="muted" style="margin:8px 0"></div><div id="s134SyncStatus" class="status" style="min-height:34px"></div><div class="s132actions"><button type="button" id="s134SyncSave">GUARDAR CONFIGURACIÓN</button><button type="button" id="s134SyncTest">PROBAR CONEXIÓN</button></div><button type="button" id="s134SyncNow" class="primary full" style="margin-top:8px">🔄 SINCRONIZAR AHORA</button><div id="s134Conflict" style="display:none;border:2px solid #f0b4ae;border-radius:12px;padding:10px;margin-top:10px;background:#fff8f7"><b>CONFLICTO DE SINCRONIZACIÓN</b><p class="muted">No se sobrescribe nada hasta que elijas. Si usas <b>ESTE DISPOSITIVO</b>, el PC conserva automáticamente su versión anterior. Si usas <b>PC DE CASA</b>, primero se guarda en el PC una copia de recuperación de este dispositivo.</p><div class="s132actions"><button type="button" id="s134UseLocal">USAR ESTE DISPOSITIVO</button><button type="button" id="s134UsePc">USAR PC DE CASA</button></div></div><p class="muted" style="margin-top:10px">Uso normal: abre para recibir la última revisión y pulsa FINALIZAR al terminar para enviar tus cambios.</p></div>';card.appendChild(box);last(d,c);e(d,'s134SyncSave').onclick=()=>{const x=readForm(d);last(d,x);status(d,'CONFIGURACIÓN DE SINCRONIZACIÓN GUARDADA.')};e(d,'s134SyncTest').onclick=()=>test(d);e(d,'s134SyncNow').onclick=()=>sync(d);e(d,'s134UseLocal').onclick=()=>useLocal(d);e(d,'s134UsePc').onclick=()=>usePc(d)}
window.Soltec134Sync={init:function(w){try{W=w;const c=loadCfg();saveCfg(c);inject(w.document);const bs=w.document.getElementById('bootState');if(bs)bs.textContent='V1.34 SYNC · DATOS REALES + PC DE CASA'}catch(x){console.error('V1.34 SYNC',x)}},syncNow:function(w){if(w)W=w;if(!W)return Promise.resolve();return sync(W.document)}};
})();