(function(){'use strict';
const CFG='SOLTEC_SYNC_CONFIG_V134',MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',DRAFT='APP_AVISOS_WEB_BORRADOR_V116',DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado';
let W=null,busy=false;
function e(d,id){return d.getElementById(id)}
function cfg(){try{return JSON.parse(W.localStorage.getItem(CFG)||'null')||{}}catch(x){return{}}}
function saveCfg(c){W.localStorage.setItem(CFG,JSON.stringify(c))}
function clean(v){return String(v||'').trim().replace(/\/+$/,'')}
function status(d,t,err){const x=e(d,'s134SyncStatus');if(x){x.textContent=t;x.style.color=err?'#b42318':'#667085'}}
function countRaw(raw){try{const p=JSON.parse(String(raw||''));return p&&Array.isArray(p.avisos)?p.avisos.length:0}catch(x){return 0}}
function localCount(){return countRaw(W.localStorage.getItem(MAIN))}
function remoteMain(s){if(s&&s.localStorage&&s.localStorage[MAIN]!=null)return String(s.localStorage[MAIN]);const a=s&&s.indexedDB&&s.indexedDB.stores&&s.indexedDB.stores[STATE];if(Array.isArray(a)){const z=a.find(x=>String(x&&x.key)==MAIN);if(z&&typeof z.value==='string')return z.value}return''}
function openDb(){return new Promise((ok,no)=>{const r=W.indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains('planos'))q.createObjectStore('planos')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error||new Error('No se pudo abrir IndexedDB'))})}
function req(r){return new Promise((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function blobData(b){return new Promise((ok,no)=>{const r=new W.FileReader();r.onload=()=>ok(String(r.result));r.onerror=()=>no(r.error);r.readAsDataURL(b)})}
async function enc(v){if(v instanceof W.Blob)return{__soltecBlob:1,mime:v.type||'',name:(W.File&&v instanceof W.File)?v.name:'',data:await blobData(v)};if(Array.isArray(v)){const a=[];for(const x of v)a.push(await enc(x));return a}if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v))o[k]=await enc(v[k]);return o}return v}
async function snapshot(){const ls={};for(let i=0;i<W.localStorage.length;i++){const k=W.localStorage.key(i);if(k&&k.startsWith('APP_AVISOS_')&&k!==DRAFT)ls[k]=W.localStorage.getItem(k)}const db=await openDb(),stores={};for(const name of Array.from(db.objectStoreNames)){const os=db.transaction(name,'readonly').objectStore(name),ks=await req(os.getAllKeys()),vs=await req(os.getAll()),a=[];for(let i=0;i<ks.length;i++){const key=String(ks[i]);if(name===STATE&&key===DRAFT)continue;let value=vs[i];if(name===STATE&&key===MAIN&&Object.prototype.hasOwnProperty.call(ls,MAIN))value=ls[MAIN];if(name===STATE&&key===MAIN&&!Object.prototype.hasOwnProperty.call(ls,MAIN)&&typeof value==='string')ls[MAIN]=value;a.push({key:await enc(ks[i]),value:await enc(value)})}stores[name]=a}db.close();return{schema:'SOLTEC_SYNC_SNAPSHOT_V134',localStorage:ls,indexedDB:{name:DB,version:DBV,stores}}}
async function hashText(t){try{if(W.crypto&&W.crypto.subtle){const b=new W.TextEncoder().encode(t),h=await W.crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,'0')).join('')}}catch(x){}let h=2166136261;for(let i=0;i<t.length;i++){h^=t.charCodeAt(i);h=Math.imul(h,16777619)}return'f'+(h>>>0).toString(16)}
async function getRemote(c){const r=await W.fetch(clean(c.serverUrl)+'/api/snapshot',{cache:'no-store',headers:{'X-Soltec-Key':String(c.key||'')}});let x=null;try{x=await r.json()}catch(q){}if(!r.ok)throw new Error(x&&x.error?x.error:'Error del servidor ('+r.status+')');return x||{}}
async function publish(d){if(busy)return;const c=cfg(),url=clean(c.serverUrl),key=String(c.key||'');if(!url||!key){status(d,'CONFIGURA PRIMERO LA DIRECCIÓN Y LA CLAVE DEL PC.',true);return}const lc=localCount();if(!lc){status(d,'ESTE DISPOSITIVO NO TIENE AVISOS PARA ENVIAR AL PC.',true);return}busy=true;const b=e(d,'s134CentralFromHere');if(b)b.disabled=true;status(d,'COMPROBANDO LA COPIA CENTRAL DEL PC…');try{const remote=await getRemote(c),rc=remote&&remote.snapshot?countRaw(remoteMain(remote.snapshot)):0;if(rc>0){status(d,'LA COPIA CENTRAL YA CONTIENE '+rc+' AVISO(S). POR SEGURIDAD NO SE HA SUSTITUIDO. USA SINCRONIZAR AHORA.',true);return}if(!W.confirm('ESTE DISPOSITIVO TIENE '+lc+' AVISO(S) Y LA COPIA CENTRAL DEL PC ESTÁ VACÍA.\n\n¿CREAR AHORA LA COPIA CENTRAL CON ESTOS DATOS?')){status(d,'OPERACIÓN CANCELADA. NO SE HA MODIFICADO EL PC.');return}status(d,'PREPARANDO '+lc+' AVISO(S), FOTOS, PLANOS Y DOCUMENTOS…');const s=await snapshot(),sc=countRaw(remoteMain(s));if(sc!==lc)throw new Error('La comprobación local no coincide: se ven '+lc+' avisos pero la copia preparada contiene '+sc+'. No se ha enviado nada.');status(d,'CREANDO COPIA CENTRAL EN EL PC…');const r=await W.fetch(url+'/api/snapshot',{method:'POST',cache:'no-store',headers:{'X-Soltec-Key':key,'Content-Type':'application/json'},body:JSON.stringify({ifRevision:Number(remote.revision)||0,deviceId:c.deviceId||'',deviceName:c.deviceName||'PC CASA',snapshot:s})});let x=null;try{x=await r.json()}catch(q){}if(!r.ok)throw new Error(x&&x.error?x.error:'Error del servidor ('+r.status+')');c.lastRevision=Number(x.revision)||0;c.lastHash=await hashText(JSON.stringify(s));c.lastSyncAt=new Date().toISOString();saveCfg(c);status(d,'COPIA CENTRAL CREADA CORRECTAMENTE · '+lc+' AVISO(S) · REV. '+c.lastRevision+'. AHORA LA TABLET PUEDE USAR RECIBIR DATOS DEL PC.');}catch(x){status(d,x.message||String(x),true)}finally{busy=false;if(b)b.disabled=false}}
function inject(w){W=w;const d=w.document;if(e(d,'s134CentralFromHere'))return;const receive=e(d,'s134ReceivePc'),sync=e(d,'s134SyncNow');const anchor=receive||sync;if(!anchor)return;const b=d.createElement('button');b.type='button';b.id='s134CentralFromHere';b.className='full';b.style.marginTop='8px';b.textContent='⬆ CREAR COPIA CENTRAL DESDE ESTE DISPOSITIVO';anchor.insertAdjacentElement('afterend',b);const p=d.createElement('div');p.className='muted';p.style.marginTop='6px';p.textContent='Recuperación segura: solo funciona si este dispositivo tiene avisos y la copia central del PC está vacía.';b.insertAdjacentElement('afterend',p);b.onclick=()=>publish(d)}
window.Soltec134CentralFix={init:function(w){try{inject(w)}catch(x){console.error('V1.34 CENTRAL FIX',x)}}};
})();