(function(){'use strict';
const META='APP_AVISOS_SUMINISTRO_V129',MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE';let W;
const el=(d,id)=>d.getElementById(id),txt=v=>v==null?'':String(v).trim(),json=(v,x)=>{try{return JSON.parse(v||'')||x}catch(_){return x}};
const tensions='<option value="">SELECCIONAR…</option><option>230 V</option><option>3X230 V</option><option>3X230/400 V</option>';
function inp(id,label,type){return'<label>'+label+'<input id="'+id+'" type="'+(type||'text')+'"'+(type==='number'?' min="0" step="0.01" inputmode="decimal"':'')+'></label>'}
function sel(id,label,opts){return'<label>'+label+'<select id="'+id+'">'+opts+'</select></label>'}
function app(id,name){return sel(id,'Concepto aplicable','<option value="">NO APLICA</option><option>'+name+'</option>')}
function row(title,body){return'<div class="t135-row"><b>'+title+'</b><div class="t135-grid">'+body+'</div></div>'}
function inject(d){const anchor=el(d,'s135MemFields')||el(d,'s132Extra');if(!anchor||el(d,'s135Technical'))return;let v='',l='';
for(let i=1;i<=3;i++)v+=row('Vivienda '+i,app('t135VivConcepto'+i,'VIVIENDA '+i)+inp('t135VivEscalera'+i,'Escalera')+inp('t135VivPiso'+i,'Piso')+inp('t135VivPuerta'+i,'Puerta')+inp('t135VivPotencia'+i,'Potencia (kW)','number')+sel('t135VivTension'+i,'Tensión (V)',tensions)+sel('t135VivGrado'+i,'Grado electrificación','<option value="">SELECCIONAR…</option><option>BÁSICA</option><option>ELEVADA</option>'));
for(let i=1;i<=2;i++)l+=row('Local '+i,app('t135LocConcepto'+i,'LOCAL '+i)+inp('t135LocAclarador'+i,'Aclarador de locales')+inp('t135LocPotencia'+i,'Potencia (kW)','number')+sel('t135LocTension'+i,'Tensión (V)',tensions)+inp('t135LocSuperficie'+i,'Superficie (m²)','number'));
const s=['ESCALERAS','ASCENSORES','OTROS'].map((n,i)=>row(n,app('t135SerConcepto'+i,n)+inp('t135SerAclarador'+i,'Aclarador de servicios')+inp('t135SerPotencia'+i,'Potencia (kW)','number')+sel('t135SerTension'+i,'Tensión (V)',tensions))).join('');
const g=['GARAJE','PUNTOS RECARGA VE'].map((n,i)=>row(n,app('t135GarConcepto'+i,n)+inp('t135GarTipo'+i,'Tipo garaje / Nº plazas')+inp('t135GarPotencia'+i,'Potencia (kW)','number')+sel('t135GarTension'+i,'Tensión (V)',tensions)+inp('t135GarSuperficie'+i,'Superficie (m²)','number'))).join('');
const box=d.createElement('details');box.id='s135Technical';box.className='s132acc t135-main';box.innerHTML='<summary>⚡ Datos técnicos de la petición</summary><div class="s132body"><p class="muted">Rellena solamente las tablas que correspondan. Se incluirán automáticamente en la memoria CNMC.</p><details class="t135-sub"><summary>A. Viviendas</summary>'+v+'</details><details class="t135-sub"><summary>B. Locales comerciales</summary>'+l+'</details><details class="t135-sub"><summary>C. Servicios comunes</summary>'+s+'</details><details class="t135-sub"><summary>D. Garajes y vehículos eléctricos (VE)</summary>'+g+'</details><details class="t135-sub"><summary>E. Acumulación de energía</summary><div class="t135-grid">'+sel('t135AcuAplica','¿Aplica?','<option>NO</option><option>SÍ</option>')+sel('t135AcuTipo','Tecnología de almacenamiento','<option value="">SELECCIONAR…</option><option>BATERÍAS</option><option>VOLANTE DE INERCIA</option><option>SUPERCONDENSADORES</option><option>OTROS</option>')+inp('t135AcuPotencia','Potencia (kW)','number')+inp('t135AcuCapacidad','Capacidad (kWh)','number')+'</div></details><details class="t135-sub"><summary>F. Generación asociada / Autoconsumo</summary><div class="t135-grid">'+sel('t135AutoAplica','¿Aplica?','<option>NO</option><option>SÍ</option>')+inp('t135AutoConsumo','Capacidad solicitada por consumo (kW)','number')+inp('t135AutoGeneracion','Capacidad solicitada para generación (kW)','number')+'</div><p class="muted">Si aplica, es obligatorio adjuntar el esquema unifilar simplificado.</p></details><div class="t135-total">'+inp('t135PotenciaTotal','Potencia total solicitada en la instalación (kW)','number')+'</div></div>';anchor.insertAdjacentElement('afterend',box)}
function style(d){const s=d.createElement('style');s.textContent='.t135-main{grid-column:1/-1}.t135-main>summary,.t135-sub>summary{cursor:pointer;font-weight:900;color:#24466e}.t135-sub{border:1px solid #dbe3ee;border-radius:10px;margin:7px 0;background:#fff}.t135-sub>summary{padding:10px}.t135-row{border-top:1px solid #e5eaf0;padding:9px}.t135-row>b{display:block;color:#8f1d16;margin-bottom:6px}.t135-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;padding:8px}.t135-grid label{font-size:12px;margin:0}.t135-grid input,.t135-grid select{width:100%;box-sizing:border-box;padding:8px!important}.t135-total{margin-top:9px;padding:10px;border:2px solid #e7281c;border-radius:10px;background:#fff7f6}.t135-total label{font-weight:900}@media(max-width:800px){.t135-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:480px){.t135-grid{grid-template-columns:1fr}}';d.head.appendChild(s)}
const value=(d,id)=>txt((el(d,id)||{}).value),set=(d,id,v)=>{const x=el(d,id);if(x)x.value=v==null?'':v};
function rows(d,p,n,keys,z){return Array.from({length:n},(_,q)=>{const r={},i=z?q:q+1;keys.forEach(k=>r[k[0]]=value(d,p+k[1]+i));return r})}
const VK=[['concepto','Concepto'],['escalera','Escalera'],['piso','Piso'],['puerta','Puerta'],['potencia','Potencia'],['tension','Tension'],['grado','Grado']],LK=[['concepto','Concepto'],['aclarador','Aclarador'],['potencia','Potencia'],['tension','Tension'],['superficie','Superficie']],SK=[['concepto','Concepto'],['aclarador','Aclarador'],['potencia','Potencia'],['tension','Tension']],GK=[['concepto','Concepto'],['tipo','Tipo'],['potencia','Potencia'],['tension','Tension'],['superficie','Superficie']];
function read(d){return{viviendas:rows(d,'t135Viv',3,VK),locales:rows(d,'t135Loc',2,LK),servicios:rows(d,'t135Ser',3,SK,true),garajes:rows(d,'t135Gar',2,GK,true),acumulacion:{aplica:value(d,'t135AcuAplica'),tipo:value(d,'t135AcuTipo'),potencia:value(d,'t135AcuPotencia'),capacidad:value(d,'t135AcuCapacidad')},autoconsumo:{aplica:value(d,'t135AutoAplica'),consumo:value(d,'t135AutoConsumo'),generacion:value(d,'t135AutoGeneracion')},potenciaTotal:value(d,'t135PotenciaTotal')}}
function putRows(d,p,n,k,a,z){for(let q=0;q<n;q++){const i=z?q:q+1,r=(a||[])[q]||{};k.forEach(x=>set(d,p+x[1]+i,r[x[0]]))}}
function write(d,t){t=t||{};putRows(d,'t135Viv',3,VK,t.viviendas);putRows(d,'t135Loc',2,LK,t.locales);putRows(d,'t135Ser',3,SK,t.servicios,true);putRows(d,'t135Gar',2,GK,t.garajes,true);const a=t.acumulacion||{},u=t.autoconsumo||{};set(d,'t135AcuAplica',a.aplica||'NO');set(d,'t135AcuTipo',a.tipo);set(d,'t135AcuPotencia',a.potencia);set(d,'t135AcuCapacidad',a.capacidad);set(d,'t135AutoAplica',u.aplica||'NO');set(d,'t135AutoConsumo',u.consumo);set(d,'t135AutoGeneracion',u.generacion);set(d,'t135PotenciaTotal',t.potenciaTotal)}
const metas=()=>json(W.localStorage.getItem(META),{});function loadData(d,id){const a=metas();write(d,id&&a[id]?a[id].tecnica:{})}function save(id,t){if(!id)return;const a=metas(),m=a[id]||{};m.tecnica=t;a[id]=m;W.localStorage.setItem(META,JSON.stringify(a))}
function hook(d){const A=W.App;if(A.__technical135)return;A.__technical135=true;const ed=A.editarAviso.bind(A);A.editarAviso=id=>{const r=ed(id);setTimeout(()=>loadData(d,id),0);return r};const nu=A.nuevoAviso.bind(A);A.nuevoAviso=()=>{const r=nu();setTimeout(()=>loadData(d,0),0);return r};const old=A.guardarAviso.bind(A);A.guardarAviso=()=>{const t=read(d),before=new Set((json(W.localStorage.getItem(MAIN),{avisos:[]}).avisos||[]).map(x=>+x.id)),id=+value(d,'avId')||0,r=old();setTimeout(()=>{const a=json(W.localStorage.getItem(MAIN),{avisos:[]}).avisos||[],n=a.filter(x=>!before.has(+x.id)).sort((x,y)=>y.id-x.id)[0];save(id||(n&&+n.id),t)},35);return r}}
window.SoltecTechnical135={init(w){W=w;const d=w.document;inject(d);style(d);hook(d)}}})();