(function(){'use strict';
var MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',NOTES='APP_AVISOS_MEMORIA_OBS_V128',patchedApp=new WeakSet(),patchedMem=new WeakSet(),folded=new WeakSet();
function jget(k,d){try{var x=JSON.parse(localStorage.getItem(k)||'null');return x&&typeof x==='object'?x:d}catch(e){return d}}
function noteMap(){return jget(NOTES,{})}
function getNote(id){return String(noteMap()[String(id)]||'')}
function setNote(id,v){if(!id)return;var m=noteMap();m[String(id)]=String(v||'').trim().toUpperCase();localStorage.setItem(NOTES,JSON.stringify(m))}
function main(){return jget(MAIN,{avisos:[]})}
function val(d,id){var e=d.getElementById(id);return e?String(e.value||'').trim():''}
function newId(before){var s={};before.forEach(function(x){s[String(x)]=1});var a=(main().avisos||[]).map(function(x){return Number(x.id)}).filter(function(x){return x&&!s[String(x)]});return a.length?Math.max.apply(Math,a):0}
function addAppStyle(d){if(d.getElementById('v128appstyle'))return;var s=d.createElement('style');s.id='v128appstyle';s.textContent='.v128memobs{grid-column:1/-1;border:2px solid #dc2626;background:#fff7f7;border-radius:13px;padding:11px;margin:2px 0 8px}.v128memobs label{margin:0;color:#b42318;font-weight:900}.v128memobs textarea{min-height:90px;border-color:#ef9a9a;color:#b42318;font-weight:800;text-transform:uppercase}.v128memobs .muted{color:#b42318;margin-top:6px}.sectionTitle.v128-fold{position:relative;cursor:pointer;border:1px solid #c8d7e8!important;border-radius:10px!important;background:#f8fbff!important;padding:10px 38px 10px 11px!important;margin:8px 0!important;user-select:none}.sectionTitle.v128-fold:after{content:"▸";position:absolute;right:13px;top:50%;transform:translateY(-50%);font-size:18px;color:#0b5ed7}.sectionTitle.v128-fold.v128-open:after{content:"▾"}.sectionTitle.v128-fold:focus{outline:2px solid #0b5ed7;outline-offset:2px}';d.head.appendChild(s)}
function placeField(d,box){var provincia=d.getElementById('avProvincia');if(provincia&&provincia.parentElement){provincia.parentElement.insertAdjacentElement('afterend',box);return}var grid=d.querySelector('#formAviso .grid2');if(!grid)return;var electric=Array.from(grid.querySelectorAll(':scope > .sectionTitle')).find(function(x){return /DATOS ELÉCTRICOS/i.test(x.textContent)});if(electric)grid.insertBefore(box,electric);else grid.appendChild(box)}
function ensureField(d){addAppStyle(d);var box=d.getElementById('v128MemObsBox');if(!box){box=d.createElement('div');box.className='v128memobs';box.id='v128MemObsBox';box.innerHTML='<label>OBSERVACIONES PARA MEMORIA<textarea id="v128MemObs" placeholder="TEXTO DESTACADO QUE APARECERÁ EN ROJO EN LA MEMORIA"></textarea></label><div class="muted">ESTE TEXTO SALDRÁ EN ROJO EN 3. UBICACIÓN DEL SUMINISTRO.</div>';placeField(d,box);var ta=d.getElementById('v128MemObs');ta.addEventListener('input',function(){var p=ta.selectionStart;ta.value=ta.value.toUpperCase();try{ta.setSelectionRange(p,p)}catch(e){}})}else placeField(d,box)}
function loadField(d,id,duplicateSource){ensureField(d);var e=d.getElementById('v128MemObs');if(e)e.value=id?getNote(id):duplicateSource?getNote(duplicateSource):''}
function sectionItems(t){var a=[],n=t.nextElementSibling;while(n&&!n.classList.contains('sectionTitle')){a.push(n);n=n.nextElementSibling}return a}
function setFold(t,open){t.classList.toggle('v128-open',!!open);t.setAttribute('aria-expanded',open?'true':'false');sectionItems(t).forEach(function(n){n.style.display=open?'':'none'})}
function prepareFolds(d){addAppStyle(d);Array.from(d.querySelectorAll('#formAviso .sectionTitle,#config .sectionTitle')).forEach(function(t){if(folded.has(t))return;folded.add(t);t.classList.add('v128-fold');t.tabIndex=0;t.setAttribute('role','button');setFold(t,false);function go(){setFold(t,!t.classList.contains('v128-open'))}t.addEventListener('click',go);t.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})})}
function patchApp(d,w){if(patchedApp.has(w)||!w.App||!d.getElementById('formAviso'))return;patchedApp.add(w);ensureField(d);prepareFolds(d);var A=w.App,n=A.nuevoAviso,e=A.editarAviso,du=A.duplicarAviso,sa=A.guardarAviso,show=A.show;
A.show=function(id){var r=show.apply(A,arguments);setTimeout(function(){ensureField(d);prepareFolds(d)},40);return r};
A.nuevoAviso=function(){var r=n.apply(A,arguments);setTimeout(function(){loadField(d,0,0);prepareFolds(d)},70);return r};
A.editarAviso=function(id){var r=e.apply(A,arguments);setTimeout(function(){loadField(d,id,0);prepareFolds(d)},70);return r};
A.duplicarAviso=function(id){var r=du.apply(A,arguments);setTimeout(function(){loadField(d,0,id);prepareFolds(d)},70);return r};
A.guardarAviso=function(){var before=(main().avisos||[]).map(function(x){return Number(x.id)}),id=Number(val(d,'avId'))||0,note=val(d,'v128MemObs').toUpperCase(),r=sa.apply(A,arguments);setTimeout(function(){var fin=id||newId(before);if(fin)setNote(fin,note)},220);return r};
var current=Number(val(d,'avId'))||0;if(d.getElementById('formAviso').style.display!=='none')loadField(d,current,0)}
function addMemStyle(d){if(d.getElementById('v128memstyle'))return;var s=d.createElement('style');s.id='v128memstyle';s.textContent='.v128-tension strong{font-size:12.5px!important;line-height:1.2!important;color:inherit!important;font-weight:700!important}.v128-alert{border:2px solid #dc2626;background:#fff5f5;border-radius:8px;padding:9px 11px;margin:9px 0 2px;color:#b42318}.v128-alert .lab{font-size:10px;font-weight:900;margin-bottom:4px;text-transform:uppercase}.v128-alert .txt{font-size:13px;font-weight:900;line-height:1.35;white-space:pre-wrap}@media(max-width:800px){.v128-tension strong{font-size:14px!important}}';d.head.appendChild(s)}
function sectionByText(first,re){return Array.from(first.querySelectorAll('.mt-section')).find(function(x){return re.test(String(x.textContent||'').trim().toUpperCase())})||null}
function firstSection(first){return sectionByText(first,/^1\.|CARACTERÍSTICAS/)}
function locationSection(first){return sectionByText(first,/^3\.|UBICACIÓN DEL SUMINISTRO/)}
function syncAlert(d,first,note){var alert=first.querySelector('.v128-alert');if(!note){if(alert)alert.remove();return}if(!alert){alert=d.createElement('div');alert.className='v128-alert';alert.innerHTML='<div class="lab">OBSERVACIONES PARA MEMORIA</div><div class="txt"></div>'}var sec=locationSection(first),anchor=sec&&sec.nextElementSibling?sec.nextElementSibling:sec;if(anchor&&alert.previousElementSibling!==anchor)anchor.insertAdjacentElement('afterend',alert);else if(!anchor&&!alert.parentElement)first.appendChild(alert);var txt=alert.querySelector('.txt');if(txt&&txt.textContent!==note)txt.textContent=note}
function normalizarTension(box){Array.from(box.querySelectorAll('.mt-field')).forEach(function(f){var sp=f.querySelector('span'),t=sp?String(sp.textContent||'').trim().toUpperCase():'';if(t==='NIVEL DE TENSIÓN'){f.classList.remove('v127-key');f.classList.add('v128-tension')}});Array.from(box.querySelectorAll('.mt-table')).forEach(function(t){Array.from(t.rows||[]).forEach(function(r){if(r.cells&&r.cells.length>=2){var c=r.cells[1];if(c)c.classList.remove('v127-bigcol')}})})}
function applyMem(d){addMemStyle(d);var box=d.getElementById('memoriaContenido');if(!box||!box.children.length)return;normalizarTension(box);var id=Number(d.getElementById('memSel')&&d.getElementById('memSel').value)||0,note=getNote(id),first=box.querySelector('.mt-page');if(first){var sec=firstSection(first);if(sec&&String(sec.textContent||'').trim()!=='1. CARACTERÍSTICAS DE LA INSTALACIÓN')sec.textContent='1. CARACTERÍSTICAS DE LA INSTALACIÓN';syncAlert(d,first,note)}}
function patchMem(d,w){if(patchedMem.has(w)||!d.getElementById('memoriaContenido'))return;patchedMem.add(w);addMemStyle(d);var b=d.getElementById('memoriaContenido'),pending=0;new MutationObserver(function(){clearTimeout(pending);pending=setTimeout(function(){applyMem(d)},35)}).observe(b,{childList:true,subtree:true});if(typeof w.renderMemoria==='function'){var old=w.renderMemoria;w.renderMemoria=function(){var r=old.apply(w,arguments);Promise.resolve(r).then(function(){setTimeout(function(){applyMem(d)},60)});return r}}setTimeout(function(){applyMem(d)},180)}
function walk(w,s){if(!w||s.has(w))return;s.add(w);var d;try{d=w.document}catch(e){return}try{if(d.getElementById('formAviso'))patchApp(d,w);if(d.getElementById('memoriaContenido'))patchMem(d,w);prepareFolds(d);Array.from(d.querySelectorAll('iframe')).forEach(function(f){try{walk(f.contentWindow,s)}catch(e){}})}catch(e){}}
function scan(){walk(window,new Set())}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scan);else scan();setInterval(scan,900);
})();
