(function(){'use strict';
var MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',CFG='APP_AVISOS_CONFIG_V127',CUPS='APP_AVISOS_CUPS_V127',patched=new WeakSet();
function jget(k,d){try{var x=JSON.parse(localStorage.getItem(k)||'null');return x&&typeof x==='object'?x:d}catch(e){return d}}
function cfg(){var x=jget(CFG,{});x.emails=x.emails||{};return x}function saveCfg(x){localStorage.setItem(CFG,JSON.stringify(x||{}))}function main(){return jget(MAIN,{avisos:[]})}function cupMap(){return jget(CUPS,{})}function cupGet(id){return cupMap()[String(id)]===true}function cupSet(id,v){var x=cupMap();x[String(id)]=!!v;localStorage.setItem(CUPS,JSON.stringify(x))}
function email(v){return String(v||'').trim().toLowerCase()}function up(v){return String(v||'').trim().toUpperCase()}function val(d,id){var e=d.getElementById(id);return e?String(e.value||'').trim():''}function newId(before){var s={};before.forEach(function(x){s[String(x)]=1});var a=(main().avisos||[]).map(function(x){return Number(x.id)}).filter(function(x){return x&&!s[String(x)]});return a.length?Math.max.apply(Math,a):0}
function resize(file){return new Promise(function(ok,no){var r=new FileReader();r.onerror=function(){no(new Error('NO SE PUDO LEER LA IMAGEN'))};r.onload=function(){var im=new Image();im.onerror=function(){no(new Error('IMAGEN NO VÁLIDA'))};im.onload=function(){var s=Math.min(1,1000/im.width,500/im.height),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);ok(c.toDataURL('image/png'))};im.src=r.result};r.readAsDataURL(file)})}
function style(d){if(d.getElementById('v127style'))return;var s=d.createElement('style');s.id='v127style';s.textContent='.v127cfg{margin:16px 0 10px;border-top:2px solid #dbe3ee;padding-top:12px}.v127imggrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.v127imgbox{border:1px solid #dbe3ee;border-radius:12px;padding:10px}.v127imgbox img{display:none;width:100%;max-height:150px;object-fit:contain;border:1px solid #e4e7ec;border-radius:8px}.v127imgbox .empty{min-height:80px;display:flex;align-items:center;justify-content:center}.v127cups{grid-column:1/-1;border:1px solid #bfd2eb;border-radius:13px;padding:11px;background:#f8fbff}.v127switch{display:flex;justify-content:space-between;align-items:center;gap:12px}.v127switch input{width:24px;height:24px;margin:0}.v127cups button{margin-top:8px;width:100%}@media(max-width:600px){.v127imggrid{grid-template-columns:1fr}}';d.head.appendChild(s)}
function ensureCfg(d){var box=d.getElementById('v127ConfigBox');if(box)return box;style(d);var card=d.querySelector('#config .card');if(!card)return null;box=d.createElement('div');box.id='v127ConfigBox';box.className='v127cfg';box.innerHTML='<div class="sectionTitle">CUENTAS DE CORREO</div><div class="grid2"><label>COMERCIALIZADORA 1<input id="v127MailCom1" type="email"></label><label>COMERCIALIZADORA 2<input id="v127MailCom2" type="email"></label><label>ENDESA<input id="v127MailEndesa" type="email"></label><label>INSPECCIÓN<input id="v127MailInspeccion" type="email"></label><label>NUEVOS SUMINISTROS<input id="v127MailNuevos" type="email"></label><label>SOLICITAR CUPS<input id="v127MailCups" type="email"></label></div><div class="sectionTitle" style="margin-top:16px">SELLO Y FIRMA PARA LA MEMORIA</div><div class="v127imggrid"><div class="v127imgbox"><b>SELLO</b><img id="v127SelloPrev"><div id="v127SelloEmpty" class="empty">SIN SELLO</div><label>IMAGEN DEL SELLO<input id="v127SelloFile" type="file" accept="image/*"></label><button type="button" id="v127SelloDel" class="full">QUITAR SELLO</button></div><div class="v127imgbox"><b>FIRMA</b><img id="v127FirmaPrev"><div id="v127FirmaEmpty" class="empty">SIN FIRMA</div><label>IMAGEN DE LA FIRMA<input id="v127FirmaFile" type="file" accept="image/*"></label><button type="button" id="v127FirmaDel" class="full">QUITAR FIRMA</button></div></div>';
var save=Array.from(card.querySelectorAll('button')).find(function(b){return /GUARDAR CONFIGURACI/i.test(b.textContent)});if(save)save.parentNode.insertBefore(box,save);else card.appendChild(box);
function bind(id,k){var f=d.getElementById(id);f.addEventListener('change',function(){var file=f.files&&f.files[0];f.value='';if(!file)return;resize(file).then(function(src){var c=cfg();c[k]=src;saveCfg(c);loadCfg(d)}).catch(function(e){alert(e.message)})})}bind('v127SelloFile','selloData');bind('v127FirmaFile','firmaData');d.getElementById('v127SelloDel').onclick=function(){var c=cfg();c.selloData='';saveCfg(c);loadCfg(d)};d.getElementById('v127FirmaDel').onclick=function(){var c=cfg();c.firmaData='';saveCfg(c);loadCfg(d)};return box}
function loadCfg(d){if(!ensureCfg(d))return;var c=cfg(),m=c.emails||{},x={v127MailCom1:m.comercializadora1||'',v127MailCom2:m.comercializadora2||'',v127MailEndesa:m.endesa||'',v127MailInspeccion:m.inspeccion||'',v127MailNuevos:m.nuevosSuministros||'',v127MailCups:m.solicitarCups||''};Object.keys(x).forEach(function(id){d.getElementById(id).value=email(x[id])});[['selloData','v127SelloPrev','v127SelloEmpty'],['firmaData','v127FirmaPrev','v127FirmaEmpty']].forEach(function(a){var im=d.getElementById(a[1]),em=d.getElementById(a[2]),src=c[a[0]]||'';if(src){im.src=src;im.style.display='block';em.style.display='none'}else{im.removeAttribute('src');im.style.display='none';em.style.display='flex'}})}
function saveInputs(d){var c=cfg();c.emails={comercializadora1:email(val(d,'v127MailCom1')),comercializadora2:email(val(d,'v127MailCom2')),endesa:email(val(d,'v127MailEndesa')),inspeccion:email(val(d,'v127MailInspeccion')),nuevosSuministros:email(val(d,'v127MailNuevos')),solicitarCups:email(val(d,'v127MailCups'))};saveCfg(c)}
function mailCups(d){var to=email((cfg().emails||{}).solicitarCups);if(!to){alert('CONFIGURA PRIMERO LA CUENTA "SOLICITAR CUPS" EN CONFIGURACIÓN.');try{d.defaultView.App.show('config')}catch(e){}return}var body=['HOLA, ENVÍO INFORMACIÓN PARA SOLICITAR CUPS DE UNA FINCA.','','DIRECCIÓN: '+up(val(d,'avDireccion')),'CÓDIGO POSTAL: '+up(val(d,'avCp')),'LOCALIDAD: '+up(val(d,'avLocalidad')),'PROVINCIA: '+up(val(d,'avProvincia'))].join('\n'),a=d.createElement('a');a.href='mailto:'+encodeURIComponent(to)+'?subject='+encodeURIComponent('CUPS')+'&body='+encodeURIComponent(body);a.style.display='none';d.body.appendChild(a);a.click();setTimeout(function(){a.remove()},500)}
function ensureCups(d){if(d.getElementById('v127CupsBox'))return;style(d);var grid=d.querySelector('#formAviso .grid2');if(!grid)return;var target=Array.from(grid.querySelectorAll('.sectionTitle')).find(function(x){return /DATOS ELÉCTRICOS/i.test(x.textContent)}),b=d.createElement('div');b.id='v127CupsBox';b.className='v127cups';b.innerHTML='<div class="v127switch"><div><b>SOLICITUD DE CUPS</b><div class="muted">SI ES SÍ, PREPARAMOS EL CORREO AUTOMÁTICAMENTE.</div></div><label style="margin:0;display:flex;align-items:center;gap:7px"><span id="v127CupsTxt">NO</span><input id="v127CupsCheck" type="checkbox"></label></div><button id="v127CupsMail" type="button" style="display:none">✉ ABRIR CORREO PARA SOLICITAR CUPS</button>';if(target)grid.insertBefore(b,target);else grid.appendChild(b);var ch=d.getElementById('v127CupsCheck'),bt=d.getElementById('v127CupsMail');ch.onchange=function(){d.getElementById('v127CupsTxt').textContent=ch.checked?'SÍ':'NO';bt.style.display=ch.checked?'block':'none';if(ch.checked)mailCups(d)};bt.onclick=function(){mailCups(d)}}
function loadCups(d,id,dup){ensureCups(d);var ch=d.getElementById('v127CupsCheck'),bt=d.getElementById('v127CupsMail'),v=!dup&&id?cupGet(id):false;if(ch){ch.checked=v;d.getElementById('v127CupsTxt').textContent=v?'SÍ':'NO';bt.style.display=v?'block':'none'}}
function patch(d,w){if(patched.has(w)||!d.getElementById('v122Box')||!w.App)return;patched.add(w);ensureCfg(d);loadCfg(d);ensureCups(d);var A=w.App,show=A.show,gc=A.guardarEmpresa,n=A.nuevoAviso,e=A.editarAviso,du=A.duplicarAviso,sa=A.guardarAviso;A.show=function(id){var r=show.apply(A,arguments);if(id==='config')setTimeout(function(){loadCfg(d)},30);return r};A.guardarEmpresa=function(){saveInputs(d);return gc.apply(A,arguments)};A.nuevoAviso=function(){var r=n.apply(A,arguments);setTimeout(function(){loadCups(d,0,false)},80);return r};A.editarAviso=function(id){var r=e.apply(A,arguments);setTimeout(function(){loadCups(d,id,false)},80);return r};A.duplicarAviso=function(id){var r=du.apply(A,arguments);setTimeout(function(){loadCups(d,0,true)},80);return r};A.guardarAviso=function(){var before=(main().avisos||[]).map(function(x){return Number(x.id)}),id=Number(val(d,'avId'))||0,yes=!!(d.getElementById('v127CupsCheck')&&d.getElementById('v127CupsCheck').checked),r=sa.apply(A,arguments);setTimeout(function(){var fin=id||newId(before);if(fin)cupSet(fin,yes)},180);return r};var id=Number(val(d,'avId'))||0;if(d.getElementById('formAviso')&&d.getElementById('formAviso').style.display!=='none')loadCups(d,id,false)}
function walk(w,s){if(!w||s.has(w))return;s.add(w);var d;try{d=w.document}catch(e){return}try{if(d.getElementById('config'))patch(d,w);Array.from(d.querySelectorAll('iframe')).forEach(function(f){try{walk(f.contentWindow,s)}catch(e){}})}catch(e){}}function scan(){walk(window,new Set())}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scan);else scan();setInterval(scan,900);
})();
