(function(){'use strict';
const MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',FLAGS='APP_AVISOS_FLAGS_V120',CUPS='APP_AVISOS_CUPS_V127',DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado',COND='APP_AVISOS_CONDICIONES_V129_';
const styled=new WeakSet(),bound=new WeakSet();
function jget(k,d){try{const x=JSON.parse(localStorage.getItem(k)||'null');return x&&typeof x==='object'?x:d}catch(e){return d}}
function data(){return jget(MAIN,{avisos:[]})}function flags(){return jget(FLAGS,{})}function cups(){return jget(CUPS,{})}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains('planos'))q.createObjectStore('planos')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function sget(k){return openDb().then(q=>new Promise((ok,no)=>{const r=q.transaction(STATE,'readonly').objectStore(STATE).get(String(k));r.onsuccess=()=>{const v=r.result;q.close();ok(v==null?null:v)};r.onerror=()=>{const e=r.error;q.close();no(e)}}))}
function style(d){if(styled.has(d))return;styled.add(d);const s=d.createElement('style');s.textContent='.v129-client-card{margin:12px 0;border:1px solid #dbe3ee;border-radius:14px;padding:12px;background:#fbfcfe}.v129-client-card h3{margin:0 0 10px;font-size:15px}.v129-client-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.v129-client-chip{border:1px solid #e1e6ed;border-radius:11px;padding:9px;background:#fff}.v129-client-chip b{display:block;font-size:10px;color:#667085;margin-bottom:4px}.v129-client-chip span{font-size:13px;font-weight:800;color:#182033}.v129-client-docs{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:9px}.v129-doc{border-radius:10px;padding:9px;text-align:center;font-size:11px;font-weight:800;border:1px solid #dbe3ee;background:#fff}.v129-doc.ok{border-color:#b7dfc3;background:#f2fbf5;color:#166534}.v129-doc.no{color:#667085}.v129-assoc{margin-top:10px;font-size:11px;color:#667085}.v129-assoc strong{color:#182033}@media(max-width:560px){.v129-client-grid{grid-template-columns:1fr}.v129-client-docs{grid-template-columns:1fr}}';d.head.appendChild(s)}
function sameClient(a,b){const an=String(a.nif||'').trim().toUpperCase(),bn=String(b.nif||'').trim().toUpperCase();if(an&&bn)return an===bn;return String(a.cliente||'').trim().toUpperCase()===String(b.cliente||'').trim().toUpperCase()}
async function render(d){const sel=d.getElementById('cliSel'),box=d.getElementById('v129ClientSummary');if(!sel||!box)return;const id=Number(sel.value)||0,p=data(),av=(p.avisos||[]).find(x=>Number(x.id)===id);if(!av){box.innerHTML='<div class="v129-client-card">SIN CLIENTE SELECCIONADO</div>';return}const f=flags()[String(id)]||{},csol=cups()[String(id)]===true,cond=await sget(COND+id),assoc=(p.avisos||[]).filter(x=>sameClient(x,av));const cupsTxt=[av.cupsE,av.cupsG].filter(Boolean).join(' / ')||'SIN CUPS';box.innerHTML='<div class="v129-client-card"><h3>RESUMEN DE FICHA DEL CLIENTE</h3><div class="v129-client-grid"><div class="v129-client-chip"><b>CLIENTE</b><span>'+esc(av.cliente||'')+'</span></div><div class="v129-client-chip"><b>NIF / CIF</b><span>'+esc(av.nif||'')+'</span></div><div class="v129-client-chip"><b>TELÉFONO</b><span>'+esc(av.telefono||'')+'</span></div><div class="v129-client-chip"><b>CORREO</b><span>'+esc(av.email||'')+'</span></div><div class="v129-client-chip"><b>CUPS ELECTRICIDAD / GAS</b><span>'+esc(cupsTxt)+'</span></div><div class="v129-client-chip"><b>IBAN</b><span>'+(f.iban?esc(f.iban.slice(0,4)+' ···· '+f.iban.slice(-4)):'SIN IBAN')+'</span></div></div><div class="v129-client-docs"><div class="v129-doc '+((av.cupsE||av.cupsG||csol)?'ok':'no')+'">CUPS<br>'+((av.cupsE||av.cupsG)?'DISPONIBLE':(csol?'SOLICITADO':'PENDIENTE'))+'</div><div class="v129-doc '+(cond&&cond.blob?'ok':'no')+'">CONDICIONES<br>'+(cond&&cond.blob?'DOCUMENTO GUARDADO':'SIN DOCUMENTO')+'</div><div class="v129-doc '+(f.contratoElectricidad?'ok':'no')+'">CONTRATO<br>'+(f.contratoElectricidad?'SÍ':'NO')+'</div></div><div class="v129-assoc"><strong>'+assoc.length+' AVISO(S) ASOCIADO(S)</strong> a este cliente.</div></div>'}
function inject(d){const view=d.getElementById('cliV'),sel=d.getElementById('cliSel'),info=d.getElementById('cliInfo');if(!view||!sel||!info)return;style(d);let box=d.getElementById('v129ClientSummary');if(!box){box=d.createElement('div');box.id='v129ClientSummary';info.insertAdjacentElement('afterend',box)}const h=view.querySelector('h2');if(h)h.textContent='FICHA DE CLIENTE';if(!bound.has(sel)){bound.add(sel);sel.addEventListener('change',()=>setTimeout(()=>render(d),20))}render(d)}
function walk(w,s){if(!w||s.has(w))return;s.add(w);let d;try{d=w.document}catch(e){return}try{inject(d);Array.from(d.querySelectorAll('iframe')).forEach(f=>{try{walk(f.contentWindow,s)}catch(e){}})}catch(e){}}
function scan(){walk(window,new Set())}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scan);else scan();setInterval(scan,900);
})();
