(function(){'use strict';
const ENV='APP_AVISOS_ENVIO_CONEXIONES_V129',CFG='APP_AVISOS_CONFIG_V127',DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado',WORK='APP_AVISOS_TRABAJOS_V129_',DEF='APP_AVISOS_DEFICIENCIAS_V129_';
const styled=new WeakSet(),bound=new WeakSet(),urls=[];
function jget(k,d){try{const x=JSON.parse(localStorage.getItem(k)||'null');return x&&typeof x==='object'?x:d}catch(e){return d}}function jset(k,v){localStorage.setItem(k,JSON.stringify(v||{}))}
function up(v){return String(v||'').trim().toUpperCase()}function low(v){return String(v||'').trim().toLowerCase()}function val(d,id){const e=d.getElementById(id);return e?String(e.value||'').trim():''}
function cfg(){const x=jget(ENV,{});return{textoTrabajos:x.textoTrabajos||'',textoDeficiencias:x.textoDeficiencias||'',textoSeguimiento:x.textoSeguimiento||''}}function saveCfg(x){jset(ENV,x)}function inspeccion(){return low((((jget(CFG,{}).emails)||{}).inspeccion)||'')}
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains('planos'))q.createObjectStore('planos')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function sget(k){return openDb().then(q=>new Promise((ok,no)=>{const r=q.transaction(STATE,'readonly').objectStore(STATE).get(String(k));r.onsuccess=()=>{const v=r.result;q.close();ok(v==null?null:v)};r.onerror=()=>{const e=r.error;q.close();no(e)}}))}
function sput(k,v){return openDb().then(q=>new Promise((ok,no)=>{const t=q.transaction(STATE,'readwrite');t.objectStore(STATE).put(v,String(k));t.oncomplete=()=>{q.close();ok()};t.onerror=()=>{const e=t.error;q.close();no(e)}}))}
function currentId(d){return Number(val(d,'avId'))||0}
function style(d){if(styled.has(d))return;styled.add(d);const s=d.createElement('style');s.textContent=`.v129-mailcfg{background:#fff;border:1px solid #e3e6eb;border-radius:17px;padding:14px}.v129-mailcfg h3{margin:0 0 8px;font-size:15px}.v129-mailcfg label{display:block;font-size:11px;font-weight:800;color:#667085;margin:9px 0}.v129-mailcfg textarea{width:100%;box-sizing:border-box;margin-top:5px;border:1px solid #d0d5dd;border-radius:11px;padding:10px;font:14px Arial;min-height:78px;resize:vertical}.v129-mailcfg button{width:100%;margin-top:6px;background:#111!important;color:#fff!important;border-color:#111!important}.v129-flow{border-top:1px solid #e5e7eb;margin-top:11px;padding-top:10px}.v129-acc{border:1px solid #dfe4ea;border-radius:13px;background:#fff;margin:8px 0;overflow:hidden}.v129-acc-head{width:100%;border:0!important;border-radius:0!important;background:#f8fafc!important;color:#182033!important;text-align:left!important;padding:13px!important;font-weight:900!important;display:flex;justify-content:space-between;align-items:center}.v129-acc-head:after{content:'▸';font-size:18px}.v129-acc.open .v129-acc-head:after{content:'▾'}.v129-acc-body{display:none;padding:10px;border-top:1px solid #e5e7eb}.v129-acc.open .v129-acc-body{display:block}.v129-phgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin-top:8px}.v129-ph{border:1px solid #e5e7eb;border-radius:10px;padding:5px}.v129-ph img{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:7px}.v129-ph button{width:100%;padding:6px;margin-top:4px;font-size:10px}.v129-send{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:8px}.v129-note{font-size:11px;color:#667085;line-height:1.4;margin:5px 0}`;d.head.appendChild(s)}
function injectHome(d){style(d);const home=d.querySelector('#inicio .soltec-home');if(!home||d.getElementById('v129MailCfg'))return;const c=cfg(),box=d.createElement('div');box.id='v129MailCfg';box.className='v129-mailcfg';box.innerHTML='<h3>TEXTOS DE CORREO · CONDICIONES</h3><div class="v129-note">DESTINATARIO: CORREO DE INSPECCIÓN CONFIGURADO EN CONFIGURACIÓN.</div><label>TEXTO · HAY TRABAJOS A REALIZAR<textarea id="v129TxtTrab">'+String(c.textoTrabajos||'').replace(/</g,'&lt;')+'</textarea></label><label>TEXTO · HAY DEFICIENCIAS<textarea id="v129TxtDef">'+String(c.textoDeficiencias||'').replace(/</g,'&lt;')+'</textarea></label><label>TEXTO · SEGUIMIENTO DE EXPEDIENTE<textarea id="v129TxtSeg">'+String(c.textoSeguimiento||'').replace(/</g,'&lt;')+'</textarea></label><button id="v129SaveMailCfg" type="button">GUARDAR TEXTOS</button><div id="v129MailCfgStatus" class="v129-note"></div>';const ver=home.querySelector('.soltec-version');if(ver)home.insertBefore(box,ver);else home.appendChild(box);d.getElementById('v129SaveMailCfg').onclick=()=>{saveCfg({textoTrabajos:val(d,'v129TxtTrab'),textoDeficiencias:val(d,'v129TxtDef'),textoSeguimiento:val(d,'v129TxtSeg')});const st=d.getElementById('v129MailCfgStatus');st.textContent='GUARDADO';setTimeout(()=>st.textContent='',1500)}}
function resize(file){return new Promise((ok,no)=>{const im=new Image(),u=URL.createObjectURL(file);im.onload=()=>{try{const max=1600,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);c.toBlob(b=>{URL.revokeObjectURL(u);if(!b)return no(new Error('NO SE PUDO PROCESAR LA FOTO'));ok({blob:b,nombre:file.name||('foto_'+Date.now()+'.jpg'),creadaEn:new Date().toISOString()})},'image/jpeg',.84)}catch(e){URL.revokeObjectURL(u);no(e)}};im.onerror=()=>{URL.revokeObjectURL(u);no(new Error('NO SE PUDO ABRIR LA FOTO'))};im.src=u})}
function key(type,id){return(type==='trab'?WORK:DEF)+id}
async function renderPhotos(d,type,id){const grid=d.getElementById(type==='trab'?'v129TrabGrid':'v129DefGrid'),st=d.getElementById(type==='trab'?'v129TrabStatus':'v129DefStatus');if(!grid||!st)return;grid.innerHTML='';if(!id){st.textContent='GUARDA PRIMERO EL AVISO PARA AÑADIR FOTOS.';return}const a=await sget(key(type,id))||[];st.textContent=a.length?a.length+' FOTO(S) GUARDADA(S).':'SIN FOTOS GUARDADAS.';a.forEach((p,i)=>{const u=URL.createObjectURL(p.blob);urls.push(u);const x=d.createElement('div');x.className='v129-ph';x.innerHTML='<img src="'+u+'" alt="Foto"><button type="button">ELIMINAR</button>';x.querySelector('button').onclick=async()=>{const cur=await sget(key(type,id))||[];cur.splice(i,1);await sput(key(type,id),cur);renderPhotos(d,type,id)};grid.appendChild(x)})}
async function addPhotos(d,type,files){const id=currentId(d);if(!id){alert('GUARDA PRIMERO EL AVISO. DESPUÉS PODRÁS APORTAR LAS FOTOS.');return}const n=await Promise.all(Array.from(files||[]).map(resize)),old=await sget(key(type,id))||[];await sput(key(type,id),old.concat(n));renderPhotos(d,type,id)}
function mdata(d,type){const c=cfg(),ref=up(val(d,'v129RefCondiciones'))||'SIN REF. CONDICIONES',dir=up(val(d,'avDireccion'))||'SIN DIRECCIÓN';let subject='',texto='',titulo='';if(type==='def'){subject='REF. CONDICIONES '+ref+' - DEFICIENCIAS - '+dir;texto=c.textoDeficiencias;titulo='DEFICIENCIAS'}else if(type==='trab'){subject='REF. CONDICIONES '+ref+' - '+dir;texto=c.textoTrabajos;titulo='TRABAJOS A REALIZAR'}else{subject='REF. CONDICIONES '+ref+' - '+dir;texto=c.textoSeguimiento;titulo='SEGUIMIENTO DE EXPEDIENTE'}const body=[texto||'',texto?'':'',titulo,'','CLIENTE: '+up(val(d,'avCliente')),'DIRECCIÓN: '+dir,'REF. CONDICIONES: '+ref,'NÚMERO DE CONTADOR: '+up(val(d,'v129Contador')),'NÚMERO DE CONTADOR CERCANO: '+up(val(d,'v129ContadorCercano'))];if(type==='def')body.push('','SE ADJUNTAN FOTOGRAFÍAS DE LAS DEFICIENCIAS.');if(type==='trab')body.push('','SE ADJUNTAN FOTOGRAFÍAS DE LOS TRABAJOS.');return{to:inspeccion(),subject,body:body.filter((x,i,a)=>!(x===''&&a[i-1]==='')).join('\n')}}
function openMail(d,type){const m=mdata(d,type);if(!m.to){alert('CONFIGURA PRIMERO EL CORREO DE INSPECCIÓN EN CONFIGURACIÓN.');return}const a=d.createElement('a');a.href='mailto:'+encodeURIComponent(m.to)+'?subject='+encodeURIComponent(m.subject)+'&body='+encodeURIComponent(m.body);a.style.display='none';d.body.appendChild(a);a.click();setTimeout(()=>a.remove(),500)}
async function share(d,type){const id=currentId(d),a=id?await sget(key(type,id))||[]:[];if(!a.length){alert('APORTA PRIMERO LAS FOTOS.');return}const m=mdata(d,type);if(!m.to){alert('CONFIGURA PRIMERO EL CORREO DE INSPECCIÓN EN CONFIGURACIÓN.');return}const files=a.map((p,i)=>new File([p.blob],p.nombre||('foto_'+(i+1)+'.jpg'),{type:p.blob.type||'image/jpeg'}));if(navigator.share&&(!navigator.canShare||navigator.canShare({files}))){try{await navigator.share({title:m.subject,text:'PARA: '+m.to+'\n\n'+m.body,files});return}catch(e){if(e&&e.name==='AbortError')return}}alert('EL NAVEGADOR NO PUEDE ADJUNTAR AUTOMÁTICAMENTE LAS FOTOS. SE ABRIRÁ EL CORREO PREPARADO.');openMail(d,type)}
function toggleOnly(d,id){const ids=['v129AccDef','v129AccTrab','v129AccSeg'],was=d.getElementById(id)?.classList.contains('open');ids.forEach(x=>d.getElementById(x)?.classList.remove('open'));if(!was)d.getElementById(id)?.classList.add('open')}
function injectForm(d){style(d);const box=d.getElementById('v129SupplyBox');if(!box||d.getElementById('v129CondFlow'))return;const old=d.getElementById('v129DefCheck');if(old){const p=old.closest('.v129-doc');if(p)p.style.display='none'}const flowBox=d.createElement('div');flowBox.id='v129CondFlow';flowBox.className='v129-flow';flowBox.innerHTML='<div class="sectionTitle" style="margin-top:0">CONDICIONES DE SUMINISTRO · ACTUACIONES</div><div id="v129AccDef" class="v129-acc"><button type="button" class="v129-acc-head">HAY DEFICIENCIAS</button><div class="v129-acc-body"><label>APORTAR FOTOS DE DEFICIENCIAS<input id="v129DefFiles" type="file" accept="image/*" multiple></label><div id="v129DefStatus" class="v129-note"></div><div id="v129DefGrid" class="v129-phgrid"></div><div class="v129-send"><button type="button" id="v129DefShare">COMPARTIR FOTOS</button><button type="button" id="v129DefMail">ABRIR CORREO A INSPECCIÓN</button></div></div></div><div id="v129AccTrab" class="v129-acc"><button type="button" class="v129-acc-head">HAY TRABAJOS A REALIZAR</button><div class="v129-acc-body"><label>APORTAR FOTOS DE TRABAJOS<input id="v129TrabFiles" type="file" accept="image/*" multiple></label><div id="v129TrabStatus" class="v129-note"></div><div id="v129TrabGrid" class="v129-phgrid"></div><div class="v129-send"><button type="button" id="v129TrabShare">COMPARTIR FOTOS</button><button type="button" id="v129TrabMail">ABRIR CORREO A INSPECCIÓN</button></div></div></div><div id="v129AccSeg" class="v129-acc"><button type="button" class="v129-acc-head">SEGUIMIENTO DE EXPEDIENTE</button><div class="v129-acc-body"><div class="v129-note">PREPARA UN CORREO CON LA REF. DE CONDICIONES, LA DIRECCIÓN Y EL TEXTO DEFINIDO EN INICIO.</div><button type="button" id="v129SegMail" style="width:100%">ABRIR CORREO A INSPECCIÓN</button></div></div>';box.appendChild(flowBox);if(bound.has(flowBox))return;bound.add(flowBox);d.querySelector('#v129AccDef .v129-acc-head').onclick=()=>toggleOnly(d,'v129AccDef');d.querySelector('#v129AccTrab .v129-acc-head').onclick=()=>toggleOnly(d,'v129AccTrab');d.querySelector('#v129AccSeg .v129-acc-head').onclick=()=>toggleOnly(d,'v129AccSeg');d.getElementById('v129TrabFiles').onchange=function(){addPhotos(d,'trab',this.files).finally(()=>this.value='')};d.getElementById('v129DefFiles').onchange=function(){addPhotos(d,'def',this.files).finally(()=>this.value='')};d.getElementById('v129TrabShare').onclick=()=>share(d,'trab');d.getElementById('v129DefShare').onclick=()=>share(d,'def');d.getElementById('v129TrabMail').onclick=()=>openMail(d,'trab');d.getElementById('v129DefMail').onclick=()=>openMail(d,'def');d.getElementById('v129SegMail').onclick=()=>openMail(d,'seg');const id=currentId(d);renderPhotos(d,'trab',id);renderPhotos(d,'def',id)}
function walk(w,s){if(!w||s.has(w))return;s.add(w);let d;try{d=w.document}catch(e){return}try{injectHome(d);injectForm(d);Array.from(d.querySelectorAll('iframe')).forEach(f=>{try{walk(f.contentWindow,s)}catch(e){}})}catch(e){}}
function scan(){walk(window,new Set())}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scan);else scan();setInterval(scan,700);
})();
