(function(){'use strict';
const ENV='APP_AVISOS_ENVIO_CONEXIONES_V129',FLOW='APP_AVISOS_CONDICIONES_FLUJO_V129',DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado',WORK='APP_AVISOS_TRABAJOS_V129_',DEF='APP_AVISOS_DEFICIENCIAS_V129_';
const styled=new WeakSet(),bound=new WeakSet(),urls=[];
function jget(k,d){try{const x=JSON.parse(localStorage.getItem(k)||'null');return x&&typeof x==='object'?x:d}catch(e){return d}}function jset(k,v){localStorage.setItem(k,JSON.stringify(v||{}))}
function up(v){return String(v||'').trim().toUpperCase()}function low(v){return String(v||'').trim().toLowerCase()}function val(d,id){const e=d.getElementById(id);return e?String(e.value||'').trim():''}
function cfg(){return jget(ENV,{email:'',textoTrabajos:'',textoDeficiencias:''})}function saveCfg(x){jset(ENV,x)}function flow(){return jget(FLOW,{})}function getFlow(id){return flow()[String(id)]||{}}function setFlow(id,x){if(!id)return;const f=flow();f[String(id)]=x;jset(FLOW,f)}
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains('planos'))q.createObjectStore('planos')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function sget(k){return openDb().then(q=>new Promise((ok,no)=>{const r=q.transaction(STATE,'readonly').objectStore(STATE).get(String(k));r.onsuccess=()=>{const v=r.result;q.close();ok(v==null?null:v)};r.onerror=()=>{const e=r.error;q.close();no(e)}}))}
function sput(k,v){return openDb().then(q=>new Promise((ok,no)=>{const t=q.transaction(STATE,'readwrite');t.objectStore(STATE).put(v,String(k));t.oncomplete=()=>{q.close();ok()};t.onerror=()=>{const e=t.error;q.close();no(e)}}))}
function currentId(d){return Number(val(d,'avId'))||0}
function style(d){if(styled.has(d))return;styled.add(d);const s=d.createElement('style');s.textContent=`.v129-mailcfg{background:#fff;border:1px solid #e3e6eb;border-radius:17px;padding:14px}.v129-mailcfg h3{margin:0 0 8px;font-size:15px}.v129-mailcfg label{display:block;font-size:11px;font-weight:800;color:#667085;margin:9px 0}.v129-mailcfg input,.v129-mailcfg textarea{width:100%;box-sizing:border-box;margin-top:5px;border:1px solid #d0d5dd;border-radius:11px;padding:10px;font:14px Arial}.v129-mailcfg textarea{min-height:78px;resize:vertical}.v129-mailcfg button{width:100%;margin-top:6px;background:#111!important;color:#fff!important;border-color:#111!important}.v129-flow{border-top:1px solid #e5e7eb;margin-top:11px;padding-top:10px}.v129-flow h4{margin:0 0 8px;font-size:13px;color:#344054}.v129-choice{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:6px 0}.v129-choice button{background:#fff!important;color:#344054!important;border:1px solid #d0d5dd!important}.v129-choice button.on{background:#e7281c!important;color:#fff!important;border-color:#e7281c!important}.v129-sub{display:none;border:1px solid #e3e6eb;border-radius:12px;padding:9px;background:#fff}.v129-sub.open{display:block}.v129-phgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin-top:8px}.v129-ph{border:1px solid #e5e7eb;border-radius:10px;padding:5px}.v129-ph img{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:7px}.v129-ph button{width:100%;padding:6px;margin-top:4px;font-size:10px}.v129-send{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:8px}.v129-note{font-size:11px;color:#667085;line-height:1.4;margin:5px 0}`;d.head.appendChild(s)}
function injectHome(d){style(d);const home=d.querySelector('#inicio .soltec-home');if(!home||d.getElementById('v129MailCfg'))return;const c=cfg(),box=d.createElement('div');box.id='v129MailCfg';box.className='v129-mailcfg';box.innerHTML='<h3>CORREOS DE CONDICIONES</h3><label>CORREO CONEXIONES<input id="v129ConnMail" type="email" value="'+String(c.email||'').replace(/"/g,'&quot;')+'"></label><label>TEXTO · TRABAJOS REALIZADOS<textarea id="v129TxtTrab">'+String(c.textoTrabajos||'').replace(/</g,'&lt;')+'</textarea></label><label>TEXTO · DEFICIENCIAS<textarea id="v129TxtDef">'+String(c.textoDeficiencias||'').replace(/</g,'&lt;')+'</textarea></label><button id="v129SaveMailCfg" type="button">GUARDAR TEXTOS Y CORREO</button><div id="v129MailCfgStatus" class="v129-note"></div>';const ver=home.querySelector('.soltec-version');if(ver)home.insertBefore(box,ver);else home.appendChild(box);d.getElementById('v129SaveMailCfg').onclick=()=>{saveCfg({email:low(val(d,'v129ConnMail')),textoTrabajos:val(d,'v129TxtTrab'),textoDeficiencias:val(d,'v129TxtDef')});const st=d.getElementById('v129MailCfgStatus');st.textContent='GUARDADO';setTimeout(()=>st.textContent='',1500)};['v129ConnMail','v129TxtTrab','v129TxtDef'].forEach(id=>{d.getElementById(id).addEventListener('blur',()=>d.getElementById('v129SaveMailCfg').click())})}
function resize(file){return new Promise((ok,no)=>{const im=new Image(),u=URL.createObjectURL(file);im.onload=()=>{try{const max=1600,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);c.toBlob(b=>{URL.revokeObjectURL(u);if(!b)return no(new Error('NO SE PUDO PROCESAR LA FOTO'));ok({blob:b,nombre:file.name||('foto_'+Date.now()+'.jpg'),creadaEn:new Date().toISOString()})},'image/jpeg',.84)}catch(e){URL.revokeObjectURL(u);no(e)}};im.onerror=()=>{URL.revokeObjectURL(u);no(new Error('NO SE PUDO ABRIR LA FOTO'))};im.src=u})}
function key(type,id){return(type==='trab'?WORK:DEF)+id}
async function renderPhotos(d,type,id){const grid=d.getElementById(type==='trab'?'v129TrabGrid':'v129Def2Grid'),st=d.getElementById(type==='trab'?'v129TrabStatus':'v129Def2Status');if(!grid||!st)return;grid.innerHTML='';if(!id){st.textContent='GUARDA PRIMERO EL AVISO PARA AÑADIR FOTOS.';return}const a=await sget(key(type,id))||[];st.textContent=a.length?a.length+' FOTO(S) GUARDADA(S).':'SIN FOTOS GUARDADAS.';a.forEach((p,i)=>{const u=URL.createObjectURL(p.blob);urls.push(u);const x=d.createElement('div');x.className='v129-ph';x.innerHTML='<img src="'+u+'" alt="Foto"><button type="button" data-i="'+i+'">ELIMINAR</button>';x.querySelector('button').onclick=async()=>{const cur=await sget(key(type,id))||[];cur.splice(i,1);await sput(key(type,id),cur);renderPhotos(d,type,id)};grid.appendChild(x)})}
async function addPhotos(d,type,files){const id=currentId(d);if(!id){alert('GUARDA PRIMERO EL AVISO. DESPUÉS PODRÁS APORTAR LAS FOTOS.');return}const n=await Promise.all(Array.from(files||[]).map(resize)),old=await sget(key(type,id))||[];await sput(key(type,id),old.concat(n));renderPhotos(d,type,id)}
function mdata(d,type){const c=cfg(),ref=up(val(d,'v129RefCondiciones'))||'SIN REF. CONDICIONES',dir=up(val(d,'avDireccion'))||'SIN DIRECCIÓN',isDef=type==='def';const subject=isDef?'REF. CONDICIONES '+ref+' - DEFICIENCIAS - '+dir:'REF. CONDICIONES '+ref+' - '+dir;const texto=isDef?c.textoDeficiencias:c.textoTrabajos;const body=[texto||'',texto?'':'',isDef?'DEFICIENCIAS EN LA INSTALACIÓN':'TRABAJOS REALIZADOS','', 'CLIENTE: '+up(val(d,'avCliente')),'DIRECCIÓN: '+dir,'REF. CONDICIONES: '+ref,'NÚMERO DE CONTADOR: '+up(val(d,'v129Contador')),'NÚMERO DE CONTADOR CERCANO: '+up(val(d,'v129ContadorCercano')),'',isDef?'SE ADJUNTAN FOTOGRAFÍAS DE LAS DEFICIENCIAS.':'SE ADJUNTAN FOTOGRAFÍAS DE LOS TRABAJOS REALIZADOS.'].filter((x,i,a)=>!(x===''&&a[i-1]==='')).join('\n');return{to:low(c.email),subject,body}}
function openMail(d,type){const m=mdata(d,type);if(!m.to){alert('DEFINE PRIMERO EL CORREO DE CONEXIONES EN LA PANTALLA DE INICIO.');return}const a=d.createElement('a');a.href='mailto:'+encodeURIComponent(m.to)+'?subject='+encodeURIComponent(m.subject)+'&body='+encodeURIComponent(m.body);a.style.display='none';d.body.appendChild(a);a.click();setTimeout(()=>a.remove(),500)}
async function share(d,type){const id=currentId(d),a=id?await sget(key(type,id))||[]:[];if(!a.length){alert('APORTA PRIMERO LAS FOTOS.');return}const m=mdata(d,type);if(!m.to){alert('DEFINE PRIMERO EL CORREO DE CONEXIONES EN LA PANTALLA DE INICIO.');return}const files=a.map((p,i)=>new File([p.blob],p.nombre||('foto_'+(i+1)+'.jpg'),{type:p.blob.type||'image/jpeg'}));if(navigator.share&&(!navigator.canShare||navigator.canShare({files}))){try{await navigator.share({title:m.subject,text:'PARA: '+m.to+'\n\n'+m.body,files});return}catch(e){if(e&&e.name==='AbortError')return}}alert('EL NAVEGADOR NO PUEDE ADJUNTAR AUTOMÁTICAMENTE LAS FOTOS AL CORREO. SE ABRIRÁ EL CORREO PREPARADO Y PODRÁS ADJUNTARLAS MANUALMENTE.');openMail(d,type)}
function setChoice(d,type,yes){const id=currentId(d),f=id?getFlow(id):{};f[type]=!!yes;if(id)setFlow(id,f);const sub=d.getElementById(type==='trab'?'v129TrabSub':'v129Def2Sub');sub&&sub.classList.toggle('open',!!yes);['v129'+(type==='trab'?'Trab':'Def2')+'Yes','v129'+(type==='trab'?'Trab':'Def2')+'No'].forEach((bid,i)=>{const b=d.getElementById(bid);if(b)b.classList.toggle('on',yes?!i:!!i)});if(yes){const inp=d.getElementById(type==='trab'?'v129TrabFiles':'v129Def2Files');setTimeout(()=>inp&&inp.click(),80)}}
function loadFlow(d){const id=currentId(d),f=id?getFlow(id):{};setChoice(d,'trab',!!f.trab);setChoice(d,'def',!!f.def);renderPhotos(d,'trab',id);renderPhotos(d,'def',id)}
function injectForm(d){style(d);const box=d.getElementById('v129SupplyBox');if(!box||d.getElementById('v129CondFlow'))return;const old=d.getElementById('v129DefCheck');if(old){const p=old.closest('.v129-doc');if(p)p.style.display='none'}const flowBox=d.createElement('div');flowBox.id='v129CondFlow';flowBox.className='v129-flow';flowBox.innerHTML='<h4>TRABAJOS REALIZADOS</h4><div class="v129-choice"><button type="button" id="v129TrabYes">SÍ</button><button type="button" id="v129TrabNo">NO</button></div><div id="v129TrabSub" class="v129-sub"><label>APORTAR FOTOS DE TRABAJOS REALIZADOS<input id="v129TrabFiles" type="file" accept="image/*" multiple></label><div id="v129TrabStatus" class="v129-note"></div><div id="v129TrabGrid" class="v129-phgrid"></div><div class="v129-send"><button type="button" id="v129TrabShare">ENVIAR CON FOTOS</button><button type="button" id="v129TrabMail">ABRIR CORREO</button></div></div><h4 style="margin-top:13px">DEFICIENCIAS</h4><div class="v129-choice"><button type="button" id="v129Def2Yes">SÍ</button><button type="button" id="v129Def2No">NO</button></div><div id="v129Def2Sub" class="v129-sub"><label>APORTAR FOTOS DE DEFICIENCIAS<input id="v129Def2Files" type="file" accept="image/*" multiple></label><div id="v129Def2Status" class="v129-note"></div><div id="v129Def2Grid" class="v129-phgrid"></div><div class="v129-send"><button type="button" id="v129Def2Share">ENVIAR CON FOTOS</button><button type="button" id="v129Def2Mail">ABRIR CORREO</button></div></div>';box.appendChild(flowBox);if(bound.has(flowBox))return;bound.add(flowBox);d.getElementById('v129TrabYes').onclick=()=>setChoice(d,'trab',true);d.getElementById('v129TrabNo').onclick=()=>setChoice(d,'trab',false);d.getElementById('v129Def2Yes').onclick=()=>setChoice(d,'def',true);d.getElementById('v129Def2No').onclick=()=>setChoice(d,'def',false);d.getElementById('v129TrabFiles').onchange=function(){addPhotos(d,'trab',this.files).finally(()=>this.value='')};d.getElementById('v129Def2Files').onchange=function(){addPhotos(d,'def',this.files).finally(()=>this.value='')};d.getElementById('v129TrabShare').onclick=()=>share(d,'trab');d.getElementById('v129Def2Share').onclick=()=>share(d,'def');d.getElementById('v129TrabMail').onclick=()=>openMail(d,'trab');d.getElementById('v129Def2Mail').onclick=()=>openMail(d,'def');loadFlow(d)}
function walk(w,s){if(!w||s.has(w))return;s.add(w);let d;try{d=w.document}catch(e){return}try{injectHome(d);injectForm(d);Array.from(d.querySelectorAll('iframe')).forEach(f=>{try{walk(f.contentWindow,s)}catch(e){}})}catch(e){}}
function scan(){walk(window,new Set())}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scan);else scan();setInterval(scan,700);
})();
