(function(){'use strict';
const MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE';
let homeDone=false,styleDone=new WeakSet();
function wins(){const out=[],seen=new Set();function walk(w){if(!w||seen.has(w))return;seen.add(w);out.push(w);let fs=[];try{fs=Array.from(w.document.querySelectorAll('iframe'))}catch(e){}fs.forEach(f=>{try{walk(f.contentWindow)}catch(e){}})}walk(window);return out}
function callWhere(test,fn){for(const w of wins()){try{if(test(w)){fn(w);return true}}catch(e){}}return false}
function resetTrabajo(){for(const w of wins()){try{const d=w.document;if(d.getElementById('memV')&&typeof w.showV==='function')w.showV('work');if(d.getElementById('photosV')&&typeof w.show==='function')w.show('work');if(d.getElementById('cliV')&&typeof w.show==='function')w.show('app')}catch(e){}}}
function baseApp(){for(const w of wins()){try{if(w.App&&w.document.getElementById('inicio')&&w.document.getElementById('avisos'))return w}catch(e){}}return null}
function goInicio(){resetTrabajo();const w=baseApp();if(w)w.App.show('inicio');closeMore()}
function goAvisos(nuevo){resetTrabajo();const w=baseApp();if(w){w.App.show('avisos');if(nuevo&&typeof w.App.nuevoAviso==='function')setTimeout(()=>w.App.nuevoAviso(),80)}closeMore()}
function goConfig(){resetTrabajo();const w=baseApp();if(w)w.App.show('config');closeMore()}
function goMemoria(){resetTrabajo();callWhere(w=>w.document.getElementById('memV')&&typeof w.showV==='function',w=>w.showV('mem'));closeMore()}
function goCliente(){resetTrabajo();callWhere(w=>w.document.getElementById('cliV')&&typeof w.show==='function',w=>w.show('cli'));closeMore()}
function goFotos(){resetTrabajo();callWhere(w=>w.document.getElementById('photosV')&&typeof w.show==='function',w=>w.show('photos'));closeMore()}
function goBackup(){callWhere(w=>!!w.document.getElementById('backupBtn'),w=>w.document.getElementById('backupBtn').click());closeMore()}
function counts(){try{const x=JSON.parse(localStorage.getItem(MAIN)||'{}'),a=Array.isArray(x.avisos)?x.avisos:[];return{total:a.length,pend:a.filter(v=>v.estado==='pendiente').length,curso:a.filter(v=>v.estado==='en_curso').length,fin:a.filter(v=>v.estado==='finalizado').length}}catch(e){return{total:0,pend:0,curso:0,fin:0}}}
function injectBaseStyle(d){if(styleDone.has(d))return;styleDone.add(d);const s=d.createElement('style');s.textContent=`
#inicio{padding-top:2px}.soltec-home{display:grid;gap:14px}.soltec-hero{background:linear-gradient(145deg,#111 0%,#242424 70%,#35110f 100%);color:#fff;border:0;border-radius:22px;padding:18px;box-shadow:0 10px 28px rgba(0,0,0,.16)}.soltec-brand{display:flex;align-items:center;gap:14px}.soltec-brand img{width:74px;height:74px;object-fit:contain;background:#fff;border-radius:19px;padding:7px}.soltec-brand h1{font-size:25px;margin:0;letter-spacing:.4px}.soltec-brand p{margin:5px 0 0;color:#ddd;font-size:13px}.soltec-red{height:4px;background:#e7281c;border-radius:999px;margin:15px 0 0}.soltec-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:14px}.soltec-stat{background:rgba(255,255,255,.09);border:1px solid rgba(255,255,255,.12);border-radius:13px;padding:9px 6px;text-align:center}.soltec-stat b{display:block;font-size:20px}.soltec-stat span{font-size:10px;color:#ddd}.soltec-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px}.soltec-action{min-height:92px;border:1px solid #e3e6eb!important;border-radius:17px!important;background:#fff!important;color:#182033!important;padding:14px!important;text-align:left;box-shadow:0 3px 12px rgba(15,23,42,.05)}.soltec-action.primary{grid-column:1/-1;background:#e7281c!important;color:#fff!important;border-color:#e7281c!important;min-height:78px}.soltec-action .ico{font-size:25px;display:block;margin-bottom:7px}.soltec-action strong{display:block;font-size:15px}.soltec-action small{display:block;font-size:11px;font-weight:600;opacity:.68;margin-top:4px}.soltec-secondary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.soltec-mini{border:1px solid #e3e6eb!important;background:#fff!important;color:#4b5563!important;border-radius:14px!important;padding:11px 6px!important;font-size:12px!important}.soltec-version{text-align:center;color:#98a2b3;font-size:10px;padding:1px 0 4px}@media(max-width:460px){.soltec-brand img{width:64px;height:64px}.soltec-brand h1{font-size:22px}.soltec-stats{grid-template-columns:repeat(2,1fr)}}`;
d.head.appendChild(s)}
function buildHome(){const w=baseApp();if(!w)return false;const d=w.document,sec=d.getElementById('inicio');if(!sec)return false;injectBaseStyle(d);const c=counts();sec.innerHTML=`<div class="soltec-home"><div class="soltec-hero"><div class="soltec-brand"><img src="/Appcondiciones/avisos-v129/icon.svg" alt="SOLTEC"><div><h1>SOLTEC Avisos</h1><p>Gestión de avisos y memorias técnicas</p></div></div><div class="soltec-red"></div><div class="soltec-stats"><div class="soltec-stat"><b>${c.total}</b><span>AVISOS</span></div><div class="soltec-stat"><b>${c.pend}</b><span>PENDIENTES</span></div><div class="soltec-stat"><b>${c.curso}</b><span>EN CURSO</span></div><div class="soltec-stat"><b>${c.fin}</b><span>FINALIZADOS</span></div></div></div><div class="soltec-actions"><button id="sNuevo" class="soltec-action primary"><span class="ico">＋</span><strong>NUEVO AVISO</strong><small>Crear un trabajo nuevo</small></button><button id="sAvisos" class="soltec-action"><span class="ico">☰</span><strong>AVISOS</strong><small>Consultar y editar trabajos</small></button><button id="sMem" class="soltec-action"><span class="ico">▤</span><strong>MEMORIA</strong><small>Memoria técnica RES-CNMC</small></button></div><div class="soltec-secondary"><button id="sCli" class="soltec-mini">👤 CLIENTE</button><button id="sFotos" class="soltec-mini">📷 FOTOS</button><button id="sCfg" class="soltec-mini">⚙ CONFIG.</button></div><div class="soltec-version">SOLTEC AVISOS · V1.29</div></div>`;
d.getElementById('sNuevo').onclick=()=>goAvisos(true);d.getElementById('sAvisos').onclick=()=>goAvisos(false);d.getElementById('sMem').onclick=goMemoria;d.getElementById('sCli').onclick=goCliente;d.getElementById('sFotos').onclick=goFotos;d.getElementById('sCfg').onclick=goConfig;homeDone=true;return true}
function hideOldBottoms(){for(const w of wins()){try{const d=w.document;if(d===document)continue;Array.from(d.querySelectorAll('nav.bottom')).forEach(n=>n.style.setProperty('display','none','important'));const b=d.getElementById('backupBtn');if(b)b.style.display='none'}catch(e){}}}
function closeMore(){document.getElementById('soltecMore')?.classList.remove('open')}
function buildDock(){if(document.getElementById('soltecDock'))return;const st=document.createElement('style');st.textContent=`#app129{height:100%}#soltecDock{position:fixed;z-index:250;left:10px;right:10px;bottom:calc(8px + env(safe-area-inset-bottom));height:66px;background:rgba(255,255,255,.97);border:1px solid #e1e5ea;border-radius:20px;display:grid;grid-template-columns:repeat(4,1fr);box-shadow:0 8px 28px rgba(15,23,42,.18);overflow:hidden}#soltecDock button{border:0;background:transparent;color:#667085;font:700 11px Arial;padding:7px 2px}#soltecDock button span{display:block;font-size:21px;margin-bottom:3px;color:#20242b}#soltecDock button:first-child span{color:#e7281c}#soltecMore{position:fixed;z-index:260;left:12px;right:12px;bottom:calc(82px + env(safe-area-inset-bottom));background:#fff;border:1px solid #e1e5ea;border-radius:19px;padding:10px;box-shadow:0 12px 35px rgba(15,23,42,.23);display:none;grid-template-columns:1fr 1fr;gap:8px}#soltecMore.open{display:grid}#soltecMore button{border:1px solid #e5e7eb;background:#fff;border-radius:13px;padding:13px 9px;font:800 12px Arial;color:#344054}#soltecMore .wide{grid-column:1/-1;color:#b42318;border-color:#f0c1bd}#installBtn{top:10px;right:10px}`;document.head.appendChild(st);const more=document.createElement('div');more.id='soltecMore';more.innerHTML='<button id="mCliente">👤 CLIENTE</button><button id="mFotos">📷 FOTOS</button><button id="mConfig">⚙ CONFIGURACIÓN</button><button id="mBackup">💾 COPIA TOTAL</button><button id="mClose" class="wide">CERRAR</button>';document.body.appendChild(more);const dock=document.createElement('nav');dock.id='soltecDock';dock.innerHTML='<button id="dInicio"><span>⌂</span>INICIO</button><button id="dAvisos"><span>☰</span>AVISOS</button><button id="dMem"><span>▤</span>MEMORIA</button><button id="dMore"><span>•••</span>MÁS</button>';document.body.appendChild(dock);document.getElementById('dInicio').onclick=goInicio;document.getElementById('dAvisos').onclick=()=>goAvisos(false);document.getElementById('dMem').onclick=goMemoria;document.getElementById('dMore').onclick=()=>more.classList.toggle('open');document.getElementById('mCliente').onclick=goCliente;document.getElementById('mFotos').onclick=goFotos;document.getElementById('mConfig').onclick=goConfig;document.getElementById('mBackup').onclick=goBackup;document.getElementById('mClose').onclick=closeMore}
function scan(){hideOldBottoms();buildDock();if(!homeDone)buildHome()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scan);else scan();setInterval(scan,900);
})();
