(function(){'use strict';
const MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',META='APP_AVISOS_SUMINISTRO_V129',CFG='APP_AVISOS_CONFIG_V127',DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado',COND='APP_AVISOS_CONDICIONES_V129_',DEF='APP_AVISOS_DEFICIENCIAS_V129_';
const patched=new WeakSet(),bound=new WeakSet(),urls=[];
function jget(k,d){try{const x=JSON.parse(localStorage.getItem(k)||'null');return x&&typeof x==='object'?x:d}catch(e){return d}}
function jset(k,v){localStorage.setItem(k,JSON.stringify(v||{}))}function up(v){return String(v||'').trim().toUpperCase()}function val(d,id){const e=d.getElementById(id);return e?String(e.value||'').trim():''}
function main(){return jget(MAIN,{avisos:[]})}function meta(){return jget(META,{})}function getMeta(id){return meta()[String(id)]||{}}function setMeta(id,x){if(!id)return;const m=meta();m[String(id)]=x||{};jset(META,m)}
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains('planos'))q.createObjectStore('planos')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function sget(k){return openDb().then(q=>new Promise((ok,no)=>{const r=q.transaction(STATE,'readonly').objectStore(STATE).get(String(k));r.onsuccess=()=>{const v=r.result;q.close();ok(v==null?null:v)};r.onerror=()=>{const e=r.error;q.close();no(e)}}))}
function sput(k,v){return openDb().then(q=>new Promise((ok,no)=>{const t=q.transaction(STATE,'readwrite');t.objectStore(STATE).put(v,String(k));t.oncomplete=()=>{q.close();ok()};t.onerror=()=>{const e=t.error;q.close();no(e)}}))}
function sdel(k){return openDb().then(q=>new Promise((ok,no)=>{const t=q.transaction(STATE,'readwrite');t.objectStore(STATE).delete(String(k));t.oncomplete=()=>{q.close();ok()};t.onerror=()=>{const e=t.error;q.close();no(e)}}))}
function newId(before){const s={};before.forEach(x=>s[String(x)]=1);const a=(main().avisos||[]).map(x=>Number(x.id)).filter(x=>x&&!s[String(x)]);return a.length?Math.max.apply(Math,a):0}
function style(d){if(d.getElementById('v129sumstyle'))return;const s=d.createElement('style');s.id='v129sumstyle';s.textContent='.v129-sum{grid-column:1/-1;border:1px solid #d7dee8;border-radius:14px;padding:11px;background:#fbfcfe;margin:3px 0 8px}.v129-sum .v129-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 10px}.v129-sum .v129-wide{grid-column:1/-1}.v129-sum .v129-doc{border-top:1px solid #e5e7eb;margin-top:8px;padding-top:9px}.v129-sum .v129-status{font-size:11px;color:#667085;margin:6px 0;line-height:1.45}.v129-sum .v129-danger{border-color:#b42318!important;color:#b42318!important}.v129-sum .v129-ok{color:#166534;font-weight:800}.v129-sum input[type=file]{padding:8px}.v129-sum .v129-photo-list{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin-top:8px}.v129-sum .v129-thumb{border:1px solid #dbe3ee;border-radius:10px;padding:6px;background:#fff}.v129-sum .v129-thumb img{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:7px}.v129-sum .v129-thumb button{width:100%;padding:7px;margin-top:5px;font-size:11px}@media(max-width:600px){.v129-sum .v129-grid{grid-template-columns:1fr}.v129-sum .v129-wide{grid-column:1}.v129-sum .v129-photo-list{grid-template-columns:1fr 1fr}}';d.head.appendChild(s)}
function ensure(d){style(d);if(d.getElementById('v129SupplyBox'))return;const grid=d.querySelector('#formAviso .grid2');if(!grid)return;const box=d.createElement('div');box.id='v129SupplyBox';box.className='v129-sum';box.innerHTML='<div class="sectionTitle" style="margin-top:0">DATOS ADICIONALES DEL SUMINISTRO</div><div class="v129-grid"><label>NÚMERO DE CONTADOR<input id="v129Contador" autocomplete="off"></label><label>NÚMERO DE CONTADOR CERCANO<input id="v129ContadorCercano" autocomplete="off"></label><label class="v129-wide">REF. CONDICIONES<input id="v129RefCondiciones" autocomplete="off"></label></div><div class="v129-doc"><b>CONDICIONES DE SUMINISTRO</b><div class="v129-status">GUARDA EL DOCUMENTO QUE RECIBES DE LA DISTRIBUIDORA PARA TENERLO EN LA FICHA Y USARLO DESPUÉS EN LA CONTRATACIÓN.</div><input id="v129CondFile" type="file" accept="application/pdf,image/*"><div id="v129CondStatus" class="v129-status"></div><div class="row"><button type="button" id="v129CondOpen">ABRIR DOCUMENTO</button><button type="button" id="v129CondDel" class="v129-danger">QUITAR DOCUMENTO</button></div></div><div class="v129-doc"><div class="v129-grid"><label class="v129-wide" style="display:flex;align-items:center;gap:9px;color:#b42318"><input id="v129DefCheck" type="checkbox" style="width:24px;height:24px;margin:0"> HAY DEFICIENCIAS EN LA INSTALACIÓN</label><label class="v129-wide">FOTOS DE LAS DEFICIENCIAS<input id="v129DefFiles" type="file" accept="image/*" multiple></label></div><div id="v129DefStatus" class="v129-status"></div><div id="v129DefList" class="v129-photo-list"></div><div class="row" style="margin-top:8px"><button type="button" id="v129DefShare">COMPARTIR CON FOTOS</button><button type="button" id="v129DefMail">ABRIR CORREO A INSPECCIÓN</button></div></div>';
const obs=d.getElementById('v128MemObsBox'),prov=d.getElementById('avProvincia');if(obs)obs.insertAdjacentElement('afterend',box);else if(prov&&prov.parentElement)prov.parentElement.insertAdjacentElement('afterend',box);else grid.appendChild(box);bindUi(d)}
function idNow(d){return Number(val(d,'avId'))||0}
async function load(d,id,dup){ensure(d);const src=dup||id,m=src?getMeta(src):{};d.getElementById('v129Contador').value=m.contador||'';d.getElementById('v129ContadorCercano').value=m.contadorCercano||'';d.getElementById('v129RefCondiciones').value=m.refCondiciones||'';d.getElementById('v129DefCheck').checked=!!m.deficiencias;await renderCond(d,id);await renderDef(d,id)}
function saveMetaFrom(d,id){setMeta(id,{contador:up(val(d,'v129Contador')),contadorCercano:up(val(d,'v129ContadorCercano')),refCondiciones:up(val(d,'v129RefCondiciones')),deficiencias:!!(d.getElementById('v129DefCheck')&&d.getElementById('v129DefCheck').checked)})}
async function renderCond(d,id){const st=d.getElementById('v129CondStatus');if(!st)return;if(!id){st.textContent='GUARDA PRIMERO EL AVISO PARA ADJUNTAR LAS CONDICIONES.';return}const x=await sget(COND+id);st.innerHTML=x&&x.blob?'<span class="v129-ok">DOCUMENTO GUARDADO: '+up(x.nombre||'CONDICIONES')+'</span>':'SIN DOCUMENTO DE CONDICIONES GUARDADO'}
async function addCond(d,file){const id=idNow(d);if(!id){alert('GUARDA PRIMERO EL AVISO. DESPUÉS PODRÁS ADJUNTAR LAS CONDICIONES DE SUMINISTRO.');d.getElementById('v129CondFile').value='';return}if(!file)return;await sput(COND+id,{blob:file,nombre:file.name||'condiciones',tipo:file.type||'',guardadoEn:new Date().toISOString()});d.getElementById('v129CondFile').value='';renderCond(d,id)}
async function openCond(d){const id=idNow(d);if(!id)return;const x=await sget(COND+id);if(!x||!x.blob){alert('NO HAY DOCUMENTO DE CONDICIONES GUARDADO.');return}const u=URL.createObjectURL(x.blob);window.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),60000)}
async function delCond(d){const id=idNow(d);if(!id)return;if(!confirm('¿QUITAR EL DOCUMENTO DE CONDICIONES DE ESTE AVISO?'))return;await sdel(COND+id);renderCond(d,id)}
function resize(file){return new Promise((ok,no)=>{const im=new Image(),u=URL.createObjectURL(file);im.onload=()=>{try{const max=1600,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);c.toBlob(b=>{URL.revokeObjectURL(u);if(!b)return no(new Error('NO SE PUDO PROCESAR LA FOTO'));ok({blob:b,nombre:file.name||('deficiencia_'+Date.now()+'.jpg'),creadaEn:new Date().toISOString()})},'image/jpeg',.82)}catch(e){URL.revokeObjectURL(u);no(e)}};im.onerror=()=>{URL.revokeObjectURL(u);no(new Error('NO SE PUDO ABRIR LA FOTO'))};im.src=u})}
async function addDefs(d,files){const id=idNow(d);if(!id){alert('GUARDA PRIMERO EL AVISO. DESPUÉS PODRÁS AÑADIR LAS FOTOS DE DEFICIENCIAS.');d.getElementById('v129DefFiles').value='';return}const nuevas=await Promise.all(Array.from(files||[]).map(resize)),old=await sget(DEF+id)||[];await sput(DEF+id,old.concat(nuevas));d.getElementById('v129DefFiles').value='';d.getElementById('v129DefCheck').checked=true;saveMetaFrom(d,id);renderDef(d,id)}
async function renderDef(d,id){const list=d.getElementById('v129DefList'),st=d.getElementById('v129DefStatus');if(!list||!st)return;urls.splice(0).forEach(u=>{try{URL.revokeObjectURL(u)}catch(e){}});list.innerHTML='';if(!id){st.textContent='GUARDA PRIMERO EL AVISO PARA AÑADIR FOTOS.';return}const a=await sget(DEF+id)||[];st.textContent=a.length?a.length+' FOTO(S) DE DEFICIENCIAS GUARDADA(S).':'SIN FOTOS DE DEFICIENCIAS.';a.forEach((p,i)=>{const u=URL.createObjectURL(p.blob);urls.push(u);const x=d.createElement('div');x.className='v129-thumb';x.innerHTML='<img src="'+u+'" alt="Deficiencia"><button type="button" class="v129-danger" data-i="'+i+'">ELIMINAR</button>';x.querySelector('button').onclick=async()=>{const cur=await sget(DEF+id)||[];cur.splice(i,1);await sput(DEF+id,cur);renderDef(d,id)};list.appendChild(x)})}
function mailData(d){const dir=up(val(d,'avDireccion')),cfg=jget(CFG,{}),to=String(((cfg.emails||{}).inspeccion)||'').trim().toLowerCase();return{to,dir,subject:'DEFICIENCIAS - '+(dir||'SUMINISTRO'),body:['DEFICIENCIAS EN LA INSTALACIÓN','', 'CLIENTE: '+up(val(d,'avCliente')),'NIF / CIF: '+up(val(d,'avNif')),'TELÉFONO: '+up(val(d,'avTelefono')),'', 'DIRECCIÓN DEL SUMINISTRO: '+dir,'CP: '+up(val(d,'avCp')),'LOCALIDAD: '+up(val(d,'avLocalidad')),'PROVINCIA: '+up(val(d,'avProvincia')),'NÚMERO DE CONTADOR: '+up(val(d,'v129Contador')),'NÚMERO DE CONTADOR CERCANO: '+up(val(d,'v129ContadorCercano')),'REF. CONDICIONES: '+up(val(d,'v129RefCondiciones')),'','SE ADJUNTAN FOTOGRAFÍAS DE LAS DEFICIENCIAS.'].join('\n')}}
async function shareDefs(d){const id=idNow(d),a=id?await sget(DEF+id)||[]:[];if(!a.length){alert('NO HAY FOTOS DE DEFICIENCIAS GUARDADAS.');return}const m=mailData(d),files=a.map((p,i)=>new File([p.blob],p.nombre||('deficiencia_'+(i+1)+'.jpg'),{type:p.blob.type||'image/jpeg'}));if(navigator.share&&(!navigator.canShare||navigator.canShare({files}))){try{await navigator.share({title:m.subject,text:(m.to?'DESTINATARIO: '+m.to+'\n\n':'')+m.body,files});return}catch(e){if(e&&e.name==='AbortError')return}}alert('ESTE DISPOSITIVO NO PERMITE COMPARTIR LAS FOTOS AUTOMÁTICAMENTE. SE ABRIRÁ EL CORREO Y TENDRÁS QUE ADJUNTARLAS MANUALMENTE.');openMail(d)}
function openMail(d){const m=mailData(d);if(!m.to){alert('CONFIGURA PRIMERO EL CORREO DE INSPECCIÓN EN CONFIGURACIÓN.');return}const a=d.createElement('a');a.href='mailto:'+encodeURIComponent(m.to)+'?subject='+encodeURIComponent(m.subject)+'&body='+encodeURIComponent(m.body);a.style.display='none';d.body.appendChild(a);a.click();setTimeout(()=>a.remove(),500)}
function bindUi(d){const box=d.getElementById('v129SupplyBox');if(!box||bound.has(box))return;bound.add(box);d.getElementById('v129CondFile').onchange=function(){addCond(d,this.files&&this.files[0]).catch(e=>alert(e.message))};d.getElementById('v129CondOpen').onclick=()=>openCond(d);d.getElementById('v129CondDel').onclick=()=>delCond(d);d.getElementById('v129DefFiles').onchange=function(){addDefs(d,this.files).catch(e=>alert(e.message))};d.getElementById('v129DefShare').onclick=()=>shareDefs(d);d.getElementById('v129DefMail').onclick=()=>openMail(d)}
function patch(d,w){if(patched.has(w)||!w.App||!d.getElementById('formAviso'))return;patched.add(w);ensure(d);const A=w.App,n=A.nuevoAviso,e=A.editarAviso,du=A.duplicarAviso,sa=A.guardarAviso,show=A.show;A.show=function(id){const r=show.apply(A,arguments);if(id==='avisos')setTimeout(()=>ensure(d),50);return r};A.nuevoAviso=function(){const r=n.apply(A,arguments);setTimeout(()=>load(d,0,0),100);return r};A.editarAviso=function(id){const r=e.apply(A,arguments);setTimeout(()=>load(d,Number(id)||0,0),100);return r};A.duplicarAviso=function(id){const r=du.apply(A,arguments);setTimeout(()=>load(d,0,Number(id)||0),100);return r};A.guardarAviso=function(){const before=(main().avisos||[]).map(x=>Number(x.id)),id=idNow(d),m={contador:up(val(d,'v129Contador')),contadorCercano:up(val(d,'v129ContadorCercano')),refCondiciones:up(val(d,'v129RefCondiciones')),deficiencias:!!(d.getElementById('v129DefCheck')&&d.getElementById('v129DefCheck').checked)},r=sa.apply(A,arguments);setTimeout(()=>{const fin=id||newId(before);if(fin)setMeta(fin,m)},250);return r};const cur=idNow(d);if(d.getElementById('formAviso').style.display!=='none')load(d,cur,0)}
function walk(w,s){if(!w||s.has(w))return;s.add(w);let d;try{d=w.document}catch(e){return}try{if(d.getElementById('formAviso'))patch(d,w);Array.from(d.querySelectorAll('iframe')).forEach(f=>{try{walk(f.contentWindow,s)}catch(e){}})}catch(e){}}
function scan(){walk(window,new Set())}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scan);else scan();setInterval(scan,800);
})();
