(function(){'use strict';
const MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',META='APP_AVISOS_SUMINISTRO_V129',DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado',COND='APP_AVISOS_CONDICIONES_V129_';
const patched=new WeakSet(),bound=new WeakSet();
function jget(k,d){try{const x=JSON.parse(localStorage.getItem(k)||'null');return x&&typeof x==='object'?x:d}catch(e){return d}}
function jset(k,v){localStorage.setItem(k,JSON.stringify(v||{}))}
function up(v){return String(v||'').trim().toUpperCase()}
function val(d,id){const e=d.getElementById(id);return e?String(e.value||'').trim():''}
function main(){return jget(MAIN,{avisos:[]})}
function meta(){return jget(META,{})}
function getMeta(id){return meta()[String(id)]||{}}
function setMeta(id,x){if(!id)return;const m=meta();m[String(id)]=x||{};jset(META,m)}
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains('planos'))q.createObjectStore('planos')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function sget(k){return openDb().then(q=>new Promise((ok,no)=>{const r=q.transaction(STATE,'readonly').objectStore(STATE).get(String(k));r.onsuccess=()=>{const v=r.result;q.close();ok(v==null?null:v)};r.onerror=()=>{const e=r.error;q.close();no(e)}}))}
function sput(k,v){return openDb().then(q=>new Promise((ok,no)=>{const t=q.transaction(STATE,'readwrite');t.objectStore(STATE).put(v,String(k));t.oncomplete=()=>{q.close();ok()};t.onerror=()=>{const e=t.error;q.close();no(e)}}))}
function sdel(k){return openDb().then(q=>new Promise((ok,no)=>{const t=q.transaction(STATE,'readwrite');t.objectStore(STATE).delete(String(k));t.oncomplete=()=>{q.close();ok()};t.onerror=()=>{const e=t.error;q.close();no(e)}}))}
function newId(before){const s={};before.forEach(x=>s[String(x)]=1);const a=(main().avisos||[]).map(x=>Number(x.id)).filter(x=>x&&!s[String(x)]);return a.length?Math.max.apply(Math,a):0}
function style(d){if(d.getElementById('v129sumstyle2'))return;const s=d.createElement('style');s.id='v129sumstyle2';s.textContent='.v129-sum{grid-column:1/-1;border:1px solid #d7dee8;border-radius:14px;padding:11px;background:#fbfcfe;margin:3px 0 8px}.v129-sum .v129-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 10px}.v129-sum .v129-wide{grid-column:1/-1}.v129-docacc{border:1px solid #dfe4ea;border-radius:13px;background:#fff;margin-top:10px;overflow:hidden}.v129-dochead{width:100%;border:0!important;border-radius:0!important;background:#f8fafc!important;color:#182033!important;text-align:left!important;padding:13px!important;font-weight:900!important;display:flex;justify-content:space-between;align-items:center}.v129-dochead:after{content:"▸";font-size:18px}.v129-docacc.open .v129-dochead:after{content:"▾"}.v129-docbody{display:none;padding:11px;border-top:1px solid #e5e7eb}.v129-docacc.open .v129-docbody{display:block}.v129-condpick{width:100%;background:#fff!important;color:#0b5ed7!important;border:1px solid #0b5ed7!important}.v129-status{font-size:11px;color:#667085;margin:7px 0;line-height:1.45}.v129-ok{color:#166534;font-weight:800}.v129-danger{border-color:#b42318!important;color:#b42318!important}.v129-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px}@media(max-width:600px){.v129-sum .v129-grid{grid-template-columns:1fr}.v129-sum .v129-wide{grid-column:1}.v129-actions{grid-template-columns:1fr}}';d.head.appendChild(s)}
function ensure(d){style(d);let box=d.getElementById('v129SupplyBox');if(box)return box;const grid=d.querySelector('#formAviso .grid2');if(!grid)return null;box=d.createElement('div');box.id='v129SupplyBox';box.className='v129-sum';box.innerHTML='<div class="sectionTitle" style="margin-top:0">DATOS ADICIONALES DEL SUMINISTRO</div><div class="v129-grid"><label>NÚMERO DE CONTADOR<input id="v129Contador" autocomplete="off"></label><label>NÚMERO DE CONTADOR CERCANO<input id="v129ContadorCercano" autocomplete="off"></label><label class="v129-wide">REF. CONDICIONES<input id="v129RefCondiciones" autocomplete="off"></label></div><div id="v129CondAcc" class="v129-docacc"><button type="button" id="v129CondHead" class="v129-dochead">CONDICIONES DE SUMINISTRO ACTUALES</button><div class="v129-docbody"><div class="v129-status">DOCUMENTO PDF RECIBIDO DE E-DISTRIBUCIÓN. SE GUARDA EN LA FICHA DEL AVISO PARA SU USO POSTERIOR.</div><input id="v129CondFile" type="file" accept="application/pdf,.pdf" style="display:none"><button type="button" id="v129CondPick" class="v129-condpick">SELECCIONAR CONDICIONES DE SUMINISTRO</button><div id="v129CondStatus" class="v129-status"></div><div class="v129-actions"><button type="button" id="v129CondOpen">ABRIR DOCUMENTO</button><button type="button" id="v129CondDel" class="v129-danger">QUITAR DOCUMENTO</button></div></div></div>';
const obs=d.getElementById('v128MemObsBox'),prov=d.getElementById('avProvincia');if(obs)obs.insertAdjacentElement('afterend',box);else if(prov&&prov.parentElement)prov.parentElement.insertAdjacentElement('afterend',box);else grid.appendChild(box);bindUi(d);return box}
function idNow(d){return Number(val(d,'avId'))||0}
async function renderCond(d,id){const st=d.getElementById('v129CondStatus');if(!st)return;if(!id){st.textContent='GUARDA PRIMERO EL AVISO PARA ADJUNTAR LAS CONDICIONES DE SUMINISTRO.';return}const x=await sget(COND+id);st.innerHTML=x&&x.blob?'<span class="v129-ok">PDF GUARDADO: '+up(x.nombre||'CONDICIONES DE SUMINISTRO')+'</span>':'SIN PDF DE CONDICIONES DE SUMINISTRO GUARDADO'}
async function addCond(d,file){const id=idNow(d);if(!id){alert('GUARDA PRIMERO EL AVISO. DESPUÉS PODRÁS ADJUNTAR LAS CONDICIONES DE SUMINISTRO.');d.getElementById('v129CondFile').value='';return}if(!file)return;if(file.type&&file.type!=='application/pdf'&&!/\.pdf$/i.test(file.name||'')){alert('SELECCIONA EL DOCUMENTO PDF DE CONDICIONES DE SUMINISTRO.');d.getElementById('v129CondFile').value='';return}await sput(COND+id,{blob:file,nombre:file.name||'condiciones_suministro.pdf',tipo:file.type||'application/pdf',guardadoEn:new Date().toISOString()});d.getElementById('v129CondFile').value='';await renderCond(d,id)}
async function openCond(d){const id=idNow(d);if(!id)return;const x=await sget(COND+id);if(!x||!x.blob){alert('NO HAY DOCUMENTO DE CONDICIONES DE SUMINISTRO GUARDADO.');return}const u=URL.createObjectURL(x.blob);window.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),60000)}
async function delCond(d){const id=idNow(d);if(!id)return;if(!confirm('¿QUITAR EL DOCUMENTO DE CONDICIONES DE SUMINISTRO DE ESTE AVISO?'))return;await sdel(COND+id);await renderCond(d,id)}
function bindUi(d){const box=d.getElementById('v129SupplyBox');if(!box||bound.has(box))return;bound.add(box);d.getElementById('v129CondHead').onclick=()=>d.getElementById('v129CondAcc').classList.toggle('open');d.getElementById('v129CondPick').onclick=()=>d.getElementById('v129CondFile').click();d.getElementById('v129CondFile').onchange=function(){addCond(d,this.files&&this.files[0]).catch(e=>alert(e.message))};d.getElementById('v129CondOpen').onclick=()=>openCond(d);d.getElementById('v129CondDel').onclick=()=>delCond(d)}
async function load(d,id,dup){ensure(d);const src=dup||id,m=src?getMeta(src):{};d.getElementById('v129Contador').value=m.contador||'';d.getElementById('v129ContadorCercano').value=m.contadorCercano||'';d.getElementById('v129RefCondiciones').value=m.refCondiciones||'';await renderCond(d,id)}
function patch(d,w){if(patched.has(w)||!w.App||!d.getElementById('formAviso'))return;patched.add(w);ensure(d);const A=w.App,n=A.nuevoAviso,e=A.editarAviso,du=A.duplicarAviso,sa=A.guardarAviso,show=A.show;A.show=function(id){const r=show.apply(A,arguments);if(id==='avisos')setTimeout(()=>ensure(d),50);return r};A.nuevoAviso=function(){const r=n.apply(A,arguments);setTimeout(()=>load(d,0,0),100);return r};A.editarAviso=function(id){const r=e.apply(A,arguments);setTimeout(()=>load(d,Number(id)||0,0),100);return r};A.duplicarAviso=function(id){const r=du.apply(A,arguments);setTimeout(()=>load(d,0,Number(id)||0),100);return r};A.guardarAviso=function(){const before=(main().avisos||[]).map(x=>Number(x.id)),id=idNow(d),m={contador:up(val(d,'v129Contador')),contadorCercano:up(val(d,'v129ContadorCercano')),refCondiciones:up(val(d,'v129RefCondiciones'))},r=sa.apply(A,arguments);setTimeout(()=>{const fin=id||newId(before);if(fin)setMeta(fin,m)},250);return r};const cur=idNow(d);if(d.getElementById('formAviso').style.display!=='none')load(d,cur,0)}
function walk(w,s){if(!w||s.has(w))return;s.add(w);let d;try{d=w.document}catch(e){return}try{if(d.getElementById('formAviso'))patch(d,w);Array.from(d.querySelectorAll('iframe')).forEach(f=>{try{walk(f.contentWindow,s)}catch(e){}})}catch(e){}}
function scan(){walk(window,new Set())}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scan);else scan();setInterval(scan,800);
})();