(function(){'use strict';
const MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',FLAGS='APP_AVISOS_FLAGS_V120',CUPS='APP_AVISOS_CUPS_V127',DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado',COND='APP_AVISOS_CONDICIONES_V129_';
const styled=new WeakSet(),bound=new WeakSet();
function jget(k,d){try{const x=JSON.parse(localStorage.getItem(k)||'null');return x&&typeof x==='object'?x:d}catch(e){return d}}
function data(){return jget(MAIN,{avisos:[]})}function flags(){return jget(FLAGS,{})}function cups(){return jget(CUPS,{})}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fecha(v){if(!v)return'';const p=String(v).split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:String(v)}
function normDir(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]/g,' ').replace(/\s+/g,' ').trim()}
function sameSupply(a,b){const ad=normDir(a&&a.direccion),bd=normDir(b&&b.direccion);return !!ad&&ad===bd}
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains('planos'))q.createObjectStore('planos')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function sget(k){return openDb().then(q=>new Promise((ok,no)=>{const r=q.transaction(STATE,'readonly').objectStore(STATE).get(String(k));r.onsuccess=()=>{const v=r.result;q.close();ok(v==null?null:v)};r.onerror=()=>{const e=r.error;q.close();no(e)}}))}
function wins(){const out=[],seen=new Set();function walk(w){if(!w||seen.has(w))return;seen.add(w);out.push(w);let fs=[];try{fs=Array.from(w.document.querySelectorAll('iframe'))}catch(e){}fs.forEach(f=>{try{walk(f.contentWindow)}catch(e){}})}walk(window);return out}
function baseApp(){for(const w of wins()){try{if(w.App&&w.document.getElementById('formAviso')&&w.document.getElementById('avisos'))return w}catch(e){}}return null}
function editAviso(id){const w=baseApp();if(!w)return;try{w.App.show('avisos');setTimeout(()=>w.App.editarAviso(Number(id)),80)}catch(e){}}
function style(d){if(styled.has(d))return;styled.add(d);const s=d.createElement('style');s.textContent='.v130-exp{margin:12px 0}.v130-exp h3{font-size:16px;margin:0 0 8px}.v130-supply-head{border:1px solid #dbe3ee;border-radius:14px;background:#f8fafc;padding:11px;margin:8px 0 10px}.v130-supply-head b{display:block;font-size:10px;color:#667085;margin-bottom:4px}.v130-supply-head strong{font-size:14px;color:#182033}.v130-exp-card{border:1px solid #dbe3ee;border-radius:14px;background:#fff;padding:11px;margin:8px 0}.v130-exp-top{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.v130-exp-title{font-size:14px;font-weight:900;color:#182033}.v130-exp-sub{font-size:11px;color:#667085;margin-top:3px;line-height:1.4}.v130-exp-status{display:flex;flex-wrap:wrap;gap:5px;margin:8px 0}.v130-pill{font-size:10px;font-weight:800;border:1px solid #dbe3ee;border-radius:999px;padding:5px 7px;background:#f8fafc;color:#667085}.v130-pill.ok{border-color:#b7dfc3;background:#f2fbf5;color:#166534}.v130-exp-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.v130-exp-actions button{padding:9px!important;font-size:11px!important}.v130-exp-empty{padding:13px;border:1px dashed #d0d5dd;border-radius:12px;color:#667085;font-size:12px}@media(max-width:520px){.v130-exp-actions{grid-template-columns:1fr}}';d.head.appendChild(s)}
async function render(d){const sel=d.getElementById('cliSel'),host=d.getElementById('v130Expediente');if(!sel||!host)return;const id=Number(sel.value)||0,p=data(),cur=(p.avisos||[]).find(x=>Number(x.id)===id);if(!cur){host.innerHTML='<div class="v130-exp-empty">SIN SUMINISTRO SELECCIONADO</div>';return}const dirKey=normDir(cur.direccion);if(!dirKey){host.innerHTML='<div class="v130-exp-empty">ESTE AVISO NO TIENE DIRECCIÓN DE SUMINISTRO. COMPLETA LA DIRECCIÓN PARA PODER AGRUPAR SU EXPEDIENTE.</div>';return}const assoc=(p.avisos||[]).filter(x=>sameSupply(x,cur)).sort((a,b)=>Number(b.id)-Number(a.id)),fl=flags(),cp=cups();const fullDir=[cur.direccion,cur.cp,cur.localidad,cur.provincia].filter(Boolean).join(' · ');let html='<div class="v130-exp"><h3>EXPEDIENTE DEL SUMINISTRO · '+assoc.length+' AVISO(S)</h3><div class="v130-supply-head"><b>DIRECCIÓN DE SUMINISTRO</b><strong>'+esc(fullDir||cur.direccion)+'</strong><div class="v130-exp-sub">Los avisos se agrupan por esta dirección, aunque todavía no exista nombre o NIF del cliente.</div></div>';for(const a of assoc){const f=fl[String(a.id)]||{},cond=await sget(COND+a.id),hasCups=!!(a.cupsE||a.cupsG||cp[String(a.id)]===true),cliente=[a.cliente,a.nif].filter(Boolean).join(' · ')||'CLIENTE PENDIENTE DE IDENTIFICAR';html+='<div class="v130-exp-card" data-id="'+Number(a.id)+'"><div class="v130-exp-top"><div><div class="v130-exp-title">AVISO '+Number(a.id)+' · '+esc(fecha(a.fecha))+'</div><div class="v130-exp-sub">'+esc(cliente)+'</div></div><div class="v130-exp-sub">'+esc(String(a.estado||'').replace('_',' ').toUpperCase())+'</div></div><div class="v130-exp-status"><span class="v130-pill '+(hasCups?'ok':'')+'">CUPS '+(hasCups?'✓':'—')+'</span><span class="v130-pill '+(cond&&cond.blob?'ok':'')+'">CONDICIONES '+(cond&&cond.blob?'✓':'—')+'</span><span class="v130-pill '+(f.contratoElectricidad?'ok':'')+'">CONTRATO '+(f.contratoElectricidad?'✓':'—')+'</span><span class="v130-pill '+(f.iban?'ok':'')+'">IBAN '+(f.iban?'✓':'—')+'</span></div><div class="v130-exp-actions"><button type="button" data-act="edit">ABRIR / EDITAR AVISO</button><button type="button" data-act="cond" '+(cond&&cond.blob?'':'disabled')+'>ABRIR CONDICIONES</button></div></div>'}html+='</div>';host.innerHTML=html;host.querySelectorAll('.v130-exp-card').forEach(card=>{const aid=Number(card.dataset.id);const be=card.querySelector('[data-act="edit"]'),bc=card.querySelector('[data-act="cond"]');be.onclick=()=>editAviso(aid);if(bc&&!bc.disabled)bc.onclick=async()=>{const x=await sget(COND+aid);if(!x||!x.blob)return;const u=URL.createObjectURL(x.blob);window.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),60000)}})}
function inject(d){const view=d.getElementById('cliV'),sel=d.getElementById('cliSel'),summary=d.getElementById('v129ClientSummary'),info=d.getElementById('cliInfo');if(!view||!sel||(!summary&&!info))return;style(d);let host=d.getElementById('v130Expediente');if(!host){host=d.createElement('div');host.id='v130Expediente';(summary||info).insertAdjacentElement('afterend',host)}const h=view.querySelector('h2');if(h)h.textContent='FICHA / EXPEDIENTE DE SUMINISTRO';if(summary)summary.style.display='none';if(!bound.has(sel)){bound.add(sel);sel.addEventListener('change',()=>setTimeout(()=>render(d),30))}render(d)}
function scan(){for(const w of wins()){try{inject(w.document)}catch(e){}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scan);else scan();setInterval(scan,900);
})();