(function(){'use strict';
const DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado',PREFIX='APP_AVISOS_FOTOS_V123_';
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains('planos'))q.createObjectStore('planos')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error||new Error('No se pudo abrir la base de datos'))})}
function get(k){return openDb().then(q=>new Promise((ok,no)=>{const r=q.transaction(STATE,'readonly').objectStore(STATE).get(String(k));r.onsuccess=()=>{const v=r.result;q.close();ok(v==null?null:v)};r.onerror=()=>{const e=r.error;q.close();no(e)}}))}
function put(k,v){return openDb().then(q=>new Promise((ok,no)=>{const t=q.transaction(STATE,'readwrite');t.objectStore(STATE).put(v,String(k));t.oncomplete=()=>{q.close();ok()};t.onerror=()=>{const e=t.error;q.close();no(e)}}))}
function resize(w,file){return new Promise((ok,no)=>{let u='';try{u=w.URL.createObjectURL(file)}catch(e){return no(e)}const im=new w.Image();im.onload=()=>{try{const max=1800,s=Math.min(1,max/Math.max(im.width,im.height)),c=w.document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));const ctx=c.getContext('2d');if(!ctx)throw new Error('No se pudo preparar la imagen');ctx.drawImage(im,0,0,c.width,c.height);c.toBlob(b=>{try{w.URL.revokeObjectURL(u)}catch(e){}if(!b)return no(new Error('No se pudo procesar la fotografía'));ok({blob:b,nombre:file.name||('foto_'+Date.now()+'.jpg'),creadaEn:new Date().toISOString(),cgp:false})},'image/jpeg',.86)}catch(e){try{w.URL.revokeObjectURL(u)}catch(x){}no(e)}};im.onerror=()=>{try{w.URL.revokeObjectURL(u)}catch(e){}no(new Error('Fotografía no válida o formato no compatible'))};im.src=u})}
function status(d,msg,err){const s=d.getElementById('s133PhotoStatus');if(!s)return;s.textContent=msg;s.style.color=err?'#b42318':'#667085'}
function preparePicker(w,d,input){input.multiple=true;input.setAttribute('multiple','');input.setAttribute('accept','image/*');input.removeAttribute('capture');input.style.display='none';if(d.getElementById('s133PhotoPick'))return;const wrap=d.createElement('div');wrap.style.cssText='margin-top:8px;display:grid;gap:6px';const b=d.createElement('button');b.type='button';b.id='s133PhotoPick';b.className='primary';b.textContent='📷 SELECCIONAR VARIAS FOTOS';const h=d.createElement('div');h.className='muted';h.style.fontSize='11px';h.textContent='Puedes marcar varias fotografías en la galería y añadirlas todas de una vez.';b.onclick=()=>{input.multiple=true;input.removeAttribute('capture');try{if(typeof input.showPicker==='function')input.showPicker();else input.click()}catch(e){input.click()}};wrap.appendChild(b);wrap.appendChild(h);const label=input.closest('label');if(label)label.appendChild(wrap);else input.parentNode.insertBefore(wrap,input.nextSibling)}
window.Soltec133PhotosFix={init:function(w){const d=w.document,input=d.getElementById('s133PhotoFiles'),sel=d.getElementById('s133PhotoSel');if(!input||!sel)return;preparePicker(w,d,input);input.onchange=async function(){const files=Array.from(this.files||[]);this.value='';if(!files.length){status(d,'NO SE HA SELECCIONADO NINGUNA FOTOGRAFÍA.',true);return}const id=Number(sel.value)||0;if(!id){status(d,'SELECCIONA PRIMERO UN AVISO.',true);w.alert('SELECCIONA PRIMERO UN AVISO.');return}const nuevas=[],errores=[];for(let i=0;i<files.length;i++){const f=files[i];status(d,'PROCESANDO '+(i+1)+' DE '+files.length+' FOTOGRAFÍAS…');try{nuevas.push(await resize(w,f))}catch(e){errores.push((f&&f.name?f.name+': ':'')+(e.message||String(e)))}}if(!nuevas.length){status(d,'NO SE PUDO GUARDAR NINGUNA FOTOGRAFÍA. '+errores.join(' · '),true);return}try{let old=await get(PREFIX+id).catch(()=>[]);if(!Array.isArray(old))old=[];await put(PREFIX+id,old.concat(nuevas));status(d,nuevas.length+' FOTOGRAFÍA(S) GUARDADA(S) DE '+files.length+' SELECCIONADA(S).'+(errores.length?' '+errores.length+' NO SE PUDIERON PROCESAR.':''),errores.length>0);sel.dispatchEvent(new w.Event('change',{bubbles:true}))}catch(e){status(d,'ERROR AL GUARDAR FOTOGRAFÍAS: '+(e.message||String(e)),true)}}}};
})();