(function(){'use strict';
const DB='APP_AVISOS_PERSISTENCIA',DBV=2,STORE='planos';let previewUrl='';
function el(d,id){return d.getElementById(id)}function val(d,id){const x=el(d,id);return x?String(x.value||'').trim():''}function id(d){return Number(val(d,'avId'))||0}function num(v){const n=parseFloat(String(v||'').replace(',','.'));return Number.isFinite(n)?n:null}
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains('estado'))q.createObjectStore('estado');if(!q.objectStoreNames.contains(STORE))q.createObjectStore(STORE)};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error||new Error('No se pudo abrir IndexedDB'))})}
function get(k){return openDb().then(q=>new Promise((ok,no)=>{const r=q.transaction(STORE,'readonly').objectStore(STORE).get(String(k));r.onsuccess=()=>{const v=r.result;q.close();ok(v||null)};r.onerror=()=>{const e=r.error;q.close();no(e)}}))}
function put(k,v){return openDb().then(q=>new Promise((ok,no)=>{const t=q.transaction(STORE,'readwrite');t.objectStore(STORE).put(v,String(k));t.oncomplete=()=>{q.close();ok()};t.onerror=()=>{const e=t.error;q.close();no(e)}}))}
function del(k){return openDb().then(q=>new Promise((ok,no)=>{const t=q.transaction(STORE,'readwrite');t.objectStore(STORE).delete(String(k));t.oncomplete=()=>{q.close();ok()};t.onerror=()=>{const e=t.error;q.close();no(e)}}))}
function setStatus(d,s,err){const x=el(d,'s133PlanStatus');if(!x)return;x.textContent=s||'';x.style.color=err?'#b42318':'#667085'}
function style(d){if(el(d,'s133PlanStyle'))return;const s=d.createElement('style');s.id='s133PlanStyle';s.textContent='.s133-plan{grid-column:1/-1;border:1px solid #bfd2eb;border-radius:14px;padding:11px;background:#f8fbff;margin:7px 0}.s133-plan-preview{min-height:120px;border:1px solid #dbe3ee;border-radius:10px;background:#fff;display:flex;align-items:center;justify-content:center;overflow:hidden;margin:8px 0}.s133-plan-preview img{display:none;width:100%;height:auto;max-height:420px;object-fit:contain}.s133-plan-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.s133-plan-meta{font-size:11px;color:#667085;line-height:1.45;margin:6px 0}.s133-plan label{margin:8px 0}@media(max-width:560px){.s133-plan-actions{grid-template-columns:1fr}}';d.head.appendChild(s)}
function clearPreview(d,msg){if(previewUrl){try{URL.revokeObjectURL(previewUrl)}catch(e){}previewUrl=''}const im=el(d,'s133PlanImg'),empty=el(d,'s133PlanEmpty'),meta=el(d,'s133PlanMeta');if(im){im.removeAttribute('src');im.style.display='none'}if(empty){empty.style.display='inline';empty.textContent=msg||'SIN PLANO GUARDADO'}if(meta)meta.textContent=''}
async function render(d,forceId){const avisoId=Number(forceId)||id(d);if(!avisoId){clearPreview(d,'GUARDA PRIMERO EL AVISO');setStatus(d,'El plano se asocia al aviso guardado.');return}try{const p=await get(avisoId);if(!p||!p.blob){clearPreview(d);setStatus(d,'SIN PLANO DE SITUACIÓN GUARDADO.');return}if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(p.blob);const im=el(d,'s133PlanImg'),empty=el(d,'s133PlanEmpty'),meta=el(d,'s133PlanMeta');im.src=previewUrl;im.style.display='block';empty.style.display='none';meta.textContent=(p.generadoEn?new Date(p.generadoEn).toLocaleString('es-ES')+' · ':'')+(p.latitud&&p.longitud?p.latitud+', '+p.longitud:'')+(p.origen?' · '+p.origen:'');setStatus(d,'PLANO GUARDADO E INCLUIDO EN LA MEMORIA RES-CNMC.')}catch(e){setStatus(d,'ERROR AL LEER EL PLANO: '+e.message,true)}}
function merc(lon,lat){const R=6378137,c=Math.max(-85.05112878,Math.min(85.05112878,lat));return{x:R*lon*Math.PI/180,y:R*Math.log(Math.tan(Math.PI/4+(c*Math.PI/180)/2))}}
async function generate(d){const avisoId=id(d);if(!avisoId){alert('GUARDA PRIMERO EL AVISO. DESPUÉS PODRÁS GENERAR EL PLANO.');return}const lat=num(val(d,'avLatitud')),lon=num(val(d,'avLongitud'));if(lat===null||lon===null){alert('PRIMERO OBTÉN LAS COORDENADAS CON CARTOCIUDAD O ESCRÍBELAS MANUALMENTE.');return}setStatus(d,'GENERANDO PLANO CON CARTOGRAFÍA IGN…');const p=merc(lon,lat),W=1000,H=760,hx=220,hy=165,b=[p.x-hx,p.y-hy,p.x+hx,p.y+hy].join(','),url='https://www.ign.es/wms-inspire/ign-base?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=IGNBaseTodo&STYLES=&CRS=EPSG:3857&BBOX='+encodeURIComponent(b)+'&WIDTH='+W+'&HEIGHT='+H+'&FORMAT=image/png&TRANSPARENT=FALSE';
const im=new Image();im.crossOrigin='anonymous';im.onload=()=>{try{const c=d.createElement('canvas');c.width=W;c.height=H+120;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(im,0,0,W,H);x.beginPath();x.arc(W/2,H/2,14,0,Math.PI*2);x.fillStyle='#d92d20';x.fill();x.lineWidth=4;x.strokeStyle='#fff';x.stroke();x.fillStyle='#182033';x.font='bold 24px Arial';x.fillText('PLANO DE SITUACIÓN',24,H+34);x.font='17px Arial';const dir=[val(d,'avDireccion'),val(d,'avCp'),val(d,'avLocalidad'),val(d,'avProvincia')].filter(Boolean).join(' · ')||'SUMINISTRO';x.fillText(dir.slice(0,95),24,H+64);x.font='15px Arial';x.fillText(('WGS84: '+lat+', '+lon+(val(d,'avRefCatastral')?' · Ref. catastral: '+val(d,'avRefCatastral'):'' )).slice(0,120),24,H+92);c.toBlob(async blob=>{if(!blob){setStatus(d,'NO SE PUDO GENERAR EL PLANO.',true);return}try{await put(avisoId,{blob,nombre:'PLANO_SITUACION_'+avisoId+'.png',generadoEn:new Date().toISOString(),latitud:String(lat),longitud:String(lon),direccion:dir,refCatastral:val(d,'avRefCatastral'),origen:'IGN'});await render(d,avisoId)}catch(e){setStatus(d,'ERROR AL GUARDAR EL PLANO: '+e.message,true)}},'image/png')}catch(e){setStatus(d,'NO SE PUDO PROCESAR LA CARTOGRAFÍA IGN: '+e.message,true)}};im.onerror=()=>setStatus(d,'NO SE PUDO CARGAR LA CARTOGRAFÍA IGN. PUEDES SUBIR UNA IMAGEN DE PLANO MANUALMENTE.',true);im.src=url}
async function upload(d,file){const avisoId=id(d);if(!avisoId){alert('GUARDA PRIMERO EL AVISO.');return}if(!file||!String(file.type||'').startsWith('image/')){alert('SELECCIONA UNA IMAGEN DE PLANO.');return}const lat=val(d,'avLatitud'),lon=val(d,'avLongitud'),dir=[val(d,'avDireccion'),val(d,'avCp'),val(d,'avLocalidad'),val(d,'avProvincia')].filter(Boolean).join(' · ');await put(avisoId,{blob:file,nombre:file.name||('PLANO_SITUACION_'+avisoId),generadoEn:new Date().toISOString(),latitud:lat,longitud:lon,direccion:dir,refCatastral:val(d,'avRefCatastral'),origen:'IMAGEN APORTADA'});await render(d,avisoId)}
async function download(d){const avisoId=id(d),p=avisoId?await get(avisoId):null;if(!p||!p.blob){alert('NO HAY PLANO GUARDADO.');return}const a=d.createElement('a');a.href=URL.createObjectURL(p.blob);a.download=p.nombre||'PLANO_SITUACION.png';d.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1200)}
async function remove(d){const avisoId=id(d);if(!avisoId)return;if(!confirm('¿QUITAR EL PLANO DE SITUACIÓN DE ESTE AVISO?'))return;await del(avisoId);await render(d,avisoId)}
function inject(d){if(el(d,'s133PlanBox'))return;style(d);const carto=d.querySelector('#formAviso .cartoBox'),grid=d.querySelector('#formAviso .grid2');if(!grid)return;const box=d.createElement('div');box.id='s133PlanBox';box.className='s133-plan';box.innerHTML='<div class="sectionTitle">PLANO DE SITUACIÓN</div><p class="muted" style="margin:4px 0">Genera el plano desde las coordenadas del suministro o aporta una imagen propia. El plano queda asociado al aviso y se incorpora automáticamente a la Memoria RES-CNMC.</p><div class="s133-plan-preview"><img id="s133PlanImg" alt="Plano de situación"><span id="s133PlanEmpty" class="muted">SIN PLANO GUARDADO</span></div><div id="s133PlanMeta" class="s133-plan-meta"></div><div id="s133PlanStatus" class="s133-plan-meta"></div><div class="s133-plan-actions"><button type="button" class="primary" id="s133PlanGen">GENERAR / ACTUALIZAR PLANO</button><button type="button" id="s133PlanDown">DESCARGAR PLANO</button></div><label>APORTAR / SUSTITUIR POR IMAGEN<input id="s133PlanFile" type="file" accept="image/*"></label><button type="button" class="danger full" id="s133PlanDel">QUITAR PLANO</button>';if(carto)carto.insertAdjacentElement('afterend',box);else grid.appendChild(box);el(d,'s133PlanGen').onclick=()=>generate(d);el(d,'s133PlanDown').onclick=()=>download(d).catch(e=>alert(e.message));el(d,'s133PlanDel').onclick=()=>remove(d).catch(e=>alert(e.message));el(d,'s133PlanFile').onchange=function(){const f=this.files&&this.files[0];this.value='';if(f)upload(d,f).catch(e=>alert(e.message))};el(d,'s133PlanImg').onclick=async()=>{const avisoId=id(d),p=avisoId?await get(avisoId):null;if(!p||!p.blob)return;const u=URL.createObjectURL(p.blob);d.defaultView.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),60000)}}
function hook(w,d){if(w.__s133plan)return;w.__s133plan=true;const A=w.App,n=A.nuevoAviso,e=A.editarAviso,du=A.duplicarAviso,sa=A.guardarAviso;if(n)A.nuevoAviso=function(){const r=n.apply(A,arguments);setTimeout(()=>render(d,0),0);return r};if(e)A.editarAviso=function(avisoId){const r=e.apply(A,arguments);setTimeout(()=>render(d,Number(avisoId)||0),0);return r};if(du)A.duplicarAviso=function(){const r=du.apply(A,arguments);setTimeout(()=>render(d,0),0);return r};if(sa)A.guardarAviso=function(){const r=sa.apply(A,arguments);setTimeout(()=>render(d),60);return r}}
window.Soltec133Plan={init:function(w){try{const d=w.document;inject(d);hook(w,d);render(d).catch(()=>{})}catch(e){console.error('V1.33 PLANO',e);alert('ERROR EN PLANO DE SITUACIÓN V1.33: '+e.message)}}};
})();