(function(){'use strict';
const MAIN='APP_AVISOS_WEB_DATOS_V116_PERSISTENTE',FLAGS='APP_AVISOS_FLAGS_V120',META='APP_AVISOS_SUMINISTRO_V129',CUPS='APP_AVISOS_CUPS_V127',DB='APP_AVISOS_PERSISTENCIA',DBV=2,STATE='estado',PLANS='planos';
const PHOTO='APP_AVISOS_FOTOS_V123_',COND='APP_AVISOS_CONDICIONES_V129_',DEF='APP_AVISOS_DEFICIENCIAS_V129_',WORK='APP_AVISOS_TRABAJOS_V129_';
function jget(k,d){try{const x=JSON.parse(localStorage.getItem(k)||'null');return x&&typeof x==='object'?x:d}catch(e){return d}}
function jset(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]/g,' ').replace(/\s+/g,' ').trim()}
function data(){return jget(MAIN,{avisos:[],papelera:[]})}
function supplyKey(a){if(!a||!norm(a.direccion))return '__ID_'+String(a&&a.id||'');return [a.direccion,a.cp,a.localidad,a.provincia].map(norm).join('|')}
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const q=r.result;if(!q.objectStoreNames.contains(STATE))q.createObjectStore(STATE);if(!q.objectStoreNames.contains(PLANS))q.createObjectStore(PLANS)};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error||new Error('No se pudo abrir IndexedDB'))})}
async function cleanupAttachments(id){id=Number(id)||0;if(!id)return;try{const db=await openDb(),stores=[];if(db.objectStoreNames.contains(STATE))stores.push(STATE);if(db.objectStoreNames.contains(PLANS))stores.push(PLANS);if(stores.length){await new Promise((ok,no)=>{const t=db.transaction(stores,'readwrite');if(stores.includes(STATE)){const s=t.objectStore(STATE);[PHOTO+id,COND+id,DEF+id,WORK+id].forEach(k=>s.delete(String(k)))}if(stores.includes(PLANS))t.objectStore(PLANS).delete(String(id));t.oncomplete=ok;t.onerror=()=>no(t.error)})}db.close()}catch(e){console.warn('V1.33 limpieza adjuntos',e)}
[FLAGS,META,CUPS].forEach(k=>{const x=jget(k,{});if(Object.prototype.hasOwnProperty.call(x,String(id))){delete x[String(id)];jset(k,x)}})}
function renderExpStable(w,d){const sel=d.getElementById('s132ExpSel'),box=d.getElementById('s132ExpBox');if(!sel||!box)return;const id=Number(sel.value)||0,p=data(),cur=(p.avisos||[]).find(x=>Number(x.id)===id);if(!cur){box.innerHTML='';return}if(!norm(cur.direccion)){box.innerHTML='<div class="s132card" style="border-color:#f3b3ad"><b>AVISO SIN DIRECCIÓN DE SUMINISTRO</b><div class="muted">Completa la dirección antes de usar este aviso como expediente.</div><button type="button" class="full" data-edit="'+id+'">ABRIR AVISO</button></div>';box.querySelector('[data-edit]').onclick=()=>{w.App.show('avisos');w.App.editarAviso(id)};return}
const key=supplyKey(cur),a=(p.avisos||[]).filter(x=>supplyKey(x)===key),fl=jget(FLAGS,{});box.innerHTML='<div class="s132card"><b>DIRECCIÓN DE SUMINISTRO</b><div>'+esc([cur.direccion,cur.cp,cur.localidad,cur.provincia].filter(Boolean).join(' · '))+'</div></div>'+a.map(x=>{const f=fl[String(x.id)]||{};return '<div class="s132card"><b>AVISO '+Number(x.id)+'</b><div class="muted">'+esc(x.cliente||'CLIENTE PENDIENTE')+'</div><span class="s132pill '+((x.cupsE||x.cupsG)?'ok':'')+'">CUPS</span><span class="s132pill '+(f.contratoElectricidad?'ok':'')+'">CONTRATO</span><span class="s132pill '+(f.iban?'ok':'')+'">IBAN</span><button type="button" class="full" data-edit="'+Number(x.id)+'">ABRIR AVISO</button></div>'}).join('');box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{w.App.show('avisos');w.App.editarAviso(Number(b.dataset.edit))})}
function installNavigation(w,d){const A=w.App;if(!A||A.__s133stableNav)return;A.__s133stableNav=true;const old=A.show.bind(A);A.show=function(id){d.querySelectorAll('main .screen').forEach(s=>s.classList.remove('active'));d.querySelectorAll('nav.bottom button').forEach(b=>b.classList.remove('active'));const r=old(id);if(id==='exp132')setTimeout(()=>renderExpStable(w,d),0);return r};const sel=d.getElementById('s132ExpSel');if(sel)sel.onchange=()=>renderExpStable(w,d)}
function installAddressGuard(w,d){const A=w.App;if(!A||A.__s133stableSave)return;A.__s133stableSave=true;const old=A.guardarAviso.bind(A);A.guardarAviso=function(){const dir=d.getElementById('avDireccion'),v=dir?String(dir.value||'').trim():'';if(!v){const st=d.getElementById('estadoAviso');if(st){st.textContent='LA DIRECCIÓN DEL SUMINISTRO ES OBLIGATORIA.';st.style.color='#b42318'}if(dir){try{dir.scrollIntoView({behavior:'smooth',block:'center'})}catch(e){}setTimeout(()=>dir.focus(),100)}return false}return old()}}
function installDeleteCleanup(w){const A=w.App;if(!A||A.__s133stableDelete)return;A.__s133stableDelete=true;const old=A.borrarDefinitivo&&A.borrarDefinitivo.bind(A);if(!old)return;A.borrarDefinitivo=function(id){id=Number(id)||0;const r=old(id);setTimeout(()=>{const p=data(),exists=(p.avisos||[]).some(x=>Number(x.id)===id)||(p.papelera||[]).some(x=>Number(x.id)===id);if(!exists)cleanupAttachments(id)},0);return r}}
window.Soltec133Stabilize={init:function(w){try{const d=w.document;installNavigation(w,d);installAddressGuard(w,d);installDeleteCleanup(w);const bs=d.getElementById('bootState');if(bs)bs.textContent='V1.33 ESTABLE · AUDITORÍA APLICADA · DATOS PROTEGIDOS'}catch(e){console.error('V1.33 STABILIZE',e)}}};
})();